import {useCallback,useEffect,useMemo,useState,type ReactNode} from "react";
import {buildLocalizedPath,isEnglish,navigate} from "../../lib/navigation/runtime";
import {AdminPageShell} from "../admin-entry/AdminPageShell";

type Project={id:string;name:string;site:string;period:string;status:string};
type Report={id:number;version:number;title:string;status:string;certificateId?:string;finalizedAt?:string};
type Submission={id:number;reportId:number;version:number;authorityCode:string;authorityName:string;reportingProgram:string;reportingPeriod:string;legalBasis:string;channel:string;deadline:string;status:string;packageHash:string;receiptNo?:string;correctionReason?:string;correctionDueDate?:string;submittedBy?:string;submittedAt?:string;receivedAt?:string;acceptedAt?:string;note?:string;updatedAt:string};
type Event={id:number;submissionId:number;code:string;previousStatus?:string;newStatus:string;actor:string;note?:string;createdAt:string};
type Workflow={project:Project;eligibleReports:Report[];items:Submission[];events:Event[]};

const STATUS_LABEL:Record<string,string>={PACKAGED:"패키지 준비",SUBMITTED:"제출 완료",RECEIVED:"접수 확인",CORRECTION_REQUIRED:"보완 필요",RESUBMITTED:"재제출",ACCEPTED:"수리 완료",CANCELLED:"취소"};
const STATUS_TONE:Record<string,string>={PACKAGED:"bg-slate-100 text-slate-700",SUBMITTED:"bg-blue-100 text-blue-800",RECEIVED:"bg-cyan-100 text-cyan-800",CORRECTION_REQUIRED:"bg-amber-100 text-amber-900",RESUBMITTED:"bg-indigo-100 text-indigo-800",ACCEPTED:"bg-emerald-100 text-emerald-800",CANCELLED:"bg-rose-100 text-rose-800"};

async function json(response:Response){const text=await response.text();let body:any={};try{body=text?JSON.parse(text):{}}catch{throw new Error(`서버 응답 형식이 올바르지 않습니다. (${response.status})`)}if(!response.ok)throw new Error(body.message||`요청 처리 실패 (${response.status})`);return body}
function isoAfter(days:number){const date=new Date();date.setDate(date.getDate()+days);return date.toISOString().slice(0,10)}
function date(value?:string){return value?new Date(value).toLocaleString():"-"}

function RegulatorySubmissionWorkspace({admin=false}:{admin?:boolean}){
 const en=isEnglish();
 const initialId=new URLSearchParams(location.search).get("projectId")||"";
 const[projectId,setProjectId]=useState(initialId),[projects,setProjects]=useState<Project[]>([]),[data,setData]=useState<Workflow|null>(null),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const[form,setForm]=useState({reportId:"",authorityCode:"MOE",authorityName:"환경부",reportingProgram:"온실가스 배출량 정기보고",reportingPeriod:String(new Date().getFullYear()-1),legalBasis:"탄소중립기본법 및 온실가스 배출량 산정·보고 지침",channel:"PORTAL",deadline:isoAfter(30),note:""});
 const base=projectId?buildLocalizedPath(`/home/api/emission-projects/${projectId}/regulatory-submissions`,`/en/home/api/emission-projects/${projectId}/regulatory-submissions`):"";
 useEffect(()=>{void fetch(buildLocalizedPath("/home/api/emission-projects?page=1&size=100","/en/home/api/emission-projects?page=1&size=100"),{credentials:"include",headers:{Accept:"application/json"}}).then(json).then(body=>setProjects(Array.isArray(body.items)?body.items:[])).catch(reason=>setError(String(reason.message||reason)))},[en]);
 const load=useCallback(async()=>{if(!base){setData(null);return}setLoading(true);setError("");try{const body=await json(await fetch(base,{credentials:"include",headers:{Accept:"application/json"}}));setData(body);setForm(value=>({...value,reportId:value.reportId||String(body.eligibleReports?.[0]?.id||"")}))}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setLoading(false)}},[base]);
 useEffect(()=>{void load()},[load]);
 function choose(value:string){setProjectId(value);const path=admin?"/admin/emission/regulatory-submissions":"/emission/report-submission";navigate(buildLocalizedPath(`${path}?projectId=${encodeURIComponent(value)}`,`/en${path}?projectId=${encodeURIComponent(value)}`))}
 async function createPackage(){if(!projectId||!form.reportId)return;setBusy(true);setError("");try{await json(await fetch(base,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({...form,reportId:Number(form.reportId),clientRequestId:crypto.randomUUID()})}));setMessage("제출 패키지를 생성했습니다. 해시와 원본 보고서 버전이 고정되었습니다.");await load()}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}}
 async function transition(item:Submission,action:string){let payload:any={action};if(action==="RECORD_RECEIPT"){const receiptNo=prompt("규제기관 접수번호를 입력하세요.",item.receiptNo||"");if(!receiptNo)return;payload.receiptNo=receiptNo}if(action==="REQUEST_CORRECTION"){const note=prompt("보완 사유를 입력하세요.");if(!note)return;const correctionDueDate=prompt("보완 제출 기한(YYYY-MM-DD)",isoAfter(14));if(!correctionDueDate)return;payload={action,note,correctionDueDate}}if(action==="RESUBMIT"){const note=prompt("보완 조치 내용과 변경 범위를 입력하세요.");if(!note)return;payload.note=note}if(action==="CANCEL"){const note=prompt("취소 사유를 입력하세요.");if(!note)return;payload.note=note}if(action==="ACCEPT"&&!confirm("접수된 제출 건을 최종 수리 처리하시겠습니까?"))return;setBusy(true);setError("");try{await json(await fetch(`${base}/${item.id}/transition`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify(payload)}));setMessage("상태를 변경하고 감사 이력에 기록했습니다.");await load()}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}}
 const latest=data?.items?.[0],events=useMemo(()=>data?.events||[],[data]);
 const actions=(item:Submission)=>item.status==="PACKAGED"?["SUBMIT","CANCEL"]:item.status==="SUBMITTED"||item.status==="RESUBMITTED"?["RECORD_RECEIPT"]:item.status==="RECEIVED"?["REQUEST_CORRECTION","ACCEPT"]:item.status==="CORRECTION_REQUIRED"?["RESUBMIT"]:[];
 const actionLabel:Record<string,string>={SUBMIT:"기관 제출",CANCEL:"패키지 취소",RECORD_RECEIPT:"접수번호 등록",REQUEST_CORRECTION:"보완 요구",RESUBMIT:"보완 재제출",ACCEPT:"최종 수리"};
 return <div className="space-y-6" data-testid={admin?"admin-regulatory-submission":"user-regulatory-submission"}>
  <section className="overflow-hidden rounded-2xl bg-gradient-to-r from-[#052b57] to-[#174ea6] p-6 text-white shadow-lg lg:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-bold text-blue-200">REGULATORY SUBMISSION CONTROL</p><h1 className="mt-2 text-3xl font-black">규제기관 제출·접수·보완</h1><p className="mt-3 max-w-3xl leading-7 text-blue-50">승인된 보고서 버전을 제출 패키지로 고정하고 기관 접수번호, 보완 기한, 재제출과 최종 수리까지 하나의 감사 가능한 흐름으로 관리합니다.</p></div><label className="min-w-72 text-sm font-bold">프로젝트 선택<select className="mt-2 h-12 w-full rounded-lg border border-white/30 bg-white px-3 text-slate-900" value={projectId} onChange={event=>choose(event.target.value)}><option value="">프로젝트를 선택하세요</option>{projects.map(project=><option key={project.id} value={project.id}>{project.name} · {project.site}</option>)}</select></label></div></section>
  {message&&<p className="rounded-xl border border-blue-200 bg-blue-50 p-4 font-bold text-blue-900" role="status">{message}</p>}{error&&<p className="rounded-xl border border-red-200 bg-red-50 p-4 font-bold text-red-800" role="alert">{error}</p>}
  {!projectId?<section className="rounded-2xl border bg-white p-10 text-center"><span className="material-symbols-outlined text-5xl text-slate-300">assignment</span><h2 className="mt-3 text-xl font-black">제출할 프로젝트를 선택하세요</h2><p className="mt-2 text-slate-600">확정 보고서가 존재하는 프로젝트에서 제출 패키지를 만들 수 있습니다.</p></section>:loading?<p className="rounded-2xl border bg-white p-10 text-center font-bold" role="status">제출 현황을 불러오는 중입니다.</p>:<>
   <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["프로젝트",data?.project?.name||projectId],["확정 보고서",`${data?.eligibleReports?.length||0}건`],["현재 제출 상태",latest?STATUS_LABEL[latest.status]||latest.status:"미생성"],["제출 기한",latest?.deadline||"-"]].map(([label,value])=><article className="rounded-2xl border bg-white p-5" key={label}><p className="text-sm font-bold text-slate-500">{label}</p><strong className="mt-2 block break-words text-xl font-black text-[#052b57]">{value}</strong></article>)}</section>
   <section className="rounded-2xl border bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black text-[#052b57]">1. 제출 패키지 생성</h2><p className="mt-1 text-sm text-slate-600">확정된 보고서와 제출 메타데이터를 SHA-256 지문으로 묶습니다.</p></div><a className="font-bold text-blue-700 underline" href={buildLocalizedPath(`/emission/report_submit?projectId=${projectId}`,`/en/emission/report_submit?projectId=${projectId}`)}>보고서 확정 화면</a></div>
    {data?.eligibleReports?.length?<div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Field label="확정 보고서"><select value={form.reportId} onChange={e=>setForm({...form,reportId:e.target.value})}>{data.eligibleReports.map(report=><option key={report.id} value={report.id}>V{report.version} · {report.title}</option>)}</select></Field><Field label="기관 코드"><input value={form.authorityCode} onChange={e=>setForm({...form,authorityCode:e.target.value})}/></Field><Field label="기관명"><input value={form.authorityName} onChange={e=>setForm({...form,authorityName:e.target.value})}/></Field><Field label="제출 제도·사업"><input value={form.reportingProgram} onChange={e=>setForm({...form,reportingProgram:e.target.value})}/></Field><Field label="보고 기간"><input value={form.reportingPeriod} onChange={e=>setForm({...form,reportingPeriod:e.target.value})}/></Field><Field label="제출 채널"><select value={form.channel} onChange={e=>setForm({...form,channel:e.target.value})}><option value="PORTAL">기관 포털</option><option value="SYSTEM">시스템</option><option value="API">API</option><option value="EMAIL">이메일</option><option value="OFFLINE">오프라인</option></select></Field><Field label="제출 기한"><input type="date" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})}/></Field><Field label="법적 근거" wide><input value={form.legalBasis} onChange={e=>setForm({...form,legalBasis:e.target.value})}/></Field><Field label="비고" wide><input value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></Field><div className="flex items-end"><button className="min-h-12 w-full rounded-lg bg-[#246beb] px-5 font-black text-white disabled:opacity-50" disabled={busy} onClick={()=>void createPackage()}>새 제출 패키지 생성</button></div></div>:<div className="mt-5 rounded-xl border border-amber-300 bg-amber-50 p-5 font-bold text-amber-900">확정된 보고서가 없습니다. 보고서 검토·확정을 먼저 완료하세요.</div>}
   </section>
   <section className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-5"><h2 className="text-xl font-black text-[#052b57]">2. 제출·접수·보완 처리</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[1120px] text-left text-sm"><thead className="bg-slate-100"><tr>{["버전","제출처·제도","상태","기한","접수번호","패키지 지문","최근 처리","업무"].map(head=><th className="px-4 py-3" key={head}>{head}</th>)}</tr></thead><tbody>{data?.items?.length?data.items.map(item=><tr className="border-t align-top" key={item.id}><td className="px-4 py-4 font-black">V{item.version}</td><td className="px-4 py-4"><b>{item.authorityName}</b><small className="mt-1 block text-slate-500">{item.reportingProgram}<br/>{item.reportingPeriod}</small></td><td className="px-4 py-4"><span className={`rounded-full px-3 py-1 text-xs font-black ${STATUS_TONE[item.status]||"bg-slate-100"}`}>{STATUS_LABEL[item.status]||item.status}</span>{item.correctionReason&&<small className="mt-2 block max-w-56 text-amber-800">{item.correctionReason}</small>}</td><td className="px-4 py-4">{item.deadline}{item.correctionDueDate&&<small className="block font-bold text-red-700">보완 {item.correctionDueDate}</small>}</td><td className="px-4 py-4 font-mono">{item.receiptNo||"-"}</td><td className="max-w-52 px-4 py-4"><code className="block truncate rounded bg-slate-100 p-2 text-xs" title={item.packageHash}>{item.packageHash}</code></td><td className="px-4 py-4">{date(item.updatedAt)}<small className="block text-slate-500">{item.submittedBy||"-"}</small></td><td className="px-4 py-4"><div className="flex max-w-64 flex-wrap gap-2">{actions(item).map(action=><button className={`rounded-lg px-3 py-2 font-bold ${action==="ACCEPT"?"bg-emerald-700 text-white":action==="REQUEST_CORRECTION"||action==="CANCEL"?"border border-red-300 text-red-700":"bg-[#052b57] text-white"}`} disabled={busy} key={action} onClick={()=>void transition(item,action)}>{actionLabel[action]}</button>)}</div></td></tr>):<tr><td className="p-10 text-center text-slate-500" colSpan={8}>아직 제출 패키지가 없습니다.</td></tr>}</tbody></table></div></section>
   <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-black text-[#052b57]">3. 감사 이력</h2><ol className="mt-5 space-y-3">{events.length?events.map(event=><li className="grid gap-2 rounded-xl border p-4 md:grid-cols-[180px_1fr_auto]" key={event.id}><div><b>{event.code}</b><small className="block text-slate-500">#{event.submissionId}</small></div><div><span className="font-bold">{event.previousStatus||"시작"} → {event.newStatus}</span>{event.note&&<p className="mt-1 text-sm text-slate-600">{event.note}</p>}</div><div className="text-sm text-slate-500 md:text-right">{event.actor}<br/>{date(event.createdAt)}</div></li>):<li className="text-slate-500">기록된 이력이 없습니다.</li>}</ol></section>
  </>}
 </div>
}

function Field({label,wide=false,children}:{label:string;wide?:boolean;children:ReactNode}){return <label className={`text-sm font-bold text-slate-700 ${wide?"md:col-span-2":""}`}>{label}<div className="mt-2 [&_input]:h-12 [&_input]:w-full [&_input]:rounded-lg [&_input]:border [&_input]:px-3 [&_select]:h-12 [&_select]:w-full [&_select]:rounded-lg [&_select]:border [&_select]:px-3">{children}</div></label>}

export function EmissionRegulatorySubmissionPage(){return <div className="min-h-screen bg-[#f5f7fa]"><main className="mx-auto max-w-7xl px-4 py-8 lg:px-8"><RegulatorySubmissionWorkspace/></main></div>}
export function AdminRegulatorySubmissionPage(){return <AdminPageShell breadcrumbs={[{label:"관리자 홈",href:"/admin"},{label:"탄소배출 운영"},{label:"결과·보고"},{label:"규제 제출 현황"}]} title="규제 제출 현황"><RegulatorySubmissionWorkspace admin/></AdminPageShell>}
