const {chromium}=require('C:/Users/jwchoo/Documents/Codex/2026-07-11/new-chat/carbon-workflow-deploy/projects/carbonet-frontend/source/node_modules/.pnpm/playwright-core@1.61.1/node_modules/playwright-core');
const fs=require('fs'),assert=require('assert');
(async()=>{const started=Date.now(),browser=await chromium.launch({headless:true,executablePath:'C:/Users/jwchoo/AppData/Local/ms-playwright/chromium-1228/chrome-win64/chrome.exe'}),page=await browser.newPage({viewport:{width:1500,height:1000}}),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));const url='http://172.16.1.232/projects/P006/assets/bulk-coverage/index.html';
await page.goto(url);await page.waitForFunction(()=>document.querySelectorAll('#rows tr').length===724).catch(async e=>{console.error({errors,body:(await page.locator('body').innerText()).slice(0,4000)});await page.screenshot({path:__dirname+'/bulk-coverage/browser-failure.png'});throw e});const loadMs=Date.now()-started;checks.push('public URL renders 724 rows');
for(const [state,count] of [['review',528],['new',176],['linked',372],['design',294],['blocked',58],['all',724]]){await page.selectOption('#state',state);assert.equal(await page.locator('#rows tr').count(),count);checks.push(state+' filter '+count)}
await page.selectOption('#state','new');await page.selectOption('#method','MODIFY');assert.equal(await page.locator('#rows tr').count(),110);await page.selectOption('#method','COMPOSE');assert.equal(await page.locator('#rows tr').count(),66);checks.push('MODIFY 110 / COMPOSE 66');await page.click('#reset');
await page.fill('#q','N007');assert.equal(await page.locator('#rows tr').count(),1);await page.locator('#rows button').click();assert.equal(page.url(),url);const detail=await page.locator('#detail').innerText();assert(detail.includes('/Catalog/N007')&&detail.includes('UNBOUND')&&detail.includes('미검증'));checks.push('card selects inline without navigation; ID-specific USD path and limits');
await page.click('#reset');await page.selectOption('#state','blocked');await page.locator('#rows button').first().click();assert((await page.locator('#detail').innerText()).includes('미연결'));checks.push('BLOCKED has no fallback model');await page.click('#reset');
await page.locator('#bases button').first().click();assert.equal(await page.locator('#rows tr').count(),16);checks.push('base selects corresponding asset group');await page.click('#reset');
await page.locator('#gallery button[data-base="fluid"]').click();assert((await page.locator('#preview').getAttribute('src')).includes('fluid'));await page.evaluate(()=>document.querySelectorAll('img').forEach(i=>i.loading='eager'));await page.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0));checks.push('17 RTX images loaded, family preview changes');await page.locator('#preview').screenshot({path:__dirname+'/bulk-coverage/browser-rtx.png'});
const resolver=await (await page.request.get(new URL('resolver.json',url).href)).json();assert.equal(resolver.length,724);assert.equal(resolver.filter(r=>r.status==='RESOLVED').length,372);assert.equal(resolver.filter(r=>r.status==='BLOCKED').length,58);assert.equal(resolver.filter(r=>r.real!=='UNBOUND').length,0);checks.push('actual resolver 724 / 372 resolved / 58 blocked / REAL 0');
const zip=await page.request.get(new URL('p006-reference-assemblies.zip',url).href),buf=await zip.body();assert.equal(zip.status(),200);assert.equal(buf.subarray(0,2).toString(),'PK');checks.push('actual USD ZIP download');
await page.reload();await page.waitForFunction(()=>document.querySelectorAll('#rows tr').length===724);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:__dirname+'/bulk-coverage/browser-overview.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));checks.push('reload 724 rows / desktop no overflow');
await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:__dirname+'/bulk-coverage/browser-mobile.png'});checks.push('390px mobile no document overflow');
await page.goto('http://172.16.1.232/projects/P006/assets/usd-coverage/index.html');await page.waitForURL(url);checks.push('previous coverage URL routes to current report');
await page.goto('http://172.16.1.232/projects/P006/assets/asset-readiness/index.html');await page.waitForFunction(()=>document.querySelectorAll('#rows tr').length===724);const stats=await page.locator('#stats').innerText();assert(stats.includes('352')&&stats.includes('362'));checks.push('readiness registry synchronized: required352 created362 ready10');assert.equal(errors.length,0);
const result={url,loadMs,totalMs:Date.now()-started,checks,rows:724,resolved:372,unresolved:352,blocked:58,ready:10,jsErrors:errors,zipBytes:buf.length,businessWrites:0,plcWrites:0,real:0,originalFactoryStudioDragDrop:'NOT_TESTED_THIS_SCOPE',account:'public read-only report; no login actor used'};fs.writeFileSync(__dirname+'/bulk-coverage/browser-qa.json',JSON.stringify(result,null,2));await browser.close();console.log(JSON.stringify(result,null,2));
})().catch(e=>{console.error(e);process.exit(1)});
