import {FormEvent,useEffect,useRef,useState} from 'react';
import {buildLocalizedPath,isEnglish} from '../../lib/navigation/runtime';
import contract from './dashboard-contract.json';
import '../../components/common-design/publicBusinessPage.css';
import './emissionDashboard.css';
import './emission-dashboard-layout.css';
type Site={id:string;name:string};
type Row={id:string;name:string;sites:Site[];periodStart:string|null;periodEnd:string|null;legacyPeriod?:string;status:string;calculatedStatus:string;approvedTotalEmission:number|null;approvedResultUnit:string|null;latestCalculationTotal:number|null;latestCalculationUnit:string|null};
type Summary={projectCount:number;completedCount:number;calculatedCount:number;notCalculatedCount:number;approvedProjectCount:number;approvedTotalEmission:number|null;approvedUnitCount:number;approvedResultUnit:string|null;latestUnapprovedCalculationProjectCount:number;latestUnapprovedCalculationTotalEmission:number|null;latestUnapprovedCalculationUnitCount:number;latestUnapprovedCalculationResultUnit:string|null};
type Counts={requestedCount:number;pendingAcceptanceCount:number;correctionCount:number;deadlineCount:number};
type TaskCounts={openCount:number;overdueCount:number;dueSoonCount:number;approvalCount:number;urgentCount:number;serverDate:string};
type Month={month:string;totalEmission:number};
type Category={category:string;totalEmission:number};
type List={contractVersion:number;items:Row[];sites:Site[];totalCount:number;page:number;pageSize:number;canCreate:boolean;scopeNotice?:string;summary?:Summary;actionCounts?:Counts;taskCounts?:TaskCounts;monthlyStatus?:string;monthlyEmissions?:Month[];latestCalculationMonthlyStatus?:string;latestCalculationMonthlyEmissions?:Month[];latestCalculationCategoryEmissions?:Category[]};
type Filters={keyword:string;siteId:string;status:string;periodFrom:string;periodTo:string};
type Report={id:number;status?:string;certificateId?:string};
type Reports={approved?:{totalEmission?:number|null}|null;reports:Report[]};
const empty:Filters={keyword:'',siteId:'',status:'',periodFrom:'',periodTo:''};
const statuses:Record<string,string>={IN_PROGRESS:'진행 중',COMPLETED:'완료',STOPPED:'중단',UNKNOWN:'확인 필요'};
const calculations:Record<string,string>={NOT_CALCULATED:'미산정',RUNNING:'산정 중',CALCULATED:'산정됨',STALE:'재산정 필요',FAILED:'산정 실패',UNKNOWN:'확인 필요'};
const menuMapping:[string,string,string][]=[['배출량 현황','/emission/index','권한 범위 프로젝트·배출량 상태'],['배출량 프로젝트','/emission/project_list','목록·등록·프로젝트 기본정보'],['탄소배출 내 업무','/emission/my-tasks','담당 업무와 다음 실행'],['마감·지연 현황','/emission/deadline-status','지연·7일 내 마감'],['조직경계·사업장 관리','/emission/org-boundary','집계 사업장·경계 기준'],['활동자료 관리','/emission/activity-data','누락 자료 입력'],['자료 제출 요청','/emission/data-request','제출·접수 상태'],['증빙자료','/emission/evidence','증빙 확인'],['외부 데이터 연계','/emission/external-data','수집 오류 확인'],['배출원·시설 관리','/home/emission/source-register','산정 대상 시설'],['배출량 산정','/emission/calculation','산정 업무'],['산정 결과','/emission/calculation-results','결과 버전 확인'],['데이터 검증','/emission/data-validation','검증 쟁점 처리'],['보완·재산정','/emission/correction','보완 및 재산정'],['산정 기준·배출계수','/home/emission/factor-reference','계수·기준 버전'],['검토·승인','/emission/review-approval','승인 대기 업무'],['배출량 확정','/emission/finalization','대표 확정 버전'],['보고서 작성','/emission/report-write','보고서 작성'],['규제기관 제출','/emission/report-submission','제출·접수·보완'],['인증서·보고서 다운로드','/emission/report-download','발급 파일 열람']];
async function getJson<T>(url:string,signal:AbortSignal):Promise<T>{
 const r=await fetch(url,{credentials:'include',signal,headers:{Accept:'application/json'}});
 if(r.status===401)throw Error('로그인이 만료되었습니다. 다시 로그인해 주세요.');
 if(r.status===403)throw Error('조회 권한이 없습니다. 소속 회사와 접근 권한을 확인해 주세요.');
 if(!(r.headers.get('content-type')||'').includes('application/json'))throw Error('정상적인 데이터 응답을 받지 못했습니다. 로그인 상태를 확인해 주세요.');
 const b=await r.json();if(!r.ok)throw Error(`데이터 조회에 실패했습니다. (HTTP ${r.status})`);return b;
}
export function EmissionDashboardPage(){
 const en=isEnglish(),local=(p:string)=>buildLocalizedPath(p,'/en'+p);
 const [draft,setDraft]=useState<Filters>({...empty}),[filters,setFilters]=useState<Filters>({...empty,periodFrom:`${new Date().getFullYear()}-01-01`,periodTo:`${new Date().getFullYear()}-12-31`});
 const [year,setYear]=useState(String(new Date().getFullYear()));
 const [chartMode,setChartMode]=useState<'latest'|'approved'>('latest');
 const [taskMode,setTaskMode]=useState<'all'|'urgent'|'approval'>('all');
 const [page,setPage]=useState(1),[reload,setReload]=useState(0),[data,setData]=useState<List|null>(null);
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[validation,setValidation]=useState(''),[loadedAt,setLoadedAt]=useState('');
 const [selected,setSelected]=useState<Row|null>(null),[reports,setReports]=useState<Reports|null>(null),[reportError,setReportError]=useState(''),[reportLoading,setReportLoading]=useState(false),[reportRetry,setReportRetry]=useState(0);
 const [sites,setSites]=useState<Site[]>([]),[siteError,setSiteError]=useState(''),[siteRetry,setSiteRetry]=useState(0);
 const selectedRef=useRef<HTMLElement|null>(null);
 useEffect(()=>{const c=new AbortController();setSiteError('');getJson<{sites:Site[]}>(local('/home/api/emission-project-drafts/options'),c.signal).then(b=>{if(!Array.isArray(b.sites))throw Error('사업장 선택 목록 형식을 확인해 주세요.');if(!c.signal.aborted)setSites(b.sites);}).catch(e=>{if(!c.signal.aborted)setSiteError(e.message);});return()=>c.abort();},[en,siteRetry]);
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');setData(null);setSelected(null);setReports(null);setLoadedAt('');
  // One 20-row server page supplies two 10-row display pages.
  const q=new URLSearchParams({...filters,page:String(Math.ceil(page/2)),pageSize:'20',sort:'UPDATED_DESC'});
  getJson<List>(local('/home/api/emission-project-list-v1')+'?'+q,c.signal).then(b=>{
   if(b.contractVersion!==1||!Array.isArray(b.items)||!Array.isArray(b.sites)||!Number.isInteger(b.totalCount)||b.pageSize!==20)throw Error('프로젝트 목록 응답 형식을 확인해 주세요.');
   if(c.signal.aborted)return;const pages=Math.max(1,Math.ceil(b.totalCount/10));if(page>pages){setPage(pages);return;}
   setData(b);setLoadedAt(new Date().toLocaleString('ko-KR'));
  }).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();
 },[filters,page,reload,en]);
 useEffect(()=>{const c=new AbortController();setReports(null);setReportError('');if(!selected){setReportLoading(false);return()=>c.abort();}setReportLoading(true);
  getJson<Reports>(local('/home/api/emission-projects/')+encodeURIComponent(selected.id)+'/reports',c.signal).then(b=>{if(!Array.isArray(b.reports))throw Error('보고서 응답 형식을 확인해 주세요.');if(!c.signal.aborted)setReports(b);}).catch(e=>{if(!c.signal.aborted)setReportError(e.message);}).finally(()=>{if(!c.signal.aborted)setReportLoading(false);});return()=>c.abort();
 },[selected?.id,reportRetry,en]);
 function search(e:FormEvent){e.preventDefault();const periodFrom=`${year}-01-01`,periodTo=`${year}-12-31`;if(periodFrom>periodTo){setValidation('산정 연도를 확인해 주세요.');return;}setValidation('');setFilters({...draft,keyword:draft.keyword.trim(),periodFrom,periodTo,status:''});setPage(1);}
 function reset(){const currentYear=String(new Date().getFullYear());setYear(currentYear);setDraft({...empty});setFilters({...empty,periodFrom:`${currentYear}-01-01`,periodTo:`${currentYear}-12-31`});setPage(1);setValidation('');}
 const ready=Boolean(data&&!loading&&!error),rows=ready?data!.items.slice((page-1)%2*10,(page-1)%2*10+10):[];
 const pages=Math.max(1,Math.ceil((data?.totalCount||0)/10));
 const detail=selected?local('/emission/project/detail')+'?projectId='+encodeURIComponent(selected.id):'';
 const emission=reports?.approved?.totalEmission;
 const metric=(value:string)=>reportError?'조회 실패':reportLoading||!reports?'조회 중':value;
 const formatEmission=(value:number|null|undefined,unit='tCO₂e')=>value!==null&&value!==undefined&&Number.isFinite(Number(value))?`${Number(value).toLocaleString('ko-KR',{maximumFractionDigits:6})} ${unit}`:'—';
 const selectedEmission=emission!==null&&emission!==undefined&&Number.isFinite(Number(emission))?formatEmission(Number(emission),selected?.approvedResultUnit||'tCO₂e'):selected?.approvedTotalEmission!==null&&selected?.approvedTotalEmission!==undefined?formatEmission(selected.approvedTotalEmission,selected.approvedResultUnit||'tCO₂e'):selected?.latestCalculationTotal!==null&&selected?.latestCalculationTotal!==undefined&&selected.calculatedStatus==='CALCULATED'?`확정 전 ${formatEmission(selected.latestCalculationTotal,selected.latestCalculationUnit||'tCO₂e')}`:reports?'확정 결과 없음':'선택 후 조회';
 const chartEmissions=chartMode==='approved'?data?.monthlyEmissions:data?.latestCalculationMonthlyEmissions;
 const chartStatus=chartMode==='approved'?data?.monthlyStatus:data?.latestCalculationMonthlyStatus;
 const categoryEmissions=data?.latestCalculationCategoryEmissions||[];
 const finalizedReports=reports?reports.reports.filter(r=>r.status==='FINALIZED').length:null;
 const certificates=reports?new Set(reports.reports.map(r=>r.certificateId).filter(Boolean)).size:null;
 function downloadRows(){const csv=[['사업장','프로젝트명','프로젝트 ID','산정 시작','산정 종료','진행 상태','산정 상태'],...rows.map(r=>[r.sites.map(s=>s.name).join(', '),r.name,r.id,r.periodStart||'',r.periodEnd||'',statuses[r.status]||r.status,calculations[r.calculatedStatus]||r.calculatedStatus])].map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff',csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`배출량현황_${year}_현재페이지.csv`;a.click();URL.revokeObjectURL(url);}
 const link=(path:string)=>local(path)+(selected?'?projectId='+encodeURIComponent(selected.id):'');
 const fallback=error?<div className="ed-empty" role="alert"><strong>{error}</strong><p>프로젝트 목록을 불러오지 못했습니다.</p><button type="button" onClick={()=>setReload(x=>x+1)}>다시 조회</button></div>:loading?<div className="ed-empty">프로젝트를 불러오는 중입니다.</div>:<div className="ed-empty">조회 가능한 프로젝트가 없습니다.</div>;
 return <div className="ccus-public-business-page"><main id="main-content" className="ccus-business-content emission-dashboard" data-screen-contract={contract.id}>
 <header className="ed-page-heading"><div><h1>배출량 현황</h1><p>사업장별 배출량과 자료 준비 상태를 확인하고 필요한 업무를 이어갑니다.</p></div><a className="ed-button" href={local('/emission/project_list')}>프로젝트 관리 →</a></header>
 <form className="ed-filter-form" onSubmit={search} aria-label="배출량 현황 조회 조건">
  <label>산정 연도<select value={year} onChange={e=>setYear(e.target.value)}>{[new Date().getFullYear(),new Date().getFullYear()-1].map(y=><option key={y} value={y}>{y}</option>)}</select></label>
  <label>사업장<select aria-label="사업장" value={draft.siteId} onChange={e=>setDraft({...draft,siteId:e.target.value})}><option value="">전체 사업장</option>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
  <label>프로젝트 검색<input aria-label="프로젝트 검색" placeholder="프로젝트명 또는 프로젝트 ID" value={draft.keyword} maxLength={100} onChange={e=>setDraft({...draft,keyword:e.target.value})}/></label>
  <div className="ed-filter-actions"><button type="button" onClick={reset}>초기화</button><button className="ed-primary" type="submit">조회</button></div>
  {validation&&<p role="alert" className="ed-validation">{validation}</p>}{siteError&&<p role="alert" className="ed-validation">사업장 목록: {siteError} <button type="button" onClick={()=>setSiteRetry(x=>x+1)}>다시 조회</button></p>}
 </form>
 <div className="ed-scope-line"><span>{year}년 · {filters.siteId?sites.find(s=>s.id===filters.siteId)?.name||'선택 사업장':'전체 사업장'} · 확정본과 최신 미확정 산정본 구분</span><span>조회 범위: 로그인 계정의 접근 가능 프로젝트 · <button type="button" onClick={()=>setReload(x=>x+1)} disabled={loading}>새로고침 ↻</button></span></div>
 <section className="ed-kpis" aria-label="배출량 요약">
  <article><div>확정 배출량</div><div className="ed-value">{loading?'조회 중':error?'조회 실패':!data?.summary?'미제공':data.summary.approvedProjectCount===0?'확정본 없음':data.summary.approvedUnitCount>1?'단위 혼재':formatEmission(data.summary.approvedTotalEmission,data.summary.approvedResultUnit||'tCO₂e')}</div><p>{data?.summary?`현재 승인·잠금된 결과 ${data.summary.approvedProjectCount}건`:'확정 결과 집계 확인 중'}</p></article>
  <article><div>최신 산정 배출량 <span className="ed-tag">미확정</span></div><div className="ed-value">{loading?'조회 중':error?'조회 실패':!data?.summary?'미제공':data.summary.latestUnapprovedCalculationProjectCount===0?'산정 결과 없음':data.summary.latestUnapprovedCalculationUnitCount>1?'단위 혼재':formatEmission(data.summary.latestUnapprovedCalculationTotalEmission,data.summary.latestUnapprovedCalculationResultUnit||'tCO₂e')}</div><p>{data?.summary?`승인 전 최신 산정 ${data.summary.latestUnapprovedCalculationProjectCount}건 · 공식 확정값 아님`:'산정 결과 집계 확인 중'}</p></article>
  <article><div>유효한 최신 산정 프로젝트</div><div className="ed-value">{loading?'조회 중':error?'조회 실패':(data?.summary?.latestUnapprovedCalculationProjectCount??0).toLocaleString('ko-KR')} <small>건</small></div><p>입력 변경으로 오래된 산정본은 제외</p></article>
  <article><div>조회 프로젝트</div><div className="ed-value">{loading?'조회 중':error?'조회 실패':(data?.summary?.projectCount??data?.totalCount??0).toLocaleString('ko-KR')} <small>건</small></div><p>{data?.summary?`완료 ${data.summary.completedCount}건 · 미산정 ${data.summary.notCalculatedCount}건`:'검색 조건에 해당하는 프로젝트'}</p></article>
 </section>
 <nav className="ed-actions-strip" aria-label="처리 필요 업무 바로가기">{[{title:'미접수 자료',count:data?.actionCounts?.requestedCount,label:'제출·접수 확인 →',path:'/emission/data-request'},{title:'보완 필요',count:data?.actionCounts?.correctionCount,label:'요청 내용 확인 →',path:'/emission/correction'},{title:'검토·승인 대기',count:data?.actionCounts?.pendingAcceptanceCount,label:'검토 대상 확인 →',path:'/emission/review-approval'},{title:'7일 이내 마감',count:data?.actionCounts?.deadlineCount,label:'마감·지연 확인 →',path:'/emission/deadline-status'}].map(item=><a key={item.title} href={link(item.path)}><span>{item.title}<small>{item.label}</small></span><b>{loading?'…':error?'—':Number(item.count??0).toLocaleString('ko-KR')}건</b></a>)}</nav>
 <div className="ed-charts"><section className="ed-panel ed-panelpad"><div className="ed-section-head"><h2>월별 배출량</h2><div className="ed-chart-switch" role="group" aria-label="월별 산정 결과 구분"><button type="button" aria-pressed={chartMode==='latest'} className={chartMode==='latest'?'active':''} onClick={()=>setChartMode('latest')}>최근 산정 · 미확정</button><button type="button" aria-pressed={chartMode==='approved'} className={chartMode==='approved'?'active':''} onClick={()=>setChartMode('approved')}>승인 확정</button></div></div>{loading?<div className="ed-empty ed-chart-empty">월별 산정 결과 조회 중</div>:error?<div className="ed-empty ed-chart-empty">월별 데이터를 불러오지 못했습니다.</div>:chartStatus==='INCOMPLETE_RESULT_PERIODS'?<div className="ed-empty ed-chart-empty">항목 월 또는 산정 합계 검증이 맞지 않아 이 결과를 차트에서 제외했습니다.</div>:chartEmissions?.length?<div className="ed-monthly-chart" role="img" aria-label={chartMode==='approved'?'승인 확정 결과 월별 배출량':'최근 산정 결과 월별 배출량'}>{chartEmissions.map(m=><div className="ed-month-column" key={m.month} title={`${m.month}: ${Number(m.totalEmission).toLocaleString('ko-KR')} tCO₂e`}><span>{Number(m.totalEmission).toLocaleString('ko-KR',{maximumFractionDigits:6})}</span><i style={{height:`${Math.max(4,Number(m.totalEmission)/Math.max(...chartEmissions.map(x=>Number(x.totalEmission)),1)*100)}%`}}/><small>{m.month.slice(5)}월</small></div>)}</div>:<div className="ed-empty ed-chart-empty">{chartStatus==='NO_APPROVED_RESULT'?'표시할 승인·잠금 월별 결과가 없습니다.':chartStatus==='NO_UNAPPROVED_CALCULATION'?'표시 가능한 최신 미확정 산정본이 없습니다.':'월별 결과가 없습니다.'}</div>}<p className="ed-caption">{chartMode==='approved'?'승인·잠금된 현재 버전만 표시합니다.':'입력 자료와 합계가 검증된 최신 산정본입니다. 승인·확정 전 참고값입니다.'} · 단위 tCO₂e</p></section>
  <section className="ed-panel ed-panelpad"><div className="ed-section-head"><h2>산정 항목별 배출 구성</h2><a href={link('/emission/calculation-results')}>산정 결과 →</a></div>{categoryEmissions.length?<div className="ed-category-list">{categoryEmissions.map(item=>{const total=Number(data?.summary?.latestUnapprovedCalculationTotalEmission)||1;const share=Math.max(0,Number(item.totalEmission)/total*100);return <div className="ed-category-row" key={item.category}><div><b>{item.category}</b><strong>{formatEmission(item.totalEmission,data?.summary?.latestUnapprovedCalculationResultUnit||'tCO₂e')}</strong></div><span className="ed-category-track"><i style={{width:`${Math.min(100,share)}%`}}/></span><small>{share.toLocaleString('ko-KR',{maximumFractionDigits:1})}%</small></div>;})}</div>:<div className="ed-empty ed-chart-empty">분류된 최신 산정 항목이 없습니다.</div>}<p className="ed-caption">활동자료에 저장된 분류별 최신 산정 합계입니다. Scope 1·2에 해당하는지는 여기서 추정하지 않습니다.</p></section></div>
 <section className="ed-panel ed-project-panel"><div className="ed-section-head ed-table-head"><div><h2>사업장·프로젝트별 현황</h2><p className="ed-caption" aria-live="polite">{loading?'조회 중':error?'조회 실패':`${data?.totalCount??0}개 프로젝트 · 행을 선택하면 상세 및 다음 업무를 확인할 수 있습니다.`}</p></div><button type="button" onClick={downloadRows} disabled={!ready||!rows.length}>조회 결과 내려받기 ↓</button></div>
  <div className="ed-table-scroll" role="region" aria-label="사업장·프로젝트 조회 결과" tabIndex={0} aria-busy={loading}><table><caption className="sr-only">프로젝트 목록 · 사업장·자료 접수·상태·확정 배출량·마감</caption><thead><tr><th scope="col">사업장 / 프로젝트</th><th scope="col">자료 접수</th><th scope="col">현재 상태</th><th scope="col" className="ed-num">확정 배출량 <small>tCO₂e</small></th><th scope="col">마감일</th><th scope="col">확인</th></tr></thead><tbody>
  {error?<tr><td colSpan={6}>{fallback}</td></tr>:loading?<tr><td colSpan={6}>{fallback}</td></tr>:rows.length?rows.map(r=><tr key={r.id} aria-selected={selected?.id===r.id}><td><b>{r.sites.map(s=>s.name).join(', ')||'사업장 매핑 확인 필요'}</b><small>{r.name} · {r.id}</small></td><td>접수 데이터 미연결</td><td><span className="ed-tag">{statuses[r.status]||'확인 필요'}</span><small>{calculations[r.calculatedStatus]||'산정 상태 확인 필요'}</small></td><td className="ed-num">{r.approvedTotalEmission!==null&&r.approvedTotalEmission!==undefined?formatEmission(r.approvedTotalEmission,r.approvedResultUnit||'tCO₂e'):r.latestCalculationTotal!==null&&r.latestCalculationTotal!==undefined&&r.calculatedStatus==='CALCULATED'?`미확정 ${formatEmission(r.latestCalculationTotal,r.latestCalculationUnit||'tCO₂e')}`:r.calculatedStatus==='STALE'?'재산정 필요':'확정값 없음'}<small>{r.approvedTotalEmission!==null&&r.approvedTotalEmission!==undefined?'승인 확정':r.latestCalculationTotal!==null&&r.latestCalculationTotal!==undefined?'최신 산정 · 승인 전':'해당 버전 없음'}</small></td><td>마감일 API 미연결</td><td><button type="button" className="ed-select-row" aria-label={`${r.name} 현황 선택`} aria-pressed={selected?.id===r.id} onClick={()=>{setSelected(r);requestAnimationFrame(()=>selectedRef.current?.scrollIntoView({block:'nearest',behavior:'smooth'}));}}>선택</button></td></tr>):<tr><td colSpan={6}>조건에 맞는 프로젝트가 없습니다. <button type="button" onClick={reset}>조건 초기화</button></td></tr>}
  </tbody></table></div>
  {ready&&pages>1&&<nav className="ed-pagination" aria-label="프로젝트 페이지 이동"><button type="button" disabled={page===1} onClick={()=>setPage(p=>p-1)}>이전</button><span aria-live="polite">{page} / {pages}</span><button type="button" disabled={page===pages} onClick={()=>setPage(p=>p+1)}>다음</button></nav>}
  <p className="ed-caption ed-project-foot">{data?.scopeNotice||'로그인 계정에 조회 권한이 있는 프로젝트만 표시합니다.'} 상단 업무 건수는 조회 범위 프로젝트 집계입니다. 표의 프로젝트별 접수·마감 상세는 미연결이며 임의 산출하지 않습니다.</p>
 </section>
 <div className="ed-lower"><section className="ed-panel ed-panelpad"><div className="ed-section-head"><h2>지금 처리할 업무</h2><a href={link('/emission/my-tasks')}>내 업무 전체 →</a></div><div className="ed-task-tabs" role="tablist" aria-label="업무 구분">{([['all','전체'],['urgent','지연·마감 임박'],['approval','검토·승인']] as const).map(([key,label])=><button type="button" role="tab" aria-selected={taskMode===key} aria-pressed={taskMode===key} className={taskMode===key?'active':''} onClick={()=>setTaskMode(key)} key={key}>{label}</button>)}</div><div className="ed-empty ed-task-empty">{loading?'업무 집계 조회 중':error?'업무 집계를 조회하지 못했습니다.':taskMode==='all'?`조회 범위 미완료 업무 ${data?.taskCounts?.openCount??0}건`:taskMode==='urgent'?`지연 ${data?.taskCounts?.overdueCount??0}건 · 7일 이내 마감 ${data?.taskCounts?.dueSoonCount??0}건`:`검토·승인 대기 업무 ${data?.taskCounts?.approvalCount??0}건`}<p>아래 메뉴에서 담당 업무를 확인할 수 있습니다.</p><div className="ed-task-links"><a href={link('/emission/my-tasks')}>탄소배출 내 업무 →</a><a href={link('/emission/deadline-status')}>마감·지연 현황 →</a><a href={link('/emission/review-approval')}>검토·승인 →</a></div></div></section>
  <aside className="ed-panel ed-panelpad ed-detail" ref={selectedRef} aria-label="선택 프로젝트 상세">{!selected?<><span className="ed-muted">선택 프로젝트</span><h2>프로젝트 상세</h2><div className="ed-empty">목록에서 프로젝트를 선택하면<br/>상태와 업무 바로가기가 표시됩니다.</div></>:<><span className="ed-muted">선택 프로젝트</span><h2>{selected.sites.map(s=>s.name).join(', ')||'사업장 확인 필요'}</h2><p>{selected.name} · {selected.id}</p><dl><dt>현재 상태</dt><dd>{statuses[selected.status]||'확인 필요'} · {calculations[selected.calculatedStatus]||'산정 상태 확인 필요'}</dd><dt>산정 기간</dt><dd>{selected.periodStart||'—'} ~ {selected.periodEnd||'—'}</dd><dt>승인 결과</dt><dd>{metric(selectedEmission)}</dd></dl>{reportError&&<p role="alert" className="ed-validation">보고·인증 현황: {reportError} <button type="button" onClick={()=>setReportRetry(x=>x+1)}>다시 조회</button></p>}<p className="ed-notice">상단 배출량·업무 건수는 조회 범위 합계입니다. 이 프로젝트의 접수·마감 상세는 아직 연결되지 않았습니다.</p><a className="ed-primary ed-detail-primary" href={detail}>선택 프로젝트 업무 열기 →</a><div className="ed-detail-links"><a href={link('/emission/activity-data')}>활동자료</a><a href={link('/emission/evidence')}>증빙자료</a><a href={link('/emission/calculation')}>배출량 산정</a><a href={link('/emission/report-download')}>보고서</a></div></>}</aside></div>
 <div className="ed-bottom-links"><b>관리 기준</b><a href={local('/emission/org-boundary')}>조직경계·사업장 관리 ↗</a><a href={local('/home/emission/source-register')}>배출원·시설 관리 ↗</a><a href={local('/home/emission/factor-reference')}>산정 기준·배출계수 ↗</a><a href={local('/emission/external-data')}>외부 데이터 연계 ↗</a></div>
 <details className="ed-help" data-help-id={contract.id}><summary>도움말 · 집계 기준</summary><p>① 기간과 사업장을 선택합니다. ② 승인·잠금 결과 합계와 프로젝트 진행 상태를 확인합니다. ③ 처리 필요 업무 건수는 현재 조회 범위의 자료 요청과 미완료 프로젝트 업무 기준입니다. ④ 목록에서 프로젝트를 선택하고 업무 화면으로 이동합니다.</p><p>{contract.aggregateRule}</p><p>{contract.boundary}</p><p>승인·잠금 결과가 없으면 0건으로 표시합니다. 월별 합계는 항목 기간·합계가 검증된 현재 잠금 버전만 표시합니다. Scope 1·2 분류 및 프로젝트별 접수·마감 상세는 원천 분류·상세 계약이 없어 미제공이며, 서로 다른 단위의 결과는 합산하지 않습니다.</p></details>
 <details className="ed-help ed-design" data-help-id={`${contract.id}-design`}><summary>화면 설계 · 전체 메뉴 매핑 · QA 검증</summary><div className="ed-designbody"><h3>설계 범위</h3><p>탄소배출 관리 20개 메뉴를 프로젝트 상태 확인, 제출·산정·검증, 확정·보고 흐름에 연결합니다. 현재 사용 가능한 API와 미연결 집계 영역을 화면에서 구분합니다.</p><table><thead><tr><th>메뉴</th><th>이 화면의 역할</th><th>이동</th></tr></thead><tbody>{menuMapping.map(([label,path,purpose])=><tr key={path}><td>{label}</td><td>{purpose}</td><td><a href={local(path)}>열기 ↗</a></td></tr>)}</tbody></table><h3>데이터 계약과 검증</h3><p>프로젝트 목록·승인 잠금 요약·검증된 월별 잠금 결과·자료 요청 상태·프로젝트 업무 건수를 현재 조회 범위로 서버 집계합니다. Scope 1·2 구분은 산정 항목에 원천 분류값이 없어 미제공이며, 업무 건수는 개인 할당 건수가 아닌 조회 범위 프로젝트의 합계입니다.</p><p>프로젝트를 선택해 업무를 이동하면 projectId를 전달합니다. 도착 API는 계정·회사·프로젝트 권한을 다시 검사해야 합니다. 화면 버전 v1.2 · API 계약 emission-project-list-v1.</p><p>검증 순서: 1) 권한 범위 프로젝트 목록 → 2) 연도·사업장·프로젝트 검색 → 3) 자료 요청·업무·월별 집계 → 4) 프로젝트 선택 및 보고 API → 5) projectId 업무 이동 → 6) 새로고침·페이지 이동·반응형 확인.</p></div></details>
 </main></div>;
}
