use strict;
use warnings;
my $path = "/opt/Resonance/projects/carbonet-frontend/source/src/features/emission-survey-report/EmissionSurveyReportMigrationPage.tsx";
open my $fh, '<:raw', $path or die $!;
local $/;
my $s = <$fh>;
close $fh;
$s =~ s/\@page\{size:A4;margin:[^}]+\}/\@page{size:A4;margin:15px;}/;
$s =~ s/font-size:16px!important;line-height:1\.35!important\}/font-size:12px!important;line-height:1.35!important}/;
$s =~ s/\.lca-sheet h2\{font-size:18px!important;line-height:1\.2!important;margin-bottom:7px!important\}/.lca-sheet h2{font-size:14px!important;line-height:1.2!important;margin-bottom:6px!important}/;
$s =~ s/\.lca-sheet p\{font-size:16px!important;line-height:1\.45!important\}/.lca-sheet p{font-size:12px!important;line-height:1.45!important}/;
$s =~ s/\.lca-table\{break-inside:auto;page-break-inside:auto;font-size:16px!important;width:100%!important\}/.lca-table{break-inside:auto;page-break-inside:auto;font-size:12px!important;width:100%!important}/;
$s =~ s/padding:6px 8px!important;font-size:16px!important;line-height:1\.28!important/padding:5px 7px!important;font-size:12px!important;line-height:1.28!important/g;
open my $out, '>:raw', $path or die $!;
print $out $s;
close $out;
