package egovframework.com.feature.member.service;

import egovframework.com.common.util.FileSecurityUtil;
import lombok.RequiredArgsConstructor;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.time.LocalDateTime;
import java.util.*;

@Service @RequiredArgsConstructor
public class CompanyMemberInvitationService {
  private static final Set<String> ALLOWED=Set.of("SITE_DATA_OWNER","CALCULATOR","VERIFIER","APPROVER");
  private static final SecureRandom RANDOM=new SecureRandom();
  private final JdbcTemplate jdbc;

  public Map<String,Object> context(String requester){String tenant=managerTenant(requester);Map<String,Object> out=new LinkedHashMap<>();out.put("success",true);out.put("tenantId",tenant);out.put("actors",jdbc.queryForList("select actor_code as value,coalesce(actor_name,actor_code) as label from framework_actor_definition where actor_code in ('SITE_DATA_OWNER','CALCULATOR','VERIFIER','APPROVER') and use_at='Y' order by case actor_code when 'SITE_DATA_OWNER' then 1 when 'CALCULATOR' then 2 when 'VERIFIER' then 3 else 4 end"));return out;}
  @Transactional public Map<String,Object> issue(String requester,String email,String name,String actor){String tenant=managerTenant(requester);if(email==null||!email.matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$"))throw new IllegalArgumentException("올바른 이메일을 입력해 주세요.");if(name==null||name.isBlank())throw new IllegalArgumentException("담당자 이름을 입력해 주세요.");if(!ALLOWED.contains(actor)||!activeActor(actor))throw new IllegalArgumentException("배정 가능한 액터가 아닙니다.");jdbc.update("update framework_company_member_invitation set status='REVOKED',revoked_at=current_timestamp where instt_id=? and lower(email)=lower(?) and status='ACTIVE'",tenant,email);byte[] b=new byte[32];RANDOM.nextBytes(b);String token=Base64.getUrlEncoder().withoutPadding().encodeToString(b);UUID id=UUID.randomUUID();LocalDateTime expires=LocalDateTime.now().plusHours(24);jdbc.update("insert into framework_company_member_invitation(invitation_id,instt_id,email,member_name,actor_code,token_hash,expires_at,created_by) values(?,?,?,?,?,?,?,?)",id,tenant,email.trim(),name.trim(),actor,sha(token),expires,requester);Map<String,Object> out=new LinkedHashMap<>();out.put("success",true);out.put("invitationId",id.toString());out.put("actorCode",actor);out.put("expiresAt",expires.toString());out.put("activationPath","/join/companyMemberInvite?token="+token);return out;}
  public Map<String,Object> inspect(String token){List<Map<String,Object>> rows=jdbc.queryForList("select x.*,i.instt_nm from framework_company_member_invitation x join comtninsttinfo i on i.instt_id=x.instt_id where x.token_hash=?",sha(token));if(rows.isEmpty())return status(false,"INVALID","유효하지 않은 초대 링크입니다.");Map<String,Object> r=rows.get(0);String state=state(r);Map<String,Object> out=status("ACTIVE".equals(state),state,"ACTIVE".equals(state)?"초대받은 담당자 계정을 설정해 주세요.":message(state));out.put("insttId",v(r,"instt_id"));out.put("companyName",v(r,"instt_nm"));out.put("memberName",v(r,"member_name"));out.put("email",mask(v(r,"email")));out.put("actorCode",v(r,"actor_code"));out.put("expiresAt",String.valueOf(r.get("expires_at")));return out;}
  @Transactional public Map<String,Object> activate(String token,String requestedTenant,String account,String password,String name){validate(account,password);List<Map<String,Object>> rows=jdbc.queryForList("select x.*,i.detail_adres,i.zip from framework_company_member_invitation x join comtninsttinfo i on i.instt_id=x.instt_id where x.token_hash=? for update of x",sha(token));if(rows.isEmpty())throw new IllegalArgumentException("유효하지 않은 초대 링크입니다.");Map<String,Object> r=rows.get(0);String s=state(r);if(!"ACTIVE".equals(s))throw new IllegalStateException(message(s));String tenant=v(r,"instt_id");if(requestedTenant!=null&&!requestedTenant.isBlank()&&!tenant.equals(requestedTenant))throw new SecurityException("초대받은 회사와 요청 회사가 일치하지 않습니다.");Integer exists=jdbc.queryForObject("select count(*) from comtnemplyrinfo where lower(emplyr_id)=lower(?)",Integer.class,account);if(exists!=null&&exists>0)throw new DuplicateKeyException("이미 사용 중인 아이디입니다.");String esntl="USR"+UUID.randomUUID().toString().replace("-","").substring(0,17).toUpperCase();String enc;try{enc=FileSecurityUtil.encryptPassword(password,account);}catch(Exception e){throw new IllegalStateException("비밀번호 암호화에 실패했습니다.",e);}jdbc.update("insert into comtnemplyrinfo(emplyr_id,orgnzt_id,user_nm,password,house_adres,password_hint,password_cnsr,house_end_telno,area_no,detail_adres,zip,email_adres,ofcps_nm,house_middle_telno,emplyr_sttus_code,esntl_id,sbscrb_de,lock_at,lock_cnt,chg_pwd_last_pnttm,marketing_yn,instt_id) values(?,?,?,?,'','기업 담당자 초대','담당자 설정','','',?,?,?,'담당자','','P',?,current_timestamp,'N',0,current_timestamp,'N',?)",account,tenant,first(name,v(r,"member_name")),enc,v(r,"detail_adres"),v(r,"zip"),v(r,"email"),esntl,tenant);jdbc.update("insert into comtnemplyrscrtyestbs(scrty_dtrmn_trget_id,mber_ty_code,author_code) values(?,'USR','ROLE_USER')",esntl);jdbc.update("insert into framework_account_actor_assignment(account_id,tenant_id,project_id,actor_code,data_scope,assignment_status) values(?,?,'*',?,?,'ACTIVE') on conflict(account_id,tenant_id,project_id,actor_code) do update set assignment_status='ACTIVE',valid_until=null",account,tenant,v(r,"actor_code"),tenant);int changed=jdbc.update("update framework_company_member_invitation set status='USED',used_at=current_timestamp,used_by_account_id=? where invitation_id=? and status='ACTIVE' and used_at is null and expires_at>current_timestamp",account,r.get("invitation_id"));if(changed!=1)throw new IllegalStateException("초대 링크가 이미 사용되었거나 만료되었습니다.");Map<String,Object> out=status(true,"ACTIVATED","담당자 계정과 액터 배정이 완료되었습니다.");out.put("accountId",account);out.put("actorCode",v(r,"actor_code"));out.put("authorityCode","ROLE_USER");out.put("loginPath","/signin/loginView");return out;}
  private String managerTenant(String user){if(user==null||user.isBlank())throw new SecurityException("로그인이 필요합니다.");List<String> rows=jdbc.queryForList("select tenant_id from framework_account_actor_assignment where lower(account_id)=lower(?) and actor_code='COMPANY_MANAGER' and assignment_status='ACTIVE' and (valid_until is null or valid_until>=current_date) order by assignment_id desc limit 1",String.class,user);if(rows.isEmpty())throw new SecurityException("기업 마스터만 담당자를 초대할 수 있습니다.");return rows.get(0);}
  private boolean activeActor(String actor){Integer n=jdbc.queryForObject("select count(*) from framework_actor_definition where actor_code=? and use_at='Y'",Integer.class,actor);return n!=null&&n>0;}
  private String state(Map<String,Object> r){if("USED".equals(v(r,"status"))||r.get("used_at")!=null)return "USED";if(!"ACTIVE".equals(v(r,"status")))return "REVOKED";Object x=r.get("expires_at");LocalDateTime t=x instanceof java.sql.Timestamp ts?ts.toLocalDateTime():(LocalDateTime)x;return t.isBefore(LocalDateTime.now())?"EXPIRED":"ACTIVE";}
  private void validate(String id,String pw){if(id==null||!id.matches("^[A-Za-z][A-Za-z0-9._-]{4,39}$"))throw new IllegalArgumentException("아이디는 영문으로 시작하는 5~40자여야 합니다.");if(pw==null||pw.length()<10||!pw.matches(".*[A-Z].*")||!pw.matches(".*[a-z].*")||!pw.matches(".*[0-9].*")||!pw.matches(".*[^A-Za-z0-9].*"))throw new IllegalArgumentException("비밀번호는 10자 이상이며 영문 대·소문자, 숫자, 특수문자를 포함해야 합니다.");}
  private String sha(String x){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest((x==null?"":x).getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
  private Map<String,Object> status(boolean ok,String code,String msg){Map<String,Object> m=new LinkedHashMap<>();m.put("success",ok);m.put("status",code);m.put("message",msg);return m;}private String message(String s){return "USED".equals(s)?"이미 사용된 초대 링크입니다.":"EXPIRED".equals(s)?"만료된 초대 링크입니다.":"취소된 초대 링크입니다.";}private String v(Map<String,Object>r,String k){Object x=r.get(k);return x==null?"":String.valueOf(x).trim();}private String first(String...xs){for(String x:xs)if(x!=null&&!x.isBlank())return x.trim();return "담당자";}private String mask(String e){int a=e.indexOf('@');return a<=1?e:e.substring(0,1)+"***"+e.substring(a);}
}
