import { useState, type ReactNode } from 'react';
type Page = {path:string;name:string;actor:string;description?:string;status?:string};
export function ClassifiedWorkflowCanvas({id,title,flow,pages,next,kind,children}:{id:string;title:string;flow:string;pages:Page[];next?:string;kind:'member'|'emission'|'reduction'|'lca'|'monitoring'|'trade';children?:ReactNode}) {
 const [choice,setChoice]=useState<{id:string;index:number}>({id,index:0});
 const index=choice.id===id?choice.index:0;
 const page=pages[index];
 if(!page)return null;
 const projectId=new URLSearchParams(location.search).get('projectId');
 const target=new URL(page.path,location.origin);
 if(kind!=='member'&&kind!=='lca'&&kind!=='monitoring'&&kind!=='trade'&&projectId&&!target.searchParams.has('projectId'))target.searchParams.set('projectId',projectId);
 if(kind==='lca') {const lcaProjectId=new URLSearchParams(location.search).get('lcaProjectId');if(lcaProjectId&&!target.searchParams.has('lcaProjectId'))target.searchParams.set('lcaProjectId',lcaProjectId);}
 const href=target.pathname+target.search+target.hash;
 return <section className={`classified-flow ${kind}-screen-canvas`} data-emission-group={kind==='emission'?id:undefined} data-member-design={kind==='member'?id:undefined} onClickCapture={(event)=>{
  const anchor=(event.target as HTMLElement).closest('a');
  if(!anchor || event.button!==0 || event.ctrlKey || event.metaKey || event.shiftKey || event.altKey)return;
  // The shell's SPA link handler preserves TaskQuestPanel and its open modal.
  // Explicit execution must open the actual URL with fresh page/overlay state.
  event.preventDefault();event.stopPropagation();
  window.location.assign(anchor.href);
 }}>
 <style>{`.classified-flow~*{display:none!important}.classified-flow{margin:-16px;background:#f7f9fb;color:#052b57}.classified-flow-track{display:flex;align-items:center;gap:40px;min-width:max-content;padding:36px 16px;min-height:400px;box-sizing:border-box}.classified-flow-viewport{overflow:auto}.classified-flow-node{flex:0 0 208px;width:208px;padding:12px;background:#fff;border:1px solid #dce4ef;border-radius:16px;box-shadow:0 2px 3px #0b254010;position:relative}.classified-flow-node:after{content:'→';position:absolute;right:-30px;top:45%;font-size:24px;color:#246beb}.classified-flow-node button{display:block!important;position:relative;width:100%;min-height:148px;padding:12px 32px 12px 12px!important;text-align:left!important;background:#eff6ff!important;color:#052b57!important;border:2px solid #246beb!important;border-radius:12px!important;box-shadow:none!important;white-space:normal!important}.classified-flow-node button[aria-pressed=true]{background:#e1edff!important;border-color:#003675!important}.classified-flow-node strong{display:block;font-size:14px;line-height:1.4}.classified-flow-node small{display:block;font-size:12px;line-height:1.4;color:#63758c;margin-top:10px}.classified-flow-node code{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font:700 12px sans-serif;color:#63758c;margin-top:14px}.classified-flow-choice{position:absolute;right:10px;top:12px;width:18px;height:18px;border:2px solid #246beb;border-radius:50%;color:#246beb;text-align:center;line-height:14px;font-size:12px}.classified-flow-start,.classified-flow-end{flex:none;display:flex;align-items:center;justify-content:center;background:white;font-size:12px;font-weight:700}.classified-flow-start{width:56px;height:34px;border:2px solid #cbd5e1;border-radius:24px}.classified-flow-end{width:48px;height:48px;border:2px solid #00bd8b;border-radius:50%;color:#008564}.classified-flow-detail{padding:20px;background:white;border-top:1px solid #dce4ef;min-height:310px}.classified-flow-detail a{display:block;margin-top:16px;padding:12px;text-align:center;background:#052b57;color:white!important;border-radius:8px;font-size:14px;font-weight:bold;text-decoration:none!important}`}</style>
 <div className="classified-flow-viewport"><div className="classified-flow-track"><span className="classified-flow-start">시작</span>{pages.map((p,i)=><div className="classified-flow-node" key={p.path}><button type="button" data-emission-page={kind==='emission'?'':undefined} data-member-page={kind==='member'?'':undefined} data-path={p.path} aria-pressed={index===i} onClick={()=>setChoice({id,index:i})}><strong>{p.name}</strong><span aria-hidden="true" className="classified-flow-choice">{index===i?'✓':''}</span><small>{p.actor} · {p.name}</small><code title={p.path}>{p.path}</code></button></div>)}<span className="classified-flow-end">완료</span></div></div>
 {kind==='trade'&&page.status==='MENU_MISMATCH'&&<p role="alert" className="border-y border-amber-300 bg-amber-50 p-4 font-bold text-amber-950">{page.description}</p>}
 <aside className="classified-flow-detail" data-canvas-selection><p className="text-xs font-black text-[#246beb]">선택한 업무</p><h4 className="mt-3 text-lg font-black">{title}</h4><p className="mt-2 text-sm text-slate-600">{flow}</p><div className="mt-5 rounded-xl border border-blue-100 bg-blue-50 p-4"><strong className="text-sm">선택 화면 기능</strong><p className="mt-2 text-sm">{page.name} · {page.actor}</p><code className="mt-2 block break-all rounded bg-white px-2 py-1.5 text-xs">{page.path}</code><p className="mt-2 text-xs text-blue-800">입력값·권한·상세 테스트는 도움말과 QA에서 확인합니다. 선택 표시는 업무 완료 상태가 아닙니다.</p></div><div className="mt-4 rounded-xl bg-slate-50 p-3"><span className="text-xs text-slate-500">다음 업무</span><strong className="mt-1 block text-sm">{pages[index+1]?.name||next||'이 프로세스의 마지막 화면'}</strong></div><a data-work-screen-open href={href}>선택 단계 업무 화면 열기 →</a></aside>
 {(kind==='lca'||kind==='monitoring'||kind==='trade')&&<div className="border-t bg-white p-5" data-lca-page-evidence><strong>{page.name} · {page.status}</strong><p>{page.description}</p><p>대상 화면에서 업무 식별자·조회 범위를 확인합니다. 다른 업무의 프로젝트 ID를 임의 전용하지 않습니다.</p></div>}
 {children && <div className="border-t bg-white p-5">{children}</div>}</section>;
}
