import { FormEvent, useCallback, useEffect, useState } from "react";
import { buildLocalizedPath, isEnglish } from "../../lib/navigation/runtime";
import { AdminPageShell } from "../admin-entry/AdminPageShell";

type Project={id:string;name:string;site:string;period:string;scope:string;owner:string;progress:number;step:string;dueDate:string;status:string};
type Payload={items:Project[];total:number;page:number;size:number;summary:{status:string;count:number}[];sites:string[]};
const empty:Payload={items:[],total:0,page:1,size:10,summary:[],sites:[]};

export function AdminEmissionProjectOperationsPage(){
  const en=isEnglish();
  const [data,setData]=useState<Payload>(empty),[keyword,setKeyword]=useState(""),[status,setStatus]=useState(""),[site,setSite]=useState(""),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);try{const query=new URLSearchParams({page:String(page),size:"10"});if(keyword)query.set("keyword",keyword);if(status)query.set("status",status);if(site)query.set("site",site);const response=await fetch(`${buildLocalizedPath("/home/api/emission-projects","/en/home/api/emission-projects")}?${query}`,{credentials:"include"});if(!response.ok)throw new Error(`HTTP ${response.status}`);const body=await response.json();setData({...empty,...body,items:Array.isArray(body.items)?body.items:[],summary:Array.isArray(body.summary)?body.summary:[],sites:Array.isArray(body.sites)?body.sites:[]});setError("")}catch(reason){setError(reason instanceof Error?reason.message:String(reason));setData(empty)}finally{setLoading(false)}},[en,keyword,status,site,page]);
  useEffect(()=>{void load()},[load]);
  function search(event:FormEvent){event.preventDefault();setPage(1);void load()}
  const completed=data.items.filter(item=>item.progress>=100).length,delayed=data.items.filter(item=>item.dueDate&&new Date(item.dueDate)<new Date()&&item.progress<100).length;
  return <AdminPageShell breadcrumbs={[{label:en?"Home":"홈",href:buildLocalizedPath("/admin/","/en/admin/")},{label:en?"Emission Operations":"탄소배출 운영"},{label:en?"Project Operations":"프로젝트 운영"}]} title={en?"Emission Project Operations":"배출량 프로젝트 운영"}>
    <div className="space-y-5" data-testid="admin-emission-project-operations">
      <section className="rounded-2xl bg-gradient-to-r from-[#052b57] to-[#174ea6] p-6 text-white"><p className="text-sm font-bold text-blue-200">EMISSION PROJECT CONTROL</p><h2 className="mt-1 text-2xl font-black">{en?"Control scope, actors, deadlines, and readiness from one workspace.":"프로젝트 범위·액터·마감·업무 준비도를 한 화면에서 통제합니다."}</h2><p className="mt-2 text-sm text-blue-50">{en?"Open the project workspace to review task evidence and the next required action.":"프로젝트 작업공간에서 단계별 완료 증적과 다음 필수 업무를 검토할 수 있습니다."}</p></section>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[en?"Projects":"전체 프로젝트",data.total],[en?"Visible complete":"현재 목록 완료",completed],[en?"Delayed":"마감 지연",delayed],[en?"Active":"진행 중",Math.max(data.items.length-completed,0)]].map(([label,value])=><article className="rounded-2xl border bg-white p-5" key={String(label)}><span className="text-sm font-bold text-slate-500">{label}</span><strong className="mt-2 block text-3xl font-black text-[#052b57]">{value}</strong></article>)}</section>
      <form className="grid gap-3 rounded-2xl border bg-white p-5 lg:grid-cols-[1fr_220px_220px_auto]" onSubmit={search}><label className="text-sm font-bold">{en?"Keyword":"검색어"}<input className="mt-2 h-11 w-full rounded-lg border px-3" value={keyword} onChange={event=>setKeyword(event.target.value)} placeholder={en?"Project, site, owner":"프로젝트·사업장·담당자"}/></label><label className="text-sm font-bold">{en?"Status":"상태"}<select className="mt-2 h-11 w-full rounded-lg border px-3" value={status} onChange={event=>setStatus(event.target.value)}><option value="">{en?"All":"전체"}</option>{data.summary.map(row=><option key={row.status}>{row.status}</option>)}</select></label><label className="text-sm font-bold">{en?"Site":"사업장"}<select className="mt-2 h-11 w-full rounded-lg border px-3" value={site} onChange={event=>setSite(event.target.value)}><option value="">{en?"All":"전체"}</option>{data.sites.map(value=><option key={value}>{value}</option>)}</select></label><button className="h-11 self-end rounded-lg bg-[#246beb] px-5 font-black text-white" type="submit">{en?"Search":"조회"}</button></form>
      {loading&&<p className="rounded-xl border bg-white p-8 text-center font-bold text-slate-600" role="status">{en?"Loading projects...":"프로젝트를 불러오는 중입니다."}</p>}
      {error&&<p className="rounded-xl border border-red-200 bg-red-50 p-4 font-bold text-red-700" role="alert">{en?"Failed to load project operations.":"프로젝트 운영 정보를 불러오지 못했습니다."} ({error})</p>}
      {!loading&&!error&&<section className="overflow-hidden rounded-2xl border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-slate-100"><tr>{(en?["Project","Site / Scope","Owner","Current step","Progress","Due","Status","Action"]:["프로젝트","사업장·Scope","담당자","현재 단계","진행률","마감일","상태","업무"]).map(head=><th className="px-4 py-3 font-bold" key={head}>{head}</th>)}</tr></thead><tbody>{data.items.length?data.items.map(item=><tr className="border-t" key={item.id}><td className="px-4 py-4"><b>{item.name}</b><div className="mt-1 font-mono text-xs text-slate-500">{item.id}</div></td><td className="px-4 py-4">{item.site}<div className="text-xs text-slate-500">{item.scope} · {item.period}</div></td><td className="px-4 py-4">{item.owner}</td><td className="px-4 py-4">{item.step}</td><td className="px-4 py-4"><b>{item.progress}%</b><div className="mt-2 h-2 w-24 overflow-hidden rounded bg-slate-100"><div className="h-full bg-[#246beb]" style={{width:`${Math.min(item.progress,100)}%`}}/></div></td><td className="px-4 py-4">{item.dueDate||"-"}</td><td className="px-4 py-4">{item.status}</td><td className="px-4 py-4"><a className="font-black text-blue-700 hover:underline" href={buildLocalizedPath(`/emission/project/detail?id=${item.id}`,`/en/emission/project/detail?id=${item.id}`)}>{en?"Open":"열기"}</a></td></tr>):<tr><td className="px-4 py-12 text-center text-slate-500" colSpan={8}>{en?"No projects match the filters.":"조건에 맞는 프로젝트가 없습니다."}</td></tr>}</tbody></table></div></section>}
      <div className="flex items-center justify-between"><span className="text-sm text-slate-500">{en?`${data.total} projects`:`총 ${data.total}개`}</span><div className="flex gap-2"><button className="rounded-lg border bg-white px-4 py-2 font-bold disabled:opacity-40" disabled={page<=1} onClick={()=>setPage(value=>value-1)}>{en?"Previous":"이전"}</button><button className="rounded-lg border bg-white px-4 py-2 font-bold disabled:opacity-40" disabled={page*10>=data.total} onClick={()=>setPage(value=>value+1)}>{en?"Next":"다음"}</button></div></div>
    </div>
  </AdminPageShell>
}
