import {useEffect,useState} from "react";
import {buildLocalizedPath,isEnglish} from "../../lib/navigation/runtime";

type Report={id:number;version:number;title:string;language:string;status:string;certificateId?:string;integrityHash?:string;issuedAt?:string;downloadCount:number};

export function EmissionReportDownloadPage(){
 const en=isEnglish(),id=new URLSearchParams(location.search).get("projectId")||"";
 const base=buildLocalizedPath(`/home/api/emission-projects/${id}/reports`,`/en/home/api/emission-projects/${id}/reports`);
 const[reports,setReports]=useState<Report[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch(base,{credentials:"include"}),b=await r.json();if(!r.ok)throw new Error(b.message);setReports(b.reports||[])}
 useEffect(()=>{if(id)void load().catch(e=>setMessage(e.message))},[id]);
 async function issue(report:Report){setBusy(true);try{const r=await fetch(`${base}/${report.id}/issue`,{method:"POST",credentials:"include"}),b=await r.json();if(!r.ok)throw new Error(b.message);setMessage(en?"Certificate issued.":"인증번호를 발급했습니다.");await load()}finally{setBusy(false)}}
 async function download(report:Report){setBusy(true);try{const r=await fetch(`${base}/${report.id}/download`,{method:"POST",credentials:"include"}),b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message||"다운로드 이력을 저장하지 못했습니다.");window.print();await load()}finally{setBusy(false)}}
 return <main className="min-h-screen bg-[#f5f7fa] px-4 py-10"><div className="mx-auto max-w-6xl"><a className="font-bold text-blue-700" href={buildLocalizedPath(`/emission/report_submit?projectId=${id}`,`/en/emission/report_submit?projectId=${id}`)}>← {en?"Report finalization":"보고서 확정"}</a><h1 className="mt-5 text-3xl font-black text-[#052b57]">{en?"Reports & Certificates":"보고서·인증서 다운로드"}</h1><p className="mt-2 text-slate-600">{en?"Issue a verifiable certificate before downloading the finalized report.":"확정 보고서에 인증번호를 발급한 후 다운로드하고 진위를 확인합니다."}</p>{message&&<p className="mt-5 rounded-lg bg-blue-50 p-4 font-bold text-blue-900">{message}</p>}<div className="mt-6 space-y-4">{reports.filter(r=>r.status==="FINALIZED").map(report=><article className="rounded-xl border bg-white p-6" key={report.id}><div className="flex flex-col justify-between gap-4 md:flex-row"><div><p className="font-bold text-blue-700">V{report.version} · {report.language.toUpperCase()}</p><h2 className="mt-1 text-xl font-black">{report.title}</h2><p className="mt-3 text-sm text-slate-600">{en?"Certificate":"인증번호"}: <strong>{report.certificateId||"미발급"}</strong></p>{report.integrityHash&&<code className="mt-2 block max-w-2xl break-all rounded bg-slate-100 p-2 text-xs">SHA-256 {report.integrityHash}</code>}<p className="mt-2 text-xs text-slate-500">{en?"Downloads":"다운로드"}: {report.downloadCount||0}</p></div><div className="flex flex-wrap items-start gap-2">{!report.certificateId?<button disabled={busy} className="rounded-lg bg-[#246beb] px-4 py-3 font-bold text-white disabled:opacity-50" onClick={()=>void issue(report).catch(e=>setMessage(e.message))}>{en?"Issue certificate":"인증번호 발급"}</button>:<><button disabled={busy} className="rounded-lg border px-4 py-3 font-bold disabled:opacity-50" onClick={()=>void download(report).catch(e=>setMessage(e.message))}>{en?"Print / Save PDF":"인쇄·PDF 저장"}</button><a className="rounded-lg border border-green-700 px-4 py-3 font-bold text-green-800" href={`/report/verify?certificateId=${encodeURIComponent(report.certificateId)}`}>{en?"Verify":"진위 확인"}</a></>}</div></div></article>)}{!reports.some(r=>r.status==="FINALIZED")&&<p className="rounded-xl border bg-white p-12 text-center text-slate-500">{en?"No finalized report.":"확정된 보고서가 없습니다."}</p>}</div></div></main>;
}
