import {useEffect,useState} from "react";
import {useAsyncValue} from "../../app/hooks/useAsyncValue";
import {fetchHomePayload} from "../../lib/api/appBootstrap";
import {buildLocalizedPath,isEnglish} from "../../lib/navigation/runtime";
import {HeaderBrand,HeaderDesktopNav,HomeInlineStyles} from "../home-entry/HomeEntrySections";
import {LOCALIZED_CONTENT} from "../home-entry/homeEntryContent";

type Report={id:number;version:number;title:string;language:string;status:string;summary?:string;createdBy:string;createdAt:string;finalizedBy?:string;finalizedAt?:string};
type Payload={project:{id:string;name:string;site:string;period:string;scope:string;progress:number;status:string};approved?:{submissionVersion:number;calculationVersion:number;totalEmission:number;lockedAt:string;lockedBy:string};reports:Report[]};
async function payload(r:Response){const t=await r.text();let b:any={};try{b=t?JSON.parse(t):{}}catch{throw new Error("서버 응답 형식이 올바르지 않습니다.")}if(!r.ok)throw new Error(b.message||"요청을 처리하지 못했습니다.");return b}

export function EmissionProjectReportPage(){
 const en=isEnglish(),content=LOCALIZED_CONTENT[en?"en":"ko"],home=useAsyncValue(()=>fetchHomePayload(),[en]);
 const id=new URLSearchParams(location.search).get("projectId")||""; const base=buildLocalizedPath(`/home/api/emission-projects/${id}/reports`,`/en/home/api/emission-projects/${id}/reports`);
 const[data,setData]=useState<Payload|null>(null),[language,setLanguage]=useState(en?"en":"ko"),[title,setTitle]=useState(""),[summary,setSummary]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function load(){setData(await payload(await fetch(base,{credentials:"include",headers:{Accept:"application/json"}})))}
 useEffect(()=>{if(id)void load().catch(e=>setMessage(e.message))},[id]);
 async function create(){setBusy(true);setMessage("");try{await payload(await fetch(base,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({language,title,summary})}));setTitle("");setSummary("");setMessage(en?"A report draft was created.":"보고서 초안을 생성했습니다.");await load()}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function finalize(reportId:number){if(!confirm(en?"Finalize this report? It will become the official project result.":"이 보고서를 최종 확정하시겠습니까? 프로젝트 공식 결과로 처리됩니다."))return;setBusy(true);try{await payload(await fetch(`${base}/${reportId}/finalize`,{method:"POST",credentials:"include",headers:{Accept:"application/json"}}));setMessage(en?"The report and project were finalized.":"보고서와 프로젝트를 최종 확정했습니다.");await load()}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 if(!id)return <main className="p-10 font-bold text-red-700">{en?"Select a project first.":"프로젝트를 먼저 선택해 주세요."}</main>;
 const approved=data?.approved;
 return <><HomeInlineStyles en={en}/><div className="min-h-screen bg-[#f5f7fa]"><header className="border-b-2 border-[#001e40] bg-white"><div className="mx-auto flex h-16 max-w-7xl items-center px-4 lg:px-8"><HeaderBrand content={content} en={en}/><HeaderDesktopNav en={en} homeMenu={home.value?.homeMenu||[]}/></div></header><main className="mx-auto max-w-7xl px-4 py-8 lg:px-8">
  <nav className="text-sm text-slate-500"><a href={buildLocalizedPath(`/emission/project/detail?id=${id}`,`/en/emission/project/detail?id=${id}`)}>{data?.project.name||id}</a><span className="mx-2">/</span>{en?"Finalization & Report":"확정·보고"}</nav>
  <div className="mt-4 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="font-bold text-[#246beb]">{data?.project.site}</p><h1 className="mt-1 text-3xl font-black text-[#052b57]">{en?"Emission Report Finalization":"배출량 보고서 작성·확정"}</h1><p className="mt-2 text-slate-600">{en?"Create an official report only from the approved, locked calculation version.":"승인되어 잠긴 산정 버전만 공식 보고서로 작성하고 확정합니다."}</p></div><a className="rounded-lg border border-[#246beb] bg-white px-5 py-3 font-bold text-[#246beb]" href={buildLocalizedPath(`/emission/validate?projectId=${id}`,`/en/emission/validate?projectId=${id}`)}>{en?"Review approval history":"승인 이력 확인"}</a></div>
  {message&&<p className="mt-5 rounded-lg border border-blue-200 bg-blue-50 p-4 font-bold text-blue-900">{message}</p>}
  <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[en?"Submission":"제출 버전",approved?`V${approved.submissionVersion}`:"-"],[en?"Calculation":"산정 버전",approved?`V${approved.calculationVersion}`:"-"],[en?"Total Emissions":"총배출량",approved?`${Number(approved.totalEmission).toLocaleString()} tCO₂e`:"-"],[en?"Project Status":"프로젝트 상태",data?.project.status||"-"]].map(([l,v])=><div className="rounded-xl border bg-white p-5" key={l}><p className="text-sm font-bold text-slate-500">{l}</p><strong className="mt-2 block text-2xl text-[#052b57]">{v}</strong></div>)}</section>
  {!approved?<section className="mt-6 rounded-xl border border-amber-300 bg-amber-50 p-7"><h2 className="text-xl font-black text-amber-950">{en?"Approval is required":"승인된 산정 결과가 필요합니다."}</h2><p className="mt-2 text-amber-900">{en?"Complete calculation verification and approval before creating a report.":"산정 결과 검증과 승인을 완료한 뒤 보고서를 생성할 수 있습니다."}</p></section>:
  <section className="mt-6 rounded-xl border bg-white p-6"><h2 className="text-xl font-black text-[#052b57]">{en?"Create report draft":"보고서 초안 생성"}</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm font-bold">{en?"Language":"언어"}<select className="mt-2 h-12 w-full rounded-lg border px-3" value={language} onChange={e=>setLanguage(e.target.value)}><option value="ko">한국어</option><option value="en">English</option></select></label><label className="text-sm font-bold">{en?"Report title":"보고서 제목"}<input className="mt-2 h-12 w-full rounded-lg border px-3" value={title} onChange={e=>setTitle(e.target.value)} placeholder={en?"Defaults to the project name":"미입력 시 프로젝트명으로 자동 생성"}/></label><label className="text-sm font-bold md:col-span-2">{en?"Executive summary":"보고 요약"}<textarea className="mt-2 min-h-28 w-full rounded-lg border p-3" value={summary} onChange={e=>setSummary(e.target.value)} placeholder={en?"Describe scope, result, and important review notes.":"산정 범위, 결과 및 주요 검토 내용을 입력하세요."}/></label></div><div className="mt-4 text-right"><button disabled={busy} onClick={()=>void create()} className="rounded-lg bg-[#246beb] px-6 py-3 font-black text-white disabled:opacity-50">{en?"Create new version":"새 보고서 버전 생성"}</button></div></section>}
  <section className="mt-6 overflow-hidden rounded-xl border bg-white"><div className="border-b p-5"><h2 className="text-xl font-black text-[#052b57]">{en?"Report versions":"보고서 버전 및 확정 이력"}</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left"><thead className="bg-slate-100"><tr>{(en?["Version","Title","Language","Status","Created","Actions"]:["버전","제목","언어","상태","생성 정보","처리"]).map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{data?.reports.map(r=><tr className="border-t" key={r.id}><td className="p-3 font-black">V{r.version}</td><td><strong>{r.title}</strong>{r.summary&&<small className="mt-1 block max-w-md truncate text-slate-500">{r.summary}</small>}</td><td>{r.language.toUpperCase()}</td><td><span className={`rounded-full px-2 py-1 text-xs font-black ${r.status==="FINALIZED"?"bg-green-100 text-green-800":"bg-blue-100 text-blue-800"}`}>{r.status}</span></td><td className="text-sm">{r.createdBy}<small className="block text-slate-500">{new Date(r.createdAt).toLocaleString()}</small></td><td><div className="flex gap-2"><button onClick={()=>window.print()} className="rounded-lg border px-3 py-2 font-bold">{en?"Print / PDF":"인쇄·PDF"}</button>{r.status==="DRAFT"&&<button disabled={busy} onClick={()=>void finalize(r.id)} className="rounded-lg bg-[#052b57] px-3 py-2 font-bold text-white">{en?"Finalize":"최종 확정"}</button>}</div></td></tr>)}{!data?.reports.length&&<tr><td colSpan={6} className="p-10 text-center text-slate-500">{en?"No report versions yet.":"생성된 보고서가 없습니다."}</td></tr>}</tbody></table></div></section>
 </main></div></>;
}
