import {CommonBreadcrumb} from '../../components/common-design/CommonBreadcrumb';
import {FormEvent,useEffect,useRef,useState} from 'react';
import {useAsyncValue} from '../../app/hooks/useAsyncValue';
import {fetchHomePayload} from '../../lib/api/appBootstrap';
import {HeaderBrand,HeaderDesktopNav,HomeInlineStyles} from '../home-entry/HomeEntrySections';
import {LOCALIZED_CONTENT} from '../home-entry/homeEntryContent';
import {isEnglish,buildLocalizedPath,navigate} from '../../lib/navigation/runtime';
import './emissionProjectListV1.css';
type Site={id:string;code:string;name:string;address:string};
export function EmissionProjectCreatePage(){
 const en=isEnglish(),t=(ko:string,eng:string)=>en?eng:ko,content=LOCALIZED_CONTENT[en?'en':'ko'],home=useAsyncValue(()=>fetchHomePayload(),[en]);
 const [name,setName]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[description,setDescription]=useState(''),[selected,setSelected]=useState<string[]>([]),[sites,setSites]=useState<Site[]>([]),[keyword,setKeyword]=useState(''),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState(false),[reload,setReload]=useState(0);
 const lock=useRef(false),request=useRef({payload:'',id:''});
 const api=buildLocalizedPath('/home/api/emission-project-drafts','/en/home/api/emission-project-drafts');
 useEffect(()=>{const c=new AbortController();setLoading(true);setLoadError('');fetch(api+'/options',{credentials:'include',signal:c.signal}).then(async r=>{const b=await r.json();if(!r.ok)throw Error(b.message||'사업장을 불러오지 못했습니다.');if(!Array.isArray(b.sites))throw Error('사업장 응답 형식을 확인해 주세요.');setSites(b.sites);}).catch(e=>{if(e.name!=='AbortError')setLoadError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[api,reload]);
 const dirty=Boolean(name||start||end||description||selected.length);
 useEffect(()=>{const fn=(e:BeforeUnloadEvent)=>{if(dirty&&!lock.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn);},[dirty]);
 async function submit(e:FormEvent){e.preventDefault();if(lock.current)return;setMessage('');if(loading||loadError)return setMessage(t('사업장 목록을 정상적으로 불러온 뒤 저장해 주세요.','Reload sites before saving.'));if(!name.trim()||!start||!end||!selected.length)return setMessage(t('프로젝트명·기간·사업장을 입력해 주세요.','Enter the name, period and sites.'));if(start>end)return setMessage(t('시작일은 종료일보다 늦을 수 없습니다.','Start must not be after end.'));if(selected.some(id=>!sites.some(s=>s.id===id)))return setMessage(t('선택한 사업장을 다시 확인해 주세요.','Check selected sites.'));
 const body={name:name.trim(),periodStart:start,periodEnd:end,siteIds:[...selected].sort(),description:description.trim()},payload=JSON.stringify(body);if(request.current.payload!==payload)request.current={payload,id:globalThis.crypto?.randomUUID?.()||`request_${Date.now()}_${Math.random().toString(36).slice(2)}`};lock.current=true;setSaving(true);
 try{const r=await fetch(api,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,clientRequestId:request.current.id})});const b=await r.json();if(!r.ok)throw Error(b.message||'저장 실패');if(!b.id)throw Error('저장된 프로젝트 ID가 없습니다.');navigate(buildLocalizedPath(`/emission/project/detail?projectId=${encodeURIComponent(b.id)}`,`/en/emission/project/detail?projectId=${encodeURIComponent(b.id)}`));}catch(e){setMessage(e instanceof Error?e.message:'저장 실패');lock.current=false;}finally{setSaving(false);}
 }
 return <><HomeInlineStyles en={en}/><div className="min-h-screen bg-white text-slate-900"><header className="border-b-2 border-[#001e40]"><div className="mx-auto flex h-20 max-w-7xl items-center px-4"><HeaderBrand content={content} en={en}/><HeaderDesktopNav en={en} homeMenu={home.value?.homeMenu||[]}/></div></header><main className="mx-auto max-w-[1220px] px-4 py-8"><CommonBreadcrumb/>

 <h1 className="text-3xl font-bold">{t('배출량 프로젝트 등록','New emission project')}</h1><p className="mb-8 mt-3 text-slate-600">{t('프로젝트 이름, 산정 기간과 참여 사업장을 저장합니다. 산정 기준과 업무 담당자는 이후에 설정합니다.','Save the name, period and participating sites. Configure methodology and work assignments later.')}</p>
 <form onSubmit={submit} className="space-y-6"><fieldset disabled={saving} className="space-y-6"><legend className="sr-only">{t('프로젝트 기본정보','Project information')}</legend>
 <label className="block font-bold">{t('프로젝트명 *','Project name *')}<input required maxLength={200} value={name} onChange={e=>setName(e.target.value)} className="mt-2 block w-full rounded border border-slate-400 p-3"/></label>
 <div className="grid gap-5 sm:grid-cols-2"><label className="font-bold">{t('산정 시작일 *','Start date *')}<input type="date" required min="2000-01-01" max="2100-12-31" value={start} onChange={e=>setStart(e.target.value)} className="mt-2 block w-full rounded border border-slate-400 p-3"/></label><label className="font-bold">{t('산정 종료일 *','End date *')}<input type="date" required min={start||'2000-01-01'} max="2100-12-31" value={end} onChange={e=>setEnd(e.target.value)} className="mt-2 block w-full rounded border border-slate-400 p-3"/></label></div>
 <section aria-label={t('참여 사업장','Sites')} className="border-y border-slate-300 py-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-bold">{t('참여 사업장 *','Sites *')} · {t('선택','Selected')} {selected.length}{t('개','')}</h2><div className="flex gap-2"><a target="_blank" rel="noopener" href={buildLocalizedPath('/admin/emission/site-management','/en/admin/emission/site-management')} className="rounded border px-3 py-2">{t('사업장 등록·관리 (새 탭)','Manage sites (new tab)')}</a><button type="button" onClick={()=>setReload(x=>x+1)} className="rounded border px-3 py-2">{t('목록 다시 불러오기','Reload')}</button></div></div>
 <p className="my-2 text-sm text-slate-600">{t('같은 회사의 활성 사업장만 선택할 수 있습니다. 사업장 관리는 해당 메뉴 권한이 필요합니다.','Select active sites in your company. Site management requires separate permission.')}</p>
 <div className="my-3 flex gap-2"><input aria-label={t('사업장 검색','Search sites')} placeholder={t('사업장명·코드·주소 검색','Search name, code or address')} value={keyword} onChange={e=>setKeyword(e.target.value)} className="w-full rounded border p-3"/><button type="button" onClick={()=>setSelected([])} className="shrink-0 rounded border px-3">{t('선택 해제','Clear selection')}</button></div>
 {loading?<p role="status">{t('사업장 불러오는 중…','Loading sites…')}</p>:loadError?<p role="alert" className="text-red-700">{loadError}</p>:<div className="max-h-80 overflow-auto"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-slate-100"><tr>{[t('선택','Select'),t('사업장명','Site'),t('코드','Code'),t('주소','Address')].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{sites.filter(s=>`${s.name} ${s.code} ${s.address}`.toLowerCase().includes(keyword.toLowerCase())).map(s=><tr key={s.id} className="border-b"><td className="p-3"><input type="checkbox" aria-label={s.name} checked={selected.includes(s.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,s.id]:ids.filter(id=>id!==s.id))}/></td><td className="p-3">{s.name}</td><td className="p-3">{s.code}</td><td className="p-3">{s.address}</td></tr>)}</tbody></table>{sites.length===0&&<p className="p-4">{t('등록 가능한 사업장이 없습니다. 사업장 등록 후 다시 불러와 주세요.','No available sites. Register a site and reload.')}</p>}</div>}</section>
 <label className="block font-bold">{t('설명 (선택)','Description (optional)')}<textarea maxLength={2000} rows={3} value={description} onChange={e=>setDescription(e.target.value)} className="mt-2 block w-full rounded border border-slate-400 p-3"/></label></fieldset>
 {message&&<p role="alert" className="rounded border border-red-300 bg-red-50 p-4 text-red-800">{message}</p>}<div className="flex justify-end gap-3"><a href={buildLocalizedPath('/emission/project_list','/en/emission/project_list')} className="rounded border px-5 py-3">{t('취소·목록','Cancel')}</a><button type="submit" disabled={saving||loading||!!loadError} className="rounded bg-[#003675] px-5 py-3 font-bold text-white disabled:opacity-50">{saving?t('저장 중…','Saving…'):t('저장 후 상세 보기','Save and open details')}</button></div></form>
 <details className="mt-8 border-t py-4"><summary className="font-bold">{t('이 화면의 업무 안내','Page guidance')}</summary><p className="mt-3">{t('등록은 기간과 사업장 연결만 저장합니다. 산정 완료나 결재 완료가 아닙니다. 저장 실패 시 입력값을 유지하며 동일 요청 재시도는 중복 생성하지 않습니다.','Registration saves period and site links, not a calculation or approval. Failed requests retain input; retrying the same request does not create duplicates.')}</p></details>
 </main></div></>;
}
