import {useEffect,useState} from 'react';
import {CommonPageContainer} from '../../components/common-design/CommonDesignPrimitives';
import {buildLocalizedPath} from '../../lib/navigation/runtime';
type Target={submissionId:number;calculationId:number;version:number;totalEmission:number;resultUnit:string};
type Lock={lockId:number;version:number;totalEmission:number;resultUnit:string;lockHash:string;lockedBy:string;lockedAt:string;integrity:string};
type State={eligible:boolean;message:string;approvedTarget?:Target;lock?:Lock};
type Project={id:string;name:string;site?:string;periodStart?:string;periodEnd?:string;status?:string};
export function EmissionResultFinalizationPage(){
 const id=new URLSearchParams(location.search).get('projectId')||'',encoded=encodeURIComponent(id),api=buildLocalizedPath(`/home/api/emission-projects/${encoded}/result-lock`,`/en/home/api/emission-projects/${encoded}/result-lock`);
 const [data,setData]=useState<State|null>(null),[audit,setAudit]=useState<Lock[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [projects,setProjects]=useState<Project[]>([]),[query,setQuery]=useState(''),[projectError,setProjectError]=useState(''),[projectsLoading,setProjectsLoading]=useState(!id);
 async function request(url:string,init?:RequestInit){const r=await fetch(url,{credentials:'include',...init,headers:{Accept:'application/json',...init?.headers}});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(`결과 확정 요청 실패 (${r.status}). ${r.status>=500?'서버 저장소를 점검해야 합니다.':b.message||'권한과 승인 상태를 확인하세요.'}`);return b;}
 useEffect(()=>{if(id)return;let active=true;setProjectsLoading(true);setProjectError('');void request(buildLocalizedPath('/home/api/emission-projects?keyword=&page=1&size=100','/en/home/api/emission-projects?keyword=&page=1&size=100')).then(b=>{if(active)setProjects(Array.isArray(b.items)?b.items:[])}).catch(e=>{if(active)setProjectError(e instanceof Error?e.message:String(e))}).finally(()=>{if(active)setProjectsLoading(false)});return()=>{active=false}},[id]);
 async function load(){setBusy(true);setError('');try{const b=await request(api);setData(b);const a=await request(api+'/audit');setAudit(a.items||[]);}catch(e){setData(null);setError(e instanceof Error?e.message:String(e));}finally{setBusy(false)}}
 useEffect(()=>{if(id)void load()},[id]);
 async function lock(){if(!data?.eligible||!data.approvedTarget||!confirm('승인된 산정 결과를 확정하고 변경할 수 없도록 잠그시겠습니까?'))return;setBusy(true);setError('');try{const target=data.approvedTarget;await request(api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({submissionId:target.submissionId,calculationId:target.calculationId,idempotencyKey:`RESULT-LOCK-${id}-${target.calculationId}`})});setMessage('승인 결과를 확정했습니다.');await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 const link=(path:string)=>buildLocalizedPath(`${path}?projectId=${encoded}`,`/en${path}?projectId=${encoded}`),target=data?.lock||data?.approvedTarget;
 return <CommonPageContainer style={{background:'#f5f7fa'}}><header className="rounded-xl border border-blue-200 bg-blue-50 p-6"><p className="font-bold text-blue-800">탄소배출 관리 · 배출량 프로젝트</p><h1 className="mt-2 text-3xl font-black text-[#052b57]">산정 결과 확정</h1><p className="mt-2 text-slate-700">승인된 산정 버전을 확인하고 보고서 기준 버전으로 확정합니다.</p></header>
 {!id?<section className="mt-5 overflow-hidden rounded-xl border bg-white"><div className="border-b p-5"><h2 className="text-xl font-black text-[#052b57]">확정할 프로젝트 선택</h2><p className="mt-1 text-sm text-slate-600">프로젝트를 선택하면 승인된 산정 버전과 확정 상태를 조회합니다.</p><form className="mt-4 flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();setQuery(query.trim())}}><input aria-label="프로젝트 검색" className="h-11 min-w-64 flex-1 rounded-lg border px-3" placeholder="프로젝트명·ID·사업장 검색" value={query} onChange={e=>setQuery(e.target.value)}/><button className="h-11 rounded-lg bg-[#003675] px-5 font-bold text-white">검색</button></form></div>{projectError&&<p role="alert" className="m-5 rounded-lg bg-red-50 p-4 text-red-800">프로젝트 목록 조회 실패: {projectError}</p>}{projectsLoading?<p role="status" className="p-8 text-center">프로젝트를 불러오는 중입니다.</p>:<div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-slate-100"><tr>{['프로젝트','사업장','산정 기간','선택'].map(x=><th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody>{projects.filter(p=>`${p.id} ${p.name} ${p.site||''}`.toLowerCase().includes(query.toLowerCase())).map(p=><tr className="border-t" key={p.id}><td className="p-4"><strong>{p.name}</strong><small className="block text-slate-500">{p.id}</small></td><td className="p-4">{p.site||'—'}</td><td className="p-4">{p.periodStart&&p.periodEnd?`${p.periodStart} ~ ${p.periodEnd}`:'—'}</td><td className="p-4"><a className="inline-flex min-h-10 items-center rounded-lg bg-[#003675] px-4 font-bold text-white" href={`${location.pathname}?projectId=${encodeURIComponent(p.id)}`}>선택</a></td></tr>)}{!projects.length&&<tr><td colSpan={4} className="p-8 text-center text-slate-600">접근 가능한 프로젝트가 없습니다.</td></tr>}</tbody></table></div>}</section>:<><div className="my-5 flex flex-wrap items-center gap-3 rounded-xl border bg-white p-4"><strong className="mr-auto text-[#052b57]">선택 프로젝트: {id}</strong><a className="rounded border px-4 py-2" href={location.pathname}>프로젝트 변경</a><a className="rounded border px-4 py-2" href={link('/emission/review-approval')}>검토·승인 확인</a><button className="rounded border px-4 py-2" disabled={busy} onClick={()=>void load()}>새로고침</button><button className="rounded bg-blue-900 px-4 py-2 text-white disabled:opacity-40" disabled={busy||!data?.eligible||Boolean(data?.lock)} onClick={()=>void lock()}>승인 결과 확정</button>{data?.lock&&<a className="rounded border px-4 py-2" href={link('/emission/report-write')}>보고서 작성</a>}</div>
 {error&&<p role="alert" className="my-4 text-red-800">{error}</p>}{message&&<p role="status">{message}</p>}{busy&&<p role="status">처리 중…</p>}
 {data&&<section className="my-6"><h2 className="text-xl font-bold">확정 대상</h2><p className="my-3">{data.message}</p>{target?<dl className="grid grid-cols-[140px_1fr] gap-3 border-y py-4"><dt>산정 버전</dt><dd>{target.version}</dd><dt>총배출량</dt><dd>{target.totalEmission} {target.resultUnit}</dd><dt>확정 상태</dt><dd>{data.lock?'확정·잠금':'미확정'}</dd>{data.lock&&<><dt>확정자·일시</dt><dd>{data.lock.lockedBy} · {data.lock.lockedAt}</dd><dt>무결성 확인</dt><dd>{data.lock.integrity}</dd></>}</dl>:<p>승인된 산정 버전이 없습니다. 검증·승인을 먼저 완료하세요.</p>}</section>}
 {data&&<section><h2 className="text-xl font-bold">확정 이력</h2><ul className="my-4">{audit.map(x=><li className="border-b py-3" key={x.lockId}>V{x.version} · {x.lockedBy} · {x.lockedAt} · {x.integrity}</li>)}</ul>{!audit.length&&<p>확정 이력이 없습니다.</p>}</section>}
 <details className="my-6"><summary>결과 확정 도움말</summary><p className="mt-3">승인 권한과 승인된 산정 버전이 필요합니다. 확정 결과는 변경하지 않고 새 산정 버전으로 재검증·재승인합니다. 보고서는 확정된 버전을 사용합니다.</p></details></>}
 </CommonPageContainer>
}
