import { useEffect,useState } from "react";
import { buildLocalizedPath,isEnglish } from "../../lib/navigation/runtime";
import { CommonPageContainer } from "../../components/common-design/CommonDesignPrimitives";

type Submission={id:number;version:number;state:string;submittedActor?:string;submittedAt?:string;calculationId?:number;requestId?:number;locked?:boolean};
type Review={id:number;submissionId:number;stage:string;decision:string;reviewer:string;comment?:string;issueCount:number;createdAt:string};
type ApprovalRequest={approval_request_id:number;input_revision:number;submission_id:number;calculation_id:number;request_status:string;approver_id:string;decision_reason?:string};
type Payload={project:{id:string;name:string;site:string};submissions:Submission[];reviews:Review[];actors:{actorCode:string;userId:string}[];currentContract?:{input_revision:number;submission_id:number;calculation_id:number;approval_request_id?:number;request_status?:string;approval_current:boolean};approvalRequests?:ApprovalRequest[]};
type ProjectOption={id:string;name:string;site?:string;period?:string;status?:string;step?:string};
type ProjectListPayload={items:ProjectOption[];total?:number};

async function readApiPayload(response:Response){
  const text=await response.text();
  const contentType=response.headers.get("content-type")||"";
  if(!contentType.includes("application/json")){
    if(response.status===401||response.redirected) throw new Error("로그인 세션이 만료되었습니다. 다시 로그인해 주세요.");
    throw new Error(`서버가 JSON 대신 HTML을 반환했습니다. (${response.status})`);
  }
  try{return JSON.parse(text)}catch{throw new Error(`서버 JSON 응답 형식이 올바르지 않습니다. (${response.status})`)}
}

export function EmissionProjectReviewPage(){
  const en=isEnglish();
  const[approver,setApprover]=useState("");
  const id=new URLSearchParams(location.search).get("projectId")||"";
  const[data,setData]=useState<Payload|null>(null),[selected,setSelected]=useState<number>(0),[comment,setComment]=useState(""),[issues,setIssues]=useState(0),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[projects,setProjects]=useState<ProjectOption[]>([]),[projectLoading,setProjectLoading]=useState(false),[projectKeyword,setProjectKeyword]=useState("");
  const base=buildLocalizedPath(`/home/api/emission-projects/${id}`,`/en/home/api/emission-projects/${id}`);
  async function load(){const r=await fetch(`${base}/review-workflow`,{credentials:"include",headers:{Accept:"application/json"}}),b=await readApiPayload(r);if(!r.ok)throw new Error(b.message||"Load failed");setData(b);setSelected((value)=>value||b.submissions?.[0]?.id||0)}
  useEffect(()=>{if(id){void load().catch(e=>setMessage(e.message));return}let cancelled=false;setProjectLoading(true);void fetch(buildLocalizedPath("/home/api/emission-projects?page=1&size=100","/en/home/api/emission-projects?page=1&size=100"),{credentials:"include",cache:"no-store",headers:{Accept:"application/json"}}).then(readApiPayload).then((body:ProjectListPayload)=>{if(!cancelled)setProjects(body.items||[])}).catch(e=>{if(!cancelled)setMessage(e instanceof Error?e.message:String(e))}).finally(()=>{if(!cancelled)setProjectLoading(false)});return()=>{cancelled=true}},[id]);
  async function action(path:string,body?:object){if(!selected)return;setBusy(true);setMessage("");try{const command={...body,...(path==='approval/decision'?{approvalRequestId:data?.currentContract?.approval_request_id}:{})};const r=await fetch(`${base}/submissions/${selected}/${path}`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify(command)}),b=await readApiPayload(r);if(!r.ok)throw new Error(b.message||"Action failed");setMessage(en?"The workflow was updated.":"업무 상태가 변경되었습니다.");setComment("");await load()}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
  if(!id){const filtered=projects.filter(p=>`${p.id} ${p.name} ${p.site||""}`.toLowerCase().includes(projectKeyword.toLowerCase()));return <CommonPageContainer><nav className="text-sm text-slate-500">{en?"Emission Management":"탄소배출 관리"}<span className="mx-2">/</span>{en?"Verification & Correction":"검증·보완"}</nav><header className="mt-5 rounded-xl border border-blue-200 bg-blue-50 p-6"><p className="font-bold text-blue-800">{en?"Emission Management":"탄소배출 관리"}</p><h1 className="mt-1 text-3xl font-black text-[#052b57]">{en?"Verification & Correction":"검증·보완"}</h1><p className="mt-2 text-slate-600">{en?"Select an authorized project to review submitted activity-data versions, record validation findings, and request corrections.":"프로젝트를 선택해 제출된 활동자료 버전을 검토하고, 검증 의견·오류 건수 기록 및 보완 요청을 처리합니다."}</p><p className="mt-3 text-sm font-bold text-slate-700">{en?"Only projects visible to your signed-in account are listed.":"로그인 계정에 허용된 프로젝트만 표시합니다."}</p></header>{message&&<p role="alert" className="mt-4 rounded-lg border border-red-200 bg-red-50 p-3 font-bold text-red-800">{message}</p>}<section className="mt-5 rounded-xl border bg-white p-5"><div className="flex flex-wrap items-end justify-between gap-3"><label className="min-w-64 flex-1 text-sm font-bold">{en?"Search projects":"프로젝트 검색"}<input value={projectKeyword} onChange={e=>setProjectKeyword(e.target.value)} className="mt-1 w-full rounded-lg border p-3 font-normal" placeholder={en?"Project, site, or ID":"프로젝트명·사업장·ID"}/></label><span className="pb-3 text-sm text-slate-500">{projectLoading?(en?"Loading…":"불러오는 중…"):`${filtered.length}${en?" projects":"개 프로젝트"}`}</span></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[680px] text-left"><thead className="bg-slate-100"><tr>{(en?["Project","Site","Period","Status","Action"]:["프로젝트","사업장","기간","현재 상태","업무"]).map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{filtered.map(p=><tr className="border-t" key={p.id}><td className="p-3"><strong>{p.name}</strong><small className="block text-slate-500">{p.id}</small></td><td className="p-3">{p.site||"-"}</td><td className="p-3">{p.period||"-"}</td><td className="p-3">{p.step||p.status||"-"}</td><td className="p-3"><a className="inline-flex rounded-lg bg-[#003675] px-4 py-2 font-bold text-white" href={buildLocalizedPath(`/emission/data-validation?projectId=${encodeURIComponent(p.id)}`,`/en/emission/data-validation?projectId=${encodeURIComponent(p.id)}`)}>{en?"Review":"검증·보완"}</a></td></tr>)}{!projectLoading&&!filtered.length&&<tr><td colSpan={5} className="p-10 text-center text-slate-500">{en?"No authorized projects found.":"접근 가능한 프로젝트가 없습니다."}</td></tr>}</tbody></table></div></section></CommonPageContainer>}
  const current=data?.submissions.find(x=>x.id===selected);
  return <CommonPageContainer>

    <div className="mt-4"><p className="font-bold text-blue-700">{data?.project.site}</p><h1 className="text-3xl font-black text-[#052b57]">{en?"Verification, Correction And Approval":"검증·보완·승인"}</h1><p className="mt-2 text-slate-600">{en?"Review submitted versions, request corrections, and lock approved calculations.":"제출 버전을 검증하고 보완 요청·승인·산정 결과 잠금을 처리합니다."}</p><div className="mt-4 flex flex-wrap items-center gap-2"><span className="text-sm font-black text-slate-600">{en?"Assigned actors":"배정 액터"}</span>{data?.actors.map(a=><span key={`${a.actorCode}-${a.userId}`} className="rounded-full border border-blue-200 bg-blue-50 px-3 py-1 text-xs font-bold text-blue-800">{a.actorCode} · {a.userId}</span>)}<a className="ml-auto font-bold text-blue-700 underline" href={buildLocalizedPath(`/emission/result?projectId=${id}`,`/en/emission/result?projectId=${id}`)}>{en?"Check calculation":"산정 결과 확인"}</a></div></div>
    {message&&<p className="mt-4 rounded-lg bg-blue-50 p-3 font-bold text-blue-800" role="status">{message}</p>}
    <section className="mt-6 border rounded p-5 bg-white" aria-label="현재 버전 승인 요청"><h2 className="text-xl font-bold">현재 버전 승인 요청</h2><p>입력 버전 {data?.currentContract?.input_revision??'-'} · 제출 {data?.currentContract?.submission_id??'-'} · 산정 {data?.currentContract?.calculation_id??'-'} · 승인 요청 {data?.currentContract?.approval_request_id??'-'} · {data?.currentContract?.request_status??'미요청'}</p><div className="mt-3 flex flex-wrap gap-3"><label>결재자 <select value={approver} onChange={e=>setApprover(e.target.value)} className="border rounded p-2"><option value="">선택</option>{data?.actors.filter(a=>a.actorCode==='APPROVER').map(a=><option key={a.userId} value={a.userId}>{a.userId}</option>)}</select></label><button className="border rounded px-4 py-2 bg-blue-800 text-white disabled:opacity-40" disabled={busy||!approver||current?.state!=='VERIFIED'||selected!==data?.currentContract?.submission_id||data?.currentContract?.request_status==='PENDING'} onClick={()=>void action('approval/request',{approverId:approver,inputRevision:data?.currentContract?.input_revision,calculationId:data?.currentContract?.calculation_id,idempotencyKey:`APPROVAL-${id}-${data?.currentContract?.input_revision}-${selected}-${data?.currentContract?.calculation_id}`})}>승인 요청</button></div><details className="mt-3"><summary>승인 요청 이력</summary>{data?.approvalRequests?.map(a=><p key={a.approval_request_id}>요청 {a.approval_request_id} · 입력 V{a.input_revision} · 산정 {a.calculation_id} · {a.request_status} · {a.approver_id} · {a.decision_reason}</p>)}</details></section>
    <section className="mt-6 grid gap-5 lg:grid-cols-[320px_1fr]"><aside className="rounded-xl border bg-white p-4"><h2 className="font-black">{en?"Submission Versions":"제출 버전"}</h2><div className="mt-3 space-y-2">{data?.submissions.map(x=><button key={x.id} onClick={()=>setSelected(x.id)} className={`w-full rounded-lg border p-3 text-left ${selected===x.id?"border-blue-600 bg-blue-50":"border-slate-200"}`}><strong>V{x.version}</strong><span className="float-right rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{x.state}</span><small className="mt-2 block text-slate-500">{x.submittedActor||"-"}</small></button>)}{!data?.submissions.length&&<p className="py-8 text-center text-slate-500">{en?"No submission.":"제출 자료가 없습니다."}</p>}</div></aside>
      <div className="space-y-5"><section className="rounded-xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">{en?"Current Decision":"현재 처리"}</h2><p className="text-sm text-slate-500">{current?`V${current.version} · ${current.state}${current.locked?" · LOCKED":""}`:"-"}</p></div><div className="flex flex-wrap gap-2"><button disabled={busy||current?.state!=="SUBMITTED"} onClick={()=>void action("verification/start")} className="rounded-lg border border-blue-600 px-4 py-2 font-bold text-blue-700 disabled:opacity-40">{en?"Start Verification":"검증 시작"}</button><button disabled={busy||current?.state!=="IN_VERIFICATION"} onClick={()=>void action("verification/decision",{decision:"PASSED",comment,issueCount:issues})} className="rounded-lg bg-emerald-700 px-4 py-2 font-bold text-white disabled:opacity-40">{en?"Pass":"검증 통과"}</button><button disabled={busy||current?.state!=="IN_VERIFICATION"||!comment.trim()||!current?.requestId} onClick={()=>void action("verification/decision",{decision:"CORRECTION_REQUESTED",comment,issueCount:issues,requestId:current?.requestId,findingCode:`VERIFY-${selected}-${Date.now()}`})} className="rounded-lg bg-orange-600 px-4 py-2 font-bold text-white disabled:opacity-40">{en?"Request Correction":"보완 요청"}</button><button disabled={busy||current?.state!=="VERIFIED"} onClick={()=>void action("approval/decision",{decision:"APPROVED",comment})} className="rounded-lg bg-blue-700 px-4 py-2 font-bold text-white disabled:opacity-40">{en?"Approve":"승인"}</button><button disabled={busy||current?.state!=="VERIFIED"||!comment.trim()} onClick={()=>void action("approval/decision",{decision:"REJECTED",comment})} className="rounded-lg border border-red-600 px-4 py-2 font-bold text-red-700 disabled:opacity-40">{en?"Reject":"반려"}</button><button disabled={busy||current?.state!=="APPROVED"||!current?.calculationId||current?.locked} onClick={()=>void action(`calculations/${current?.calculationId}/lock`,{idempotencyKey:`LOCK-${id}-${current?.calculationId}`})} className="rounded-lg bg-slate-950 px-4 py-2 font-bold text-white disabled:opacity-40">{en?"Lock Result":"결과 잠금"}</button></div></div><div className="mt-4 grid gap-3 sm:grid-cols-[140px_1fr]"><label className="text-sm font-bold">{en?"Issue Count":"오류 건수"}<input type="number" min={0} value={issues} onChange={e=>setIssues(Number(e.target.value))} className="mt-1 w-full rounded-lg border p-2"/></label><label className="text-sm font-bold">{en?"Review Comment":"검토 의견"}<textarea value={comment} onChange={e=>setComment(e.target.value)} className="mt-1 min-h-20 w-full rounded-lg border p-2" placeholder={en?"A reason is required for correction or rejection.":"보완 요청과 반려에는 사유가 필수입니다."}/></label></div></section>
      <section className="overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[700px] text-left"><thead className="bg-slate-100"><tr>{(en?["Time","Version","Stage","Decision","Reviewer","Comment"]:["처리일시","버전","단계","결정","처리자","의견"]).map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{data?.reviews.map(x=><tr key={x.id} className="border-t"><td className="p-3 text-sm">{x.createdAt}</td><td>#{x.submissionId}</td><td>{x.stage}</td><td className="font-bold">{x.decision}</td><td>{x.reviewer}</td><td>{x.comment||"-"}</td></tr>)}{!data?.reviews.length&&<tr><td colSpan={6} className="p-10 text-center text-slate-500">{en?"No review history.":"검토 이력이 없습니다."}</td></tr>}</tbody></table></section></div>
    </section></CommonPageContainer>;
}
