import { useEffect, useState } from "react";
import { useAsyncValue } from "../../app/hooks/useAsyncValue";
import { fetchHomePayload } from "../../lib/api/appBootstrap";
import { buildLocalizedPath, isEnglish, navigate } from "../../lib/navigation/runtime";
import { HeaderBrand, HeaderDesktopNav, HomeInlineStyles } from "../home-entry/HomeEntrySections";
import { LOCALIZED_CONTENT } from "../home-entry/homeEntryContent";

type Task={code:string;name:string;order:number;status:string;weight:number;dueDate:string};
type Detail={id:string;name:string;site:string;period:string;scope:string;owner:string;progress:number;step:string;dueDate:string;status:string;tasks:Task[];members:{name:string;role:string}[];history:{type:string;description:string;actor:string;createdAt:string}[]};
const flows=[
  ["ACTIVITY_DATA","활동자료","Activity Data","/emission/data_input"], ["UPLOAD","엑셀 업로드","Excel Upload","/emission/data_input?mode=upload"], ["FACTOR","배출계수 매핑","Factor Mapping","/emission/data_input?tab=mapping"],
  ["CALCULATION","산정 결과","Calculation Results","/emission/result"], ["VERIFICATION","데이터 검증","Validation","/emission/validate"], ["APPROVAL","승인·확정","Approval","/emission/validate?tab=approval"], ["REPORT","보고서","Report","/emission/report_submit"]
];
export function EmissionProjectDetailPage(){
  const en=isEnglish(),content=LOCALIZED_CONTENT[en?"en":"ko"],home=useAsyncValue(()=>fetchHomePayload(),[en]); const id=new URLSearchParams(location.search).get("id")||"";
  const [data,setData]=useState<Detail|null>(null),[error,setError]=useState(""),[working,setWorking]=useState(false);
  const api=buildLocalizedPath(`/home/api/emission-projects/${encodeURIComponent(id)}`,`/en/home/api/emission-projects/${encodeURIComponent(id)}`);
  useEffect(()=>{ if(!id){setError(en?"No project was selected.":"프로젝트가 선택되지 않았습니다.");return;} fetch(api,{credentials:"include"}).then(async r=>{if(!r.ok)throw new Error(en?"Project not found.":"프로젝트를 찾을 수 없습니다.");return r.json();}).then(setData).catch(e=>setError(String(e.message||e))); },[id]);
  async function copy(){setWorking(true);try{const r=await fetch(`${api}/copy`,{method:"POST",credentials:"include"});const b=await r.json();if(!r.ok)throw new Error(b.message);navigate(buildLocalizedPath(`/emission/project/detail?id=${b.id}`,`/en/emission/project/detail?id=${b.id}`));}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setWorking(false);}}
  async function remove(){if(!confirm(en?"Delete this project?":"이 프로젝트를 삭제하시겠습니까?"))return;setWorking(true);try{const r=await fetch(api,{method:"DELETE",credentials:"include"});if(!r.ok)throw new Error(en?"Could not delete the project.":"프로젝트를 삭제하지 못했습니다.");navigate(buildLocalizedPath("/emission/project_list","/en/emission/project_list"));}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setWorking(false);}}
  return <><HomeInlineStyles en={en}/><div className="min-h-screen bg-[#f5f7fa]"><header className="border-b-2 border-[#001e40] bg-white"><div className="mx-auto flex h-16 max-w-7xl items-center px-4 lg:px-8"><HeaderBrand content={content} en={en}/><HeaderDesktopNav en={en} homeMenu={home.value?.homeMenu||[]}/></div></header><main className="mx-auto max-w-7xl px-4 py-8 lg:px-8">
    <nav className="text-sm text-slate-500"><a href={buildLocalizedPath("/emission/project_list","/en/emission/project_list")}>{en?"Emission Projects":"배출량 프로젝트"}</a><span className="mx-2">/</span>{en?"Project Detail":"프로젝트 상세"}</nav>
    {error&&<div className="mt-6 rounded-lg bg-red-50 p-4 font-bold text-red-700">{error}</div>}{!data&&!error&&<p className="mt-8">{en?"Loading...":"불러오는 중..."}</p>}
    {data&&<><section className="mt-5 rounded-2xl bg-[#052b57] p-6 text-white"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="text-sm font-bold text-blue-200">{data.id} · {data.status}</div><h1 className="mt-2 text-3xl font-black">{data.name}</h1><p className="mt-2 text-blue-100">{data.site} · {data.period} · {data.scope}</p></div><div className="flex gap-2"><button className="rounded-lg border border-white/50 px-4 py-3 font-bold" disabled={working} onClick={copy}>{en?"Copy":"복사"}</button><button className="rounded-lg border border-red-300 px-4 py-3 font-bold text-red-100" disabled={working} onClick={remove}>{en?"Delete":"삭제"}</button></div></div></section>
      <section className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[en?"Progress":"진행률",`${data.progress}%`],[en?"Current step":"현재 단계",data.step],[en?"Owner":"담당자",data.owner],[en?"Due date":"마감일",data.dueDate]].map(([l,v])=><div className="rounded-xl border bg-white p-5" key={l}><p className="text-sm font-bold text-slate-500">{l}</p><strong className="mt-2 block text-xl text-[#052b57]">{v}</strong></div>)}</section>
      <section className="mt-5 rounded-xl border bg-white p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-black text-[#052b57]">{en?"Work process":"업무 진행 단계"}</h2><span className="text-sm font-bold text-blue-700">{data.tasks.filter(t=>t.status==="DONE").length}/{data.tasks.length}</span></div><div className="mt-5 grid gap-3 md:grid-cols-3 lg:grid-cols-6">{data.tasks.map((t,i)=><div className={`rounded-lg border p-4 ${t.status==="IN_PROGRESS"?"border-blue-500 bg-blue-50":"border-slate-200"}`} key={t.code}><span className="text-xs font-black text-slate-500">STEP {i+1}</span><strong className="mt-2 block text-sm text-[#052b57]">{t.name}</strong><span className="mt-3 block text-xs">{t.status}</span></div>)}</div></section>
      <section className="mt-5 rounded-xl border bg-white p-6"><h2 className="text-xl font-black text-[#052b57]">{en?"Continue work":"업무 바로가기"}</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{flows.map(([code,ko,enLabel,path])=><a className="group rounded-xl border border-slate-200 p-5 hover:border-blue-500 hover:bg-blue-50" href={`${buildLocalizedPath(path,path.startsWith("/en")?path:`/en${path}`)}${path.includes("?")?"&":"?"}projectId=${encodeURIComponent(id)}`} key={code}><span className="text-xs font-black text-blue-700">{code}</span><strong className="mt-2 block text-lg text-[#052b57]">{en?enLabel:ko}</strong><span className="mt-3 block text-sm text-slate-500 group-hover:text-blue-700">{en?"Open →":"이동 →"}</span></a>)}</div></section>
      <section className="mt-5 rounded-xl border bg-white p-6"><h2 className="text-xl font-black text-[#052b57]">{en?"Recent history":"최근 변경 이력"}</h2><div className="mt-4 divide-y">{data.history.map((h,i)=><div className="flex flex-col justify-between gap-1 py-3 sm:flex-row" key={`${h.createdAt}-${i}`}><div><strong>{h.description}</strong><p className="text-sm text-slate-500">{h.actor||"-"}</p></div><time className="text-sm text-slate-500">{String(h.createdAt).replace("T"," ")}</time></div>)}</div></section>
    </>}
  </main></div></>;
}
