import { useEffect, useMemo, useState } from "react";
import { buildLocalizedPath, isEnglish } from "../../lib/navigation/runtime";

type Task={id:number;projectId:string;projectName:string;site:string;name:string;status:string;assignee:string;dueDate:string;targetUrl:string};
type Filter="ALL"|"OVERDUE"|"TODAY"|"WEEK";
const day=86400000;
const today=()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),d.getDate())};
const left=(date:string)=>Math.round((new Date(`${date}T00:00:00`).getTime()-today().getTime())/day);
const risk=(task:Task)=>task.status==="DONE"?"DONE":left(task.dueDate)<0?"OVERDUE":left(task.dueDate)===0?"TODAY":left(task.dueDate)<=7?"WEEK":"NORMAL";

export function EmissionDeadlineStatusPage(){
  const en=isEnglish(),api=buildLocalizedPath("/home/api/emission-tasks","/en/home/api/emission-tasks");
  const[items,setItems]=useState<Task[]>([]),[filter,setFilter]=useState<Filter>("ALL"),[keyword,setKeyword]=useState(""),[assignee,setAssignee]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
  useEffect(()=>{const c=new AbortController();fetch(api,{credentials:"include",signal:c.signal}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.message||"Failed to load tasks");setItems(b.items||[])}).catch(e=>{if(e.name!=="AbortError")setError(e.message)}).finally(()=>setLoading(false));return()=>c.abort()},[api]);
  const owners=useMemo(()=>[...new Set(items.map(x=>x.assignee).filter(Boolean))].sort(),[items]);
  const visible=useMemo(()=>items.filter(x=>filter==="ALL"||risk(x)===filter).filter(x=>!assignee||x.assignee===assignee).filter(x=>!keyword||`${x.name} ${x.projectName} ${x.site} ${x.assignee}`.toLowerCase().includes(keyword.toLowerCase())).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)),[items,filter,assignee,keyword]);
  const count=(value:string)=>items.filter(x=>risk(x)===value).length;
  const ko={eyebrow:"탄소배출 관리",title:"마감·지연 현황",desc:"프로젝트 업무의 지연 및 마감 임박 현황을 위험도 순으로 확인합니다.",overdue:"지연",today:"오늘 마감",week:"7일 이내 마감",done:"완료",all:"전체 마감",search:"프로젝트, 업무, 사업장, 담당자 검색",owner:"전체 담당자",risk:"위험도",task:"업무 / 프로젝트",site:"사업장",assignee:"담당자",due:"마감일",status:"상태",action:"처리",open:"업무 열기",empty:"선택한 조건에 해당하는 업무가 없습니다.",loading:"마감 현황을 불러오는 중입니다."};
  const eng={eyebrow:"Carbon Emission Management",title:"Deadline & Delay Status",desc:"Review overdue and upcoming project tasks by risk level.",overdue:"Overdue",today:"Due Today",week:"Due Within 7 Days",done:"Completed",all:"All Deadlines",search:"Search project, task, site or assignee",owner:"All Assignees",risk:"Risk",task:"Task / Project",site:"Site",assignee:"Assignee",due:"Due Date",status:"Status",action:"Action",open:"Open",empty:"No tasks match the selected conditions.",loading:"Loading deadline status..."};const t=en?eng:ko;
  const cards:[[Filter|string,string,string],number][]=[[["OVERDUE",t.overdue,"border-red-200 bg-red-50 text-red-800"],count("OVERDUE")],[["TODAY",t.today,"border-orange-200 bg-orange-50 text-orange-800"],count("TODAY")],[["WEEK",t.week,"border-blue-200 bg-blue-50 text-blue-800"],count("WEEK")],[["DONE",t.done,"border-emerald-200 bg-emerald-50 text-emerald-800"],count("DONE")]];
  return <main className="min-h-[calc(100vh-80px)] bg-[#f5f7fa] px-4 py-8 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold text-[#246beb]">{t.eyebrow}</p><h1 className="mt-2 text-3xl font-black text-[#052b57]">{t.title}</h1><p className="mt-2 text-slate-600">{t.desc}</p>
  <section className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([[value,label,style],valueCount])=><button key={value} type="button" onClick={()=>value!=="DONE"&&setFilter(value as Filter)} className={`rounded-2xl border p-5 text-left shadow-sm ${style}`}><span className="text-sm font-bold">{label}</span><strong className="mt-2 block text-3xl">{valueCount}</strong></button>)}</section>
  <section className="mt-5 rounded-2xl border bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-[1fr_180px_180px]"><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder={t.search} className="h-11 rounded-lg border px-4"/><select value={assignee} onChange={e=>setAssignee(e.target.value)} className="h-11 rounded-lg border bg-white px-3"><option value="">{t.owner}</option>{owners.map(x=><option key={x}>{x}</option>)}</select><select value={filter} onChange={e=>setFilter(e.target.value as Filter)} className="h-11 rounded-lg border bg-white px-3"><option value="ALL">{t.all}</option><option value="OVERDUE">{t.overdue}</option><option value="TODAY">{t.today}</option><option value="WEEK">{t.week}</option></select></div></section>
  {error&&<p className="mt-4 rounded-xl bg-red-50 p-4 font-bold text-red-700">{error}</p>}<section className="mt-5 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-[#eef2f7]"><tr>{[t.risk,t.task,t.site,t.assignee,t.due,t.status,t.action].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{visible.map(x=>{const r=risk(x),d=left(x.dueDate),badge=r==="OVERDUE"?`${t.overdue} ${Math.abs(d)}${en?"d":"일"}`:r==="TODAY"?t.today:r==="WEEK"?`D-${d}`:r==="DONE"?t.done:`D-${d}`;const base=x.targetUrl||"/emission/project/detail",glue=base.includes("?")?"&":"?",koUrl=`${base}${glue}projectId=${encodeURIComponent(x.projectId)}`;return <tr key={x.id} className="border-t hover:bg-slate-50"><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-black ${r==="OVERDUE"?"bg-red-100 text-red-700":r==="TODAY"?"bg-orange-100 text-orange-700":r==="WEEK"?"bg-blue-100 text-blue-700":"bg-slate-100 text-slate-700"}`}>{badge}</span></td><td className="px-4 py-4"><strong className="block">{x.name}</strong><span className="text-slate-500">{x.projectName}</span></td><td className="px-4">{x.site||"-"}</td><td className="px-4">{x.assignee||"-"}</td><td className="px-4 font-semibold">{x.dueDate}</td><td className="px-4">{x.status}</td><td className="px-4"><a href={buildLocalizedPath(koUrl,`/en${koUrl}`)} className="inline-flex rounded-lg bg-[#246beb] px-3 py-2 font-bold text-white">{t.open}</a></td></tr>})}</tbody></table></div>{(loading||!visible.length)&&<p className="p-10 text-center text-slate-500">{loading?t.loading:t.empty}</p>}</section></div></main>;
}
