import { FormEvent, useEffect, useMemo, useState } from "react";
import { buildLocalizedPath, isEnglish, navigate } from "../../lib/navigation/runtime";

type Task={id:number;code:string;name:string;order:number;status:string;effectiveStatus?:string;effectiveReason?:string;weight:number;dueDate:string;targetUrl:string;actorCode?:string;assignee?:string;priority?:string;completionRule?:string;blockedReason?:string;completedAt?:string;completedBy?:string};
type Project={id:string;name:string;site:string;period:string;scope:string;owner:string;progress:number;step:string;dueDate:string;status:string;tasks:Task[];members:{name:string;role:string}[];history:HistoryItem[]};
type HistoryItem={type:string;description:string;actor:string;createdAt:string};
type Metrics={activityCount:number;missingEvidenceCount:number;unmappedCount:number;blockingCount:number;warningCount:number;qualityScore:number;submitReady:boolean;approvalPendingCount:number;correctionCount:number;calculationRunCount:number;verifiedCount:number;approvedCount:number;totalEmission:number;finalizedReportCount:number};
type Activity={id:number;name:string;category:string;period:string;quantity:number;unit:string;evidence?:string;mappingStatus:string;updatedAt:string};
type Submission={id:number;version:number;state:string;submittedActor?:string;submittedAt?:string;deadlineDate?:string};
type Breakdown={label:string;value:number};
type Workspace={project:Project;metrics:Metrics;recentActivities:Activity[];recentSubmissions:Submission[];emissionBreakdown:Breakdown[];messages:HistoryItem[]};

const statusStyle:Record<string,string>={DONE:"bg-emerald-100 text-emerald-800",READY:"bg-blue-100 text-blue-800",IN_PROGRESS:"bg-blue-700 text-white",BLOCKED:"bg-red-100 text-red-800",WAITING:"bg-slate-100 text-slate-600"};
const statusKo:Record<string,string>={DONE:"완료",READY:"진행 가능",IN_PROGRESS:"진행 중",BLOCKED:"선행 업무 대기",WAITING:"대기"};

async function json(response:Response){
  const text=await response.text();
  let body:any={};
  try{body=text?JSON.parse(text):{}}catch{throw new Error(`서버 응답 형식이 올바르지 않습니다. (${response.status})`)}
  if(!response.ok)throw new Error(body.message||`요청을 처리하지 못했습니다. (${response.status})`);
  return body;
}

function localizedTarget(target:string,id:string,en:boolean){
  if(!target)return buildLocalizedPath(`/emission/project/detail?id=${id}`,`/en/emission/project/detail?id=${id}`);
  const source=target.includes("projectId=")?target:`${target}${target.includes("?")?"&":"?"}projectId=${encodeURIComponent(id)}`;
  return en&&!source.startsWith("/en/")?`/en${source}`:source;
}

function MetricCard({label,value,tone="blue",hint}:{label:string;value:string|number;tone?:"blue"|"red"|"amber"|"green";hint?:string}){
  const toneClass={blue:"border-blue-100 bg-blue-50/50 text-[#052b57]",red:"border-red-200 bg-red-50 text-red-900",amber:"border-amber-200 bg-amber-50 text-amber-950",green:"border-emerald-200 bg-emerald-50 text-emerald-900"}[tone];
  return <article className={`rounded-2xl border p-5 ${toneClass}`}><p className="text-sm font-bold opacity-75">{label}</p><strong className="mt-2 block text-2xl font-black">{value}</strong>{hint&&<p className="mt-1 text-xs opacity-70">{hint}</p>}</article>;
}

export function EmissionProjectDetailPage(){
  const en=isEnglish();
  const id=new URLSearchParams(location.search).get("id")||new URLSearchParams(location.search).get("projectId")||"";
  const [data,setData]=useState<Workspace|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[working,setWorking]=useState(false);
  const [edit,setEdit]=useState(false),[owner,setOwner]=useState(""),[dueDate,setDueDate]=useState("");
  const [messageType,setMessageType]=useState("COMMENT"),[message,setMessage]=useState("");
  const base=buildLocalizedPath(`/home/api/emission-projects/${encodeURIComponent(id)}`,`/en/home/api/emission-projects/${encodeURIComponent(id)}`);
  const workspaceApi=`${base}/workspace`;
  async function load(){if(!id)throw new Error(en?"Select a project first.":"프로젝트를 먼저 선택해 주세요.");const body=await json(await fetch(workspaceApi,{credentials:"include",headers:{Accept:"application/json"}}));setData(body);setOwner(body.project.owner||"");setDueDate(body.project.dueDate||"");}
  useEffect(()=>{void load().catch(reason=>setError(reason instanceof Error?reason.message:String(reason)))},[id]);
  const tasks=data?.project.tasks||[];
  const effective=(task:Task)=>task.effectiveStatus||task.status;
  const current=useMemo(()=>tasks.find(task=>effective(task)==="IN_PROGRESS")||tasks.find(task=>effective(task)==="READY")||tasks.find(task=>effective(task)!=="DONE"),[tasks]);
  const completed=tasks.filter(task=>effective(task)==="DONE").length,metrics=data?.metrics;
  const readiness=metrics?Math.round(((metrics.activityCount>0?1:0)+(metrics.missingEvidenceCount===0&&metrics.activityCount>0?1:0)+(metrics.unmappedCount===0&&metrics.activityCount>0?1:0)+(metrics.blockingCount===0&&metrics.activityCount>0?1:0))*25):0;
  const maxEmission=Math.max(1,...(data?.emissionBreakdown||[]).map(row=>Number(row.value)||0));
  async function mutate(request:()=>Promise<Response>,success:string){setWorking(true);setError("");setNotice("");try{await json(await request());setNotice(success);await load();}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setWorking(false)}}
  async function saveProject(event:FormEvent){event.preventDefault();await mutate(()=>fetch(workspaceApi,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({owner,dueDate})}),en?"Project settings updated.":"담당자와 마감일을 변경했습니다.");setEdit(false)}
  async function addMessage(event:FormEvent){event.preventDefault();if(!message.trim())return;await mutate(()=>fetch(`${workspaceApi}/messages`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({type:messageType,description:message.trim()})}),en?"Message registered.":"프로젝트 업무 메시지를 등록했습니다.");setMessage("")}
  async function startTask(task:Task){await mutate(()=>fetch(buildLocalizedPath(`/home/api/emission-tasks/${task.id}/status`,`/en/home/api/emission-tasks/${task.id}/status`),{method:"POST",credentials:"include",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({status:"IN_PROGRESS"})}),en?"Task started.":"업무를 시작했습니다.")}
  async function copyProject(){await mutate(()=>fetch(`${base}/copy`,{method:"POST",credentials:"include"}),en?"Project copied.":"프로젝트를 복사했습니다.")}
  async function removeProject(){if(!confirm(en?"Delete this project?":"이 프로젝트를 삭제하시겠습니까?"))return;setWorking(true);try{await json(await fetch(base,{method:"DELETE",credentials:"include"}));navigate(buildLocalizedPath("/emission/project_list","/en/emission/project_list"))}catch(reason){setError(reason instanceof Error?reason.message:String(reason));setWorking(false)}}
  return <div className="min-h-screen bg-[#f5f7fa]"><main className="mx-auto max-w-7xl px-4 py-8 lg:px-8">
    <nav className="text-sm text-slate-500"><a href={buildLocalizedPath("/emission/project_list","/en/emission/project_list")}>{en?"Emission Projects":"배출량 프로젝트"}</a><span className="mx-2">/</span>{en?"Project Control Workspace":"프로젝트 통합 작업공간"}</nav>
    {error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 font-bold text-red-800" role="alert">{error}</div>}{notice&&<div className="mt-5 rounded-xl border border-blue-200 bg-blue-50 p-4 font-bold text-blue-900" role="status">{notice}</div>}{!data&&!error&&<p className="mt-8 font-bold text-slate-600">{en?"Loading workspace...":"프로젝트 작업공간을 불러오는 중입니다."}</p>}
    {data&&<><section className="mt-5 overflow-hidden rounded-3xl bg-gradient-to-r from-[#052b57] to-[#174ea6] p-6 text-white shadow-lg lg:p-8"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="text-sm font-black text-blue-200">{data.project.id} · {data.project.status}</p><h1 className="mt-2 text-3xl font-black tracking-tight lg:text-4xl">{data.project.name}</h1><p className="mt-3 text-blue-100">{data.project.site} · {data.project.period} · {data.project.scope}</p></div><div className="flex flex-wrap gap-2"><button className="rounded-xl border border-white/50 px-4 py-3 font-bold hover:bg-white/10" onClick={()=>setEdit(value=>!value)}>{en?"Manage project":"담당자·일정 관리"}</button><a className="rounded-xl bg-white px-5 py-3 font-black text-blue-900 shadow" href={current?localizedTarget(current.targetUrl,id,en):buildLocalizedPath(`/emission/project/completion?projectId=${id}`,`/en/emission/project/completion?projectId=${id}`)}>{current?(en?"Continue current work":"현재 업무 바로 실행"):(en?"View completion":"완료 결과 확인")} →</a></div></div></section>
      {edit&&<form className="mt-4 grid gap-4 rounded-2xl border border-blue-200 bg-white p-5 shadow-sm sm:grid-cols-[1fr_220px_auto] sm:items-end" onSubmit={saveProject}><label className="text-sm font-bold text-slate-700">{en?"Project owner":"프로젝트 책임자"}<input className="mt-2 h-11 w-full rounded-lg border px-3" required value={owner} onChange={e=>setOwner(e.target.value)}/></label><label className="text-sm font-bold text-slate-700">{en?"Due date":"마감일"}<input className="mt-2 h-11 w-full rounded-lg border px-3" required type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label><button className="h-11 rounded-lg bg-[#246beb] px-5 font-black text-white disabled:opacity-50" disabled={working}>{en?"Save":"변경 저장"}</button></form>}
      <section className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><MetricCard label={en?"Progress":"전체 진행률"} value={`${data.project.progress}%`} hint={`${completed}/${tasks.length} ${en?"tasks complete":"단계 완료"}`}/><MetricCard label={en?"Data readiness":"자료 준비도"} value={`${readiness}%`} tone={readiness===100?"green":"blue"}/><MetricCard label={en?"Missing / unmapped":"증빙 누락·미매핑"} value={`${metrics?.missingEvidenceCount||0} · ${metrics?.unmappedCount||0}`} tone={(metrics?.missingEvidenceCount||0)+(metrics?.unmappedCount||0)>0?"amber":"green"}/><MetricCard label={en?"Quality issues":"검증 오류·주의"} value={`${metrics?.blockingCount||0} · ${metrics?.warningCount||0}`} tone={(metrics?.blockingCount||0)>0?"red":"green"}/><MetricCard label={en?"Approval / correction":"승인대기·보완"} value={`${metrics?.approvalPendingCount||0} · ${metrics?.correctionCount||0}`} tone={(metrics?.correctionCount||0)>0?"red":"blue"}/></section>
      <section className="mt-5 rounded-2xl border bg-white p-5 shadow-sm lg:p-6"><div className="flex flex-col justify-between gap-3 lg:flex-row lg:items-end"><div><p className="text-sm font-black text-[#246beb]">{en?"GOVERNED WORKFLOW":"검증 기준 업무 흐름"}</p><h2 className="mt-1 text-xl font-black text-[#052b57]">{en?"Project lifecycle":"프로젝트 전체 단계"}</h2><p className="mt-1 text-sm text-slate-500">{en?"The lifecycle is an overview. Only the current actionable task is opened below.":"전체 단계는 진행 위치만 보여주며, 실행 가능한 현재 업무는 아래에서 하나만 제공합니다."}</p></div><strong className="text-sm text-blue-700">{completed}/{tasks.length} {en?"complete":"완료"}</strong></div><ol className="mt-5 grid gap-2 sm:grid-cols-3 lg:grid-cols-6">{tasks.map((task,index)=><li className={`relative rounded-xl border p-4 ${task===current?"border-blue-600 bg-blue-50 ring-2 ring-blue-100":"border-slate-200"}`} key={task.code}><div className="flex items-center justify-between"><span className="text-xs font-black text-slate-500">{index+1}</span><span className={`rounded-full px-2 py-1 text-[11px] font-black ${statusStyle[task.status]||statusStyle.WAITING}`}>{en?task.status:(statusKo[task.status]||task.status)}</span></div><strong className="mt-3 block text-sm text-[#052b57]">{task.name}</strong>{task.blockedReason&&<p className="mt-2 text-xs text-red-700">{task.blockedReason}</p>}</li>)}</ol></section>
      <section className="mt-5 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><article className="rounded-2xl border border-blue-200 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><p className="text-sm font-black text-blue-700">{en?"CURRENT ACTION":"지금 할 업무"}</p><h2 className="mt-1 text-2xl font-black text-[#052b57]">{current?.name||(en?"All project work complete":"모든 프로젝트 업무 완료")}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{current?.completionRule||(en?"Review and close the project.":"최종 산출물과 이력을 확인하세요.")}</p><div className="mt-4 flex flex-wrap gap-2 text-xs font-bold text-slate-600"><span className="rounded-full bg-slate-100 px-3 py-1.5">{en?"Actor":"수행 액터"}: {current?.actorCode||"-"}</span><span className="rounded-full bg-slate-100 px-3 py-1.5">{en?"Assignee":"담당자"}: {current?.assignee||data.project.owner}</span><span className="rounded-full bg-slate-100 px-3 py-1.5">{en?"Due":"마감"}: {current?.dueDate||data.project.dueDate}</span></div></div>{current&&<div className="flex shrink-0 flex-col gap-2">{current.status==="READY"&&<button className="min-h-11 rounded-lg border border-blue-600 px-4 font-bold text-blue-700 disabled:opacity-50" disabled={working} onClick={()=>void startTask(current)}>{en?"Start task":"업무 시작"}</button>}<a className="inline-flex min-h-12 items-center justify-center rounded-lg bg-[#246beb] px-6 font-black text-white" href={localizedTarget(current.targetUrl,id,en)}>{en?"Open workspace":"업무 화면 열기"} →</a></div>}</div><div className="mt-6 grid gap-3 sm:grid-cols-2"><Condition ok={(metrics?.activityCount||0)>0} label={en?"Activity data registered":"활동자료 등록"} value={`${metrics?.activityCount||0}${en?" rows":"건"}`}/><Condition ok={(metrics?.missingEvidenceCount||0)===0&&(metrics?.activityCount||0)>0} label={en?"Evidence complete":"필수 증빙 완비"} value={`${metrics?.missingEvidenceCount||0}${en?" missing":"건 누락"}`}/><Condition ok={(metrics?.unmappedCount||0)===0&&(metrics?.activityCount||0)>0} label={en?"Factors mapped":"배출계수 매핑"} value={`${metrics?.unmappedCount||0}${en?" unmapped":"건 미매핑"}`}/><Condition ok={(metrics?.blockingCount||0)===0} label={en?"No blocking errors":"차단 오류 없음"} value={`${metrics?.blockingCount||0}${en?" blocking":"건"}`}/></div></article>
        <article className="rounded-2xl border bg-white p-6 shadow-sm"><p className="text-sm font-black text-blue-700">{en?"EMISSION SUMMARY":"배출량 요약"}</p><h2 className="mt-1 text-xl font-black text-[#052b57]">{Number(metrics?.totalEmission||0).toLocaleString(undefined,{maximumFractionDigits:3})} <small className="text-sm text-slate-500">tCO₂e</small></h2><p className="mt-1 text-xs text-slate-500">{data.project.scope}</p><div className="mt-5 space-y-4">{data.emissionBreakdown.map(row=><div key={row.label}><div className="flex justify-between gap-3 text-sm"><strong>{row.label}</strong><span>{Number(row.value).toLocaleString(undefined,{maximumFractionDigits:3})}</span></div><div className="mt-1.5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#246beb]" style={{width:`${Math.max(2,Number(row.value)/maxEmission*100)}%`}}/></div></div>)}{!data.emissionBreakdown.length&&<p className="rounded-lg bg-slate-50 p-5 text-center text-sm text-slate-500">{en?"Results appear after calculation.":"배출량 산정 후 구분별 결과가 표시됩니다."}</p>}</div><a className="mt-5 inline-flex font-bold text-blue-700 hover:underline" href={buildLocalizedPath(`/emission/result?projectId=${id}`,`/en/emission/result?projectId=${id}`)}>{en?"View calculation details":"산정 결과 상세 보기"} →</a></article></section>
      <section className="mt-5 grid gap-5 xl:grid-cols-2"><article className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="text-xl font-black text-[#052b57]">{en?"Recent data and evidence":"최근 활동자료·증빙"}</h2><p className="mt-1 text-sm text-slate-500">{en?"Review the latest submitted source data.":"최근 입력된 원천자료와 증빙 상태를 확인합니다."}</p></div><a className="font-bold text-blue-700" href={buildLocalizedPath(`/emission/activity-data?projectId=${id}`,`/en/emission/activity-data?projectId=${id}`)}>{en?"Manage":"관리"}</a></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-slate-50"><tr>{(en?["Activity","Period","Quantity","Evidence","Mapping"]:["활동자료","기간","활동량","증빙","매핑"]).map(label=><th className="px-4 py-3" key={label}>{label}</th>)}</tr></thead><tbody>{data.recentActivities.map(row=><tr className="border-t" key={row.id}><td className="px-4 py-3 font-bold">{row.name}<small className="block text-slate-500">{row.category}</small></td><td>{row.period}</td><td>{row.quantity} {row.unit}</td><td><span className={`rounded-full px-2 py-1 text-xs font-bold ${row.evidence?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-900"}`}>{row.evidence||(en?"Missing":"누락")}</span></td><td>{row.mappingStatus}</td></tr>)}{!data.recentActivities.length&&<tr><td className="p-8 text-center text-slate-500" colSpan={5}>{en?"No activity data.":"등록된 활동자료가 없습니다."}</td></tr>}</tbody></table></div></article>
        <article className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex justify-between gap-3"><div><h2 className="text-xl font-black text-[#052b57]">{en?"Verification and correction":"검증 오류·보완 요청"}</h2><p className="mt-1 text-sm text-slate-500">{en?"Resolve exceptions before approval.":"승인 전에 오류와 보완 요청을 처리합니다."}</p></div><span className={`h-fit rounded-full px-3 py-1 text-xs font-black ${(metrics?.blockingCount||0)+(metrics?.correctionCount||0)>0?"bg-red-100 text-red-800":"bg-emerald-100 text-emerald-800"}`}>{(metrics?.blockingCount||0)+(metrics?.correctionCount||0)} {en?"open":"건"}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><a className="rounded-xl border border-red-200 bg-red-50 p-4 hover:border-red-500" href={buildLocalizedPath(`/emission/activity-data?tab=quality&projectId=${id}`,`/en/emission/activity-data?tab=quality&projectId=${id}`)}><p className="text-sm font-bold text-red-800">{en?"Blocking errors":"차단 오류"}</p><strong className="mt-1 block text-3xl text-red-900">{metrics?.blockingCount||0}</strong><span className="mt-2 block text-sm font-bold text-red-700">{en?"Open quality check":"품질검사 열기"} →</span></a><a className="rounded-xl border border-amber-200 bg-amber-50 p-4 hover:border-amber-500" href={buildLocalizedPath(`/emission/validate?projectId=${id}`,`/en/emission/validate?projectId=${id}`)}><p className="text-sm font-bold text-amber-900">{en?"Correction requests":"보완 요청"}</p><strong className="mt-1 block text-3xl text-amber-950">{metrics?.correctionCount||0}</strong><span className="mt-2 block text-sm font-bold text-amber-800">{en?"Review requests":"요청 검토"} →</span></a></div><div className="mt-5 border-t pt-4"><h3 className="font-black text-slate-800">{en?"Recent submissions":"최근 제출 버전"}</h3>{data.recentSubmissions.slice(0,3).map(row=><div className="mt-3 flex items-center justify-between rounded-lg bg-slate-50 px-4 py-3" key={row.id}><div><strong>V{row.version}</strong><small className="ml-2 text-slate-500">{row.submittedActor||"-"}</small></div><span className="rounded-full bg-white px-2 py-1 text-xs font-bold">{row.state}</span></div>)}{!data.recentSubmissions.length&&<p className="mt-3 text-sm text-slate-500">{en?"No submission history.":"제출 이력이 없습니다."}</p>}</div></article></section>
      <section className="mt-5 grid gap-5 xl:grid-cols-[.9fr_1.1fr]"><article className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black text-[#052b57]">{en?"Project communication":"알림·댓글·업무 요청"}</h2><form className="mt-4" onSubmit={addMessage}><div className="grid gap-3 sm:grid-cols-[150px_1fr]"><select className="h-11 rounded-lg border px-3 font-bold" value={messageType} onChange={e=>setMessageType(e.target.value)}><option value="COMMENT">{en?"Comment":"댓글"}</option><option value="WORK_REQUEST">{en?"Work request":"업무 요청"}</option><option value="ALERT">{en?"Alert":"중요 알림"}</option></select><input className="h-11 rounded-lg border px-3" placeholder={en?"Write a project message":"프로젝트 참여자에게 전달할 내용을 입력하세요"} value={message} onChange={e=>setMessage(e.target.value)}/></div><button className="mt-3 min-h-11 w-full rounded-lg bg-[#052b57] px-5 font-black text-white disabled:opacity-50" disabled={working||!message.trim()}>{en?"Register message":"메시지 등록"}</button></form><div className="mt-5 max-h-72 space-y-3 overflow-y-auto">{data.messages.map((item,index)=><div className="rounded-xl bg-slate-50 p-4" key={`${item.createdAt}-${index}`}><div className="flex justify-between gap-3"><span className="text-xs font-black text-blue-700">{item.type}</span><time className="text-xs text-slate-400">{String(item.createdAt).replace("T"," ")}</time></div><p className="mt-2 text-sm font-bold text-slate-800">{item.description}</p><small className="mt-1 block text-slate-500">{item.actor||"-"}</small></div>)}{!data.messages.length&&<p className="py-6 text-center text-sm text-slate-500">{en?"No project messages.":"등록된 프로젝트 메시지가 없습니다."}</p>}</div></article>
        <article className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-black text-[#052b57]">{en?"Change and approval history":"변경·승인 이력"}</h2><span className="text-sm text-slate-500">{data.project.history.length}{en?" events":"건"}</span></div><div className="mt-4 max-h-[420px] divide-y overflow-y-auto">{data.project.history.map((item,index)=><div className="grid gap-2 py-4 sm:grid-cols-[120px_1fr_auto] sm:items-start" key={`${item.createdAt}-${index}`}><span className="w-fit rounded-full bg-slate-100 px-2 py-1 text-[11px] font-black text-slate-700">{item.type}</span><div><strong className="text-sm text-slate-900">{item.description}</strong><p className="mt-1 text-xs text-slate-500">{item.actor||"-"}</p></div><time className="text-xs text-slate-400">{String(item.createdAt).replace("T"," ")}</time></div>)}</div></article></section>
      <section className="mt-5 flex flex-col justify-between gap-4 rounded-2xl border bg-white p-5 sm:flex-row sm:items-center"><div><h2 className="font-black text-[#052b57]">{en?"Project administration":"프로젝트 관리"}</h2><p className="mt-1 text-sm text-slate-500">{en?"Copy or delete only when necessary. All operations are recorded.":"복사·삭제는 필요한 경우에만 사용하며 변경 이력에 기록됩니다."}</p></div><div className="flex gap-2"><a className="rounded-lg border px-4 py-2 font-bold" href={buildLocalizedPath("/admin/system/actor-process?process=EMISSION_PROJECT","/en/admin/system/actor-process?process=EMISSION_PROJECT")}>{en?"Design contract":"설계 계약"}</a><button className="rounded-lg border px-4 py-2 font-bold" disabled={working} onClick={()=>void copyProject()}>{en?"Copy":"복사"}</button><button className="rounded-lg border border-red-300 px-4 py-2 font-bold text-red-700" disabled={working} onClick={()=>void removeProject()}>{en?"Delete":"삭제"}</button></div></section>
    </>}
  </main></div>;
}

function Condition({ok,label,value}:{ok:boolean;label:string;value:string}){return <div className={`flex items-center justify-between rounded-xl border p-3 ${ok?"border-emerald-200 bg-emerald-50":"border-amber-200 bg-amber-50"}`}><div className="flex items-center gap-2"><span className={`grid h-6 w-6 place-items-center rounded-full text-xs font-black text-white ${ok?"bg-emerald-600":"bg-amber-600"}`}>{ok?"✓":"!"}</span><strong className="text-sm">{label}</strong></div><span className="text-xs font-bold text-slate-600">{value}</span></div>}

export default EmissionProjectDetailPage;
