import { useEffect,useMemo,useState } from "react";
import { useAsyncValue } from "../../app/hooks/useAsyncValue";
import { fetchHomePayload } from "../../lib/api/appBootstrap";
import { buildLocalizedPath,isEnglish } from "../../lib/navigation/runtime";
import { HeaderBrand,HeaderDesktopNav,HomeInlineStyles } from "../home-entry/HomeEntrySections";
import { LOCALIZED_CONTENT } from "../home-entry/homeEntryContent";

type Factor={id:string;name:string;category:string;unit:string;value:number;source:string};
type SourceItem={id:number;name:string;category:string;period:string;quantity:number;unit:string;note:string;submissionId:number;factorId?:string;factorName?:string;factorValue?:number;factorUnit?:string;factorSource?:string;mappingMethod?:string;confidence?:number;unitMatch?:boolean;decisionReason?:string;decidedBy?:string;decidedAt?:string};
type ResultItem={name:string;category:string;period:string;quantity:number;unit:string;factorId:string;factorName:string;factorUnit:string;factorSource:string;factorValue:number;emissionValue:number;formula:string};
type Run={id:number;version:number;status:string;totalEmission:number;resultUnit:string;submissionIds:string;snapshotHash:string;methodology:string;calculatedBy:string;calculatedAt:string};
type Data={project:{id:string;name:string;site:string;step?:string};activityCount:number;unmappedCount:number;incompatibleUnitCount:number;acceptedSubmissionCount:number;actorRoles:string[];factors:Factor[];sourceItems:SourceItem[];runs:Run[];items:ResultItem[]};

export function EmissionProjectResultPage(){
 const en=isEnglish(),content=LOCALIZED_CONTENT[en?"en":"ko"],home=useAsyncValue(()=>fetchHomePayload(),[en]),id=new URLSearchParams(location.search).get("projectId")||"";
 const[data,setData]=useState<Data|null>(null),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[mappingId,setMappingId]=useState<number|null>(null);
 const api=buildLocalizedPath(`/home/api/emission-projects/${id}/calculation`,`/en/home/api/emission-projects/${id}/calculation`),activityApi=buildLocalizedPath(`/home/api/emission-projects/${id}/activities`,`/en/home/api/emission-projects/${id}/activities`);
 async function request(url:string,init?:RequestInit){const r=await fetch(url,{credentials:"include",headers:{Accept:"application/json",...(init?.headers||{})},...init}),b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message||"요청 처리에 실패했습니다.");return b;}
 async function load(){setError("");try{setData(await request(api))}catch(e){setError(e instanceof Error?e.message:String(e))}}
 useEffect(()=>{if(id)void load()},[id]);
 const canCalculate=data?.actorRoles?.includes("CALCULATOR"),latest=data?.runs?.[0],ready=!!data?.activityCount&&!data?.unmappedCount&&!data?.incompatibleUnitCount;
 const preview=useMemo(()=>data?.sourceItems.reduce((sum,row)=>sum+Number(row.quantity||0)*Number(row.factorValue||0),0)||0,[data?.sourceItems]);
 async function map(item:SourceItem,factorId:string){setMappingId(item.id);setMessage("");setError("");try{await request(`${activityApi}/${item.id}/factor`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({factorId,reason:"산정 워크스페이스에서 접수 제출본과 단위를 확인한 후 직접 선택"})});setMessage(en?"Factor decision saved with audit evidence.":"배출계수 결정과 근거 이력을 저장했습니다.");await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setMappingId(null)}}
 async function autoMap(){setBusy(true);setMessage("");setError("");try{const b=await request(`${activityApi}/auto-map`,{method:"POST"});setMessage(en?`${b.count} new rows mapped. Review low-confidence or unit-mismatch rows.`:`신규 ${b.count}건을 자동 매핑했습니다. 낮은 신뢰도와 단위 불일치 행을 검토하세요.`);await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function calculate(){setBusy(true);setMessage("");setError("");try{await request(api,{method:"POST"});setMessage(en?"Immutable calculation version created and validation task opened.":"불변 산정 버전을 생성하고 검증 업무를 열었습니다.");await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 if(!id)return <p className="p-10 font-bold text-red-700">{en?"Select a project first.":"프로젝트를 먼저 선택해 주세요."}</p>;
 return <><HomeInlineStyles en={en}/><div className="min-h-screen bg-[#f5f7fa]"><header className="border-b-2 border-[#001e40] bg-white"><div className="mx-auto flex h-16 max-w-7xl items-center px-4 lg:px-8"><HeaderBrand content={content} en={en}/><HeaderDesktopNav en={en} homeMenu={home.value?.homeMenu||[]}/></div></header><main className="mx-auto max-w-7xl px-4 py-8 lg:px-8">
  <nav className="text-sm text-slate-500"><a href={buildLocalizedPath(`/emission/project/detail?projectId=${id}`,`/en/emission/project/detail?projectId=${id}`)}>{data?.project.name||id}</a><span className="mx-2">/</span>{en?"Factor Mapping & Calculation":"배출계수 매핑·산정"}</nav>
  <div className="mt-4 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="font-bold text-blue-700">{data?.project.site}</p><h1 className="text-3xl font-black text-[#052b57]">{en?"Emission Calculation Workspace":"배출량 산정 워크스페이스"}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">{en?"Only manager-accepted submission snapshots are mapped and calculated. Every factor decision and calculation version remains auditable.":"관리자가 접수한 제출 스냅샷만 매핑·산정합니다. 계수 결정과 산정 버전은 변경 불가 감사 이력으로 남습니다."}</p></div><div className="flex gap-2"><button className="min-h-12 rounded-lg border border-blue-700 bg-white px-5 font-black text-blue-800 disabled:opacity-40" disabled={busy||!canCalculate||!data?.activityCount} onClick={autoMap}>{en?"Auto-map accepted rows":"접수 자료 자동 매핑"}</button><button className="min-h-12 rounded-lg bg-[#246beb] px-6 font-black text-white disabled:opacity-40" disabled={busy||!canCalculate||!ready} onClick={calculate}>{busy?(en?"Processing...":"처리 중..."):(en?"Create calculation version":"산정 버전 생성")}</button></div></div>
  {error&&<div className="mt-5 rounded-lg border border-red-300 bg-red-50 p-4 font-bold text-red-800" role="alert">{error}</div>}{message&&<div className="mt-5 rounded-lg border border-blue-300 bg-blue-50 p-4 font-bold text-blue-800" role="status">{message}</div>}
  <section className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[[en?"Accepted submissions":"접수 제출본",data?.acceptedSubmissionCount||0],[en?"Eligible activity rows":"산정 대상 행",data?.activityCount||0],[en?"Unmapped rows":"미매핑 행",data?.unmappedCount||0],[en?"Unit mismatches":"단위 불일치",data?.incompatibleUnitCount||0],[en?"Preview total":"예상 총배출량",`${preview.toFixed(6)} tCO₂e`]].map(([l,v])=><div className="rounded-xl border bg-white p-5" key={String(l)}><p className="text-sm font-bold text-slate-500">{l}</p><strong className="mt-2 block text-2xl text-[#052b57]">{v}</strong></div>)}</section>
  {!data?.acceptedSubmissionCount&&<div className="mt-5 rounded-xl border border-amber-300 bg-amber-50 p-5"><strong>{en?"No accepted submission":"접수 완료된 제출본이 없습니다."}</strong><p className="mt-1 text-sm">{en?"A company manager must accept every active data request before calculation can start.":"기업 담당자가 활성 자료 요청을 모두 접수해야 산정이 시작됩니다."}</p><a className="mt-3 inline-block font-bold text-blue-700 underline" href={buildLocalizedPath(`/emission/data-request?projectId=${id}`,`/en/emission/data-request?projectId=${id}`)}>{en?"Open request acceptance":"자료 요청·접수 열기"}</a></div>}
  <section className="mt-5 overflow-hidden rounded-xl border bg-white"><div className="flex flex-col justify-between gap-3 border-b p-5 sm:flex-row"><div><h2 className="text-xl font-black text-[#052b57]">{en?"1. Accepted Input & Factor Decisions":"1. 접수 입력·배출계수 결정"}</h2><p className="mt-1 text-sm text-slate-600">{en?"Confirm source, unit compatibility, confidence, and formula preview for every row.":"각 행의 출처, 단위 호환성, 신뢰도와 계산식 미리보기를 확인합니다."}</p></div><span className="self-start rounded-full bg-slate-100 px-3 py-1 text-sm font-bold">{ready?(en?"READY":"산정 가능"):(en?"ACTION REQUIRED":"조치 필요")}</span></div><div className="overflow-x-auto"><table className="w-full min-w-[1120px] text-left text-sm"><thead className="bg-slate-100"><tr>{(en?["Accepted activity","Quantity","Evidence","Factor decision","Source / Unit","Confidence","Formula preview"]:["접수 활동자료","활동량","증빙","배출계수 결정","출처·단위","신뢰도","계산식 미리보기"]).map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{data?.sourceItems.map(row=><tr className="border-b align-top" key={row.id}><td className="p-3"><strong>{row.name}</strong><small className="mt-1 block text-slate-500">{row.category} · {row.period} · 제출 #{row.submissionId}</small></td><td className="p-3 font-bold">{row.quantity} {row.unit}</td><td className="max-w-52 p-3 text-slate-600">{row.note}</td><td className="p-3"><select aria-label={`${row.name} 배출계수`} className="h-11 min-w-72 rounded-lg border px-2" disabled={!canCalculate||mappingId===row.id} value={row.factorId||""} onChange={e=>e.target.value&&map(row,e.target.value)}><option value="">{en?"Select factor":"배출계수 선택"}</option>{data.factors.map(f=><option key={f.id} value={f.id}>{f.name} · {f.value}/{f.unit}</option>)}</select>{row.decisionReason&&<small className="mt-1 block max-w-72 text-slate-500">{row.mappingMethod} · {row.decidedBy} · {row.decisionReason}</small>}</td><td className="p-3"><strong>{row.factorSource||"-"}</strong><small className={`mt-1 block font-bold ${row.unitMatch===false?"text-red-700":"text-green-700"}`}>{row.factorUnit?`${row.unit} → ${row.factorUnit} ${row.unitMatch===false?"불일치":"일치"}`:"-"}</small></td><td className="p-3">{row.confidence!=null?`${Math.round(Number(row.confidence)*100)}%`:"-"}</td><td className="p-3 font-mono">{row.factorValue!=null?`${row.quantity} × ${row.factorValue} = ${(Number(row.quantity)*Number(row.factorValue)).toFixed(8)} tCO₂e`:"-"}</td></tr>)}{!data?.sourceItems.length&&<tr><td colSpan={7} className="p-12 text-center text-slate-500">{en?"No accepted activity rows.":"접수된 산정 대상 자료가 없습니다."}</td></tr>}</tbody></table></div></section>
  <section className="mt-5 grid gap-5 lg:grid-cols-[1fr_340px]"><div className="overflow-hidden rounded-xl border bg-white"><div className="border-b p-5"><h2 className="text-xl font-black text-[#052b57]">{en?"2. Latest Calculation Detail":"2. 최신 산정 상세"}</h2><p className="mt-1 text-sm text-slate-600">{latest?`v${latest.version} · ${latest.calculatedBy} · ${latest.calculatedAt}`:(en?"Create a version after all factors are confirmed.":"모든 계수를 확정한 뒤 산정 버전을 생성하세요.")}</p></div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-slate-100"><tr>{(en?["Activity","Quantity","Factor evidence","Formula","Emission"]:["활동자료","활동량","계수 근거","계산식","배출량"]).map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{data?.items.map((x,i)=><tr className="border-b" key={`${x.name}-${i}`}><td className="p-3 font-bold">{x.name}<small className="block text-slate-500">{x.category} · {x.period}</small></td><td className="p-3">{x.quantity} {x.unit}</td><td className="p-3">{x.factorName}<small className="block text-slate-500">{x.factorSource} · {x.factorValue}/{x.factorUnit}</small></td><td className="p-3 font-mono">{x.formula}</td><td className="p-3 font-black">{Number(x.emissionValue).toFixed(8)} tCO₂e</td></tr>)}{!data?.items.length&&<tr><td className="p-10 text-center text-slate-500" colSpan={5}>{en?"No calculation version yet.":"생성된 산정 버전이 없습니다."}</td></tr>}</tbody></table></div></div><aside className="rounded-xl bg-[#052b57] p-6 text-white"><p className="text-sm font-bold text-blue-200">{en?"LATEST IMMUTABLE VERSION":"최신 불변 산정 버전"}</p><strong className="mt-3 block text-3xl">{latest?`${Number(latest.totalEmission).toFixed(6)} ${latest.resultUnit}`:"-"}</strong><dl className="mt-6 space-y-4 text-sm"><div><dt className="text-blue-200">{en?"Methodology":"방법론"}</dt><dd className="mt-1 font-bold">{latest?.methodology||"ACTIVITY_X_FACTOR"}</dd></div><div><dt className="text-blue-200">{en?"Accepted submissions":"접수 제출본"}</dt><dd className="mt-1 font-bold">{latest?.submissionIds||"-"}</dd></div><div><dt className="text-blue-200">{en?"Input fingerprint":"입력 지문"}</dt><dd className="mt-1 break-all font-mono text-xs">{latest?.snapshotHash||"-"}</dd></div></dl>{latest&&<a className="mt-6 block rounded-lg bg-white px-4 py-3 text-center font-black text-[#052b57]" href={buildLocalizedPath(`/emission/validate?projectId=${id}&calculationId=${latest.id}`,`/en/emission/validate?projectId=${id}&calculationId=${latest.id}`)}>{en?"Continue to validation":"검증 업무로 이동"}</a>}</aside></section>
  <section className="mt-5 rounded-xl border bg-white p-5"><h2 className="text-xl font-black text-[#052b57]">{en?"3. Version History":"3. 산정 버전 이력"}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data?.runs.map(run=><article className="rounded-lg border p-4" key={run.id}><div className="flex justify-between"><strong>v{run.version}</strong><span className="rounded-full bg-green-100 px-2 py-1 text-xs font-bold text-green-800">{run.status}</span></div><p className="mt-2 text-xl font-black">{Number(run.totalEmission).toFixed(6)} {run.resultUnit}</p><p className="mt-2 text-xs text-slate-500">{run.calculatedBy} · {run.calculatedAt}</p><code className="mt-2 block truncate text-xs text-slate-400">{run.snapshotHash}</code></article>)}</div></section>
 </main></div></>;
}
