import {useEffect,useState} from 'react';
import {buildLocalizedPath,isEnglish} from '../../lib/navigation/runtime';
import './projectDetailOverview.css';

export function ProjectDetailOverview({data,error,notice,onSettings,settings}:{data:any;error:string;notice:string;onSettings:()=>void;settings:React.ReactNode}){
 const en=isEnglish(),t=(ko:string,eng:string)=>en?eng:ko,p=data.project,tasks=p.tasks||[];
 const route=(path:string)=>buildLocalizedPath(`${path}?projectId=${encodeURIComponent(p.id)}`,`/en${path}?projectId=${encodeURIComponent(p.id)}`);
 const state=(task:any)=>task.effectiveStatus||task.status;
 const labels:Record<string,string>={DONE:'완료',READY:'진행 가능',IN_PROGRESS:'진행 중',BLOCKED:'선행 업무 대기',WAITING:'대기'};
 const [page,setPage]=useState(1),pageSize=10;
 useEffect(()=>setPage(1),[p.id]);
 const [statusFilter,setStatusFilter]=useState(''),[selectedId,setSelectedId]=useState<string|null>(null);
 const filtered=tasks.filter((x:any)=>!statusFilter||state(x)===statusFilter);
 const pages=Math.max(1,Math.ceil(filtered.length/pageSize)),activePage=Math.min(page,pages),start=(activePage-1)*pageSize;
 const selected=tasks.find((x:any)=>String(x.id||x.code)===selectedId);
 const taskUrl=(task:any)=>{try{const u=new URL(task.targetUrl,location.origin);if(u.origin!==location.origin||!u.pathname.startsWith('/'))return '';u.searchParams.set('projectId',p.id);return u.pathname+u.search+u.hash;}catch{return '';}};
 const why=(task:any)=>{if(!['BLOCKED','WAITING'].includes(state(task)))return '';const reason=task.effectiveReason||task.blockedReason;if(!reason)return '';const known:Record<string,string>={PREREQUISITE_PROCESS_REQUIRED:'선행 프로세스를 먼저 완료해야 합니다.',PREDECESSOR_TASK_REQUIRED:'앞선 업무가 아직 완료되지 않았습니다.',ACTOR_NOT_AUTHORIZED:'이 업무를 수행할 권한이 필요합니다.'};return known[reason]||(/[A-Z_]{6}/.test(reason)?'선행 조건 또는 담당 권한을 확인해야 합니다.':reason);};
 useEffect(()=>{setSelectedId(null);setStatusFilter('');},[p.id]);
 return <div className="project-detail-overview">

  <header><h1>{t('배출량 프로젝트 상세','Emission project details')}</h1><p>{p.id}</p><div className="detail-actions"><a className="primary" href={route('/emission/organizational-boundary')}>{t('조직경계 보기·설정','Organizational boundary')}</a><button onClick={onSettings}>{t('담당자·일정 관리','Owner and schedule')}</button><a href={buildLocalizedPath('/emission/project_list','/en/emission/project_list')}>{t('목록','Back to list')}</a></div></header>
  {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{settings}
  <section><h2>{t('기본정보','Project information')}</h2><dl><dt>{t('프로젝트명','Project name')}</dt><dd>{p.name}</dd><dt>{t('산정 기간','Period')}</dt><dd>{p.period||'—'}</dd><dt>{t('참여 사업장','Sites')}</dt><dd>{(p.sites?.length?p.sites:[p.site]).join(', ')}</dd><dt>{t('산정 범위','Scope')}</dt><dd>{p.scope||t('미설정','Not configured')}</dd><dt>{t('완료 업무','Completed tasks')}</dt><dd>{tasks.filter((x:any)=>state(x)==='DONE').length} / {tasks.length}</dd></dl></section>
  <section><h2>{t('참여 사업장','Participating sites')}</h2><ul>{(p.sites?.length?p.sites:[p.site]).map((name:string,i:number)=><li key={i}>{name}</li>)}</ul><p className="hint">{t('현재 업무는 프로젝트 단위로 관리됩니다. 사업장별 업무 상태와 별도 배정은 아직 연결되지 않았습니다.','Tasks are currently project-wide. Site-level status and assignment are not connected yet.')}</p></section>
  <section><div className="section-heading"><h2>{t('처리할 업무','Project tasks')}</h2><span aria-live="polite">{t('전체','Total')} {filtered.length}{t('건','')} · {filtered.length?start+1:0}–{Math.min(start+pageSize,filtered.length)}</span></div>
  <label>{t('업무 상태','Task status')} <select className="task-status-filter" value={statusFilter} onChange={e=>{setStatusFilter(e.target.value);setPage(1);setSelectedId(null);}}><option value="">{t('전체','All')}</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{en?k:v}</option>)}</select></label>
  {!filtered.length?<p>{tasks.length?t('조건에 해당하는 업무가 없습니다.','No matching tasks.'):t('업무 단계가 구성되지 않았습니다. 조직경계 초안부터 확인해 주세요.','No tasks configured. Start with the boundary draft.')}</p>:<div className="table-scroll"><table><thead><tr>{[t('순서','No.'),t('업무','Task'),t('대상','Target'),t('상태','Status'),t('담당자','Assignee'),t('선택','Select')].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{filtered.slice(start,start+pageSize).map((task:any)=><tr key={task.id||task.code} aria-selected={String(task.id||task.code)===selectedId}><td>{tasks.indexOf(task)+1}</td><td>{task.name}</td><td>{t('프로젝트 공통','Project-wide')}</td><td>{en?state(task):labels[state(task)]||'확인 필요'}</td><td>{task.assignee||t('미지정','Unassigned')}</td><td><button type="button" aria-label={`${task.name} ${t('선택','select')}`} onClick={()=>setSelectedId(String(task.id||task.code))}>{t('업무 선택','Select task')}</button></td></tr>)}</tbody></table></div>}
  {pages>1&&<nav className="task-pagination" aria-label={t('업무 목록 페이지','Task pages')}><button type="button" disabled={activePage===1} onClick={()=>setPage(activePage-1)}>{t('이전','Previous')}</button>{Array.from({length:pages},(_,i)=>i+1).map(n=><button type="button" key={n} aria-label={en?`Page ${n}`:`${n}페이지`} aria-current={n===activePage?'page':undefined} onClick={()=>setPage(n)}>{n}</button>)}<button type="button" disabled={activePage===pages} onClick={()=>setPage(activePage+1)}>{t('다음','Next')}</button></nav>}</section>
  <section aria-label={t('선택한 업무','Selected task')} aria-live="polite"><h2>{t('선택한 업무','Selected task')}</h2>{!selected?<p>{t('목록에서 업무를 선택하면 해야 할 일과 이동할 화면을 확인할 수 있습니다.','Select a task to see its requirements and destination.')}</p>:<><h3>{selected.name}</h3><dl><dt>{t('해야 할 일','Required work')}</dt><dd>{selected.completionRule||t('상세 업무 조건이 등록되지 않았습니다. 담당자가 확인해야 합니다.','Detailed requirements are not registered.')}</dd><dt>{t('프로젝트','Project')}</dt><dd>{p.name} ({p.id})</dd><dt>{t('산정 기간','Period')}</dt><dd>{p.period}</dd><dt>{t('대상','Target')}</dt><dd>{t('프로젝트 공통','Project-wide')}</dd><dt>{t('담당자','Assignee')}</dt><dd>{selected.assignee||t('미지정','Unassigned')}</dd><dt>{t('업무 상태','Status')}</dt><dd>{en?state(selected):labels[state(selected)]||'확인 필요'}{why(selected)&&<p>{why(selected)}</p>}</dd></dl><div className="detail-actions">{taskUrl(selected)?<a className="primary" href={taskUrl(selected)}>{['READY','IN_PROGRESS'].includes(state(selected))?t('업무 화면으로 이동','Open task'):t('업무 내용 보기','View task')}</a>:<p>{t('연결할 업무 화면이 등록되지 않았습니다.','No destination registered.')}</p>}{selected.processCode&&<a href={route('/emission/work-assignment')+'&processCode='+encodeURIComponent(selected.processCode)}>{t('프로세스 담당자 배정','Process assignments')}</a>}</div><p className="hint">{t('이동만으로 업무가 완료되거나 권한이 부여되지 않습니다. 담당자 배정은 연결된 프로세스의 업무별 배정을 확인하는 화면에서 진행합니다.','Navigation does not complete tasks or grant permissions. Review per-step assignments on the process assignment page.')}</p></>}</section>
  <details><summary>{t('이 화면의 도움말','Help')}</summary><p>{t('프로젝트에 연결된 사업장·기간과 업무 상태를 확인하는 상세 화면입니다. 배출량 입력, 산정, 승인 작업은 각 업무 화면에서 진행합니다.','Review project sites, period and tasks here. Enter data, calculate and approve on the relevant task pages.')}</p></details>
 </div>;
}
