apiVersion: v1
kind: Secret
metadata:
  name: carbonet-runtime-secret
  namespace: carbonet-prod
  labels:
    app: carbonet-runtime
    framework: resonance
    project: carbonet
type: Opaque
stringData:
  DB_USERNAME: "dba"
  DB_PASSWORD: "change-me-to-secure-value"
  DB_URL: "jdbc:cubrid:cubrid-carbonet.carbonet-prod.svc.cluster.local:33000:carbonet:::?charset=UTF-8"
  SPRING_DATASOURCE_USERNAME: "dba"
  SPRING_DATASOURCE_PASSWORD: "change-me-to-secure-value"
  TOKEN_ACCESS_SECRET: "change-me-to-secure-value"
  TOKEN_REFRESH_SECRET: "change-me-to-secure-value"
---
apiVersion: v1
kind: Secret
metadata:
  name: carbonet-runtime-ecoinvent-secret
  namespace: carbonet-prod
  labels:
    app: carbonet-runtime
    framework: resonance
    project: carbonet
type: Opaque
stringData:
  CARBONET_ECOINVENT_CLIENT_ID: "change-me-to-secure-value"
  CARBONET_ECOINVENT_CLIENT_SECRET: "change-me-to-secure-value"
