apiVersion: v1
kind: Secret
metadata:
  name: carbonet-runtime-secret
  namespace: carbonet-prod
  labels:
    app: carbonet-runtime
    framework: resonance
    project: carbonet
type: Opaque
stringData:
  DB_USERNAME: "replace-me"
  DB_PASSWORD: "replace-me"
  DB_URL: "replace-me"
  SPRING_DATASOURCE_USERNAME: "replace-me"
  SPRING_DATASOURCE_PASSWORD: "replace-me"
  TOKEN_ACCESS_SECRET: "replace-me"
  TOKEN_REFRESH_SECRET: "replace-me"
