import { useEffect, useMemo, useState } from "react";
import { AdminPageShell } from "../admin-entry/AdminPageShell";
import { buildLocalizedPath, isEnglish } from "../../lib/navigation/runtime";

type HomeSection = {
  sectionCode: string; sectionName: string; sectionNameEn: string; categoryCode: string;
  description: string; componentKey: string; implementationStatus: string; dataStatus: string;
  designReference: string; enabled: boolean; sortOrder: number; audienceCodes: string;
};
type Version = { versionId: number; versionNo: number; publishedBy: string; publishedAt: string };
type Payload = { variant: string; sections: HomeSection[]; versions: Version[] };

const CATEGORY_LABELS: Record<string,string> = { DATA:"데이터·지표", SERVICE:"공개 서비스", NAVIGATION:"빠른 이동", WORK:"내 업무", CONTENT:"콘텐츠·지원" };
const STATUS_STYLE: Record<string,string> = { IMPLEMENTED:"bg-emerald-100 text-emerald-800", PLANNED:"bg-slate-100 text-slate-700", CONNECTED:"bg-blue-100 text-blue-800", SAMPLE:"bg-amber-100 text-amber-800", NOT_CONNECTED:"bg-rose-100 text-rose-800" };

export function HomePageWorkbenchMigrationPage() {
  const en=isEnglish(), base=buildLocalizedPath("/admin/api/system/home-composition","/en/admin/api/system/home-composition");
  const [data,setData]=useState<Payload|null>(null),[variant,setVariant]=useState("PUBLIC"),[filter,setFilter]=useState("ALL"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  async function load(){const r=await fetch(`${base}?variant=${variant}`,{credentials:"include"}),b=await r.json();if(!r.ok)throw new Error(b.message||"홈 구성을 불러오지 못했습니다.");setData(b);}
  useEffect(()=>{void load().catch(e=>setMessage(e.message));},[variant]);
  async function save(sections:HomeSection[]){setData(current=>current?{...current,sections}:current);setMessage(en?"Saving draft...":"초안을 자동 저장하고 있습니다.");const r=await fetch(`${base}/draft`,{method:"PUT",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({variant,sections})}),b=await r.json();if(!r.ok)throw new Error(b.message);setMessage(en?"Draft saved automatically.":"초안이 자동 저장되었습니다.");}
  async function toggle(code:string){if(!data)return;const next=data.sections.map(s=>s.sectionCode===code?{...s,enabled:!s.enabled}:s);await save(next);}
  async function move(code:string,direction:-1|1){if(!data)return;const ordered=[...data.sections].sort((a,b)=>a.sortOrder-b.sortOrder),index=ordered.findIndex(s=>s.sectionCode===code),target=index+direction;if(index<0||target<0||target>=ordered.length)return;[ordered[index],ordered[target]]=[ordered[target],ordered[index]];const next=ordered.map((s,i)=>({...s,sortOrder:(i+1)*10}));await save(next);}
  async function publish(){if(!confirm(en?"Publish this composition to the home page?":"현재 초안을 홈페이지에 발행하시겠습니까?"))return;setBusy(true);try{const r=await fetch(`${base}/publish`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({variant})}),b=await r.json();if(!r.ok)throw new Error(b.message);setMessage(en?`Version ${b.versionNo} published.`:`버전 ${b.versionNo}을 발행했습니다.`);await load();}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setBusy(false)}}
  const visible=useMemo(()=>data?.sections.filter(s=>filter==="ALL"||s.categoryCode===filter)||[],[data,filter]);
  const enabled=data?.sections.filter(s=>s.enabled).length||0, connected=data?.sections.filter(s=>s.dataStatus==="CONNECTED").length||0, implemented=data?.sections.filter(s=>s.implementationStatus==="IMPLEMENTED").length||0;
  return <AdminPageShell title={en?"Home Composition Studio":"홈 구성 스튜디오"} subtitle={en?"Select, order, preview, and publish governed home sections.":"홈 섹션을 선택·정렬·미리보기하고 발행 버전으로 관리합니다."}>
    <div className="space-y-5">
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["전체 섹션",data?.sections.length||0],["선택됨",enabled],["UI 구현",implemented],["실데이터 연결",connected]].map(([label,value])=><article className="rounded-xl border border-slate-200 bg-white p-5" key={String(label)}><p className="text-sm font-bold text-slate-500">{label}</p><strong className="mt-2 block text-3xl text-[#052b57]">{value}</strong></article>)}</section>
      <section className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2"><select className="h-11 rounded-lg border px-3 font-bold" value={variant} onChange={e=>setVariant(e.target.value)}><option value="PUBLIC">비로그인 홈</option><option value="AUTHENTICATED">로그인 홈</option><option value="ADMIN">관리자 홈</option></select>{["ALL",...Object.keys(CATEGORY_LABELS)].map(code=><button className={`rounded-full border px-4 py-2 text-sm font-bold ${filter===code?"border-blue-700 bg-blue-700 text-white":"border-slate-300 bg-white"}`} key={code} onClick={()=>setFilter(code)}>{code==="ALL"?"전체":CATEGORY_LABELS[code]}</button>)}</div><div className="flex gap-2"><a className="rounded-lg border border-blue-700 px-4 py-3 font-black text-blue-800" href={buildLocalizedPath("/home","/en/home")} target="_blank" rel="noreferrer">홈 미리보기</a><button className="rounded-lg bg-[#246beb] px-5 py-3 font-black text-white disabled:opacity-50" disabled={busy} onClick={publish}>현재 초안 발행</button></div></div>{message&&<p className="mt-3 rounded-lg bg-blue-50 p-3 text-sm font-bold text-blue-800">{message}</p>}</section>
      <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
        <section className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b bg-slate-50 px-5 py-4"><h2 className="text-lg font-black">섹션 카탈로그</h2><p className="mt-1 text-sm text-slate-500">체크 변경과 순서 변경은 초안에 즉시 저장됩니다. 미구현 섹션도 개발 대상으로 선택할 수 있습니다.</p></div><div className="divide-y">{visible.map(section=><article className="grid gap-4 p-5 md:grid-cols-[auto_1fr_auto] md:items-center" key={section.sectionCode}><input aria-label={`${section.sectionName} 사용`} className="h-5 w-5 accent-blue-700" type="checkbox" checked={section.enabled} onChange={()=>void toggle(section.sectionCode).catch(e=>setMessage(e.message))}/><div><div className="flex flex-wrap items-center gap-2"><strong className="text-base text-slate-950">{en?section.sectionNameEn:section.sectionName}</strong><span className={`rounded-full px-2 py-1 text-[11px] font-black ${STATUS_STYLE[section.implementationStatus]||STATUS_STYLE.PLANNED}`}>{section.implementationStatus}</span><span className={`rounded-full px-2 py-1 text-[11px] font-black ${STATUS_STYLE[section.dataStatus]||STATUS_STYLE.NOT_CONNECTED}`}>{section.dataStatus}</span></div><p className="mt-1 text-sm text-slate-600">{section.description}</p><p className="mt-2 font-mono text-xs text-slate-400">{section.componentKey} · {section.designReference}</p></div><div className="flex items-center gap-2"><span className="w-9 text-center text-sm font-black">{section.sortOrder}</span><button className="h-9 w-9 rounded border" aria-label="위로" onClick={()=>void move(section.sectionCode,-1)}>↑</button><button className="h-9 w-9 rounded border" aria-label="아래로" onClick={()=>void move(section.sectionCode,1)}>↓</button></div></article>)}</div></section>
        <aside className="space-y-5"><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">발행 미리보기</h2><div className="mt-4 space-y-2">{data?.sections.filter(s=>s.enabled).sort((a,b)=>a.sortOrder-b.sortOrder).map((s,i)=><div className="flex items-center gap-3 rounded-lg border bg-slate-50 p-3" key={s.sectionCode}><span className="flex h-8 w-8 items-center justify-center rounded-full bg-blue-700 text-sm font-black text-white">{i+1}</span><div><strong className="text-sm">{s.sectionName}</strong><p className="text-xs text-slate-500">{s.implementationStatus} · {s.dataStatus}</p></div></div>)}</div></section><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">발행 이력</h2><div className="mt-4 space-y-3">{data?.versions.map(v=><div className="border-b pb-3 text-sm" key={v.versionId}><strong>Version {v.versionNo}</strong><p className="mt-1 text-xs text-slate-500">{v.publishedBy} · {new Date(v.publishedAt).toLocaleString()}</p></div>)}</div></section></aside>
      </div>
    </div>
  </AdminPageShell>;
}
