CREATE TABLE IF NOT EXISTS carbonet_menu_reconciliation_history (
    reconciliation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    trigger_type varchar(20) NOT NULL,
    expected_count integer NOT NULL,
    restored_info integer NOT NULL DEFAULT 0,
    restored_order integer NOT NULL DEFAULT 0,
    restored_detail integer NOT NULL DEFAULT 0,
    status varchar(20) NOT NULL,
    message varchar(1000)
);

CREATE INDEX IF NOT EXISTS idx_menu_reconciliation_run_at
    ON carbonet_menu_reconciliation_history (run_at DESC);

COMMENT ON TABLE carbonet_menu_reconciliation_history
    IS 'Audit history for automatic restoration of missing managed admin menu rows.';
