package egovframework.com.feature.home.web;

import egovframework.com.feature.auth.service.CurrentUserContextService;
import egovframework.com.feature.home.service.EmissionProjectRegistryService;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.ResponseEntity;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;
import java.time.LocalDate;
import java.math.BigDecimal;

@RestController
public class ReductionTaskWorkflowController {
 private final JdbcTemplate db; private final CurrentUserContextService users; private final EmissionProjectRegistryService registry; private final TransactionTemplate tx; private final ObjectMapper json;
 public ReductionTaskWorkflowController(JdbcTemplate d,CurrentUserContextService u,EmissionProjectRegistryService r,PlatformTransactionManager t,ObjectMapper j){db=d;users=u;registry=r;tx=new TransactionTemplate(t);json=j;}
 private String str(Map<String,Object>b,String k){return Objects.toString(b.get(k),"").trim();}
 private String required(Map<String,Object>b,String k,int max){String s=str(b,k);if(s.isBlank()||s.length()>max)throw new IllegalArgumentException(k+" 항목을 확인해 주세요. (1~"+max+"자)");return s;}
 private BigDecimal number(Map<String,Object>b,String k){try{BigDecimal n=new BigDecimal(str(b,k));if(n.signum()<0||n.compareTo(new BigDecimal("100000000000000"))>0||n.scale()>6)throw new IllegalArgumentException();return n;}catch(Exception e){throw new IllegalArgumentException(k+"은 0 이상의 숫자, 소수점 6자리 이내로 입력해 주세요.");}}
 private String encode(Object o){try{return json.writeValueAsString(o);}catch(Exception e){throw new IllegalArgumentException("저장 형식을 확인해 주세요.");}}
 private Map<String,Object> decode(Object o){try{return json.readValue(o.toString(),Map.class);}catch(Exception e){throw new IllegalStateException("저장 데이터를 읽지 못했습니다.");}}
 private String[] identity(String project,HttpServletRequest req){var u=users.resolve(req);if(!u.isAuthenticated())throw new SecurityException("로그인이 필요합니다.");String tenant=u.isWebmaster()?"DEFAULT":u.getInsttId();if(tenant==null||tenant.isBlank())throw new SecurityException("소속 회사를 확인해 주세요.");registry.organizationalBoundary(project,tenant,u.getUserId(),u.isWebmaster());return new String[]{tenant,u.getUserId(),u.isWebmaster()?"MASTER":"USER"};}
 private boolean role(String[]id,String project,String account,String...roles){for(String role:roles){Boolean ok=db.queryForObject("SELECT EXISTS(SELECT 1 FROM framework_account_actor_assignment WHERE tenant_id=? AND lower(account_id)=lower(?) AND actor_code=? AND assignment_status='ACTIVE' AND project_id IN ('*',?) AND data_scope='*' AND (valid_from IS NULL OR valid_from<=current_date) AND (valid_until IS NULL OR valid_until>=current_date))",Boolean.class,id[0],account,role,project);if(Boolean.TRUE.equals(ok))return true;}return false;}
 private void writeAllowed(String[]id,String project){if(!"MASTER".equals(id[2])&&!role(id,project,id[1],"REDUCTION_MANAGER","COMPANY_MANAGER","SITE_DATA_OWNER","CALCULATOR"))throw new SecurityException("감축 과제 작성 권한이 필요합니다.");}
 private Map<String,Object> row(String[]id,String project,String task,boolean lock){var rows=db.queryForList("SELECT * FROM reduction_task_workflow WHERE tenant_id=? AND project_id=? AND task_id=?"+(lock?" FOR UPDATE":""),id[0],project,task);if(rows.isEmpty())throw new IllegalArgumentException("이 프로젝트의 과제를 찾지 못했습니다.");Map<String,Object> r=new LinkedHashMap<>(rows.get(0));r.put("payload",decode(r.get("payload")));return r;}
 private void version(Map<String,Object>r,Map<String,Object>b){if(!Objects.toString(r.get("version")).equals(str(b,"version")))throw new IllegalStateException("다른 사용자가 수정했습니다. 다시 조회해 주세요.");}
 private void history(String task,String event,int version,String actor,Map<String,Object>body){db.update("INSERT INTO reduction_task_workflow_history(task_id,event_type,version,actor_id,snapshot) VALUES (?,?,?,?,?::jsonb)",task,event,version,actor,encode(body));}
 private ResponseEntity<?> error(Exception e,HttpServletRequest req){int code=e instanceof SecurityException?(users.resolve(req).isAuthenticated()?403:401):e instanceof IllegalStateException?409:e instanceof IllegalArgumentException?400:500;return ResponseEntity.status(code).body(Map.of("message",code==500?"저장하지 못했습니다. 입력값을 유지하고 다시 시도해 주세요.":Objects.toString(e.getMessage(),"요청을 확인해 주세요.")));}
 private void basic(String[]id,String project,Map<String,Object>b,Map<String,Object>p){p.put("name",required(b,"name",200));p.put("measure",required(b,"measure",1000));p.put("equipment",required(b,"equipment",500));String site=required(b,"siteId",64);Boolean ok=db.queryForObject("SELECT EXISTS(SELECT 1 FROM emission_project_site ps JOIN emission_site_registry s ON s.site_id=ps.site_id WHERE ps.project_id=? AND s.tenant_id=? AND s.site_id::text=?)",Boolean.class,project,id[0],site);if(!Boolean.TRUE.equals(ok))throw new IllegalArgumentException("프로젝트에 연결된 사업장을 선택해 주세요.");LocalDate start=LocalDate.parse(required(b,"startDate",10)),end=LocalDate.parse(required(b,"endDate",10));if(start.isAfter(end))throw new IllegalArgumentException("종료일은 시작일 이후여야 합니다.");if(start.getYear()<2000||end.getYear()>2100)throw new IllegalArgumentException("기간은 2000~2100년 이내여야 합니다.");p.put("siteId",site);p.put("startDate",start.toString());p.put("endDate",end.toString());p.put("basicSaved",true);}
 @GetMapping({"/home/api/reduction-projects/{project}/tasks","/en/home/api/reduction-projects/{project}/tasks"})
 public ResponseEntity<?> list(@PathVariable String project,HttpServletRequest req){try{var id=identity(project,req);var items=db.queryForList("SELECT task_id,task_name,task_status,version,updated_at FROM reduction_task_workflow WHERE tenant_id=? AND project_id=? ORDER BY updated_at DESC",id[0],project);var sites=db.queryForList("SELECT s.site_id::text AS id,s.site_name AS name FROM emission_project_site p JOIN emission_site_registry s ON p.site_id=s.site_id WHERE p.project_id=? AND s.tenant_id=? ORDER BY p.display_order",project,id[0]);var accounts=db.queryForList("SELECT DISTINCT account_id,actor_code FROM framework_account_actor_assignment WHERE tenant_id=? AND project_id IN ('*',?) AND data_scope='*' AND assignment_status='ACTIVE' AND actor_code IN ('REDUCTION_MANAGER','COMPANY_MANAGER','SITE_DATA_OWNER','CALCULATOR','APPROVER') AND (valid_from IS NULL OR valid_from<=current_date) AND (valid_until IS NULL OR valid_until>=current_date) ORDER BY account_id,actor_code",id[0],project);return ResponseEntity.ok(Map.of("items",items,"sites",sites,"accounts",accounts,"accountId",id[1]));}catch(Exception e){return error(e,req);}}
 @GetMapping({"/home/api/reduction-projects/{project}/tasks/{task}","/en/home/api/reduction-projects/{project}/tasks/{task}"})
 public ResponseEntity<?> detail(@PathVariable String project,@PathVariable String task,HttpServletRequest req){try{var id=identity(project,req);var r=row(id,project,task,false);r.put("history",db.queryForList("SELECT event_type,version,actor_id,created_at FROM reduction_task_workflow_history WHERE task_id=? ORDER BY history_id DESC",task));return ResponseEntity.ok(r);}catch(Exception e){return error(e,req);}}
 @PostMapping({"/home/api/reduction-projects/{project}/tasks","/en/home/api/reduction-projects/{project}/tasks"})
 public ResponseEntity<?> create(@PathVariable String project,@RequestBody Map<String,Object>b,HttpServletRequest req){try{var id=identity(project,req);writeAllowed(id,project);String task=required(b,"taskId",64);if(!task.matches("RT-[A-Za-z0-9-]{20,60}"))throw new IllegalArgumentException("과제 요청 ID가 올바르지 않습니다.");Map<String,Object>p=new LinkedHashMap<>();basic(id,project,b,p);return ResponseEntity.ok(tx.execute(status->{db.query("SELECT pg_advisory_xact_lock(hashtextextended(?,0))",rs->{},task);var exists=db.queryForList("SELECT task_id FROM reduction_task_workflow WHERE task_id=?",task);if(!exists.isEmpty()){var existing=row(id,project,task,false);if(!str((Map)existing.get("payload"),"name").equals(str(p,"name")))throw new IllegalStateException("중복 요청 내용이 다릅니다.");return existing;}db.update("INSERT INTO reduction_task_workflow(task_id,tenant_id,project_id,task_name,payload,created_by,updated_by) VALUES (?,?,?,?,?::jsonb,?,?)",task,id[0],project,p.get("name"),encode(p),id[1],id[1]);history(task,"CREATED",1,id[1],p);return row(id,project,task,false);}));}catch(Exception e){return error(e,req);}}
 @PutMapping({"/home/api/reduction-projects/{project}/tasks/{task}/{section}","/en/home/api/reduction-projects/{project}/tasks/{task}/{section}"})
 public ResponseEntity<?> save(@PathVariable String project,@PathVariable String task,@PathVariable String section,@RequestBody Map<String,Object>b,HttpServletRequest req){try{var id=identity(project,req);writeAllowed(id,project);return ResponseEntity.ok(tx.execute(status->{var r=row(id,project,task,true);version(r,b);String state=str(r,"task_status");if(!List.of("DRAFT","REJECTED").contains(state))throw new IllegalStateException("승인 요청 또는 승인 완료된 과제는 수정할 수 없습니다.");Map<String,Object>p=new LinkedHashMap<>((Map)r.get("payload"));
 if(section.equals("basic")){basic(id,project,b,p);p.remove("estimateSaved");p.remove("expectedReduction");}
 else if(section.equals("resources")){String assignee=required(b,"assignee",100);if(!role(id,project,assignee,"REDUCTION_MANAGER","COMPANY_MANAGER","SITE_DATA_OWNER","CALCULATOR"))throw new IllegalArgumentException("유효한 과제 담당 계정을 선택해 주세요.");p.put("assignee",assignee);p.put("budget",number(b,"budget"));p.put("resourceNotes",required(b,"resourceNotes",2000));p.put("resourcesSaved",true);}
 else if(section.equals("estimate")){BigDecimal baseline=number(b,"baselineEmission"),expected=number(b,"expectedEmission");if(baseline.signum()==0||expected.compareTo(baseline)>0)throw new IllegalArgumentException("기준 배출량은 0보다 커야 하며 예상 배출량은 기준 배출량 이하여야 합니다.");p.put("baselineEmission",baseline);p.put("expectedEmission",expected);p.put("expectedReduction",baseline.subtract(expected));p.put("estimateUnit","tCO2e/년");p.put("baselineRef",required(b,"baselineRef",2000));p.put("assumptions",required(b,"assumptions",4000));p.put("estimateSaved",true);}
 else throw new IllegalArgumentException("지원하지 않는 저장 구간입니다.");int v=((Number)r.get("version")).intValue()+1;db.update("UPDATE reduction_task_workflow SET task_name=?,payload=?::jsonb,task_status='DRAFT',version=?,updated_by=?,updated_at=now() WHERE task_id=?",p.get("name"),encode(p),v,id[1],task);history(task,section.toUpperCase()+"_SAVED",v,id[1],p);return row(id,project,task,false);}));}catch(Exception e){return error(e,req);}}
 @PostMapping({"/home/api/reduction-projects/{project}/tasks/{task}/{action}","/en/home/api/reduction-projects/{project}/tasks/{task}/{action}"})
 public ResponseEntity<?> transition(@PathVariable String project,@PathVariable String task,@PathVariable String action,@RequestBody Map<String,Object>b,HttpServletRequest req){try{var id=identity(project,req);return ResponseEntity.ok(tx.execute(status->{var r=row(id,project,task,true);version(r,b);Map<String,Object>p=new LinkedHashMap<>((Map)r.get("payload"));String state=str(r,"task_status"),next;
 if(action.equals("submit")){writeAllowed(id,project);if(!List.of("DRAFT","REJECTED").contains(state))throw new IllegalStateException("작성 중인 과제만 승인 요청할 수 있습니다.");if(!Boolean.TRUE.equals(p.get("basicSaved"))||!Boolean.TRUE.equals(p.get("resourcesSaved"))||!Boolean.TRUE.equals(p.get("estimateSaved")))throw new IllegalArgumentException("기본정보·자원계획·예상 감축량을 모두 저장해 주세요.");String approver=required(b,"approver",100);if(approver.equalsIgnoreCase(str(r,"created_by"))||approver.equalsIgnoreCase(str(p,"assignee")))throw new IllegalArgumentException("작성자·담당자와 다른 결재자를 선택해 주세요.");if(!role(id,project,approver,"APPROVER"))throw new IllegalArgumentException("유효한 승인 권한을 가진 결재자를 선택해 주세요.");p.put("approver",approver);p.put("submissionNote",required(b,"note",2000));next="SUBMITTED";}
 else if(action.equals("approve")||action.equals("reject")){if(!state.equals("SUBMITTED"))throw new IllegalStateException("승인 요청된 과제만 처리할 수 있습니다.");if(!id[1].equalsIgnoreCase(str(p,"approver"))||!role(id,project,id[1],"APPROVER"))throw new SecurityException("지정된 결재자만 처리할 수 있습니다.");p.put("decisionNote",required(b,"note",2000));next=action.equals("approve")?"APPROVED":"REJECTED";}
 else throw new IllegalArgumentException("지원하지 않는 요청입니다.");int v=((Number)r.get("version")).intValue()+1;db.update("UPDATE reduction_task_workflow SET payload=?::jsonb,task_status=?,version=?,updated_by=?,updated_at=now() WHERE task_id=?",encode(p),next,v,id[1],task);history(task,next,v,id[1],p);return row(id,project,task,false);}));}catch(Exception e){return error(e,req);}}
}
