import { useEffect, useState } from 'react';
import design from './reduction-task-design.json';
type Fields=Record<string,any>;
const routes=[['/reduction/task/new','과제 등록','basic'],['/reduction/task/resources','담당자·예산·일정','resources'],['/reduction/task/estimate','예상 감축량','estimate'],['/reduction/task/approval','과제 검토·승인','approval']];
const definitions:Record<string,{key:string;label:string;type?:string;help?:string}[]>={
 basic:[{key:'name',label:'과제명'},{key:'siteId',label:'대상 사업장',type:'site'},{key:'measure',label:'감축 수단·실행 내용',type:'textarea'},{key:'equipment',label:'대상 설비·공정'},{key:'startDate',label:'착수일',type:'date'},{key:'endDate',label:'종료일',type:'date'}],
 resources:[{key:'assignee',label:'담당 계정',type:'account'},{key:'budget',label:'총 예산 (원)',type:'number'},{key:'resourceNotes',label:'실행 자원·예산 근거',type:'textarea'}],
 estimate:[{key:'baselineEmission',label:'동일 조건 기준 배출량 (tCO₂e/년)',type:'number'},{key:'expectedEmission',label:'도입 후 예상 배출량 (tCO₂e/년)',type:'number'},{key:'baselineRef',label:'기준 배출량 출처·산정 버전·증빙 위치',type:'textarea'},{key:'assumptions',label:'예상량 산정 근거·가정·적용 범위',type:'textarea',help:'동일 사업장·기간·생산 조건으로 비교합니다. 계획 단계의 예상량이며 검증된 실적이 아닙니다.'}]
};
export function ReductionTaskEditor(){
 const q=new URLSearchParams(location.search),project=q.get('projectId')||'';
 const path=location.pathname.replace(/^\/en/,'');const stage=routes.find(r=>r[0]===path)?.[2]||'list';
 const [task,setTask]=useState(q.get('reductionTaskId')||'');const [options,setOptions]=useState<Fields>({items:[],sites:[],accounts:[]});const [projects,setProjects]=useState<Fields[]>([]);
 const [row,setRow]=useState<Fields|null>(null),[form,setForm]=useState<Fields>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(true),[error,setError]=useState('');
 const [approver,setApprover]=useState(''),[note,setNote]=useState('');const [requestId]=useState(()=> 'RT-'+Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join(''));
 const base='/home/api/reduction-projects/'+encodeURIComponent(project)+'/tasks';
 const href=(p:string,t=task)=>p+'?'+new URLSearchParams({projectId:project,...(t?{reductionTaskId:t}:{})}).toString();
 async function api(url:string,method='GET',body?:Fields){const res=await fetch(url,{method,credentials:'include',headers:{'Content-Type':'application/json',Accept:'application/json'},...(body?{body:JSON.stringify(body)}:{})});const b=await res.json();if(!res.ok)throw Error(b.message||'조회·저장에 실패했습니다.');return b;}
 async function refresh(t=task){setBusy(true);setError('');try{const o=await api(base);setOptions(o);if(t){const r=await api(base+'/'+encodeURIComponent(t));setRow(r);setForm(r.payload||{});setApprover(r.payload?.approver||'');}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{if(project)void refresh();else void api('/home/api/emission-project-list-v1?pageSize=100').then(b=>setProjects(b.items||[])).catch(e=>setError(e.message));},[project]);
 async function save(){setBusy(true);setError('');setMessage('');try{const r=task?await api(base+'/'+task+'/'+stage,'PUT',{...form,version:row?.version}):await api(base,'POST',{...form,taskId:requestId});setTask(r.task_id);setRow(r);setForm(r.payload);history.replaceState(null,'',href(path,r.task_id));await refresh(r.task_id);setMessage('저장 후 서버에서 다시 조회했습니다. 과제 '+r.task_id+' · 버전 '+r.version);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function action(a:string){if(!confirm(a==='submit'?'선택한 결재자에게 승인 요청하시겠습니까?':a==='approve'?'이 과제를 승인하시겠습니까?':'이 과제를 반려하시겠습니까?'))return;setBusy(true);setError('');try{const r=await api(base+'/'+task+'/'+a,'POST',{version:row?.version,approver,note});setRow(r);setForm(r.payload);await refresh();setMessage('처리 결과: '+r.task_status+' · 버전 '+r.version);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const title=stage==='list'?'감축 과제 목록':routes.find(r=>r[2]===stage)?.[1];
 const locked=!!row&&!['DRAFT','REJECTED'].includes(row.task_status);
 const accountOptions=Array.from(new Set<string>((options.accounts||[]).filter((a:Fields)=>a.actor_code!=='APPROVER').map((a:Fields)=>a.account_id)));
 const approvers=Array.from(new Set<string>((options.accounts||[]).filter((a:Fields)=>a.actor_code==='APPROVER').map((a:Fields)=>a.account_id)));
 return <main className="reduction-task-editor" data-reduction-task-stage={stage}><style>{`.reduction-task-editor{max-width:1216px;margin:0 auto;padding:32px 24px 60px;background:white;color:#172b4d}.reduction-task-editor h1{font-size:30px;font-weight:700;margin:20px 0 28px}.reduction-task-editor nav{display:flex;gap:12px;flex-wrap:wrap;margin-bottom:24px}.reduction-task-editor nav a{padding:10px 16px;border:1px solid #bbc8d8;border-radius:4px;color:#003675}.reduction-task-editor nav a[aria-current=step]{background:#003675;color:white}.reduction-task-editor form{border-top:2px solid #33475b;padding-top:24px}.reduction-task-grid{display:grid;grid-template-columns:1fr 1fr;gap:24px}.reduction-task-editor label{display:block;font-size:14px;font-weight:700}.reduction-task-editor input,.reduction-task-editor select,.reduction-task-editor textarea{display:block;width:100%;min-height:44px;border:1px solid #8b9aac;border-radius:4px;padding:10px;margin-top:8px;background:white;color:#172b4d}.reduction-task-editor textarea{min-height:110px}.reduction-task-editor button{min-height:44px;padding:10px 18px;background:#003675;color:white;border-radius:4px;margin:16px 8px 0 0}.reduction-task-editor button:disabled{opacity:.5}.reduction-task-editor table{width:100%;border-collapse:collapse;margin:24px 0}.reduction-task-editor th,.reduction-task-editor td{padding:12px;border-bottom:1px solid #d5dce3;text-align:left}.reduction-task-editor th{background:#f4f5f7}.reduction-task-editor a{color:#003675;text-decoration:underline}.reduction-task-editor .notice{padding:16px;border:1px solid #d6e0eb;background:#f5f7fa;margin:16px 0}.reduction-task-editor .error{color:#a30e16;background:#fff1f2;border-color:#eeafb5}@media(max-width:700px){.reduction-task-grid{grid-template-columns:1fr}}`}</style>
 <style>{`body:has(.reduction-task-editor),body:has(.reduction-task-editor) #root{background:#fff}`}</style><h1>{title}</h1>
 {error&&<div className="notice error" role="alert">{error}</div>}{message&&<div className="notice" role="status">{message}</div>}
 {!project?<label>프로젝트 선택<select aria-label="프로젝트 선택" defaultValue="" onChange={e=>location.assign(path+'?projectId='+encodeURIComponent(e.target.value))}><option value="">프로젝트를 선택하세요</option>{projects.map(p=><option key={p.id||p.projectId} value={p.id||p.projectId}>{p.name||p.projectName||p.projectNm||p.id}</option>)}</select></label>:<>
 <p>프로젝트 {project}{task?' · 과제 '+task:''}{row?' · '+row.task_status+' · 버전 '+row.version:''}</p>
 <nav><a href={href('/reduction/tasks','')}>과제 목록</a>{routes.map(([p,n,s],i)=><a key={p} aria-current={s===stage?'step':undefined} href={href(p)}>{i+1}. {n}</a>)}</nav>
 {stage==='list'?<><a href={href('/reduction/task/new','')}>새 감축 과제 등록</a><table><thead><tr><th>과제명</th><th>상태</th><th>최근 수정</th></tr></thead><tbody>{options.items.map((r:Fields)=><tr key={r.task_id}><td><a href={href('/reduction/task/new',r.task_id)}>{r.task_name}</a></td><td>{r.task_status}</td><td>{String(r.updated_at)}</td></tr>)}</tbody></table>{!options.items.length&&<p>등록된 과제가 없습니다.</p>}</>:stage!=='basic'&&!task?<div className="notice">먼저 과제를 등록하거나 <a href={href('/reduction/tasks','')}>목록에서 과제를 선택</a>하세요.</div>:stage==='approval'?<>
 <table><tbody>{[['과제명',form.name],['대상 설비',form.equipment],['기간',form.startDate+' ~ '+form.endDate],['담당자',form.assignee],['예산 (원)',form.budget],['기준 배출량 (tCO₂e/년)',form.baselineEmission],['도입 후 예상 배출량',form.expectedEmission],['예상 감축량',form.expectedReduction],['산정 근거',form.baselineRef],['가정',form.assumptions]].map(([k,v])=><tr key={k}><th>{k}</th><td>{v??'미입력'}</td></tr>)}</tbody></table>
 <label>결재자<select aria-label="결재자" value={approver} disabled={locked} onChange={e=>setApprover(e.target.value)}><option value="">기존 승인 권한 계정 선택</option>{approvers.map(a=><option key={a} value={a}>{a}</option>)}</select></label><label>요청·검토 의견<textarea aria-label="요청·검토 의견" value={note} onChange={e=>setNote(e.target.value)}/></label>
 {!locked&&<button disabled={busy||!row} onClick={()=>void action('submit')}>승인 요청</button>}{row?.task_status==='SUBMITTED'&&form.approver===options.accountId&&<><button disabled={busy} onClick={()=>void action('approve')}>승인</button><button disabled={busy} onClick={()=>void action('reject')}>반려</button></>}
 </>:<form onSubmit={e=>{e.preventDefault();void save();}}><div className="reduction-task-grid">{definitions[stage]?.map(f=><label key={f.key}>{f.label} *{f.type==='site'||f.type==='account'?<select name={f.key} value={form[f.key]||''} required disabled={locked||busy} onChange={e=>setForm({...form,[f.key]:e.target.value})}><option value="">선택하세요</option>{f.type==='site'?options.sites.map((s:Fields)=><option key={s.id} value={s.id}>{s.name}</option>):accountOptions.map(a=><option key={a} value={a}>{a}</option>)}</select>:f.type==='textarea'?<textarea name={f.key} required maxLength={f.key==='assumptions'?4000:2000} disabled={locked||busy} value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>:<input name={f.key} type={f.type||'text'} min={f.type==='number'?'0':undefined} step={f.type==='number'?'0.000001':undefined} required disabled={locked||busy} value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>} {f.help&&<small>{f.help}</small>}</label>)}</div>
 {stage==='estimate'&&<p className="notice">예상 연간 감축량 = 기준 배출량 − 도입 후 예상 배출량. 저장된 결과: <strong>{form.expectedReduction??'미산정'} tCO₂e/년</strong></p>}
 <button type="submit" disabled={busy||locked}>{busy?'저장 중…':stage==='estimate'?'계산·저장':'저장'}</button><button type="button" disabled={busy} onClick={()=>{if(confirm('입력 중인 변경을 버리고 저장값을 다시 조회합니까?'))void refresh();}}>저장값 다시 조회</button>{locked&&<p>승인 요청 이후에는 수정할 수 없습니다. 반려된 과제는 보완 후 다시 요청하세요.</p>}</form>}
 {row?.history?.length>0&&<details className="notice"><summary>변경 이력 ({row.history.length})</summary><ol>{row.history.map((h:Fields,i:number)=><li key={i}>v{h.version} · {h.event_type} · {h.actor_id} · {String(h.created_at)}</li>)}</ol></details>}
 </>}
 <details className="notice"><summary>이 화면의 도움말·설계·QA</summary><p>{design.pages.find(p=>p.path===path)?.action}</p><p>입력: {design.pages.find(p=>p.path===path)?.input}</p><p>출력: {design.pages.find(p=>p.path===path)?.output}</p><p>{design.flow}</p><p>{design.qa}</p><p>{design.boundary}</p></details>
 </main>;
}
