// Generated by scripts/generate-resonance-project-registry.mjs. Do not edit.
export type ResonanceProjectRecord = {
  projectId: string;
  projectName: string;
  description: string;
  owner: string;
  lifecycle: string;
  compatibilityClass: string;
  sourcePath: string;
  metadataPath: string;
  assetPath: string;
  databaseMode: string;
  databaseSchema: string;
  runtimeMode: string;
  runtimeStatus: string;
  runtimeRoute: string;
  designRoute: string;
  screenSpaceRoute: string;
  integrationStatus: string;
};
export const RESONANCE_PROJECT_REGISTRY: ResonanceProjectRecord[] = [
  {
    "projectId": "CCUS-PLATFORM",
    "projectName": "CCUS Platform",
    "description": "Resonance 기반 탄소배출·LCA·감축·거래 통합 플랫폼",
    "owner": "ccus-platform-team",
    "lifecycle": "production",
    "compatibilityClass": "RESONANCE_NATIVE",
    "sourcePath": "projects/carbonet-frontend",
    "metadataPath": "projects/carbonet-backend-metadata",
    "assetPath": "projects/carbonet-assets",
    "databaseMode": "SHARED_HA_DATABASE",
    "databaseSchema": "public",
    "runtimeMode": "KUBERNETES",
    "runtimeStatus": "RUNNING",
    "runtimeRoute": "http://172.16.1.232",
    "designRoute": "/ccus-screen-designs",
    "screenSpaceRoute": "/ccus-screen-space",
    "integrationStatus": "CONNECTED"
  },
  {
    "projectId": "P004",
    "projectName": "Resonance-Sample-Blue",
    "description": "Metadata-first Resonance project P004",
    "owner": "project-team",
    "lifecycle": "experimental",
    "compatibilityClass": "METADATA_FIRST",
    "sourcePath": "projects/P004",
    "metadataPath": "projects/P004/manifest.json",
    "assetPath": "projects/P004",
    "databaseMode": "PROJECT_DB",
    "databaseSchema": "public",
    "runtimeMode": "DEDICATED_PROJECT_RUNTIME",
    "runtimeStatus": "READY_FOR_DATABASE",
    "runtimeRoute": "/r/P004",
    "designRoute": "/ccus-screen-designs",
    "screenSpaceRoute": "/ccus-screen-space",
    "integrationStatus": "SEPARATED"
  },
  {
    "projectId": "P005",
    "projectName": "Resonance-Sample-Green",
    "description": "Metadata-first Resonance project P005",
    "owner": "project-team",
    "lifecycle": "experimental",
    "compatibilityClass": "METADATA_FIRST",
    "sourcePath": "projects/P005",
    "metadataPath": "projects/P005/manifest.json",
    "assetPath": "projects/P005",
    "databaseMode": "PROJECT_DB",
    "databaseSchema": "public",
    "runtimeMode": "DEDICATED_PROJECT_RUNTIME",
    "runtimeStatus": "READY_FOR_DATABASE",
    "runtimeRoute": "/r/P005",
    "designRoute": "/ccus-screen-designs",
    "screenSpaceRoute": "/ccus-screen-space",
    "integrationStatus": "SEPARATED"
  }
];
