(function(){
function createAppearancePanel(){
 const v=document.getElementById('viewport3d'); if(!v||document.getElementById('appearancePanel')) return;
 let b=document.getElementById('appearanceToggle'); if(!b){ b=document.createElement('button'); b.id='appearanceToggle'; b.type='button'; b.textContent='\uacf5\uc7a5 \uafb8\ubbf8\uae30'; b.className='appearance-toggle'; v.appendChild(b); } else { b.classList.add('appearance-toggle-global'); }
 const p=document.createElement('aside'); p.id='appearancePanel'; p.className='appearance-panel'; p.hidden=true;
 p.innerHTML='<h3>\uacf5\uc7a5 \uafb8\ubbf8\uae30</h3><section><h4>\uc0c9\uc0c1 \\xb7 ﬂ¨\uc9c8</h4><label>\ub300\uc0c1</label><span id="appearanceTarget">\ud604\uc7ac › \ud0dd</span><label>\uc0c9\uc0c1</label><input id="appearanceColor" type="color" value="#78909c"><label>\uc7ac\uc9c8</label><select id="appearanceMaterial"><option>DEFAULT</option><option>CONCRETE</option><option>METAL</option><option>MATTE</option><option>GLOSSY</option><option>TRANSLUCENT</option></select><label>\ud22c\uba85\ub3c4</label><input id="appearanceOpacity" type="number" min="0" max="1" step=".05" value="1"><label>Roughness</label><input id="appearanceRoughness" type="number" min="0" max="1" step=".05" value=".8"><label>Metalness</label><input id="appearanceMetalness" type="number" min="0" max="1" step=".05" value="0"><button id="appearanceReset" type="button">\uae30\ubcf8\uac12 \ubcf5\uc6d0</button></section><section><h4>\ubc14\ub2e5</h4><label>\ubc14\ub2e5 \\\uc2dc</label><input id="appearanceFloorVisible" type="checkbox" checked><label>\ubc14\ub2e5 ‹…\uc0c1</label><input id="appearanceFloorColor" type="color" value="#78909c"><label>\ubc14\ub2e5 ﬂ¨\uc9c8</label><select id="appearanceFloorMaterial"><option>CONCRETE</option><option>DEFAULT</option><option>METAL</option></select><label>\ud22c\uba85\ub3c4</label><input id="appearanceFloorOpacity" type="number" min="0" max="1" step=".05" value="1"></section><section><h4>\uc870\uba85</h4><label>Preset</label><select id="appearancePreset"><option>DEFAULT</option><option>BRIGHT</option><option>DARK</option></select><label>Ambient</label><input id="appearanceAmbient" type="number" min="0" max="10" step=".1" value="2"><label>Directional</label><input id="appearanceDirectional" type="number" min="0" max="20" step=".1" value="3"><label>Direction X</label><input id="appearanceDX" type="number" value="20"><label>Direction Y</label><input id="appearanceDY" type="number" value="30"><label>Direction Z</label><input id="appearanceDZ" type="number" value="10"><label>Shadow</label><input id="appearanceShadow" type="checkbox"><button id="appearanceLightReset" type="button">\uae30\ubcf8\uac12 \ubcf5\uc6d0</button></section>';
 document.body.appendChild(p); b.onclick=()=>{p.hidden=!p.hidden;p.classList.toggle('open',!p.hidden);if(!p.hidden)syncAppearancePanel()};
}
function syncAppearancePanel(){const p=document.getElementById('appearancePanel');if(!p)return;const i=[...(window.selected||[])][0];const item=window.doc?.instances?.find(x=>x.id===i);const st=item?.style||{};const set=(id,val)=>{const e=document.getElementById(id);if(e&&val!=null)e.value=val};set('appearanceColor',st.color||'#78909c');set('appearanceMaterial',st.materialPreset||'DEFAULT');set('appearanceOpacity',st.opacity??1);set('appearanceRoughness',st.roughness??.8);set('appearanceMetalness',st.metalness??0);const l=window.sceneLighting?window.sceneLighting():{ambient:2,directional:3,direction:[20,30,10],shadow:false};set('appearanceAmbient',l.ambient);set('appearanceDirectional',l.directional);set('appearanceDX',l.direction[0]);set('appearanceDY',l.direction[1]);set('appearanceDZ',l.direction[2]);document.getElementById('appearanceShadow').checked=!!l.shadow}
function wireAppearancePanel(){const p=document.getElementById('appearancePanel');if(!p||p.dataset.wired)return;p.dataset.wired='1';const styleIds=['appearanceColor','appearanceMaterial','appearanceOpacity','appearanceRoughness','appearanceMetalness'];styleIds.forEach(id=>document.getElementById(id).addEventListener('change',()=>{const iid=[...(window.selected||[])][0];const item=window.doc?.instances?.find(x=>x.id===iid);if(item&&window.mutate){window.mutate(()=>{item.style={...(item.style||{}),color:document.getElementById('appearanceColor').value,materialPreset:document.getElementById('appearanceMaterial').value,opacity:Number(document.getElementById('appearanceOpacity').value),roughness:Number(document.getElementById('appearanceRoughness').value),metalness:Number(document.getElementById('appearanceMetalness').value)}});window.renderThreeScene?.()}}));document.getElementById('appearanceLightReset').onclick=()=>window.mutate?.(()=>{window.doc.sceneStyle={ambientIntensity:2,directionalIntensity:3,directionalDirection:[20,30,10],shadowEnabled:false,lightingPreset:'DEFAULT'};window.applySceneLighting?.()});document.getElementById('appearanceReset').onclick=()=>{const iid=[...(window.selected||[])][0],item=window.doc?.instances?.find(x=>x.id===iid);if(item)window.mutate?.(()=>{item.style={}});window.renderThreeScene?.()}}
function openAppearancePanel(){const p=document.getElementById('appearancePanel');if(p){p.hidden=false;p.classList.add('open');syncAppearancePanel()}}
function closeAppearancePanel(){const p=document.getElementById('appearancePanel');if(p){p.hidden=true;p.classList.remove('open')}}
function initAppearance(){createAppearancePanel();wireAppearancePanel();} if(document.readyState==='loading'){window.addEventListener('DOMContentLoaded',initAppearance,{once:true});}else{initAppearance();}
window.createAppearancePanel=createAppearancePanel;window.openAppearancePanel=openAppearancePanel;window.closeAppearancePanel=closeAppearancePanel;window.syncAppearancePanel=syncAppearancePanel;
})();
window.addEventListener('DOMContentLoaded',()=>{
 const q=id=>document.getElementById(id);
 const bridge=()=>window;
 const change=(id,fn)=>{const e=q(id);if(e)e.addEventListener('change',fn)};
 change('appearanceFloorVisible',e=>{if('drawing3dVisible' in window)window.drawing3dVisible=e.target.checked;window.renderThreeScene?.()});
 ['appearanceFloorColor','appearanceFloorMaterial','appearanceFloorOpacity'].forEach(id=>change(id,()=>{const f=window.doc?.instances?.find(x=>x.templateId==='floor');if(!f)return;window.mutate?.(()=>{f.style={...(f.style||{}),color:q('appearanceFloorColor').value,materialPreset:q('appearanceFloorMaterial').value,opacity:Number(q('appearanceFloorOpacity').value)} });window.renderThreeScene?.()}));
 ['appearancePreset','appearanceAmbient','appearanceDirectional','appearanceDX','appearanceDY','appearanceDZ','appearanceShadow'].forEach(id=>change(id,()=>{if(!window.doc)return;window.mutate?.(()=>{const d=window.doc.sceneStyle||{};window.doc.sceneStyle={...d,lightingPreset:q('appearancePreset').value,ambientIntensity:Number(q('appearanceAmbient').value),directionalIntensity:Number(q('appearanceDirectional').value),directionalDirection:[Number(q('appearanceDX').value),Number(q('appearanceDY').value),Number(q('appearanceDZ').value)],shadowEnabled:q('appearanceShadow').checked}});window.applySceneLighting?.();window.renderThreeScene?.()}));
});

function fixAppearanceKorean(){const p=document.getElementById('appearancePanel');if(!p)return;const hs=p.querySelectorAll('h4');if(hs[0])hs[0].textContent='\uC0C9\uC0C1 \u00B7 \uC7AC\uC9C8';const ls=p.querySelectorAll('label');const names=['\uB300\uC0C1','\uC0C9\uC0C1','\uC7AC\uC9C8','\uD22C\uBA85\uB3C4','Roughness','Metalness','\uBC14\uB2E5 \uD45C\uC2DC','\uBC14\uB2E5 \uC0C9\uC0C1','\uBC14\uB2E5 \uC7AC\uC9C8','\uD22C\uBA85\uB3C4','Preset','Ambient','Directional','Direction X','Direction Y','Direction Z','Shadow'];ls.forEach((e,i)=>{if(names[i])e.textContent=names[i]})}if(document.readyState==='loading'){window.addEventListener('DOMContentLoaded',()=>setTimeout(fixAppearanceKorean,0),{once:true})}else{setTimeout(fixAppearanceKorean,0)}

function forceAppearanceLabels(){const p=document.getElementById('appearancePanel');if(!p)return;const h=p.querySelectorAll('h4');if(h[0])h[0].textContent=String.fromCodePoint(0xC0C9,0xC0C1,0x20B7,0xC7AC,0xC9C8);const a=p.querySelectorAll('label'),n=['\uB300\uC0C1','\uC0C9\uC0C1','\uC7AC\uC9C8','\uD22C\uBA85\uB3C4','Roughness','Metalness','\uBC14\uB2E5 \uD45C\uC2DC','\uBC14\uB2E5 \uC0C9\uC0C1','\uBC14\uB2E5 \uC7AC\uC9C8','\uD22C\uBA85\uB3C4','Preset','Ambient','Directional','Direction X','Direction Y','Direction Z','Shadow'];a.forEach((e,i)=>{if(n[i])e.textContent=n[i]})}setTimeout(forceAppearanceLabels,50);
