'use strict';
(()=>{
 const samples=[];window.CPerf={samples,record:(phase,ms,detail)=>{samples.push({phase,ms,detail});if(samples.length>4000)samples.splice(0,1000)}};
 const record=window.CPerf.record,oldCanvas=renderCanvas,oldInspector=renderInspector,oldCheckpoint=checkpoint,legacy=new URLSearchParams(location.search).get('renderer')==='legacy';
 checkpoint=function(){const t=performance.now();oldCheckpoint();record('stateUpdate',performance.now()-t)};
 const nodes=new Map(),lines=new Map();let previousSelection=new Set(),inspectorKey='',raf=0;
 function imageNode(el,a){el.innerHTML=image(a)+'<span class="objectname"></span><button class="remove" aria-label="삭제">×</button>';const img=el.querySelector('img');if(img){img.loading='lazy';img.decoding='async'}el.querySelector('.remove').dataset.remove=el.dataset.id}
 renderCanvas=function(){if(legacy){oldCanvas();return}const begin=performance.now(),v=$('#viewport'),container=$('#objects'),world=$('#world'),z=zoom(),margin=180;let tick=performance.now();
  const index=new Map(doc.instances.map(i=>[i.id,i])),layout=[];const bounds=[v.scrollLeft-margin,v.scrollTop-margin,v.scrollLeft+v.clientWidth+margin,v.scrollTop+v.clientHeight+margin];
  for(const i of doc.instances){const d=dims(i),w=Math.max(24,d[0]*i.scale[0]*z),h=Math.max(24,d[2]*i.scale[2]*z),r=i.rotation[1]*Math.PI/180,ex=(Math.abs(Math.cos(r))*w+Math.abs(Math.sin(r))*h)/2,ez=(Math.abs(Math.sin(r))*w+Math.abs(Math.cos(r))*h)/2,x=px(i.position[0]),y=pz(i.position[2]);if(selected.has(i.id)||(x+ex>=bounds[0]&&x-ex<=bounds[2]&&y+ez>=bounds[1]&&y-ez<=bounds[3]))layout.push({i,w,h,x,y})}
  record('layoutCalculation',performance.now()-tick);tick=performance.now();const visible=new Set(layout.map(o=>o.i.id));for(const [id,n]of nodes)if(!visible.has(id)){n.el.remove();nodes.delete(id)}
  const fragment=document.createDocumentFragment();let newImages=0,updated=0;
  for(const {i,w,h,x,y}of layout){let n=nodes.get(i.id),a=assetMap.get(i.assetId),t=templates.get(i.templateId);if(!n){const el=document.createElement('div');el.dataset.id=i.id;el.tabIndex=0;el.className='object '+(t?'param '+t.id:'');imageNode(el,t?null:a);if(t){el.querySelector('.missing')?.remove();el.style.backgroundColor=t.color}fragment.append(el);n={el,key:''};nodes.set(i.id,n);newImages+=t?0:1}
   const key=JSON.stringify([x,y,w,h,i.rotation[1],i.label,i.assetId,i.templateId]);if(n.key!==key){updated++;Object.assign(n.el.style,{left:x-w/2+'px',top:y-h/2+'px',width:w+'px',height:h+'px',transform:`rotate(${i.rotation[1]}deg)`});n.el.querySelector('.objectname').textContent=i.label;n.el.setAttribute('aria-label','배치 '+i.label);n.el.title=`${i.label} · ${i.assetId||i.templateId} · ${i.position.join(' / ')}m`;n.key=key}
  }container.append(fragment);record('domRender',performance.now()-tick,{visible:visible.size,total:doc.instances.length,updated,newImages});tick=performance.now();
  for(const id of new Set([...selected,...previousSelection]))nodes.get(id)?.el.classList.toggle('selected',selected.has(id));previousSelection=new Set(selected);record('selectionOverlay',performance.now()-tick);tick=performance.now();
  const edgeIds=new Set();for(const e of doc.relationships){const a=index.get(e.from),b=index.get(e.to);if(!a||!b)continue;const x1=px(a.position[0]),y1=pz(a.position[2]),x2=px(b.position[0]),y2=pz(b.position[2]);if(Math.max(x1,x2)<bounds[0]||Math.min(x1,x2)>bounds[2]||Math.max(y1,y2)<bounds[1]||Math.min(y1,y2)>bounds[3])continue;edgeIds.add(e.id);let l=lines.get(e.id);if(!l){l=document.createElementNS('http://www.w3.org/2000/svg','line');l.setAttribute('stroke','#007b87');l.setAttribute('stroke-width','2');l.setAttribute('stroke-dasharray','5 3');l.setAttribute('marker-end','url(#arrow)');$('#edges').append(l);lines.set(e.id,l)}const key=[x1,y1,x2,y2,e.type].join('|');if(l.dataset.key!==key){for(const [k,val]of Object.entries({x1,y1,x2,y2}))l.setAttribute(k,val);l.dataset.key=key}}
  for(const [id,l]of lines)if(!edgeIds.has(id)){l.remove();lines.delete(id)}record('relationshipRedraw',performance.now()-tick);let grid=doc.settings.grid*z;while(grid<12)grid*=2;world.style.backgroundSize=`${grid}px ${grid}px`;world.classList.toggle('quiet-labels',$('#toggleLabels')?.getAttribute('aria-pressed')!=='true');$('#empty').hidden=!!doc.instances.length;$('#canvasCount').textContent=`${doc.instances.length}개 객체 · ${visible.size}개 표시 · ${doc.relationships.length}개 관계 · 선택 ${selected.size}`;record('renderTotal',performance.now()-begin);
 };
 renderInspector=function(){const start=performance.now(),key=JSON.stringify([doc.id,doc.version,[...selected],doc.instances.filter(i=>selected.has(i.id)),doc.instances.map(i=>[i.id,i.label]),doc.relationships]);if(key!==inspectorKey){oldInspector();inspectorKey=key}record('propertyPanel',performance.now()-start)};
 window.perfPaintDrag=()=>{if(!legacy){renderCanvas();return true}return false};
 $('#viewport').addEventListener('scroll',()=>{if(!raf)raf=requestAnimationFrame(()=>{raf=0;renderCanvas()})},{passive:true});new ResizeObserver(()=>{if(window.composerReady)renderCanvas()}).observe($('#viewport'));
 // Existing SVG marker is presentation only, not a physical connection.
 $('#edges').innerHTML='<defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8Z" fill="#007b87"/></marker></defs>';
 try{new PerformanceObserver(list=>{for(const e of list.getEntries())if(e.initiatorType==='img')record('thumbnailLoad',e.duration,{url:e.name,transferSize:e.transferSize,async:true})}).observe({type:'resource',buffered:true})}catch{}
 window.composerPerformanceMode=legacy?'LEGACY':'INCREMENTAL_VIRTUALIZED';
})();
