(() => {
  'use strict';
  const C=window.ProductPlannerCore,$=s=>document.querySelector(s),STORE='p006-product-plans-v1';
  const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const labels={MAKE:'内部 제작',BUY:'구매',OUTSOURCE:'외주',STOCK:'재고 사용',UNDECIDED:'미정',PROCESS:'가공·처리',ASSEMBLE:'조립·결합',INSPECT:'검사',DISPATCH:'출고'};labels.MAKE='내부 제작';
  let saved={plans:[],activeId:null},plan=C.empty(),runtime=null,products=[],layouts=[],timer=null,last=0,tab='product',preparingWholeRun=false,runChannel=null,lastRunPublish=0,lastRunPublishState='';
  try{saved=JSON.parse(localStorage.getItem(STORE)||'null')||saved;plan=saved.plans.find(p=>p.id===saved.activeId)||plan;}catch{saved={plans:[],activeId:null};}
  try{const r=JSON.parse(localStorage.getItem(STORE+':run:'+plan.id)||'null');if(r&&r.planRevision===plan.revision){runtime=r;if(runtime.state==='RUNNING')runtime.state='PAUSED';}}catch{}
  function notice(text,error=false){$('#appNotice').textContent=text;$('#appNotice').classList.toggle('error',error);}
  function saveLocal(){plan.updatedAt=new Date().toISOString();saved.plans=saved.plans.filter(p=>p.id!==plan.id);saved.plans.push(C.copy(plan));saved.activeId=plan.id;localStorage.setItem(STORE,JSON.stringify(saved));if(runtime)localStorage.setItem(STORE+':run:'+plan.id,JSON.stringify(runtime));$('#saveStatus').textContent='이 브라우저 저장 · '+new Date().toLocaleTimeString('ko-KR');renderSaved();}
  function stop(){if(timer)cancelAnimationFrame(timer);timer=null;}
  function visualSlot(name=''){const v=String(name).toLowerCase();if(/차체|프레임|body|panel/.test(v))return'frame';if(/구동|모터|감속|drive|motor/.test(v))return'drive';if(/배터리|battery/.test(v))return'battery';if(/섀시|샤시|서스펜션|조향|제동|chassis|suspension/.test(v))return'chassis';return null;}
  function publishRunState(force=false){if(!runChannel)return;const state=runtime?.state||'READY',now=performance.now();if(!force&&state==='RUNNING'&&state===lastRunPublishState&&now-lastRunPublish<100)return;lastRunPublish=now;lastRunPublishState=state;const compiled=runtime?.schedule||C.compile(plan),partById=new Map(plan.parts.map(p=>[p.id,p])),factoryById=new Map(plan.factories.map(f=>[f.id,f])),siteById=new Map(plan.sites.map(s=>[s.id,s]));const tasks=compiled.ok?compiled.tasks.map(t=>{const process=plan.processes.find(p=>p.id===t.processId),partIds=[t.partId,...(t.consume||[]).map(x=>x.partId),...(t.produce||[]).map(x=>x.partId)].filter(Boolean),parts=[...new Set(partIds)].map(id=>partById.get(id)).filter(Boolean),factory=factoryById.get(t.factoryId),site=siteById.get(factory?.siteId),model=process?.equipmentModel||{};return{id:t.id,name:t.name,kind:t.type,processId:t.processId||null,partId:t.partId||null,partName:partById.get(t.partId)?.name||'',partIds:[...new Set(partIds)],partNames:parts.map(p=>p.name),components:parts.map(p=>({id:p.id,name:p.name,quantity:p.quantity,slot:visualSlot(p.name)})),componentSlots:[...new Set(parts.map(p=>visualSlot(p.name)).filter(Boolean))],assetId:model.assetId||'',assetName:model.assetName||'',assetGlbPath:model.glbPath||'',factoryId:t.factoryId||'',factoryName:factory?.name||'',siteName:site?.name||'',start:t.start,end:t.end,dependsOn:[...(t.deps||[])],consume:(t.consume||[]).map(x=>({partId:x.partId,quantity:x.quantity})),produce:(t.produce||[]).map(x=>({partId:x.partId,quantity:x.quantity}))};}):[];const activeTaskIds=state==='RUNNING'?tasks.filter(t=>runtime.time>=t.start&&runtime.time<t.end).map(t=>t.id):[];runChannel.postMessage({schema:'P006_PRODUCT_PLAN_SYNC_V1',type:'snapshot',sentAt:Date.now(),planId:plan.id,planRevision:plan.revision,planUpdatedAt:plan.updatedAt||'',productName:plan.productName||'제품 생산 계획',state,time:runtime?.time||0,totalMinutes:compiled.ok?compiled.totalMinutes:0,speed:Number(plan.speed)||60,activeTaskIds,tasks});}
  function changed(){stop();runtime=null;plan.revision=(plan.revision||0)+1;localStorage.removeItem(STORE+':run:'+plan.id);saveLocal();render();}
  const select=(value,options,attrs='')=>`<select ${attrs}>${options.map(([id,name])=>`<option value="${esc(id)}" ${String(value??'')===String(id)?'selected':''}>${esc(name)}</option>`).join('')}</select>`;
  const opts=(rows,blank='선택')=>[['',blank],...rows.map(x=>[x.id,x.name])];
  const field=(type,row,key)=>`data-group="${type}" data-id="${esc(row.id)}" data-key="${key}" aria-label="${esc(row.name||row.id)} ${key}"`;
  const input=(type,row,key,numeric=false)=>`<input ${field(type,row,key)} type="${numeric?'number':'text'}" ${numeric?'min="0" step="any"':''} value="${esc(row[key]??'')}">`;
  const remove=(group,id)=>`<button type="button" class="icon-button" data-remove="${group}" data-id="${esc(id)}" aria-label="행 삭제">삭제</button>`;
  function renderSaved(){const value=plan.id;$('#savedPlans').innerHTML=opts([...saved.plans.map(p=>({id:p.id,name:p.productName||'이름 없는 계획'})),...layouts.filter(x=>x.name?.startsWith('제품 생산 계획 · ')).map(x=>({id:'server:'+x.id,name:'서버 · '+x.name+' v'+x.version}))],'저장 계획 선택').map(([id,n])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(n)}</option>`).join('');}
  function render(){
    $('#productName').value=plan.productName;$('#quantity').value=plan.quantity;$('#productSource').value=plan.productSource||'';$('#animationEnabled').checked=plan.animationEnabled!==false;$('#speed').value=String(plan.speed||60);
    $('#partsBody').innerHTML=plan.parts.map(p=>`<tr><td>${input('parts',p,'name')}</td><td>${input('parts',p,'quantity',true)}<small>총 ${p.quantity*plan.quantity}개</small></td><td>${select(p.procurement,Object.entries(labels).filter(([k])=>['MAKE','BUY','OUTSOURCE','STOCK','UNDECIDED'].includes(k)),field('parts',p,'procurement'))}</td><td>${select(p.factoryId,opts(plan.factories),field('parts',p,'factoryId'))}</td><td>${input('parts',p,'leadMinutes',true)}<small>구매·외주·재고 배치</small></td><td>${select(p.joinProcessId,opts(plan.processes.filter(x=>x.kind==='ASSEMBLE')),field('parts',p,'joinProcessId'))}</td><td>${remove('parts',p.id)}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">주요 부품을 추가하세요. 나사·와셔 등 소모품은 필요한 경우에만 포함합니다.</td></tr>';
    $('#sitesBody').innerHTML=plan.sites.map(s=>`<tr><td>${select(s.mode,[['REAL','실제'],['VIRTUAL','가상']],field('sites',s,'mode'))}</td><td>${input('sites',s,'name')}</td><td>${remove('sites',s.id)}</td></tr>`).join('');
    $('#factoriesBody').innerHTML=plan.factories.map(f=>`<tr><td>${select(f.mode,[['REAL','실제'],['VIRTUAL','가상']],field('factories',f,'mode'))}</td><td>${input('factories',f,'name')}</td><td>${select(f.siteId,opts(plan.sites),field('factories',f,'siteId'))}</td><td>${select(f.layoutId,[['','연결 없음'],...layouts.filter(x=>x.count>0).map(x=>[x.id,x.name]),...(f.layoutId&&!layouts.some(x=>x.id===f.layoutId)?[[f.layoutId,'참조 '+f.layoutId]]:[])],field('factories',f,'layoutId'))}</td><td>${remove('factories',f.id)}</td></tr>`).join('');
    $('#processesBody').innerHTML=plan.processes.map((p,i)=>`<tr><td><small>${i+1}</small>${input('processes',p,'name')}<div><button type="button" data-move="${i}" data-delta="-1" ${i===0?'disabled':''}>↑</button><button type="button" data-move="${i}" data-delta="1" ${i===plan.processes.length-1?'disabled':''}>↓</button></div></td><td>${select(p.kind,['MAKE','PROCESS','ASSEMBLE','INSPECT','DISPATCH'].map(k=>[k,labels[k]]),field('processes',p,'kind'))}</td><td>${select(p.partId,opts(plan.parts,'완제품'),field('processes',p,'partId'))}</td><td>${select(p.factoryId,opts(plan.factories),field('processes',p,'factoryId'))}</td><td><select multiple size="3" ${field('processes',p,'dependsOn')}>${plan.processes.filter(x=>x.id!==p.id).map(x=>`<option value="${esc(x.id)}" ${(p.dependsOn||[]).includes(x.id)?'selected':''}>${esc(x.name)}</option>`).join('')}</select><small>Ctrl/Cmd로 복수 선택</small></td><td>${input('processes',p,'durationMinutes',true)}${select(p.timeBasis,[['BATCH','배치 전체'],['UNIT','개당']],field('processes',p,'timeBasis'))}</td><td>${remove('processes',p.id)}</td></tr>`).join('');
    $('#routesBody').innerHTML=plan.routes.map(r=>`<tr><td>${select(r.partId,opts(plan.parts),field('routes',r,'partId'))}</td><td>${select(r.fromFactoryId,opts(plan.factories),field('routes',r,'fromFactoryId'))}</td><td>${select(r.toFactoryId,opts(plan.factories),field('routes',r,'toFactoryId'))}</td><td>${input('routes',r,'distanceKm',true)}</td><td>${input('routes',r,'travelMinutes',true)}</td><td>${input('routes',r,'handlingMinutes',true)}</td><td>${remove('routes',r.id)}</td></tr>`).join('');
    const schedule=C.compile(plan);$('#validationList').innerHTML=schedule.ok?`<p class="success">시간·수량 계획 실행 준비 · 공정 및 조달 ${schedule.tasks.length}단계 · 예상 ${schedule.totalMinutes.toFixed(1)}분</p><p class="hint">입력 시간 기준의 계획값입니다. 설비 용량·작업자·공유 설비 경합·물리적 이송은 별도 검증 대상입니다.</p>`:`<ul>${schedule.errors.map(e=>`<li>${esc(e)}</li>`).join('')}</ul>`;
    $('#productOverview').innerHTML=`<div class="overview-title"><h2>${esc(plan.productName||'어떤 제품을 만들까요?')}</h2><span class="badge">${plan.evidence==='FUNCTIONAL_DEMO'?'가상 계획 예시':'사용자 생산 계획'}</span></div><p>완제품 ${plan.quantity}개 · 주요 부품 ${plan.parts.length}종 · 필요 부품 ${plan.parts.reduce((a,p)=>a+p.quantity*plan.quantity,0)}개</p><div class="part-journeys">${plan.parts.map(p=>{const chain=plan.processes.filter(x=>x.partId===p.id).map(x=>x.name);return `<article><b>${esc(p.name)} · ${p.quantity*plan.quantity}개</b><p>${esc(labels[p.procurement]||'조달 미정')} ${chain.length?'→ '+chain.map(esc).join(' → '):''} → <strong>${esc(plan.processes.find(x=>x.id===p.joinProcessId)?.name||'결합 공정 미지정')}</strong></p><small>${esc(plan.factories.find(f=>f.id===p.factoryId)?.name||'담당 공장 미정')}</small></article>`;}).join('')||'<p class="empty">제품을 선택하거나 새로 이름과 주요 부품을 등록하세요.</p>'}</div>`;
    $('#flowOverview').innerHTML=plan.processes.map(p=>`<span class="flow-chip">${esc(p.name)} · ${p.durationMinutes}분/${p.timeBasis==='UNIT'?'개':'배치'}</span>`).join(' ');
    window.ProductPlannerDetails?.render(plan,schedule);renderRun();showTab(tab);renderSaved();
  }
  function showTab(t){tab=t;document.querySelectorAll('[data-panel]').forEach(e=>e.hidden=e.dataset.panel!==t);document.querySelectorAll('[data-tab]').forEach(e=>{e.classList.toggle('is-active',e.dataset.tab===t);if(e.dataset.tab===t)e.setAttribute('aria-current','step');else e.removeAttribute('aria-current');});}
  window.ProductPlannerPlayback={snapshot:()=>({time:runtime?.time||0,state:runtime?.state||"READY",planId:plan.id}),getPlan:()=>C.copy(plan)};
  let lastRunPaint=0,lastPaintState="";
  function renderRun(){publishRunState();const paintNow=performance.now();if(runtime?.state==="RUNNING"&&lastPaintState==="RUNNING"&&paintNow-lastRunPaint<100)return;lastRunPaint=paintNow;lastPaintState=runtime?.state;const s=runtime?.schedule||C.compile(plan),time=runtime?.time||0;$('#runStart').disabled=!s.ok||runtime?.state==='RUNNING';$('#runPause').disabled=runtime?.state!=='RUNNING';if($('#runStep'))$('#runStep').disabled=!s.ok||runtime?.state==='RUNNING';if($('#runAllAnimation')){$('#runAllAnimation').disabled=!s.ok||runtime?.state==='RUNNING'||preparingWholeRun;const label=runtime?.state==='PAUSED'?'▶ 이어서 재생':runtime?.state==='COMPLETE'?'↻ 처음부터 다시 재생':'▶ 전체 공정 애니메이션 재생';$('#runAllAnimation').textContent=label;$('#runAllAnimation').setAttribute('aria-label',label);}
    const status={READY:'대기',RUNNING:'진행 중',PAUSED:'일시정지',COMPLETE:'완료'}[runtime?.state]||'실행 전';
    $('#runMetrics').innerHTML=`<div><small>상태</small><b>${status}</b></div><div><small>계획 시간</small><b>${time.toFixed(1)} / ${s.ok?s.totalMinutes.toFixed(1):'—'}분</b></div><div><small>완제품 출고</small><b>${runtime?.finished||0} / ${plan.quantity}개</b></div><div><small>운송 중 부품</small><b>${Object.values(runtime?.inTransit||{}).reduce((a,b)=>a+b,0)}개</b></div>`;
    const completed=new Set(runtime?.processed||[]);$('#eventLog').innerHTML=(runtime?.events||[]).slice(-100).map(e=>`<li><time>${e.time.toFixed(1)}분</time> ${esc(e.name)} · ${e.phase==='start'?'시작':'완료'}</li>`).join('')||'<li>재생하면 부품 확보·운송·결합·검사·출고 기록이 표시됩니다.</li>';
    window.ProductPlannerDetails?.update(runtime,plan);
    const svg=$('#runScene');svg.style.display=plan.animationEnabled===false?'none':'block';
    if(plan.animationEnabled===false)return;
    const tasks=s.ok?s.tasks:[],width=1000,cols=4,rows=Math.max(1,Math.ceil(tasks.length/cols)),height=rows*145+60;svg.setAttribute('viewBox',`0 0 ${width} ${height}`);svg.setAttribute('aria-label','공정 흐름 애니메이션 · 입력 시간 기반');
    const positions=new Map(tasks.map((t,i)=>[t.id,{x:25+(i%cols)*245,y:25+Math.floor(i/cols)*145}]));
    const edges=tasks.flatMap(t=>t.deps.map(d=>{const a=positions.get(d),b=positions.get(t.id);if(!a||!b)return '';const active=completed.has(d+':end')&&!completed.has(t.id+':end');return `<path d="M${a.x+210} ${a.y+48} C${a.x+235} ${a.y+48} ${b.x-20} ${b.y+48} ${b.x} ${b.y+48}" fill="none" stroke="${active?'#0798a3':'#b8cbd3'}" stroke-width="2" marker-end="url(#arrow)"/>`;})).join('');
    const cards=tasks.map(t=>{const p=positions.get(t.id),done=completed.has(t.id+':end'),active=completed.has(t.id+':start')&&!done,progress=done?1:active?(t.duration?Math.min(1,Math.max(0,(time-t.start)/t.duration)):1):0;return `<g transform="translate(${p.x},${p.y})"><rect width="210" height="112" rx="12" fill="${done?'#e6f5ee':active?'#e4f6f8':'#fff'}" stroke="${active?'#007d89':'#c7d9e0'}"/><text x="12" y="25" fill="#173e54" font-size="13">${esc(t.name.slice(0,19))}</text><text x="12" y="47" fill="#55717d" font-size="11">${esc(plan.factories.find(f=>f.id===t.factoryId)?.name?.slice(0,23)||'공장 미지정')}</text><rect x="12" y="62" width="186" height="6" rx="3" fill="#dbe8ed"/><rect x="12" y="62" width="${186*progress}" height="6" rx="3" fill="#00818d"/><text x="12" y="94" fill="#355b65" font-size="11">${done?'완료':active?'진행 중':'선행 작업 대기'} · ${t.duration.toFixed(1)}분</text>${active?`<circle cx="${14+180*progress}" cy="62" r="6" fill="#ed9d30"/>`:''}</g>`;}).join('');
    svg.innerHTML=`<defs><marker id="arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6" fill="#93b4be"/></marker></defs>${edges}${cards}${!tasks.length?'<text x="30" y="60" fill="#59717e" font-size="18">공정 조건을 입력하면 흐름도가 표시됩니다.</text>':''}`;
  }
  function run(){try{if(!runtime||runtime.state==='COMPLETE')runtime=C.createRuntime(plan);runtime=C.advance(runtime,runtime.time);last=performance.now();stop();if(runtime.state==='COMPLETE'){renderRun();saveLocal();return;}runtime.state='RUNNING';const tick=now=>{try{const dt=Math.max(0,(now-last)/1000);last=now;runtime=C.advance(runtime,runtime.time+dt*(Number(plan.speed)||1)/60);renderRun();if(runtime.state==='COMPLETE'){timer=null;saveLocal();notice('계획 실행 완료 · 완제품 '+runtime.finished+'개 출고');}else timer=requestAnimationFrame(tick);}catch(e){stop();if(runtime)runtime.state='PAUSED';notice(e.message,true);renderRun();}};timer=requestAnimationFrame(tick);showTab('run');renderRun();notice('입력 시간에 따른 공정 계획을 실행합니다.');}catch(e){notice(e.message,true);}}
  async function runWholeAnimation(){const schedule=C.compile(plan);if(!schedule.ok){notice('먼저 공정 입력 오류를 수정하세요.',true);return;}if(runtime?.state==='RUNNING')return;const resumeAt=runtime?.state==='PAUSED'?runtime.time:0;preparingWholeRun=true;renderRun();showTab('run');try{if(plan.animationEnabled===false){plan.animationEnabled=true;$('#animationEnabled').checked=true;}const sceneHost=$('#productionSceneDirectHost');sceneHost?.scrollIntoView({behavior:'smooth',block:'center'});if(!sceneHost)throw Error('페이지 내 생산 현장 3D 영역을 찾지 못했습니다.');if(!window.ProductPlannerProductionScene)throw Error('페이지 내 3D 렌더러가 아직 준비 중입니다. 잠시 후 다시 시도하세요.');window.ProductPlannerProductionScene.setPlan(plan);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));stop();if(!runtime||runtime.state==='COMPLETE')runtime=C.createRuntime(plan);runtime=C.advance(runtime,runtime.time);renderRun();run();notice(`${resumeAt>0?resumeAt.toFixed(1)+'분부터 이어 ':''}통합 실행 시작 · 페이지 내 생산 현장 3D와 같은 시간표 · ${schedule.totalMinutes.toFixed(1)}분 계획`);window.ProductPlannerMultiView?.capture();}catch(e){notice('통합 실행 준비 실패: '+e.message,true);}finally{preparingWholeRun=false;renderRun();}}
  async function api(path,payload){const r=await fetch('/projects/P006/registry-api/composer'+path,{credentials:'same-origin',cache:'no-store',method:payload?'POST':'GET',headers:payload?{'Content-Type':'application/json','X-P006-Requested-With':'equipment-registry'}:{},body:payload?JSON.stringify(payload):undefined});if(!r.ok)throw Error('서버 요청 실패 (HTTP '+r.status+')');return r.json();}
  async function catalogs(){const results=await Promise.allSettled([api('/products'),api('/layouts')]);if(results[0].status==='fulfilled')products=results[0].value.items||[];if(results[1].status==='fulfilled')layouts=results[1].value.items||[];
    $('#productSelect').innerHTML='<option value="">제품 선택</option><option value="new">+ 새 제품 계획</option><option value="car">자동차 주요 모듈 · 전기차 가상 계획</option><option value="example">가상 예시 · 하우징·구동 모듈 조립품</option>'+products.map(p=>`<option value="api:${esc(p.id)}">${esc(p.name)} · 저장 제품 v${p.version}</option>`).join('');
    if(results.some(r=>r.status==='rejected'))notice('새 계획과 가상 예시를 사용할 수 있습니다. 서버 목록 일부를 가져오지 못했습니다. 브라우저 저장·JSON 내보내기는 사용할 수 있습니다.');render();}
  document.addEventListener('change',e=>{try{const el=e.target;if(el.dataset.group){if(runtime?.state==='RUNNING'){notice('일시정지 후 계획을 수정하세요.');render();return;}const row=plan[el.dataset.group].find(x=>x.id===el.dataset.id);if(!row)return;const key=el.dataset.key;row[key]=el.multiple?[...el.selectedOptions].map(o=>o.value):el.type==='number'?Number(el.value):el.value;if(key==='layoutId')row.layoutVersion=layouts.find(l=>l.id===el.value)?.version||null;changed();return;}
    if(['productName','quantity','productSource'].includes(el.id)){if(runtime?.state==='RUNNING'){notice('일시정지 후 계획을 수정하세요.');render();return;}plan[el.id]=el.type==='number'?Number(el.value):el.value;changed();}
    if(el.id==='animationEnabled'){plan.animationEnabled=el.checked;saveLocal();renderRun();}
    if(el.id==='speed'){plan.speed=Number(el.value);saveLocal();}
    if(el.id==='productSelect'&&el.value){stop();saveLocal();if(el.value==='car')plan=C.carExample();else if(el.value==='example')plan=C.example();else{plan=C.empty();const p=products.find(p=>'api:'+p.id===el.value);if(p){plan.productId=p.id;plan.productVersion=p.version;plan.productName=p.name;plan.productSource=p.sourceReference||'';plan.parts=(p.bom||[]).map(b=>({id:b.partId,name:b.name||b.partId,quantity:b.quantity,procurement:'UNDECIDED',factoryId:'',leadMinutes:0,joinProcessId:''}));}}runtime=null;saveLocal();render();notice(plan.evidence==='FUNCTIONAL_DEMO'?'가상 예시를 불러왔습니다. 모든 시간·거리·부품은 수정 가능한 예시값입니다.':'제품의 주요 부품과 조달 방식을 입력하세요.');}
  }catch(err){notice(err.message,true);}});
  document.addEventListener('click',e=>{try{const t=e.target.closest('button');if(!t)return;if(t.dataset.tab){showTab(t.dataset.tab);return;}if(t.dataset.remove){if(runtime?.state==='RUNNING')throw Error('일시정지 후 수정하세요.');plan[t.dataset.remove]=plan[t.dataset.remove].filter(x=>x.id!==t.dataset.id);changed();return;}if(t.dataset.move!==undefined){if(runtime?.state==='RUNNING')throw Error('일시정지 후 수정하세요.');const i=Number(t.dataset.move),j=i+Number(t.dataset.delta);if(j>=0&&j<plan.processes.length)[plan.processes[i],plan.processes[j]]=[plan.processes[j],plan.processes[i]];changed();return;}
    if(t.id.startsWith('add')&&runtime?.state==='RUNNING')throw Error('일시정지 후 수정하세요.');
    const f=plan.factories[0]?.id||'';
    if(t.id==='addPart'){plan.parts.push({id:C.uuid(),name:'새 주요 부품',quantity:1,procurement:'UNDECIDED',factoryId:f,leadMinutes:0,joinProcessId:''});changed();}
    if(t.id==='addSite'){plan.sites.push({id:C.uuid(),name:'새 부지',mode:'VIRTUAL'});changed();}
    if(t.id==='addFactory'){plan.factories.push({id:C.uuid(),name:'새 공장',mode:'VIRTUAL',siteId:plan.sites[0]?.id||'',layoutId:''});changed();}
    if(t.id==='addProcess'){plan.processes.push({id:C.uuid(),name:'새 공정',kind:'PROCESS',partId:'',factoryId:f,dependsOn:[],durationMinutes:1,timeBasis:'BATCH'});changed();}
    if(t.id==='addRoute'){plan.routes.push({id:C.uuid(),partId:plan.parts[0]?.id||'',fromFactoryId:f,toFactoryId:plan.factories[1]?.id||'',distanceKm:0,travelMinutes:0,handlingMinutes:0});changed();}
  }catch(err){notice(err.message,true);}});
  $('#savePlan').onclick=()=>{try{saveLocal();notice('생산 계획과 현재 실행 상태를 이 브라우저에 저장했습니다.');}catch(e){notice(e.message,true);}};
  $('#loadPlan').onclick=async()=>{try{const id=$('#savedPlans').value;let p;if(id.startsWith('server:')){const doc=await api('/layouts/'+encodeURIComponent(id.slice(7)));p=doc.settings?.productProductionPlan;if(!p||p.schema!=='P006_PRODUCT_PLAN_V1')throw Error('이 저장 항목은 제품 생산 계획 형식이 아닙니다.');p=C.copy(p);p.serverDocument={id:doc.id,version:doc.version};}else p=saved.plans.find(p=>p.id===id);if(!p)return;stop();plan=C.copy(p);runtime=null;try{const r=JSON.parse(localStorage.getItem(STORE+':run:'+plan.id)||'null');if(r?.planRevision===plan.revision){runtime=r;if(r.state==='RUNNING')runtime.state='PAUSED';}}catch{}saved.activeId=plan.id;saveLocal();render();notice('저장 계획을 복원했습니다.');}catch(e){notice('계획 불러오기 실패: '+e.message,true);}};
  $('#runAllAnimation').onclick=runWholeAnimation;$('#runStart').onclick=run;$('#runPause').onclick=()=>{stop();if(runtime)runtime.state='PAUSED';saveLocal();renderRun();};$('#runReset').onclick=()=>{stop();runtime=null;localStorage.removeItem(STORE+':run:'+plan.id);renderRun();notice('실행 상태와 재고를 초기화했습니다. 설계 입력은 유지됩니다.');};
  if($('#runStep'))$('#runStep').onclick=()=>{try{if(!runtime||runtime.state==='COMPLETE')runtime=C.createRuntime(plan);const next=runtime.schedule.tasks.flatMap(t=>[t.start,t.end]).filter(t=>t>runtime.time).sort((a,b)=>a-b)[0]??runtime.time;runtime=C.advance(runtime,next);if(runtime.state!=='COMPLETE')runtime.state='PAUSED';saveLocal();renderRun();}catch(e){notice(e.message,true);}};
  $('#exportPlan').onclick=()=>{const blob=new Blob([JSON.stringify({schema:'P006_PRODUCT_PLAN_BUNDLE_V1',plan,runtime},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='product-plan-'+plan.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  $('#importPlan').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>5000000)throw Error('JSON 파일은 5MB 이하로 선택하세요.');const data=JSON.parse(await file.text()),p=data.plan||data;if(p.schema!=='P006_PRODUCT_PLAN_V1'||!['parts','sites','factories','processes','routes'].every(k=>Array.isArray(p[k])))throw Error('생산 계획 JSON 형식이 아닙니다.');if(!Number.isFinite(p.quantity)||typeof p.productName!=='string'||[...p.parts,...p.sites,...p.factories,...p.processes,...p.routes].some(x=>!x||typeof x.id!=='string'))throw Error('생산 계획 항목 형식이 올바르지 않습니다.');C.compile(p);stop();saveLocal();plan=C.copy(p);plan.id=C.uuid();delete plan.serverDocument;runtime=null;saveLocal();render();notice('JSON을 새 계획으로 가져왔습니다. 실행 전 입력 조건을 확인하세요.');}catch(err){notice(err.message,true);}finally{e.target.value='';}};
  $('#saveServer').onclick=async()=>{try{saveLocal();const old=plan.serverDocument;const clean=C.copy(plan);delete clean.serverDocument;const doc={id:old?.id||C.uuid(),name:'제품 생산 계획 · '+plan.productName,version:old?.version||0,settings:{unit:'m',coordinateSystem:'RIGHT_HANDED_Y_UP',grid:.5,snap:true,rotationSnap:15,zoom:20,productProductionPlan:clean},instances:[],relationships:[]};const result=await api('/layouts',doc);plan.serverDocument={id:result.id,version:result.version};saveLocal();notice('서버에 제품 생산 계획 v'+result.version+' 저장 완료');}catch(e){notice('서버 저장을 완료하지 못했습니다. 브라우저 저장본과 JSON을 사용할 수 있습니다.',true);}};
  function readModelFields(){document.querySelectorAll('[data-model-key]').forEach(x=>{const scope=x.dataset.modelScope,id=x.dataset.modelId,key=x.dataset.modelKey,value=x.value.trim();const row=scope==='product'?plan:plan[scope]?.find(r=>r.id===id);if(!row)return;if(key==='timeSource')row.timeSource=value;else{const k=scope==='product'?'productModel':scope==='processes'?'equipmentModel':'model';row[k]||={};row[k][key]=value;}});}
  $('#applyModels').onclick=()=>{if(runtime?.state==='RUNNING'){notice('일시정지 후 모델·시간 근거를 적용하세요.');return;}readModelFields();changed();notice('모델 연결과 시간 근거를 저장했습니다. 실행 단계에서 연결 모델 로딩을 누르세요.');};
  // Commit to the owning plan, not the details view's detached copy.
  window.ProductPlannerActions={connectEquipmentCandidates(request){
    if(request.planId!==plan.id||request.revision!==plan.revision)throw Error('계획이 변경되었습니다. 현재 계획에서 다시 연결하세요.');
    if(runtime?.state==='RUNNING')throw Error('공정을 일시정지한 뒤 설비 후보를 연결하세요. 실행 상태를 초기화하지 않았습니다.');
    readModelFields();let added=0,enriched=0,preserved=0;
    for(const item of request.items){const process=plan.processes.find(p=>p.id===item.processId);if(!process)continue;
      const current=process.equipmentModel||{};
      if(current.assetId||current.usdPath||current.glbPath){
        if(current.assetId===item.model.assetId&&(!current.usdPath||!current.glbPath)){
          if(!current.usdPath)current.usdPath=item.model.usdPath;
          if(!current.glbPath)current.glbPath=item.model.glbPath;
          current.source=current.source||item.model.source;process.equipmentModel=current;enriched++;
        }else preserved++;
        continue;
      }
      process.equipmentModel=C.copy(item.model);added++;
    }
    if(added||enriched)changed();else saveLocal();
    notice(`설비 시각화 후보 ${added}개 연결 · 같은 Asset 경로 보완 ${enriched}개 · 기존 연결 ${preserved}개 보존 · 이 브라우저 저장 완료 · 서버 DB/공정 적합성/기계 동작 별도 미검증`);
    return {added,enriched,preserved};
  }};
  window.addEventListener('pagehide',()=>{try{saveLocal();}catch{}});
  try{runChannel=new BroadcastChannel('p006-product-planner-run-v1');runChannel.onmessage=e=>{if(e.data?.type==='request-state')publishRunState(true);};}catch{}
  render();const requestedTab=location.hash.slice(1);if(['product','site','process','run'].includes(requestedTab))showTab(requestedTab);catalogs();
})();
