'use strict';
(()=>{
 const style=document.createElement('style');style.textContent='#world.quiet-labels .object:not(.selected):not(:hover) .objectname{display:none}#world.quiet-labels .object.selected .objectname,#world.quiet-labels .object:hover .objectname{display:block;z-index:20}#layoutEvidenceStatus{max-height:64px;overflow:auto}';document.head.append(style);
 const labels=document.createElement('button');labels.id='toggleLabels';labels.textContent='이름: 선택 시';labels.setAttribute('aria-pressed','false');document.querySelector('.tools').append(labels);let showAll=false;labels.onclick=()=>{showAll=!showAll;labels.textContent=showAll?'이름: 전체':'이름: 선택 시';labels.setAttribute('aria-pressed',String(showAll));document.querySelector('#world').classList.toggle('quiet-labels',!showAll)};
 const canvas=renderCanvas;renderCanvas=function(){canvas();const world=document.querySelector('#world');world.classList.toggle('quiet-labels',!showAll);let pixels=doc.settings.grid*zoom();while(pixels<12)pixels*=2;world.style.backgroundSize=`${pixels}px ${pixels}px`;world.title=`표시 격자 ${(pixels/zoom()).toFixed(2)}m / 실제 Snap ${doc.settings.grid}m`;};
 const old=renderInspector;renderInspector=function(){old();let box=document.querySelector('#placementEvidence');if(!box){box=document.createElement('section');box.id='placementEvidence';box.className='relations';document.querySelector('.inspector').append(box)}const id=[...selected][0],ev=doc.settings.evidence?.instances?.[id];box.innerHTML=ev?'<b>배치 근거 · 실물 확정 아님</b><pre>'+esc(JSON.stringify(ev,null,2))+'</pre>':'<b>배치 근거</b><small>추가된 객체의 위치·실측·포트는 별도 근거가 없으면 UNKNOWN입니다.</small>';let bar=document.querySelector('#layoutEvidenceStatus');if(!bar){bar=document.createElement('div');bar.id='layoutEvidenceStatus';bar.style.cssText='padding:6px 20px;background:#fff5dc;font-size:12px';document.querySelector('main').before(bar)}const e=doc.settings.evidence;bar.hidden=!e;bar.textContent=e?`${e.status} · 업체/공장 UNKNOWN · 원장 후보 ${doc.instances.filter(i=>i.intakeId).length}개 참조 · 실제 Equipment Instance ${doc.instances.filter(i=>i.equipmentId).length}개 · ${e.coordinateMethod||'성능시험 반복 배치 — 실제 공장 아님'}`:''};
 const a=document.createElement('a');a.href='scale-report.html';a.textContent='공장 규모 검증';a.style.fontSize='12px';document.querySelector('.documentbar').append(a);const p=document.createElement('a');p.href='perf-report.html';p.textContent='성능·QA';p.style.fontSize='12px';document.querySelector('.documentbar').append(p);
 const inspector=renderInspector;renderInspector=function(){inspector();if(!document.getElementById('scaleGuidance')){const section=document.createElement('section');section.id='scaleGuidance';section.innerHTML='<h3>공장 규모 업무 · 64개 후보 / 50–500개 시험</h3><p>도움말: 전체 보기 → 선택/호버로 이름 확인 → 원장 근거 확인 → 편집 → DB 저장 → USD Stage 생성.</p><p>설계: 36개 원장 후보 + 28개 REFERENCE 건축·인프라. 제조사/실측/포트는 UNKNOWN이며 READY/REAL은 불변입니다.</p><p>QA: 드래그·다중 이동·복사/삭제·Undo/Redo·저장/복원·Stage/GUI 증거를 별도로 확인합니다.</p><p>성능: 500개 편집 13.6ms P95, 전체 Stage 1.450초. 증분 Stage는 1.336초이며 전체 검증을 유지합니다.</p><p>다음 업무: 증분 검증 해상도를 분리해 1초 이하로 낮춥니다.</p><a href="scale-report.html">전체 검증</a> · <a href="perf-report.html">성능·QA / 다음 업무</a> · <a href="scale-design.md">설계 문서</a>';document.getElementById('guidance').append(section)}};
})();
