import { createRouteFamily, type PageUnitsOf, type RouteDefinitionsOf } from "../../../framework/registry/routeFamilyTypes";
import { buildManifestBackedRoutePageContracts } from "./manifestBackedPageContracts";

const AI_MANAGEMENT_ROUTE_DEFINITIONS = [
  { id: "ai-dashboard", label: "AI 대시보드", group: "admin", koPath: "/admin/ai/dashboard", enPath: "/en/admin/ai/dashboard" },
  { id: "ai-hermes", label: "Hermes 에이전트", group: "admin", koPath: "/admin/ai/hermes", enPath: "/en/admin/ai/hermes" },
  { id: "ai-models", label: "모델 관리", group: "admin", koPath: "/admin/ai/models", enPath: "/en/admin/ai/models" },
  { id: "ai-model-register", label: "모델 등록", group: "admin", koPath: "/admin/ai/models/register", enPath: "/en/admin/ai/models/register" },
  { id: "ai-model-versions", label: "모델 버전 관리", group: "admin", koPath: "/admin/ai/models/versions", enPath: "/en/admin/ai/models/versions" },
  { id: "ai-model-deploy", label: "모델 배포", group: "admin", koPath: "/admin/ai/models/deploy", enPath: "/en/admin/ai/models/deploy" },
  { id: "ai-model-monitor", label: "모델 상태 모니터링", group: "admin", koPath: "/admin/ai/models/monitor", enPath: "/en/admin/ai/models/monitor" },
  { id: "ai-model-resources", label: "GPU/CPU 리소스", group: "admin", koPath: "/admin/ai/models/resources", enPath: "/en/admin/ai/models/resources" },
  { id: "ai-model-compare", label: "모델 비교", group: "admin", koPath: "/admin/ai/models/compare", enPath: "/en/admin/ai/models/compare" },
  { id: "ai-training", label: "학습 관리", group: "admin", koPath: "/admin/ai/training", enPath: "/en/admin/ai/training" },
  { id: "ai-training-data", label: "학습 데이터 관리", group: "admin", koPath: "/admin/ai/training/data", enPath: "/en/admin/ai/training/data" },
  { id: "ai-training-approval", label: "데이터 승인", group: "admin", koPath: "/admin/ai/training/approval", enPath: "/en/admin/ai/training/approval" },
  { id: "ai-training-lora", label: "LoRA 관리", group: "admin", koPath: "/admin/ai/training/lora", enPath: "/en/admin/ai/training/lora" },
  { id: "ai-training-execute", label: "파인튜닝 실행", group: "admin", koPath: "/admin/ai/training/execute", enPath: "/en/admin/ai/training/execute" },
  { id: "ai-training-history", label: "학습 이력", group: "admin", koPath: "/admin/ai/training/history", enPath: "/en/admin/ai/training/history" },
  { id: "ai-training-evaluation", label: "학습 결과 평가", group: "admin", koPath: "/admin/ai/training/evaluation", enPath: "/en/admin/ai/training/evaluation" },
  { id: "ai-rag", label: "RAG 관리", group: "admin", koPath: "/admin/ai/rag", enPath: "/en/admin/ai/rag" },
  { id: "ai-rag-documents", label: "문서 등록", group: "admin", koPath: "/admin/ai/rag/documents", enPath: "/en/admin/ai/rag/documents" },
  { id: "ai-rag-chunks", label: "청크 관리", group: "admin", koPath: "/admin/ai/rag/chunks", enPath: "/en/admin/ai/rag/chunks" },
  { id: "ai-rag-embedding", label: "임베딩 관리", group: "admin", koPath: "/admin/ai/rag/embedding", enPath: "/en/admin/ai/rag/embedding" },
  { id: "ai-rag-vectordb", label: "벡터DB 관리", group: "admin", koPath: "/admin/ai/rag/vectordb", enPath: "/en/admin/ai/rag/vectordb" },
  { id: "ai-rag-verify", label: "검색 결과 검증", group: "admin", koPath: "/admin/ai/rag/verify", enPath: "/en/admin/ai/rag/verify" },
  { id: "ai-rag-reranking", label: "리랭킹 관리", group: "admin", koPath: "/admin/ai/rag/reranking", enPath: "/en/admin/ai/rag/reranking" },
  { id: "ai-rag-index", label: "인덱스 재생성", group: "admin", koPath: "/admin/ai/rag/index", enPath: "/en/admin/ai/rag/index" },
  { id: "ai-agents", label: "에이전트 관리", group: "admin", koPath: "/admin/ai/agents", enPath: "/en/admin/ai/agents" },
  { id: "ai-agent-register", label: "에이전트 등록", group: "admin", koPath: "/admin/ai/agents/register", enPath: "/en/admin/ai/agents/register" },
  { id: "ai-agent-tools", label: "Tool 관리", group: "admin", koPath: "/admin/ai/agents/tools", enPath: "/en/admin/ai/agents/tools" },
  { id: "ai-agent-prompts", label: "Prompt 관리", group: "admin", koPath: "/admin/ai/agents/prompts", enPath: "/en/admin/ai/agents/prompts" },
  { id: "ai-agent-workflows", label: "Workflow 관리", group: "admin", koPath: "/admin/ai/agents/workflows", enPath: "/en/admin/ai/agents/workflows" },
  { id: "ai-agent-router", label: "Router 설정", group: "admin", koPath: "/admin/ai/agents/router", enPath: "/en/admin/ai/agents/router" },
  { id: "ai-logs", label: "로그 관리", group: "admin", koPath: "/admin/ai/logs", enPath: "/en/admin/ai/logs" },
  { id: "ai-logs-conversation", label: "대화 로그", group: "admin", koPath: "/admin/ai/logs/conversation", enPath: "/en/admin/ai/logs/conversation" },
  { id: "ai-logs-tasks", label: "작업 로그", group: "admin", koPath: "/admin/ai/logs/tasks", enPath: "/en/admin/ai/logs/tasks" },
  { id: "ai-logs-errors", label: "오류 로그", group: "admin", koPath: "/admin/ai/logs/errors", enPath: "/en/admin/ai/logs/errors" },
  { id: "ai-logs-tools", label: "Tool 호출 로그", group: "admin", koPath: "/admin/ai/logs/tools", enPath: "/en/admin/ai/logs/tools" },
  { id: "ai-logs-inference", label: "추론 로그", group: "admin", koPath: "/admin/ai/logs/inference", enPath: "/en/admin/ai/logs/inference" },
  { id: "ai-quality", label: "품질 관리", group: "admin", koPath: "/admin/ai/quality", enPath: "/en/admin/ai/quality" },
  { id: "ai-quality-evaluation", label: "응답 평가", group: "admin", koPath: "/admin/ai/quality/evaluation", enPath: "/en/admin/ai/quality/evaluation" },
  { id: "ai-quality-feedback", label: "사용자 피드백", group: "admin", koPath: "/admin/ai/quality/feedback", enPath: "/en/admin/ai/quality/feedback" },
  { id: "ai-quality-hallucination", label: "Hallucination 검토", group: "admin", koPath: "/admin/ai/quality/hallucination", enPath: "/en/admin/ai/quality/hallucination" },
  { id: "ai-quality-accuracy", label: "정답률 분석", group: "admin", koPath: "/admin/ai/quality/accuracy", enPath: "/en/admin/ai/quality/accuracy" },
  { id: "ai-quality-abtest", label: "A/B 테스트", group: "admin", koPath: "/admin/ai/quality/abtest", enPath: "/en/admin/ai/quality/abtest" },
  { id: "ai-observability", label: "AI 관측", group: "admin", koPath: "/admin/ai/observability", enPath: "/en/admin/ai/observability" },
  { id: "ai-observability-prompt", label: "Prompt 추적", group: "admin", koPath: "/admin/ai/observability/prompt", enPath: "/en/admin/ai/observability/prompt" },
  { id: "ai-observability-tokens", label: "Token 사용량", group: "admin", koPath: "/admin/ai/observability/tokens", enPath: "/en/admin/ai/observability/tokens" },
  { id: "ai-observability-context", label: "컨텍스트 분석", group: "admin", koPath: "/admin/ai/observability/context", enPath: "/en/admin/ai/observability/context" },
  { id: "ai-observability-trace", label: "Trace Viewer", group: "admin", koPath: "/admin/ai/observability/trace", enPath: "/en/admin/ai/observability/trace" },
  { id: "ai-observability-failures", label: "실패 원인 분석", group: "admin", koPath: "/admin/ai/observability/failures", enPath: "/en/admin/ai/observability/failures" },
] as const satisfies RouteDefinitionsOf;

const AI_MANAGEMENT_PAGE_UNITS = [
  { id: "ai-dashboard", exportName: "AiDashboardPage", loader: () => import("../../../features/ai-management/AiDashboardPage") },
  { id: "ai-hermes", exportName: "HermesAgentPage", loader: () => import("../../../features/hermes-agent/HermesAgentPage") },
  { id: "ai-models", exportName: "AiModelsPage", loader: () => import("../../../features/ai-management/AiModelsPage") },
  { id: "ai-model-register", exportName: "AiModelRegisterPage", loader: () => import("../../../features/ai-management/AiModelRegisterPage") },
  { id: "ai-model-versions", exportName: "AiModelVersionsPage", loader: () => import("../../../features/ai-management/AiModelVersionsPage") },
  { id: "ai-model-deploy", exportName: "AiModelDeployPage", loader: () => import("../../../features/ai-management/AiModelDeployPage") },
  { id: "ai-model-monitor", exportName: "AiModelMonitorPage", loader: () => import("../../../features/ai-management/AiModelMonitorPage") },
  { id: "ai-model-resources", exportName: "AiModelResourcesPage", loader: () => import("../../../features/ai-management/AiModelResourcesPage") },
  { id: "ai-model-compare", exportName: "AiModelComparePage", loader: () => import("../../../features/ai-management/AiModelComparePage") },
  { id: "ai-training", exportName: "AiTrainingPage", loader: () => import("../../../features/ai-management/AiTrainingPage") },
  { id: "ai-training-data", exportName: "AiTrainingDataPage", loader: () => import("../../../features/ai-management/AiTrainingDataPage") },
  { id: "ai-training-approval", exportName: "AiTrainingApprovalPage", loader: () => import("../../../features/ai-management/AiTrainingApprovalPage") },
  { id: "ai-training-lora", exportName: "AiTrainingLoraPage", loader: () => import("../../../features/ai-management/AiTrainingLoraPage") },
  { id: "ai-training-execute", exportName: "AiTrainingExecutePage", loader: () => import("../../../features/ai-management/AiTrainingExecutePage") },
  { id: "ai-training-history", exportName: "AiTrainingHistoryPage", loader: () => import("../../../features/ai-management/AiTrainingHistoryPage") },
  { id: "ai-training-evaluation", exportName: "AiTrainingEvaluationPage", loader: () => import("../../../features/ai-management/AiTrainingEvaluationPage") },
  { id: "ai-rag", exportName: "AiRagPage", loader: () => import("../../../features/ai-management/AiRagPage") },
  { id: "ai-rag-documents", exportName: "AiRagDocumentsPage", loader: () => import("../../../features/ai-management/AiRagDocumentsPage") },
  { id: "ai-rag-chunks", exportName: "AiRagChunksPage", loader: () => import("../../../features/ai-management/AiRagChunksPage") },
  { id: "ai-rag-embedding", exportName: "AiRagEmbeddingPage", loader: () => import("../../../features/ai-management/AiRagEmbeddingPage") },
  { id: "ai-rag-vectordb", exportName: "AiRagVectordbPage", loader: () => import("../../../features/ai-management/AiRagVectordbPage") },
  { id: "ai-rag-verify", exportName: "AiRagVerifyPage", loader: () => import("../../../features/ai-management/AiRagVerifyPage") },
  { id: "ai-rag-reranking", exportName: "AiRagRerankingPage", loader: () => import("../../../features/ai-management/AiRagRerankingPage") },
  { id: "ai-rag-index", exportName: "AiRagIndexPage", loader: () => import("../../../features/ai-management/AiRagIndexPage") },
  { id: "ai-agents", exportName: "AiAgentsPage", loader: () => import("../../../features/ai-management/AiAgentsPage") },
  { id: "ai-agent-register", exportName: "AiAgentRegisterPage", loader: () => import("../../../features/ai-management/AiAgentRegisterPage") },
  { id: "ai-agent-tools", exportName: "AiAgentToolsPage", loader: () => import("../../../features/ai-management/AiAgentToolsPage") },
  { id: "ai-agent-prompts", exportName: "AiAgentPromptsPage", loader: () => import("../../../features/ai-management/AiAgentPromptsPage") },
  { id: "ai-agent-workflows", exportName: "AiAgentWorkflowsPage", loader: () => import("../../../features/ai-management/AiAgentWorkflowsPage") },
  { id: "ai-agent-router", exportName: "AiAgentRouterPage", loader: () => import("../../../features/ai-management/AiAgentRouterPage") },
  { id: "ai-logs", exportName: "AiLogsPage", loader: () => import("../../../features/ai-management/AiLogsPage") },
  { id: "ai-logs-conversation", exportName: "AiLogsConversationPage", loader: () => import("../../../features/ai-management/AiLogsConversationPage") },
  { id: "ai-logs-tasks", exportName: "AiLogsTasksPage", loader: () => import("../../../features/ai-management/AiLogsTasksPage") },
  { id: "ai-logs-errors", exportName: "AiLogsErrorsPage", loader: () => import("../../../features/ai-management/AiLogsErrorsPage") },
  { id: "ai-logs-tools", exportName: "AiLogsToolsPage", loader: () => import("../../../features/ai-management/AiLogsToolsPage") },
  { id: "ai-logs-inference", exportName: "AiLogsInferencePage", loader: () => import("../../../features/ai-management/AiLogsInferencePage") },
  { id: "ai-quality", exportName: "AiQualityPage", loader: () => import("../../../features/ai-management/AiQualityPage") },
  { id: "ai-quality-evaluation", exportName: "AiQualityEvaluationPage", loader: () => import("../../../features/ai-management/AiQualityEvaluationPage") },
  { id: "ai-quality-feedback", exportName: "AiQualityFeedbackPage", loader: () => import("../../../features/ai-management/AiQualityFeedbackPage") },
  { id: "ai-quality-hallucination", exportName: "AiQualityHallucinationPage", loader: () => import("../../../features/ai-management/AiQualityHallucinationPage") },
  { id: "ai-quality-accuracy", exportName: "AiQualityAccuracyPage", loader: () => import("../../../features/ai-management/AiQualityAccuracyPage") },
  { id: "ai-quality-abtest", exportName: "AiQualityAbtestPage", loader: () => import("../../../features/ai-management/AiQualityAbtestPage") },
  { id: "ai-observability", exportName: "AiObservabilityPage", loader: () => import("../../../features/ai-management/AiObservabilityPage") },
  { id: "ai-observability-prompt", exportName: "AiObservabilityPromptPage", loader: () => import("../../../features/ai-management/AiObservabilityPromptPage") },
  { id: "ai-observability-tokens", exportName: "AiObservabilityTokensPage", loader: () => import("../../../features/ai-management/AiObservabilityTokensPage") },
  { id: "ai-observability-context", exportName: "AiObservabilityContextPage", loader: () => import("../../../features/ai-management/AiObservabilityContextPage") },
  { id: "ai-observability-trace", exportName: "AiObservabilityTracePage", loader: () => import("../../../features/ai-management/AiObservabilityTracePage") },
  { id: "ai-observability-failures", exportName: "AiObservabilityFailuresPage", loader: () => import("../../../features/ai-management/AiObservabilityFailuresPage") },
] as const satisfies PageUnitsOf<typeof AI_MANAGEMENT_ROUTE_DEFINITIONS>;

export const AI_MANAGEMENT_FAMILY = createRouteFamily(AI_MANAGEMENT_ROUTE_DEFINITIONS, AI_MANAGEMENT_PAGE_UNITS, {
  familyId: "ai-management",
  pageFamily: "registry",
  ownershipLane: "SYSTEM",
  installScope: "COMMON_DEF_PROJECT_BIND",
  systemization: {
    manifestOwner: "aiManagementFamily",
    templateProfile: "ai-management-governance-suite",
    frameProfile: "admin-governed-management-layout",
    helpBinding: "ai-management.help",
    accessibilityBinding: "ai-governance-accessibility",
    securityBinding: "ai-management-route-guard"
  },
  authorityScope: {
    actorFamily: "ADMIN",
    dataScope: "GLOBAL",
    actionScopes: ["view", "create", "update", "delete", "execute", "approve", "export"],
    menuPolicy: "AI management menus follow admin governance visibility policy",
    entryPolicy: "admin-governance-only",
    queryPolicy: "AI management queries stay inside admin governance scope",
    actionPolicy: "AI management mutations require the same admin governance guard",
    approvalPolicy: "approval and execution escalation stay inside admin governance flow",
    auditPolicy: "AI management deny and execute paths emit governance audit evidence",
    tracePolicy: "AI management traces stay correlated by pageId",
    denyState: "admin-governance-denied-state"
  },
  commonDefinition: {
    owner: "app/routes/families/aiManagementFamily",
    artifacts: ["route family definition", "AI management page manifests", "AI management validator", "AI governance trace baseline"]
  },
  projectBinding: {
    owner: "AI management menu and route placement binding",
    menuBinding: "AI management menu binding",
    routeBinding: "AI management route binding",
    authorityBinding: "admin governance authority narrowing",
    themeBinding: "admin governance presentation binding"
  },
  projectExecutor: {
    owner: "AI management project executor",
    responsibilities: ["AI dashboard execution", "model management execution", "training management execution", "RAG management execution", "agent management execution"]
  },
  installDeploy: {
    packagingOwnerPath: "frontend/src/app/routes/families",
    assemblyOwnerPath: "frontend/src/app/routes/families/allRouteFamilies.ts",
    bootstrapPayloadTarget: "/admin/ai/dashboard",
    bindingInputs: ["AI management menu binding", "route ownership", "authority narrowing", "integration endpoint selection"],
    validatorChecks: ["AI management manifest linked", "authority scope aligned", "runtime target known", "AI monitoring evidence linked"],
    runtimeVerificationTarget: "/admin/ai/dashboard",
    compareTarget: "/admin/ai/models",
    deploySequence: "frontend build -> package -> restart-18000 -> AI management route verify",
    freshnessVerificationSequence: "npm run build -> package -> restart-18000 -> codex freshness verify -> AI management route verify",
    validator: "AI management route family aggregate validator",
    rollbackEvidence: "AI management governance compare and backup evidence",
    auditTrace: "AI management governance and monitoring trace linkage"
  },
  pageContracts: buildManifestBackedRoutePageContracts(AI_MANAGEMENT_ROUTE_DEFINITIONS, {
    familyId: "ai-management",
    manifestRoot: "aiManagementFamily.manifest",
    menuCodePrefix: "AI_MANAGEMENT",
    validator: "AI management route family aggregate validator",
    rollbackEvidence: "AI management governance compare and backup evidence"
  }),
  pageSystemizationCloseout:
    "CLOSED: page systemization is complete for ai-management; identity, authority scope, contracts, project binding, validator checks, and runtime verification target are explicit.",
  authorityScopeApplicationCloseout:
    "CLOSED: authority scope is consistently applied for ai-management; menu, entry, query, action, approval, audit, and trace surfaces follow the same governed policy.",
  builderInstallDeployCloseout:
    "CLOSED: builder install and deploy closeout is complete for ai-management; install inputs, project bindings, packaging source of truth, runtime target, and evidence surfaces are explicit.",
  projectBindingPatternsCloseout:
    "CLOSED: project binding is explicit for ai-management; common definition, project binding, and project executor lines are separately traceable."
});