import { useEffect, useMemo, useState, type ReactNode } from "react";
import { buildLocalizedPath, isEnglish } from "../../lib/navigation/runtime";
import { HOME_ENTRY_ASSETS, LOCALIZED_CONTENT } from "../home-entry/homeEntryContent";
import { HeaderBrand, HomeFooter, HomeInlineStyles } from "../home-entry/HomeEntrySections";

type JsonRecord=Record<string,unknown>;
type RuntimeComponent={componentId:string;componentType:string;defaultProps?:string|JsonRecord};
type DataContract={bindingKey:string;sourceType:string;endpoint?:string;staticPayload?:string|JsonRecord};
type RuntimeAction={actionCode:string;actionType:string;target?:string;method?:string;confirmation?:string};
type RuntimePage={pageId:string;components:RuntimeComponent[];dataContracts:DataContract[];actions:RuntimeAction[];version?:{versionNo:number}};
const asRecord=(value:unknown):JsonRecord=>{if(value&&typeof value==="object"&&!Array.isArray(value))return value as JsonRecord;if(typeof value==="string")try{return JSON.parse(value) as JsonRecord;}catch{return {};}return {};};
const text=(value:unknown)=>value==null?"":String(value);
const list=(value:unknown)=>Array.isArray(value)?value as JsonRecord[]:[];

function PageHeader({props}:{props:JsonRecord}){return <section className="rounded-2xl bg-gradient-to-br from-[#123a70] to-[#245b9b] p-7 text-white shadow-sm md:p-10"><p className="text-sm font-bold tracking-[.16em] text-blue-100">{text(props.eyebrow)}</p><h1 className="mt-2 text-3xl font-black md:text-4xl">{text(props.title)}</h1><p className="mt-4 max-w-3xl leading-7 text-blue-50">{text(props.description)}</p></section>}
function KpiGrid({props}:{props:JsonRecord}){return <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{list(props.items).map((item,index)=><article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm" key={index}><p className="text-sm font-bold text-slate-600">{text(item.label)}</p><p className="mt-3 text-3xl font-black text-[#123a70]">{text(item.value)} <span className="text-sm text-slate-500">{text(item.unit)}</span></p></article>)}</section>}
function Timeline({props}:{props:JsonRecord}){return <section className="rounded-xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-black">{text(props.title)}</h2><ol className="mt-5 grid gap-4 lg:grid-cols-3">{list(props.items).map((item,index)=><li className="rounded-lg bg-slate-50 p-5" key={index}><span className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-[#123a70] font-black text-white">{index+1}</span><h3 className="mt-3 font-black">{text(item.title)}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text(item.description)}</p></li>)}</ol></section>}
function DataTable({props}:{props:JsonRecord}){const columns=list(props.columns),rows=list(props.rows);return <section className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-200 p-6"><h2 className="text-xl font-black">{text(props.title)}</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[640px] text-left"><thead className="bg-slate-50"><tr>{columns.map((column,index)=><th className="px-5 py-3 text-sm" key={index}>{text(column.label)}</th>)}</tr></thead><tbody>{rows.map((row,rowIndex)=><tr className="border-t border-slate-100" key={rowIndex}>{columns.map((column,columnIndex)=><td className="px-5 py-4 text-sm text-slate-700" key={columnIndex}>{text(row[text(column.key)])}</td>)}</tr>)}</tbody></table></div></section>}
function Notice({props}:{props:JsonRecord}){return <section className="rounded-xl border border-blue-200 bg-blue-50 p-5"><h2 className="font-black text-blue-950">{text(props.title)}</h2><p className="mt-2 text-sm leading-6 text-blue-900">{text(props.description)}</p></section>}
const COMPONENT_REGISTRY:Record<string,(args:{props:JsonRecord})=>ReactNode>={PAGE_HEADER:PageHeader,KPI_GRID:KpiGrid,TIMELINE:Timeline,DATA_TABLE:DataTable,NOTICE:Notice};

function RuntimeActions({actions}:{actions:RuntimeAction[]}){async function run(action:RuntimeAction){if(action.confirmation&&!window.confirm(action.confirmation))return;if(action.actionType==="NAVIGATE"&&action.target){window.location.href=action.target;return;}if(action.actionType==="HTTP"&&action.target){const response=await fetch(action.target,{method:action.method||"POST",credentials:"same-origin",headers:{Accept:"application/json"}});if(!response.ok)window.alert("요청 처리에 실패했습니다.");else window.location.reload();}}return actions.length?<div className="flex flex-wrap justify-end gap-2">{actions.map(action=><button className="rounded-lg bg-[#123a70] px-5 py-3 font-bold text-white hover:bg-[#0b2b57]" key={action.actionCode} onClick={()=>void run(action)}>{action.actionCode}</button>)}</div>:null;}

export function DynamicPageRuntime(){const en=isEnglish();const content=en?LOCALIZED_CONTENT.en:LOCALIZED_CONTENT.ko;const pageId=useMemo(()=>new URLSearchParams(window.location.search).get("pageId")||"",[]);const [page,setPage]=useState<RuntimePage|null>(null);const [bindings,setBindings]=useState<Record<string,JsonRecord>>({});const [error,setError]=useState("");
useEffect(()=>{if(!pageId){setError(en?"A pageId is required.":"pageId가 필요합니다.");return;}fetch(`${en?"/en":""}/home/api/dynamic-pages/${encodeURIComponent(pageId)}`,{headers:{Accept:"application/json"}}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.message||"Not found");setPage(body as RuntimePage);const next:Record<string,JsonRecord>={};await Promise.all(((body as RuntimePage).dataContracts||[]).map(async contract=>{if(contract.sourceType==="HTTP_GET"&&contract.endpoint){const result=await fetch(contract.endpoint,{headers:{Accept:"application/json"},credentials:"same-origin"});if(result.ok)next[contract.bindingKey]=asRecord(await result.json());}else next[contract.bindingKey]=asRecord(contract.staticPayload);}));setBindings(next);}).catch(reason=>setError(reason instanceof Error?reason.message:String(reason)));},[en,pageId]);
return <><HomeInlineStyles en={en}/><div className="min-h-screen bg-slate-50 text-slate-900"><div className="border-b border-slate-200 bg-slate-100"><div className="mx-auto flex max-w-7xl items-center gap-2 px-4 py-2 lg:px-8"><img alt={content.govAlt} className="h-4" src={HOME_ENTRY_ASSETS.GOV_SYMBOL}/><span className="text-[13px] font-medium text-slate-600">{content.govText}</span></div></div><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-24 max-w-7xl items-center px-4 lg:px-8"><HeaderBrand content={content} en={en}/><a className="ml-auto rounded-lg border border-[#123a70] px-4 py-2 font-bold text-[#123a70]" href={buildLocalizedPath("/home","/en/home")}>{en?"Home":"홈"}</a></div></header><main className="mx-auto max-w-7xl space-y-6 px-4 py-10 lg:px-8">{error&&<Notice props={{title:en?"Unable to load page":"화면을 불러오지 못했습니다",description:error}}/>}{!page&&!error&&<p className="py-20 text-center font-bold text-slate-500">{en?"Loading...":"화면을 구성하고 있습니다..."}</p>}{page&&<><RuntimeActions actions={page.actions||[]}/>{page.components.map(component=>{const View=COMPONENT_REGISTRY[component.componentType];const base=asRecord(component.defaultProps);const binding=asRecord(bindings[text(base.bindingKey)]);return View?<View key={component.componentId} props={{...base,...binding}}/>:<Notice key={component.componentId} props={{title:"Unsupported component",description:component.componentType}}/>;})}<p className="text-right text-xs text-slate-400">{page.pageId} · v{page.version?.versionNo||0}</p></>}</main><HomeFooter content={content}/></div></>}
