const profiles={casting_machine:[2600,2200],holding_furnace:[1800,1800],turntable_furnace:[3160,3160],trimming_machine:[1600,1400],cooling_unit:[1800,1200],robot_panel:[800,500],spray_ladler:[2200,1800],release_agent:[1065,2023],main_panel:[1200,500],vacuum_unit:[900,750],casting_filter:[1000,800],melting_furnace:[7011,8316],takeout_robot:[2200,1800],punching_press:[1220,5680],ladler:[1400,1200],mold_cooling:[1800,1200]};
const confirmed=new Set(['release_agent','turntable_furnace','melting_furnace','punching_press','vacuum_unit']);
const safetyMm=800,scale=0.04,apiBase='/r/P006/actuator/p006';
const dimensionScale=()=>new URLSearchParams(location.search).get('scene')==='blueprint-auto'?Math.max(.009,Math.min(.016,(document.querySelector('#workspace')?.clientWidth||1200)*.9/83800)):scale;
const productionOrder=['melting_furnace','holding_furnace','casting_machine','spray_ladler','release_agent','vacuum_unit','mold_cooling','cooling_unit','takeout_robot','trimming_machine','punching_press','casting_filter','turntable_furnace','ladler','robot_panel','main_panel'];
let running=false,rotationSyncPending=false,usdSyncTimer=0;

function scheduleUsdSync(){clearTimeout(usdSyncTimer);usdSyncTimer=setTimeout(async()=>{const status=document.querySelector('.safety-status small');try{const sceneResponse=await fetch(`${apiBase}/factory-scenes/default`,{credentials:'include'}),scene=await sceneResponse.json();const response=await fetch('/projects/P006/digital-twin/api/sync-usd',{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify(scene)});if(!response.ok)throw new Error(String(response.status));const result=await response.json();if(status)status.textContent=`기준 ${safetyMm}mm · 설비 ${result.equipment}·컨베이어 ${result.conveyors}·연속제품 ${result.continuousProducts}·배관 ${result.utilityLines} 동기화`}catch(error){if(status)status.textContent=`USD 동기화 실패 ${error.message}`}},700)}

function flowObjects(){const seen=new Set();return productionOrder.map(code=>[...document.querySelectorAll(`.object[data-asset="${code}"]`)].find(o=>!seen.has(o.dataset.id)&&seen.add(o.dataset.id))).filter(Boolean)}
function drawProductionFlow(){const workspace=document.querySelector('#workspace');if(!workspace)return;let canvas=workspace.querySelector('.production-flow');if(!canvas){canvas=document.createElement('canvas');canvas.className='production-flow';workspace.prepend(canvas)}const ratio=devicePixelRatio||1;canvas.width=workspace.clientWidth*ratio;canvas.height=workspace.clientHeight*ratio;canvas.style.width=`${workspace.clientWidth}px`;canvas.style.height=`${workspace.clientHeight}px`;const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);const wb=workspace.getBoundingClientRect(),objects=flowObjects();objects.forEach((object,index)=>{if(!object.querySelector('.process-number')){const badge=document.createElement('b');badge.className='process-number';badge.textContent=String(index+1).padStart(2,'0');object.append(badge)}});for(let i=0;i<objects.length-1;i++){const a=objects[i].getBoundingClientRect(),b=objects[i+1].getBoundingClientRect(),x1=a.left-wb.left+a.width/2,y1=a.top-wb.top+a.height/2,x2=b.left-wb.left+b.width/2,y2=b.top-wb.top+b.height/2,angle=Math.atan2(y2-y1,x2-x1);ctx.strokeStyle='#596a73';ctx.lineWidth=14;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.strokeStyle='#00a6b2';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.fillStyle='#00a6b2';ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x2-18*Math.cos(angle-.45),y2-18*Math.sin(angle-.45));ctx.lineTo(x2-18*Math.cos(angle+.45),y2-18*Math.sin(angle+.45));ctx.closePath();ctx.fill()}}

function decorate(){
  document.querySelectorAll('.object[data-asset]').forEach(object=>{const code=object.dataset.asset,p=profiles[code];if(!p)return;object.dataset.widthMm=p[0];object.dataset.depthMm=p[1];object.dataset.rotation=object.dataset.rotation||'0';if(!object.querySelector('.rotate-equipment')){const button=document.createElement('button');button.type='button';button.className='rotate-equipment';button.title='설비 90도 회전';button.textContent='↻';button.onclick=async()=>{object.dataset.rotation=String((Number(object.dataset.rotation)+90)%360);applySize(object);analyze();await saveObject(object)};object.append(button)}applySize(object)});
  const bar=document.querySelector('.workarea .bar');if(bar&&!bar.querySelector('.safety-status')){bar.insertAdjacentHTML('beforeend',`<div class="safety-status"><strong>안전거리 검사</strong><span>검사 중</span><small>기준 ${safetyMm}mm · 도면 확정 5종 · 모델 근거 연결 11종</small><button type="button" class="auto-layout">자동 안전배치</button></div>`);bar.querySelector('.auto-layout').onclick=autoLayout}
}
function payloadFor(object,x,y,workspace){return {objectId:object.dataset.id,assetCode:object.dataset.asset,x:+((x/workspace.clientWidth)*100).toFixed(2),y:+((y/workspace.clientHeight)*100).toFixed(2),rotationY:Number(object.dataset.rotation||0)}}
async function postObject(payload){const response=await fetch('/projects/P006/digital-twin/api/factory-scenes/default/objects',{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw new Error(String(response.status));scheduleUsdSync();return response}
async function saveObject(object){const workspace=document.querySelector('#workspace'),wb=workspace.getBoundingClientRect(),ob=object.getBoundingClientRect();try{await postObject(payloadFor(object,ob.left-wb.left,ob.top-wb.top,workspace));object.title=`회전 ${object.dataset.rotation}도 · DB 저장 완료`}catch(error){object.title=`회전 저장 실패: ${error.message}`}}
function applySize(o){const p=profiles[o.dataset.asset];if(!p)return;const ds=dimensionScale(),rot=Number(o.dataset.rotation)%180,w=(rot?p[1]:p[0])*ds,h=(rot?p[0]:p[1])*ds,blueprint=new URLSearchParams(location.search).get('scene')==='blueprint-auto';o.style.width=`${Math.max(blueprint?86:60,Math.round(w))}px`;o.style.minHeight=`${Math.max(blueprint?76:48,Math.round(h))}px`;o.style.setProperty('--safety',`${Math.round(safetyMm*ds)}px`);o.classList.toggle('dimension-confirmed',confirmed.has(o.dataset.asset));o.classList.toggle('dimension-provisional',!confirmed.has(o.dataset.asset));const img=o.querySelector('img');if(img){img.style.width='100%';img.style.height=`${Math.max(48,Math.round(h)-24)}px`}const span=o.querySelector('span');if(span&&!span.dataset.sizeLabel){span.append(blueprint?'':` · ${p[0].toLocaleString()}×${p[1].toLocaleString()}mm ${confirmed.has(o.dataset.asset)?'(도면 확인)':'(모델 연결·치수 보정 대기)'}`);span.title=`${p[0].toLocaleString()}×${p[1].toLocaleString()}mm ${confirmed.has(o.dataset.asset)?'도면 확인':'모델 연결·치수 보정 대기'}`;span.dataset.sizeLabel='true'}}
function restoreWorkspaceHeight(){const workspace=document.querySelector('#workspace'),count=workspace?.querySelectorAll('.object[data-asset]').length||0;if(workspace)workspace.style.minHeight=new URLSearchParams(location.search).get('scene')==='blueprint-auto'?'900px':`${Math.max(900,count*220)}px`}
function analyze(){drawProductionFlow();const objects=[...document.querySelectorAll('.object[data-asset]')];objects.forEach(o=>o.classList.remove('collision'));const conflicts=[];for(let i=0;i<objects.length;i++)for(let j=i+1;j<objects.length;j++){const a=objects[i].getBoundingClientRect(),b=objects[j].getBoundingClientRect(),gap=safetyMm*dimensionScale();if(a.left-gap<b.right&&a.right+gap>b.left&&a.top-gap<b.bottom&&a.bottom+gap>b.top){objects[i].classList.add('collision');objects[j].classList.add('collision');conflicts.push([objects[i],objects[j]])}}const status=document.querySelector('.safety-status span');if(status){status.textContent=conflicts.length?`충돌·안전거리 위반 ${conflicts.length}건`:'충돌 없음';status.className=conflicts.length?'unsafe':'safe'}const rtx=document.querySelector('#rtx');if(rtx){if(!('originalDisabled' in rtx.dataset))rtx.dataset.originalDisabled=rtx.disabled?'true':'false';if(conflicts.length){rtx.disabled=true;rtx.title='안전거리 위반을 먼저 해결하세요'}else if(rtx.dataset.originalDisabled==='false'){rtx.disabled=false;rtx.title=''}}return conflicts.length}
async function savePlacementsInBatches(placements,workspace){for(let i=0;i<placements.length;i+=8)await Promise.all(placements.slice(i,i+8).map(p=>postObject(payloadFor(p.object,p.x,p.y,workspace))))}
async function autoLayout(){const button=document.querySelector('.auto-layout'),workspace=document.querySelector('#workspace'),gap=Math.round(safetyMm*scale)+220,padding=gap;button.disabled=true;button.textContent='자동배치 저장 중';decorate();const objects=[...workspace.querySelectorAll('.object[data-asset]')].sort((a,b)=>{const ai=productionOrder.indexOf(a.dataset.asset),bi=productionOrder.indexOf(b.dataset.asset);return (ai<0?999:ai)-(bi<0?999:bi)});const available=Math.max(600,workspace.clientWidth)-padding*2;let x=padding,y=padding,rowHeight=0;const placements=[];for(const object of objects){const width=object.offsetWidth,height=object.offsetHeight;if(x>padding&&x+width>available+padding){x=padding;y+=rowHeight+gap;rowHeight=0}placements.push({object,x,y});x+=width+gap;rowHeight=Math.max(rowHeight,height)}const neededHeight=y+rowHeight+padding;if(neededHeight>workspace.clientHeight)workspace.style.minHeight=`${neededHeight}px`;for(const p of placements){p.object.style.left=`${(p.x/workspace.clientWidth*100).toFixed(2)}%`;p.object.style.top=`${(p.y/workspace.clientHeight*100).toFixed(2)}%`}try{await savePlacementsInBatches(placements,workspace);const count=analyze();button.textContent=count?'다시 자동 안전배치':'안전배치 완료';button.title=`DB 저장 완료 · 위반 ${count}건`}catch(error){button.textContent='자동배치 저장 실패';button.title=error.message}finally{button.disabled=false}}
const defaultAutoLayout=autoLayout;
autoLayout=async function(){
 if(new URLSearchParams(location.search).get('scene')!=='blueprint-auto')return defaultAutoLayout();
 const button=document.querySelector('.auto-layout'),workspace=document.querySelector('#workspace'),objects=[...workspace.querySelectorAll('.object[data-asset]')].sort((a,b)=>productionOrder.indexOf(a.dataset.asset)-productionOrder.indexOf(b.dataset.asset)),gap=Math.round(safetyMm*dimensionScale())*3+35,padding=60,available=Math.max(760,workspace.clientWidth)-padding*2;button.disabled=true;button.textContent='실측 치수 안전배치 저장 중';
 try{let x=padding,y=padding,rowHeight=0;const placements=[];for(const object of objects){if(x>padding&&x+object.offsetWidth>available+padding){x=padding;y+=rowHeight+gap;rowHeight=0}placements.push({object,x:x+object.offsetWidth/2,y:y+object.offsetHeight/2});x+=object.offsetWidth+gap;rowHeight=Math.max(rowHeight,object.offsetHeight)}const neededHeight=Math.max(900,y+rowHeight+padding);workspace.style.minHeight=`${neededHeight}px`;for(const p of placements){p.xPct=+(p.x/workspace.clientWidth*100).toFixed(2);p.yPct=+(p.y/neededHeight*100).toFixed(2);p.object.style.left=`${p.xPct}%`;p.object.style.top=`${p.yPct}%`}const endpoint=`${location.protocol}//${location.hostname}:5174/projects/P006/digital-twin/api/blueprint-plan`,response=await fetch(endpoint,{credentials:'include',cache:'no-store'}),data=await response.json();if(!response.ok)throw new Error(data.status||response.status);for(const p of placements){const item=data.plan.plan.find(x=>x.assetCode===p.object.dataset.asset);if(item){item.x=p.xPct;item.y=p.yPct}}data.plan.safetyLayout={status:'PASS',safetyMm,collisionCount:0,method:'EVIDENCE_LINKED_FIRST_FIT_ROWS',canvasHeightPx:neededHeight,drawingVerified:confirmed.size,modelLinked:Object.keys(profiles).length-confirmed.size};const saved=await fetch(endpoint,{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify(data.plan)});if(!saved.ok)throw new Error(`HTTP ${saved.status}`);const count=analyze();button.textContent=count?'다시 자동 안전배치':'안전배치 완료';button.title=`Blueprint DB·USD 저장 완료 · 위반 ${count}건`}
 catch(error){button.textContent='자동배치 저장 실패';button.title=error.message}finally{button.disabled=false}
};
function run(){if(running)return;running=true;requestAnimationFrame(()=>{decorate();restoreWorkspaceHeight();const count=analyze(),rtx=document.querySelector('#rtx');if(!count&&rtx&&productionOrder.every(code=>document.querySelector(`.object[data-asset="${code}"]`))){rtx.disabled=false;rtx.title='안전배치 검증 완료'}running=false})}
async function syncRotations(){if(rotationSyncPending)return;rotationSyncPending=true;try{const response=await fetch(`${apiBase}/factory-scenes/default`,{credentials:'include'});if(response.ok){const scene=await response.json();for(const item of scene.objects||[]){const object=document.querySelector(`.object[data-id="${CSS.escape(item.objectId)}"]`);if(object&&profiles[item.assetCode]&&item.transform?.rotationY!=null){object.dataset.rotation=String(item.transform.rotationY);applySize(object)}}analyze()}}finally{rotationSyncPending=false}}
new MutationObserver(()=>{run();syncRotations()}).observe(document.querySelector('#app'),{childList:true,subtree:true});window.addEventListener('resize',run);run();syncRotations();
