const mappingLabels={melting_furnace:'용해로',holding_furnace:'보온로',casting_machine:'주조기',spray_ladler:'스프레이 로봇·래들',release_agent:'이형제 장치',vacuum_unit:'진공장치',mold_cooling:'금형 고압냉각',takeout_robot:'취출 로봇',trimming_machine:'트리밍',punching_press:'펀칭 프레스',casting_filter:'주조기 필터',turntable_furnace:'턴테이블로',ladler:'래들러',robot_panel:'로봇 제어반',main_panel:'전체 제어반'};
const mappingBase='/projects/P006/assets/catalog/';
const mappingEscape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
async function mappingUsdSync(){const scene=await fetch('/r/P006/actuator/p006/factory-scenes/default',{credentials:'include'}).then(r=>r.json());const response=await fetch('/projects/P006/sync-usd',{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify(scene)});if(!response.ok)throw new Error('USD 동기화 실패')}
async function mountMappingAdmin(){
 if(!location.pathname.endsWith('/factory-asset-mapping'))return;const main=document.querySelector('main');if(!main||main.dataset.mappingAdmin)return;main.dataset.mappingAdmin='true';
 const [manifest,map]=await Promise.all([fetch(mappingBase+'manifest.json',{cache:'no-store'}).then(r=>r.json()),fetch('/projects/P006/catalog-mappings',{credentials:'include',cache:'no-store'}).then(r=>r.json())]);
 const physical=new Set(['equipment-module','part-jig']),assets=manifest.assets.filter(a=>physical.has(a.category)),byId=new Map(map.mappings.map(row=>[row.assetId,row]));let selected=assets[0],filter='unreviewed';
 main.innerHTML=`<section class="hero"><small>WOOSU · DIGITAL TWIN · P006</small><h1>자산–3D 매핑 검토</h1><p>128개 자산을 필터링하고 Unity Mesh 번들을 일괄 승인합니다.</p></section><section class="mapping-progress card"><div><strong id="review-progress">검토 진행률 계산 중</strong><span id="review-count"></span></div><progress id="review-bar" max="128" value="0"></progress></section><section class="mapping-layout"><aside class="card mapping-list"><header><h2>매핑 검토 목록</h2><input id="mapping-search" type="search" placeholder="자산 이름 검색"><select id="mapping-filter"><option value="unreviewed">미검토</option><option value="low">저신뢰도 85% 미만</option><option value="reviewed">관리자 확정</option><option value="all">전체 128개</option></select><button class="btn" id="approve-visible">검색 결과 일괄 승인</button></header><p id="mapping-result"></p><div id="mapping-assets"></div></aside><section class="card mapping-detail" id="mapping-detail"></section></section><section class="grid cards mapping-guides"><article class="card"><b>도움말</b><p>필터로 대상을 좁히고 이전·다음 또는 일괄 승인을 사용합니다.</p></article><article class="card"><b>화면 설계</b><p>입력: 검색·필터·번들·신뢰도 / 출력: 승인율·DB·USD</p></article><article class="card"><b>QA 검증</b><p>단건·일괄 저장, 재조회, 권한, USD 동기화를 검증합니다.</p></article><article class="card"><b>다음 업무</b><p>미검토 0개 달성과 저신뢰도 항목 재검토입니다.</p></article></section>`;
 const list=main.querySelector('#mapping-assets'),detail=main.querySelector('#mapping-detail'),search=main.querySelector('#mapping-search'),filterEl=main.querySelector('#mapping-filter'),result=main.querySelector('#mapping-result');
 const rows=()=>{const q=search.value.trim().toLowerCase();return assets.filter(a=>{const m=byId.get(a.id),matches=!q||`${a.name} ${a.relativePath}`.toLowerCase().includes(q);return matches&&(filter==='all'||filter==='unreviewed'&&m.mappingSource!=='ADMIN_DB'||filter==='reviewed'&&m.mappingSource==='ADMIN_DB'||filter==='low'&&m.confidence<.85)})};
 const updateProgress=()=>{const reviewed=[...byId.values()].filter(m=>m.mappingSource==='ADMIN_DB').length;main.querySelector('#review-progress').textContent=`검토 완료 ${reviewed}/128개 · ${Math.round(reviewed/128*100)}%`;main.querySelector('#review-count').textContent=`남은 자산 ${128-reviewed}개`;main.querySelector('#review-bar').value=reviewed};
 const selectAsset=asset=>{selected=asset;renderList();renderDetail()};
 const renderList=()=>{const visible=rows();result.textContent=`현재 결과 ${visible.length}개`;list.innerHTML=visible.map(a=>{const m=byId.get(a.id);return `<button type="button" data-map-asset="${a.id}" class="${a.id===selected.id?'active':''}"><img src="${mappingBase}${a.preview}" alt=""><span><strong>${mappingEscape(a.name)}</strong><small>${m.mappingSource==='ADMIN_DB'?'확정':'미검토'} · ${mappingLabels[m.bundleCode]} · ${Math.round(m.confidence*100)}%</small></span></button>`}).join('')||'<p class="mapping-empty">조건에 맞는 자산이 없습니다.</p>';list.querySelectorAll('[data-map-asset]').forEach(b=>b.onclick=()=>selectAsset(assets.find(a=>a.id===b.dataset.mapAsset)));updateProgress()};
 const move=direction=>{const visible=rows();let index=visible.findIndex(a=>a.id===selected.id);if(index<0)index=0;selectAsset(visible[(index+direction+visible.length)%visible.length]||assets[0])};
 const saveRows=async mappings=>{const response=await fetch('/projects/P006/catalog-mappings',{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify(mappings.length===1?mappings[0]:{mappings})});const saved=await response.json();if(!response.ok)throw new Error(saved.message||`HTTP ${response.status}`);await mappingUsdSync();for(const row of mappings){const old=byId.get(row.assetId);byId.set(row.assetId,{...old,...row,mappingSource:'ADMIN_DB',updatedAt:new Date().toLocaleString('ko-KR')})}return saved};
 const renderDetail=()=>{const m=byId.get(selected.id);detail.innerHTML=`<header><div><b>${selected.id}</b><h2>${mappingEscape(selected.name)}</h2></div><span class="mapping-source">${m.mappingSource==='ADMIN_DB'?'관리자 확정':'자동 매핑'}</span></header><div class="mapping-review-nav"><button class="btn" id="mapping-prev">← 이전</button><strong>${assets.findIndex(a=>a.id===selected.id)+1}/128</strong><button class="btn" id="mapping-next">다음 →</button></div><div class="mapping-compare"><figure><img src="${mappingBase}${selected.preview}" alt="${mappingEscape(selected.name)} 원본"><figcaption>원본 사진</figcaption></figure><figure><img src="${mappingBase}mesh-previews/${m.bundleCode}.png" alt="${mappingLabels[m.bundleCode]} Unity 3D"><figcaption>Unity 3D Mesh 번들</figcaption></figure></div><form id="mapping-form"><label>3D 번들<select name="bundleCode">${Object.entries(mappingLabels).map(([code,label])=>`<option value="${code}" ${code===m.bundleCode?'selected':''}>${label} (${code})</option>`).join('')}</select></label><label>매핑 신뢰도<input name="confidence" type="number" min="50" max="100" value="${Math.round(m.confidence*100)}"><span>%</span></label><p id="mapping-message" aria-live="polite">현재 ${m.mappingSource} · ${m.updatedAt||map.generatedAt}</p><button class="btn primary" type="submit">현재 항목 승인 및 다음</button></form>`;detail.querySelector('#mapping-prev').onclick=()=>move(-1);detail.querySelector('#mapping-next').onclick=()=>move(1);detail.querySelector('select').onchange=e=>{detail.querySelector('.mapping-compare figure:nth-child(2) img').src=`${mappingBase}mesh-previews/${e.target.value}.png`};detail.querySelector('form').onsubmit=async event=>{event.preventDefault();const form=new FormData(event.currentTarget),button=event.currentTarget.querySelector('button'),message=detail.querySelector('#mapping-message');button.disabled=true;message.textContent='DB 저장·USD 동기화 중';try{await saveRows([{assetId:selected.id,bundleCode:form.get('bundleCode'),confidence:Number(form.get('confidence'))/100}]);message.textContent='승인 완료';renderList();setTimeout(()=>move(1),350)}catch(error){message.textContent=`저장 실패 · ${error.message}`}finally{button.disabled=false}}};
 main.querySelector('#approve-visible').onclick=async event=>{const visible=rows().filter(a=>byId.get(a.id).mappingSource!=='ADMIN_DB');if(!visible.length)return;event.currentTarget.disabled=true;event.currentTarget.textContent=`${visible.length}개 승인 중`;try{await saveRows(visible.map(a=>{const m=byId.get(a.id);return {assetId:a.id,bundleCode:m.bundleCode,confidence:m.confidence}}));renderList();renderDetail();event.currentTarget.textContent=`${visible.length}개 일괄 승인 완료`}catch(error){event.currentTarget.textContent=`일괄 승인 실패 · ${error.message}`}finally{event.currentTarget.disabled=false}};
 search.oninput=renderList;filterEl.onchange=()=>{filter=filterEl.value;const visible=rows();if(visible.length)selected=visible[0];renderList();renderDetail()};renderList();renderDetail();
}
new MutationObserver(()=>mountMappingAdmin().catch(console.error)).observe(document.documentElement,{childList:true,subtree:true});mountMappingAdmin().catch(console.error);
