const adminEquip=['melting_furnace','holding_furnace','casting_machine','spray_ladler','release_agent','vacuum_unit','mold_cooling','cooling_unit','takeout_robot','trimming_machine','punching_press','casting_filter','turntable_furnace','ladler','robot_panel','main_panel'],adminTags=['state','alarm_code','temperature','pressure','cycle_seconds'];
function csvRows(text){const lines=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/),head=lines.shift().split(',').map(x=>x.trim());if(head.join(',')!=='equipment_code,tag_key,address')throw new Error('CSV 헤더가 올바르지 않습니다.');return lines.map(line=>{const [equipmentCode,tagKey,...rest]=line.split(',');return {equipmentCode:equipmentCode?.trim(),tagKey:tagKey?.trim(),address:rest.join(',').trim()}})}
async function mountPlcAdmin(){if(!location.pathname.endsWith('/plc-admin'))return;const main=document.querySelector('main');if(!main||main.dataset.plcAdmin)return;main.dataset.plcAdmin='1';const data=await fetch('/projects/P006/plc-tags',{credentials:'include'}).then(r=>r.json()),map=new Map((data.equipment||[]).map(x=>[`${x.equipment_code}:${x.tag_key}`,x.address||''])),profile=data.profile||{protocol:'OPC_UA',host:'',port:4840,base_path:''};
 const configured=Number(data.configuredCount??data.configuredcount??0);main.innerHTML=`<section class="hero"><small>WOOSU · PLC/MES · PROJECT ADMIN</small><h1>PLC/MES 연결 관리자</h1><p>연결 프로필과 80개 태그 주소를 검증·저장합니다. 저장 후에도 승인 전까지 수집기는 활성화되지 않습니다.</p></section><section class="plc-admin-grid"><form class="card plc-form" id="plc-admin-form"><h2>연결 프로필</h2><label>프로토콜<select name="protocol"><option>OPC_UA</option><option>MODBUS_TCP</option><option>REST</option></select></label><label>호스트/IP<input name="host" required placeholder="192.0.2.10"></label><label>포트<input name="port" type="number" min="1" max="65535" required></label><label>기본 경로<input name="basePath" placeholder="/api/plc 또는 opc.tcp 경로"></label><div class="plc-import"><b>CSV 일괄 등록</b><p>equipment_code,tag_key,address 3열·정확히 80행</p><input id="plc-csv" type="file" accept=".csv,text/csv"></div><div class="plc-form-actions"><button class="btn" type="button" id="plc-template">CSV 템플릿</button><button class="btn" type="button" id="plc-preflight">연결 사전점검</button><button class="btn primary" type="submit">DRAFT로 저장</button></div><p class="plc-admin-status" id="plc-admin-status" aria-live="polite">현재 주소 ${configured}/80개</p></form><section class="card"><h2>태그 주소 80개</h2><div class="plc-address-scroll"><table class="plc-address-table"><thead><tr><th>설비</th><th>태그</th><th>주소</th></tr></thead><tbody>${adminEquip.flatMap(e=>adminTags.map(t=>`<tr><td>${e}</td><td>${t}</td><td><input data-e="${e}" data-t="${t}" value="${map.get(`${e}:${t}`)||''}" required></td></tr>`)).join('')}</tbody></table></div></section></section><section class="grid cards plc-guides"><article class="card"><b>도움말</b><p>사전점검은 TCP 도달성만 확인하며 장비 쓰기 명령을 전송하지 않습니다.</p></article><article class="card"><b>화면 설계</b><p>입력: 프로토콜·호스트·포트·80주소 / 출력: 검증·DRAFT 저장·감사 이력</p></article><article class="card"><b>QA 검증</b><p>권한, 80행 완전성, 중복, 잘못된 주소, 비활성 저장을 검사합니다.</p></article><article class="card"><b>다음 업무</b><p>현장 승인 후 실제 어댑터를 활성화하고 시뮬레이터를 원자적으로 전환합니다.</p></article></section>`;
 const form=main.querySelector('#plc-admin-form'),status=main.querySelector('#plc-admin-status');form.protocol.value=profile.protocol;form.host.value=profile.host||'';form.port.value=profile.port||4840;form.basePath.value=profile.base_path||'';const tags=()=>[...main.querySelectorAll('[data-e]')].map(x=>({equipmentCode:x.dataset.e,tagKey:x.dataset.t,address:x.value.trim()}));
 main.querySelector('#plc-template').onclick=()=>{const csv=['equipment_code,tag_key,address',...adminEquip.flatMap(e=>adminTags.map(t=>`${e},${t},`))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv'}));a.download='p006-plc-tags-80.csv';a.click();URL.revokeObjectURL(a.href)};
 main.querySelector('#plc-csv').onchange=async e=>{try{const rows=csvRows(await e.target.files[0].text());if(rows.length!==80)throw new Error(`80행이 필요합니다: ${rows.length}행`);const by=new Map(rows.map(r=>[`${r.equipmentCode}:${r.tagKey}`,r.address]));if(by.size!==80)throw new Error('중복 또는 누락 태그가 있습니다.');for(const input of main.querySelectorAll('[data-e]'))input.value=by.get(`${input.dataset.e}:${input.dataset.t}`)||'';status.textContent='CSV 80행 검증 완료'}catch(x){status.textContent=`CSV 오류 · ${x.message}`}};
 main.querySelector('#plc-preflight').onclick=async()=>{status.textContent='TCP 사전점검 중';const r=await fetch('/projects/P006/plc-tags/preflight',{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({host:form.host.value,port:Number(form.port.value)})}).then(r=>r.json());status.textContent=`${r.status} · ${r.elapsedMs}ms ${r.detail||''}`};
 form.onsubmit=async e=>{e.preventDefault();status.textContent='80개 주소 검증·저장 중';const payload={profile:{protocol:form.protocol.value,host:form.host.value,port:Number(form.port.value),basePath:form.basePath.value},tags:tags()},r=await fetch('/projects/P006/plc-tags',{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),b=await r.json();status.textContent=r.ok?`저장 완료 · ${b.tagCount}개 · 비활성 DRAFT`:`저장 실패 · ${b.message}`};}
new MutationObserver(()=>mountPlcAdmin().catch(console.error)).observe(document.documentElement,{childList:true,subtree:true});mountPlcAdmin().catch(console.error);
