const telemetryUrl='/projects/P006/telemetry';
const telemetryLabels={cycleSeconds:['공정시간','초'],inputPerHour:['시간당 투입','개/h'],goodUnitsPerHour:['시간당 양품','개/h'],defectRate:['불량률','%'],yieldRate:['수율','%']};
async function telemetryFetch(options){const r=await fetch(telemetryUrl,{credentials:'include',...options});const body=await r.json();if(!r.ok)throw new Error(body.message||`HTTP ${r.status}`);return body}
function telemetryPanel(data){const c=data.comparison,a=data.actual;return `<section class="scenario-card telemetry-card"><div class="section-head"><div><small>PLC/MES · 실측 비교</small><h2>예측 정확도 QA</h2></div><strong class="qa-grade ${c.grade.toLowerCase()}">${c.grade} · 평균오차 ${c.mape}%</strong></div><p>판정 기준: 평균 절대 백분율 오차 5% 이하 PASS, 10% 이하 WATCH, 초과 ACTION</p><table class="compare-table"><thead><tr><th>KPI</th><th>예측</th><th>실측</th><th>차이</th><th>오차율</th></tr></thead><tbody>${c.rows.map(r=>`<tr><td>${telemetryLabels[r.field][0]}</td><td>${r.predicted}${telemetryLabels[r.field][1]}</td><td>${r.actual}${telemetryLabels[r.field][1]}</td><td>${r.difference>0?'+':''}${r.difference}</td><td><b class="${r.errorPercent<=5?'good':'warn'}">${r.errorPercent}%</b></td></tr>`).join('')}</tbody></table><form id="telemetry-form"><h3>실측 스냅샷 입력</h3><div class="telemetry-inputs"><label>데이터 출처<input name="source" value="${a.source}" required></label>${Object.entries(telemetryLabels).map(([k,v])=>`<label>${v[0]}<input name="${k}" type="number" step="0.01" min="0" value="${a[k]}" required></label>`).join('')}<label>설비 가동률<input name="equipmentUptime" type="number" step="0.01" min="0" max="100" value="${a.equipmentUptime}" required></label></div><button type="submit">실측 저장·오차 재계산</button><p class="telemetry-status" aria-live="polite"></p></form></section>`}
function supportCards(){return `<section class="governance-grid" aria-label="업무 지원 카드"><article><b>도움말</b><p>같은 시간대의 PLC/MES 집계값을 입력합니다.</p></article><article><b>화면 설계</b><p>KRDS 카드·표·상태 배지와 WCAG 2.1 AA 기준입니다.</p></article><article><b>QA 검증</b><p>오차 5% 이하 PASS, 5~10% WATCH, 초과 ACTION입니다.</p></article><article><b>업무 길잡이</b><p>시나리오 저장 → 실측 입력 → 오차 검토 → 모델 보정 순서입니다.</p></article><article><b>전체 업무 보기</b><p>16개 공정, 예측 KPI 6개, 비교 KPI 5개입니다.</p></article><article><b>다음 업무</b><p>PLC/MES 수집기를 연결해 입력을 자동화합니다.</p></article></section>`}
function bindTelemetry(root){const form=root.querySelector('#telemetry-form');if(!form)return;form.onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,status=f.querySelector('.telemetry-status'),payload=Object.fromEntries(new FormData(f));for(const k of [...Object.keys(telemetryLabels),'equipmentUptime'])payload[k]=Number(payload[k]);status.textContent='전용 DB 저장 중';try{const saved=await telemetryFetch({method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});f.closest('.telemetry-card').outerHTML=telemetryPanel(saved);bindTelemetry(root)}catch(x){status.textContent=`저장 실패 · ${x.message}`}}}
let telemetryMounting=false;
async function mountTelemetry(){if(!location.pathname.endsWith('/results')||telemetryMounting)return;const page=document.querySelector('.scenario-page');if(!page||page.querySelector('.telemetry-card'))return;telemetryMounting=true;try{const data=await telemetryFetch();page.querySelector('.kpi-grid').insertAdjacentHTML('afterend',telemetryPanel(data));page.insertAdjacentHTML('beforeend',supportCards());bindTelemetry(page)}finally{telemetryMounting=false}}
new MutationObserver(mountTelemetry).observe(document.documentElement,{subtree:true,childList:true});mountTelemetry();
