import { FormEvent, ReactNode, useCallback, useEffect, useState } from "react";
import { buildLocalizedPath, isEnglish } from "../../lib/navigation/runtime";
import { AdminPageShell } from "../admin-entry/AdminPageShell";
import { GovernanceCompressionNav } from "../admin-system/GovernanceCompressionNav";

type Row=Record<string,unknown>;type Payload={actors:Row[];assignments:Row[];processes:Row[];steps:Row[];cases:Row[];runs:Row[]};
const value=(row:Row,key:string)=>String(row[key]??"");

export function ActorProcessGovernancePage(){const en=isEnglish(),base=buildLocalizedPath("/admin/api/system/actor-process","/en/admin/api/system/actor-process");const[data,setData]=useState<Payload>({actors:[],assignments:[],processes:[],steps:[],cases:[],runs:[]}),[tab,setTab]=useState("actors"),[error,setError]=useState("");
const load=useCallback(()=>fetch(base,{credentials:"include"}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.message);setData(b)}).catch(e=>setError(e.message)),[base]);useEffect(()=>{load()},[load]);
async function submit(e:FormEvent<HTMLFormElement>,path:string){e.preventDefault();setError("");const form=e.currentTarget,body=Object.fromEntries(new FormData(form).entries());const r=await fetch(`${base}/${path}`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),b=await r.json();if(!r.ok)throw new Error(b.message);form.reset();await load()}
const t=en?{title:"Actor & Process Governance",desc:"Define actors, bind accounts and projects, approve process simulations, and open development only after the gate passes.",actors:"Actors",assignments:"Account Assignments",processes:"Processes",simulation:"Simulation",code:"Code",name:"Name",purpose:"Purpose",type:"Type",capabilities:"Capabilities",account:"Account ID",tenant:"Tenant",project:"Project",scope:"Data Scope",actor:"Actor",goal:"Goal",start:"Start Condition",complete:"Completion Condition",version:"Version",status:"Status",steps:"Steps",cases:"Cases",passed:"Passed",register:"Register",assign:"Assign",process:"Register Process",case:"Register Test Case",run:"Record Simulation",caseCode:"Case Code",preconditions:"Preconditions",stepsJson:"Steps JSON",assertions:"Assertions JSON",result:"Result",failure:"Failure Reason"}:{title:"액터·프로세스 관리",desc:"액터를 정의하고 계정·프로젝트에 배정한 뒤 프로세스 시뮬레이션 통과 시에만 개발 가능 상태로 전환합니다.",actors:"액터",assignments:"계정·액터 배정",processes:"프로세스",simulation:"시뮬레이션",code:"코드",name:"명칭",purpose:"목적",type:"유형",capabilities:"기능 권한",account:"계정 ID",tenant:"Tenant",project:"프로젝트",scope:"데이터 범위",actor:"액터",goal:"목표",start:"시작 조건",complete:"완료 조건",version:"버전",status:"상태",steps:"단계",cases:"케이스",passed:"통과",register:"등록",assign:"배정",process:"프로세스 등록",case:"테스트 케이스 등록",run:"시뮬레이션 결과 등록",caseCode:"케이스 코드",preconditions:"사전 조건",stepsJson:"단계 JSON",assertions:"검증 조건 JSON",result:"결과",failure:"실패 사유"};
const input="h-11 w-full rounded-lg border border-slate-300 px-3",label="mb-1 block text-xs font-bold text-slate-600";
return <AdminPageShell breadcrumbs={[{label:en?"Home":"홈",href:buildLocalizedPath("/admin/","/en/admin/")},{label:en?"System":"시스템"},{label:t.title}]} title={t.title}><GovernanceCompressionNav activeId="actor-process" en={en}/><div className="space-y-5"><section className="rounded-2xl bg-gradient-to-r from-[#052b57] to-[#174ea6] p-6 text-white"><h2 className="text-2xl font-black">{t.title}</h2><p className="mt-2 max-w-4xl text-blue-50">{t.desc}</p><div className="mt-5 grid gap-3 sm:grid-cols-4">{[[t.actors,data.actors.length],[t.assignments,data.assignments.length],[t.processes,data.processes.length],[t.cases,data.cases.length]].map(([x,n])=><div key={x} className="rounded-xl bg-white/10 p-4"><span className="text-sm">{x}</span><strong className="mt-1 block text-2xl">{n}</strong></div>)}</div></section>{error&&<p className="rounded-xl bg-red-50 p-4 font-bold text-red-700">{error}</p>}
<nav className="flex flex-wrap gap-2">{[["actors",t.actors],["assignments",t.assignments],["processes",t.processes],["simulation",t.simulation]].map(([id,name])=><button key={id} onClick={()=>setTab(id)} className={`rounded-lg px-4 py-3 font-bold ${tab===id?"bg-[#246beb] text-white":"border bg-white text-slate-700"}`}>{name}</button>)}</nav>
{tab==="actors"&&<><form className="grid gap-3 rounded-2xl border bg-white p-5 lg:grid-cols-6" onSubmit={e=>submit(e,"actors").catch(x=>setError(x.message))}><Field l={t.code}><input className={input} name="actorCode" required/></Field><Field l={t.name}><input className={input} name="actorName" required/></Field><Field l={t.type}><select className={input} name="actorType"><option>BUSINESS</option><option>REVIEW</option><option>APPROVAL</option><option>OPERATION</option><option>AUTOMATION</option></select></Field><Field l={t.capabilities}><input className={input} name="capabilityCodes" placeholder="VIEW,EDIT,SUBMIT"/></Field><div className="lg:col-span-2"><label className={label}>{t.purpose}</label><input className={input} name="purpose" required/></div><button className="rounded-lg bg-[#246beb] px-4 font-bold text-white lg:col-start-6" type="submit">{t.register}</button></form><Table heads={[t.code,t.name,t.type,t.purpose,t.capabilities]} rows={data.actors.map(x=>[value(x,"actorCode"),value(x,"actorName"),value(x,"actorType"),value(x,"purpose"),value(x,"capabilityCodes")])}/></>}
{tab==="assignments"&&<><form className="grid gap-3 rounded-2xl border bg-white p-5 lg:grid-cols-6" onSubmit={e=>submit(e,"assignments").catch(x=>setError(x.message))}>{[[t.account,"accountId"],[t.tenant,"tenantId"],[t.project,"projectId"],[t.scope,"dataScope"]].map(([l,n])=><Field key={n} l={l}><input className={input} name={n} defaultValue={n==="tenantId"?"DEFAULT":n==="projectId"||n==="dataScope"?"*":""} required/></Field>)}<Field l={t.actor}><select className={input} name="actorCode" required>{data.actors.map(x=><option key={value(x,"actorCode")} value={value(x,"actorCode")}>{value(x,"actorName")} ({value(x,"actorCode")})</option>)}</select></Field><button className="rounded-lg bg-[#246beb] font-bold text-white" type="submit">{t.assign}</button></form><Table heads={[t.account,t.tenant,t.project,t.actor,t.scope,t.status]} rows={data.assignments.map(x=>[value(x,"accountId"),value(x,"tenantId"),value(x,"projectId"),value(x,"actorCode"),value(x,"dataScope"),value(x,"status")])}/></>}
{tab==="processes"&&<><form className="grid gap-3 rounded-2xl border bg-white p-5 lg:grid-cols-4" onSubmit={e=>submit(e,"processes").catch(x=>setError(x.message))}>{[[t.code,"processCode"],[t.name,"processName"],["Domain","domainCode"],[t.version,"version"],[t.goal,"goal"],[t.start,"startCondition"],[t.complete,"completionCondition"]].map(([l,n])=><Field key={n} l={l}><input className={input} name={n} defaultValue={n==="version"?"1.0.0":""} required/></Field>)}<button className="rounded-lg bg-[#246beb] font-bold text-white" type="submit">{t.process}</button></form><Table heads={[t.code,t.name,"Domain",t.version,t.status,t.steps,t.cases,t.passed]} rows={data.processes.map(x=>[value(x,"processCode"),value(x,"processName"),value(x,"domainCode"),value(x,"version"),value(x,"status"),value(x,"stepCount"),value(x,"caseCount"),value(x,"passedRuns")])}/></>}
{tab==="simulation"&&<><div className="grid gap-4 xl:grid-cols-2"><form className="grid gap-3 rounded-2xl border bg-white p-5 sm:grid-cols-2" onSubmit={e=>submit(e,"cases").catch(x=>setError(x.message))}><Field l={t.caseCode}><input className={input} name="caseCode" required/></Field><Field l={t.processes}><select className={input} name="processCode">{data.processes.map(x=><option key={value(x,"processCode")}>{value(x,"processCode")}</option>)}</select></Field><Field l={t.name}><input className={input} name="caseName" required/></Field><Field l={t.type}><select className={input} name="caseType"><option>HAPPY_PATH</option><option>EXCEPTION</option><option>AUTHORITY</option><option>ISOLATION</option><option>RECOVERY</option></select></Field><Field l={t.preconditions}><textarea className={input} name="preconditions" required/></Field><Field l={t.stepsJson}><textarea className={input} name="stepsJson" defaultValue="[]" required/></Field><Field l={t.assertions}><textarea className={input} name="assertionsJson" defaultValue="[]" required/></Field><button className="rounded-lg bg-[#246beb] font-bold text-white" type="submit">{t.case}</button></form><form className="grid gap-3 rounded-2xl border bg-white p-5 sm:grid-cols-2" onSubmit={e=>submit(e,"runs").catch(x=>setError(x.message))}><Field l={t.caseCode}><select className={input} name="caseCode">{data.cases.map(x=><option key={value(x,"caseCode")}>{value(x,"caseCode")}</option>)}</select></Field><Field l={t.result}><select className={input} name="result"><option>PASSED</option><option>FAILED</option><option>BLOCKED</option></select></Field><Field l={t.failure}><textarea className={input} name="failureReason"/></Field><Field l="Evidence JSON"><textarea className={input} name="evidenceJson" defaultValue="{}"/></Field><button className="rounded-lg bg-emerald-600 py-3 font-bold text-white sm:col-span-2" type="submit">{t.run}</button></form></div><Table heads={[t.caseCode,t.processes,t.name,t.type,t.status]} rows={data.cases.map(x=>[value(x,"caseCode"),value(x,"processCode"),value(x,"caseName"),value(x,"caseType"),value(x,"status")])}/></>}
</div></AdminPageShell>}
function Field({l,children}:{l:string;children:ReactNode}){return <div><label className="mb-1 block text-xs font-bold text-slate-600">{l}</label>{children}</div>}
function Table({heads,rows}:{heads:string[];rows:string[][]}){return <section className="overflow-hidden rounded-2xl border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-100"><tr>{heads.map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-t">{r.map((x,j)=><td key={j} className="max-w-[320px] px-4 py-3">{x||"-"}</td>)}</tr>)}</tbody></table></div></section>}
