type Row = Record<string, unknown>;
const value=(row:Row,key:string)=>String(row[key]??"");

export function DeliveryControlPanel({rows,summary,onSelect}:{rows:Row[];summary:Row;onSelect:(code:string)=>void}) {
  const labels:Record<string,string>={DEFINE_STEPS:"단계 정의",BIND_ACTORS:"액터 연결",DESIGN_TESTS:"5대 테스트 설계",RUN_TESTS:"테스트 실행",GENERATE_TASKS:"개발 작업 생성",RECOVER_BLOCKED_TASKS:"차단 작업 복구",EXECUTE_TASKS:"개발 작업 실행",DEFINE_ARTIFACTS:"산출물 정의",VERIFY_ARTIFACTS:"산출물 검증",DEFINE_SCREENS:"화면 계약 정의",COMPLETE_SCREENS:"화면 완성",COMPLETE:"완료"};
  return <div className="space-y-5">
    <section className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><h3 className="text-lg font-black text-[#052b57]">프로젝트 완성 개발 실행 큐</h3><p className="mt-2 text-sm leading-6 text-slate-700">액터 배정, 프로세스 단계, 정상·예외·권한·격리·복구 테스트, 필수 Task, 산출물과 화면 계약을 하나의 완료 게이트로 판정합니다. 상단 항목부터 처리하면 선행조건 누락 없이 프로젝트 완성도가 올라갑니다.</p></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["전체 프로세스","totalProcesses"],["완료","completeProcesses"],["차단","blockers"],["긴급 보완","highPriority"],["평균 완성도","averageScore"]].map(([label,key])=><article key={key} className="rounded-2xl border bg-white p-5"><span className="text-sm font-bold text-slate-500">{label}</span><strong className="mt-2 block text-3xl font-black text-[#052b57]">{value(summary,key)}{key==="averageScore"?"%":""}</strong></article>)}</section>
    <section className="overflow-hidden rounded-2xl border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[1250px] text-left text-sm"><thead className="bg-slate-100"><tr>{["우선","프로세스","완성도","액터·단계","테스트","Task","산출물","화면","다음 작업"].map(head=><th key={head} className="px-4 py-3 font-bold text-slate-700">{head}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={value(row,"processCode")} className="border-t align-middle"><td className="px-4 py-4 font-black">{value(row,"priority")}</td><td className="px-4 py-4"><b>{value(row,"processName")}</b><div className="font-mono text-xs text-slate-500">{value(row,"processCode")}</div></td><td className="px-4 py-4"><b className="text-blue-700">{value(row,"completionScore")}%</b></td><td className="px-4 py-4">{value(row,"actorBoundSteps")}/{value(row,"stepCount")}</td><td className="px-4 py-4">{value(row,"passedTests")}/{value(row,"testCount")} · 유형 {value(row,"testTypeCount")}/5</td><td className="px-4 py-4">{value(row,"completedTasks")}/{value(row,"requiredTasks")}</td><td className="px-4 py-4">{value(row,"verifiedArtifacts")}/{value(row,"requiredArtifacts")}</td><td className="px-4 py-4">{value(row,"readyScreens")}/{value(row,"screenContracts")}</td><td className="px-4 py-4"><button type="button" className="rounded-lg bg-[#246beb] px-3 py-2 font-bold text-white" onClick={()=>onSelect(value(row,"processCode"))}>{labels[value(row,"nextAction")]??value(row,"nextAction")}</button></td></tr>)}</tbody></table></div></section>
  </div>;
}
