import { FormEvent, useMemo, useState } from "react";

type Row=Record<string,unknown>;
type Props={actors:Row[];blueprints:Row[];busy:boolean;onPost:(path:string,body:Record<string,unknown>)=>Promise<void>;processes:Row[];projects:Row[];releases:Row[]};
const text=(row:Row,key:string)=>String(row[key]??"");
const control="min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm focus:border-[#246beb] focus:outline-none focus:ring-2 focus:ring-blue-100";

export function ProjectDeliveryBlueprintPanel({actors,blueprints,busy,onPost,processes,projects,releases}:Props){
  const [selectedProcesses,setSelectedProcesses]=useState<string[]>([]);
  const [selectedActors,setSelectedActors]=useState<string[]>([]);
  const [applyBlueprint,setApplyBlueprint]=useState("");
  const [bindings,setBindings]=useState<Record<string,string>>({});
  const approved=useMemo(()=>blueprints.filter(row=>text(row,"blueprintStatus")==="APPROVED"),[blueprints]);
  const requiredActors=useMemo(()=>{const row=approved.find(item=>text(item,"blueprintCode")===applyBlueprint);try{const specification=JSON.parse(text(row??{},"specification"));return Array.isArray(specification.actors)?specification.actors.map((item:Row)=>String(item.actorCode??"" )).filter(Boolean):[]}catch{return[]}},[applyBlueprint,approved]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget).entries());await onPost("delivery/blueprints",{...values,approve:true,actors:selectedActors.map(actorCode=>({actorCode})),processCodes:selectedProcesses});}
  async function apply(event:FormEvent<HTMLFormElement>){event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget).entries());const project=projects.find(row=>text(row,"projectId")===String(values.projectId));const actorBindings=requiredActors.map(actorCode=>({actorCode,accountId:(bindings[actorCode]??"").trim(),dataScope:"*"}));await onPost("delivery/apply",{...values,tenantId:text(project??{},"tenantId")||"DEFAULT",actorBindings});}
  return <div className="space-y-5">
    <section className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><h3 className="text-lg font-black text-[#052b57]">원자적 프로젝트 업무팩</h3><p className="mt-2 text-sm leading-6 text-slate-700">액터 계정·프로세스·화면·테스트를 먼저 검증하고, 통과한 업무팩만 프로젝트에 한 번에 반영합니다. 오류가 발생하면 전체 트랜잭션을 복구합니다.</p></section>
    <form className="space-y-5 rounded-2xl border bg-white p-5" onSubmit={save}>
      <h3 className="font-black text-[#052b57]">1. 표준 업무팩 등록·승인</h3>
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label className="text-sm font-bold">업무팩 코드<input className={control} name="blueprintCode" placeholder="EMISSION_STANDARD" required/></label><label className="text-sm font-bold">업무팩 이름<input className={control} name="blueprintName" placeholder="표준 배출량 프로젝트" required/></label><label className="text-sm font-bold">버전<input className={control} name="blueprintVersion" defaultValue="1.0.0" required/></label><label className="text-sm font-bold">업무 도메인<input className={control} name="domainCode" defaultValue="EMISSION" required/></label></div>
      <div><h4 className="text-sm font-black text-slate-700">프로세스 선택 · {selectedProcesses.length}개</h4><div className="mt-2 grid max-h-64 gap-2 overflow-auto rounded-xl border p-3 md:grid-cols-2 xl:grid-cols-3">{processes.map(row=>{const code=text(row,"processCode"),checked=selectedProcesses.includes(code);return <label className="flex min-h-10 items-center gap-2 text-sm" key={code}><input checked={checked} onChange={()=>setSelectedProcesses(current=>checked?current.filter(item=>item!==code):[...current,code])} type="checkbox"/><span><b>{text(row,"processName")}</b> <small className="text-slate-500">{code}</small></span></label>})}</div></div>
      <div><h4 className="text-sm font-black text-slate-700">필수 액터 선택 · {selectedActors.length}개</h4><div className="mt-2 grid gap-2 rounded-xl border p-3 md:grid-cols-2 xl:grid-cols-3">{actors.map(row=>{const code=text(row,"actorCode"),checked=selectedActors.includes(code);return <label className="flex min-h-10 items-center gap-2 text-sm font-bold" key={code}><input checked={checked} onChange={()=>setSelectedActors(current=>checked?current.filter(item=>item!==code):[...current,code])} type="checkbox"/>{text(row,"actorName")} <small className="text-slate-500">{code}</small></label>})}</div></div>
      <button className="min-h-11 rounded-lg bg-[#246beb] px-5 font-black text-white disabled:opacity-50" disabled={busy||selectedProcesses.length===0||selectedActors.length===0} type="submit">검증 후 업무팩 승인</button>
    </form>
    <form className="space-y-4 rounded-2xl border bg-white p-5" onSubmit={apply}><div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-bold">승인 업무팩<select className={control} name="blueprintCode" onChange={event=>{setApplyBlueprint(event.target.value);setBindings({})}} required value={applyBlueprint}><option value="">선택</option>{approved.map(row=><option key={text(row,"blueprintCode")} value={text(row,"blueprintCode")}>{text(row,"blueprintName")} · {text(row,"blueprintVersion")}</option>)}</select></label><label className="text-sm font-bold">대상 프로젝트<select className={control} name="projectId" required><option value="">선택</option>{projects.map(row=><option key={text(row,"projectId")} value={text(row,"projectId")}>{text(row,"projectName")} · {text(row,"projectId")}</option>)}</select></label><button className="min-h-11 self-end rounded-lg bg-[#0f7b49] px-5 font-black text-white disabled:opacity-50" disabled={busy||requiredActors.length===0||requiredActors.some(code=>!(bindings[code]??"").trim())} type="submit">2. 원자적 적용·화면 동기화</button></div>{requiredActors.length>0&&<div><h4 className="text-sm font-black text-slate-700">프로젝트별 액터 계정 바인딩</h4><div className="mt-2 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{requiredActors.map(code=><label className="text-sm font-bold" key={code}>{text(actors.find(row=>text(row,"actorCode")===code)??{},"actorName")} <small className="text-slate-500">{code}</small><input className={control} onChange={event=>setBindings(current=>({...current,[code]:event.target.value}))} placeholder="계정 ID" required value={bindings[code]??""}/></label>)}</div></div>}</form>
    <section className="overflow-hidden rounded-2xl border bg-white"><h3 className="border-b px-5 py-4 font-black text-[#052b57]">릴리스·복구 이력 · {releases.length}건</h3><div className="overflow-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left"><tr>{["릴리스","프로젝트","업무팩","상태","적용자","적용 시각"].map(item=><th className="px-4 py-3" key={item}>{item}</th>)}</tr></thead><tbody>{releases.map(row=><tr className="border-t" key={text(row,"releaseId")}><td className="px-4 py-3 font-mono text-xs">{text(row,"releaseCode")}</td><td className="px-4 py-3">{text(row,"projectId")}</td><td className="px-4 py-3">{text(row,"blueprintCode")}</td><td className="px-4 py-3 font-black">{text(row,"releaseStatus")}</td><td className="px-4 py-3">{text(row,"requestedBy")}</td><td className="px-4 py-3">{text(row,"promotedAt")||text(row,"createdAt")}</td></tr>)}</tbody></table></div></section>
  </div>;
}
