// Auto-generated API Client
// Generated by Builder Layer 04

import axios, { AxiosError } from 'axios';

// ============================================================================
// API Client Configuration
// ============================================================================

const apiClient = axios.create({
  baseURL: process.env.REACT_APP_API_BASE_URL || '/api',
  timeout: 30000,
  headers: { 'Content-Type': 'application/json' },
});

// Request interceptor
apiClient.interceptors.request.use(
  (config) => {
    const token = localStorage.getItem('accessToken');
    if (token) {
      config.headers.Authorization = `Bearer ${token}`;
    }
    console.log(`[API] ${config.method?.toUpperCase()} ${config.url}`);
    return config;
  },
  (error) => Promise.reject(error)
);

// Response interceptor
apiClient.interceptors.response.use(
  (response) => {
    console.log(`[API] ${response.status} ${response.config.url}`);
    return response;
  },
  async (error: AxiosError) => {
    if (error.response?.status === 401) {
      const refreshToken = localStorage.getItem('refreshToken');
      if (refreshToken) {
        try {
          const res = await axios.post('/api/auth/refresh', { refreshToken });
          localStorage.setItem('accessToken', res.data.accessToken);
          error.config.headers.Authorization = `Bearer ${res.data.accessToken}`;
          return apiClient.request(error.config);
        } catch {
          localStorage.clear();
          window.location.href = '/login';
        }
      } else {
        window.location.href = '/login';
      }
    }
    console.error('[API Error]', error.response?.data || error.message);
    return Promise.reject(error);
  }
);

// ============================================================================
// Generic API Methods
// ============================================================================

export const api = {
  get: <T = any>(url: string, params?: any, config?: any): Promise<T> =>
    apiClient.get(url, { params, ...config }).then((res) => res.data),

  post: <T = any>(url: string, data?: any, config?: any): Promise<T> =>
    apiClient.post(url, data, config).then((res) => res.data),

  put: <T = any>(url: string, data?: any, config?: any): Promise<T> =>
    apiClient.put(url, data, config).then((res) => res.data),

  patch: <T = any>(url: string, data?: any, config?: any): Promise<T> =>
    apiClient.patch(url, data, config).then((res) => res.data),

  delete: <T = any>(url: string, config?: any): Promise<T> =>
    apiClient.delete(url, config).then((res) => res.data),
};

// ============================================================================
// Error Handler
// ============================================================================

export const handleApiError = (error: any): string => {
  if (axios.isAxiosError(error)) {
    const data = error.response?.data;
    if (data?.message) return data.message;
    switch (error.response?.status) {
      case 400:
        return 'Invalid request';
      case 401:
        return 'Please login';
      case 403:
        return 'Access denied';
      case 404:
        return 'Not found';
      case 500:
        return 'Server error';
      default:
        return 'An error occurred';
    }
  }
  return 'Network error';
};

// ============================================================================
// Typed API Endpoints
// ============================================================================

export const endpoints = {
  auth: {
    login: (body: any) => api.post('/auth/login', body),
    logout: () => api.post('/auth/logout'),
    refresh: (body: any) => api.post('/auth/refresh', body),
    me: () => api.get('/auth/me'),
  },
  common: {
    codes: (codeGroup: string) => api.get(`/common/codes/${codeGroup}`),
    users: {
      list: (params?: any) => api.get('/users', { params }),
    },
    organizations: () => api.get('/organizations'),
  },
};

export default apiClient;
