// Auto-generated Screen Registry
// Generated by Builder Layer 04

import React from 'react';

// Screen component type
export type ScreenComponent = React.FC<any>;

// Registry entry
export interface ScreenEntry {
  component: ScreenComponent;
  route: string;
  screenName: string;
  contractId: number;
  processCode: string;
}

// Screen registry - populated by generator
export const screenRegistry: Record<string, ScreenEntry> = {};

// Register screen
export const registerScreen = (
  key: string,
  component: ScreenComponent,
  route: string,
  screenName: string,
  contractId: number,
  processCode: string
) => {
  screenRegistry[key] = { component, route, screenName, contractId, processCode };
};

// Get screen by key
export const getScreen = (key: string): ScreenEntry | undefined => {
  return screenRegistry[key];
};

// Get all registered screens
export const getAllScreens = (): ScreenEntry[] => {
  return Object.values(screenRegistry);
};

// Generate route config for react-router
export const generateRouteConfig = () => {
  return Object.entries(screenRegistry).map(([key, entry]) => ({
    path: entry.route,
    element: React.createElement(entry.component),
    key: key,
  }));
};
