// Auto-generated Section Components
// Generated by Builder Layer 04

import React, { useState } from 'react';
import {
  Card, CardHeader, CardContent, CardActions, Box, Typography, Button,
  IconButton, Chip, Collapse, Table, TableBody, TableCell, TableContainer,
  TableHead, TableRow, Paper
} from '@mui/material';
import { ExpandMore, Add, Edit, Delete, Refresh } from '@mui/icons-material';

// ============================================================================
// CardSection - Collapsible card section
// ============================================================================

interface CardSectionProps {
  title: string;
  subtitle?: string;
  children: React.ReactNode;
  actions?: React.ReactNode;
  collapsible?: boolean;
  defaultExpanded?: boolean;
}

export const CardSection: React.FC<CardSectionProps> = ({
  title,
  subtitle,
  children,
  actions,
  collapsible = false,
  defaultExpanded = true
}) => {
  const [expanded, setExpanded] = useState(defaultExpanded);

  return (
    <Card sx={{ mb: 2 }}>
      <CardHeader
        title={title}
        subheader={subtitle}
        action={
          <Box display="flex" alignItems="center" gap={1}>
            {actions}
            {collapsible && (
              <IconButton onClick={() => setExpanded(!expanded)} size="small">
                <ExpandMore
                  sx={{
                    transform: expanded ? 'rotate(180deg)' : 'none',
                    transition: '0.2s'
                  }}
                />
              </IconButton>
            )}
          </Box>
        }
      />
      <Collapse in={expanded}>
        <CardContent>{children}</CardContent>
      </Collapse>
    </Card>
  );
};

// ============================================================================
// StatusChip - Status indicator
// ============================================================================

interface StatusChipProps {
  status: string;
}

export const StatusChip: React.FC<StatusChipProps> = ({ status }) => {
  const statusConfig: Record<string, { color: any; label: string }> = {
    READY: { color: 'success', label: 'Ready' },
    LOADING: { color: 'info', label: 'Loading' },
    SAVING: { color: 'warning', label: 'Saving' },
    ERROR: { color: 'error', label: 'Error' },
    EMPTY: { color: 'default', label: 'Empty' },
    SUBMITTED: { color: 'success', label: 'Submitted' },
    APPROVED: { color: 'success', label: 'Approved' },
    REJECTED: { color: 'error', label: 'Rejected' },
    PENDING: { color: 'warning', label: 'Pending' },
  };

  const config = statusConfig[status.toUpperCase()] || { color: 'default' as const, label: status };

  return <Chip label={config.label} color={config.color} size="small" />;
};

// ============================================================================
// TableSection - Table with data
// ============================================================================

interface Column {
  field: string;
  headerName: string;
  render?: (value: any, row?: any) => React.ReactNode;
  width?: number | string;
}

interface TableSectionProps {
  title: string;
  columns: Column[];
  data: any[];
  onRowClick?: (row: any) => void;
  onAdd?: () => void;
  onEdit?: (row: any) => void;
  onDelete?: (row: any) => void;
  emptyMessage?: string;
}

export const TableSection: React.FC<TableSectionProps> = ({
  title,
  columns,
  data = [],
  onRowClick,
  onAdd,
  onEdit,
  onDelete,
  emptyMessage = 'No data'
}) => {
  return (
    <Card sx={{ mb: 2 }}>
      <CardHeader
        title={title}
        action={onAdd && (
          <Button startIcon={<Add />} onClick={onAdd} size="small">
            Add
          </Button>
        )}
      />
      <CardContent>
        {data.length === 0 ? (
          <Typography variant="body2" color="text.secondary" align="center" py={3}>
            {emptyMessage}
          </Typography>
        ) : (
          <TableContainer>
            <Table size="small">
              <TableHead>
                <TableRow>
                  {columns.map((col) => (
                    <TableCell
                      key={col.field}
                      sx={{ fontWeight: 'bold', width: col.width }}
                    >
                      {col.headerName}
                    </TableCell>
                  ))}
                  {(onEdit || onDelete) && <TableCell width={100}>Actions</TableCell>}
                </TableRow>
              </TableHead>
              <TableBody>
                {data.map((row, i) => (
                  <TableRow
                    key={i}
                    hover
                    onClick={() => onRowClick?.(row)}
                    sx={{ cursor: onRowClick ? 'pointer' : 'default' }}
                  >
                    {columns.map((col) => (
                      <TableCell key={col.field}>
                        {col.render
                          ? col.render(row[col.field], row)
                          : row[col.field]}
                      </TableCell>
                    ))}
                    {(onEdit || onDelete) && (
                      <TableCell>
                        {onEdit && (
                          <IconButton
                            size="small"
                            onClick={(e) => {
                              e.stopPropagation();
                              onEdit(row);
                            }}
                          >
                            <Edit fontSize="small" />
                          </IconButton>
                        )}
                        {onDelete && (
                          <IconButton
                            size="small"
                            onClick={(e) => {
                              e.stopPropagation();
                              onDelete(row);
                            }}
                          >
                            <Delete fontSize="small" color="error" />
                          </IconButton>
                        )}
                      </TableCell>
                    )}
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
        )}
      </CardContent>
    </Card>
  );
};
