// Auto-generated Utility Functions
// Generated by Builder Layer 04

// ============================================================================
// Validation Utilities
// ============================================================================

export type ValidatorFn = (value: any) => string | null;

export const required: ValidatorFn = (value) => {
  if (value === null || value === undefined || value === '') return 'Required';
  if (Array.isArray(value) && value.length === 0) return 'Required';
  return null;
};

export const minLength = (min: number): ValidatorFn => 
  (value) => value && value.length < min ? `Minimum ${min} characters` : null;

export const maxLength = (max: number): ValidatorFn => 
  (value) => value && value.length > max ? `Maximum ${max} characters` : null;

export const email: ValidatorFn = (value) => 
  value && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value) ? 'Invalid email' : null;

export const phone: ValidatorFn = (value) => 
  value && !/^\d{3}-\d{4}-\d{4}$/.test(value) ? 'Format: 010-0000-0000' : null;

export const pattern = (regex: RegExp, message: string): ValidatorFn => 
  (value) => value && !regex.test(value) ? message : null;

export const min = (minVal: number): ValidatorFn => 
  (value) => value !== null && value !== undefined && Number(value) < minVal ? `Minimum: ${minVal}` : null;

export const max = (maxVal: number): ValidatorFn => 
  (value) => value !== null && value !== undefined && Number(value) > maxVal ? `Maximum: ${maxVal}` : null;

export const oneOf = (values: any[], message?: string): ValidatorFn =>
  (value) => value && !values.includes(value) ? (message || 'Invalid value') : null;

export const validateField = (value: any, validators: ValidatorFn[]): string | null => {
  for (const validator of validators) {
    const error = validator(value);
    if (error) return error;
  }
  return null;
};

export const validateForm = (values: Record<string, any>, rules: Record<string, ValidatorFn[]>): Record<string, string> => {
  const errors: Record<string, string> = {};
  for (const [field, validators] of Object.entries(rules)) {
    const error = validateField(values[field], validators);
    if (error) errors[field] = error;
  }
  return errors;
};

// ============================================================================
// Formatting Utilities
// ============================================================================

export const formatDate = (date: string | Date, format: string = 'yyyy-MM-dd'): string => {
  if (!date) return '';
  const d = new Date(date);
  return format
    .replace('yyyy', String(d.getFullYear()))
    .replace('MM', String(d.getMonth() + 1).padStart(2, '0'))
    .replace('dd', String(d.getDate()).padStart(2, '0'))
    .replace('HH', String(d.getHours()).padStart(2, '0'))
    .replace('mm', String(d.getMinutes()).padStart(2, '0'))
    .replace('ss', String(d.getSeconds()).padStart(2, '0'));
};

export const formatNumber = (num: number, decimals: number = 0): string => {
  if (num === null || num === undefined) return '';
  return Number(num).toLocaleString('ko-KR', {
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals
  });
};

export const formatCurrency = (amount: number, currency: string = 'KRW'): string => {
  return new Intl.NumberFormat('ko-KR', { style: 'currency', currency }).format(amount);
};

// ============================================================================
// General Utilities
// ============================================================================

export const generateId = (): string => Math.random().toString(36).substr(2, 9);

export const debounce = <T extends (...args: any[]) => any>(
  func: T, wait: number
): ((...args: Parameters<T>) => void) => {
  let timeout: NodeJS.Timeout;
  return (...args: Parameters<T>) => {
    clearTimeout(timeout);
    timeout = setTimeout(() => func(...args), wait);
  };
};

export const cloneDeep = <T>(obj: T): T => JSON.parse(JSON.stringify(obj));

export const isEmpty = (value: any): boolean => {
  if (value === null || value === undefined) return true;
  if (typeof value === 'string') return value.trim() === '';
  if (Array.isArray(value)) return value.length === 0;
  if (typeof value === 'object') return Object.keys(value).length === 0;
  return false;
};
