import { createRouteFamily, type PageUnitsOf, type RouteDefinitionsOf } from "../../../framework/registry/routeFamilyTypes";
import { buildManifestBackedRoutePageContracts } from "./manifestBackedPageContracts";

const ADMIN_SYSTEM_ROUTE_DEFINITIONS = [
  { id: "system-code-inquiry", label: "코드 조회", group: "admin", koPath: "/admin/system/code", enPath: "/en/admin/system/code" },
  { id: "system-code-inquiry-class", label: "대분류", group: "admin", koPath: "/admin/system/code/class", enPath: "/en/admin/system/code/class" },
  { id: "system-code-inquiry-group", label: "중분류", group: "admin", koPath: "/admin/system/code/group", enPath: "/en/admin/system/code/group" },
  { id: "system-code-inquiry-detail", label: "소분류", group: "admin", koPath: "/admin/system/code/detail", enPath: "/en/admin/system/code/detail" },
  { id: "system-code-register", label: "코드 등록", group: "admin", koPath: "/admin/system/code/register", enPath: "/en/admin/system/code/register" },
  { id: "system-code-register-class", label: "대분류 등록", group: "admin", koPath: "/admin/system/code/register/class", enPath: "/en/admin/system/code/register/class" },
  { id: "system-code-register-group", label: "중분류 등록", group: "admin", koPath: "/admin/system/code/register/group", enPath: "/en/admin/system/code/register/group" },
  { id: "system-code-register-detail", label: "소분류 등록", group: "admin", koPath: "/admin/system/code/register/detail", enPath: "/en/admin/system/code/register/detail" },
  { id: "page-management", label: "화면 관리", group: "admin", koPath: "/admin/system/page-management", enPath: "/en/admin/system/page-management" },
  { id: "function-management", label: "기능 관리", group: "admin", koPath: "/admin/system/feature-management", enPath: "/en/admin/system/feature-management" },
  { id: "menu-management", label: "메뉴 관리", group: "admin", koPath: "/admin/system/menu", enPath: "/en/admin/system/menu" },
  { id: "faq-menu-management", label: "FAQ 메뉴 관리", group: "admin", koPath: "/admin/content/menu", enPath: "/en/admin/content/menu" },
  { id: "full-stack-management", label: "풀스택 관리", group: "admin", koPath: "/admin/system/full-stack-management", enPath: "/en/admin/system/full-stack-management" },
  { id: "infra", label: "인프라", group: "admin", koPath: "/admin/system/infra", enPath: "/en/admin/system/infra" },
  { id: "screen-flow-management", label: "화면 흐름 관리", group: "admin", koPath: "/admin/system/screen-flow-management", enPath: "/en/admin/system/screen-flow-management" },
  { id: "system-design-governance", label: "설계 완성도", group: "admin", koPath: "/admin/system/design-governance", enPath: "/en/admin/system/design-governance" },
  { id: "actor-process-governance", label: "액터·프로세스 관리", group: "admin", koPath: "/admin/system/actor-process", enPath: "/en/admin/system/actor-process" },
  { id: "process-orchestration", label: "전문 업무 프로세스 작업공간", group: "admin", koPath: "/admin/system/process-workspace", enPath: "/en/admin/system/process-workspace" },
  { id: "ops-capability-bridge", label: "Ops 통합 관제", group: "admin", koPath: "/admin/system/ops-bridge", enPath: "/en/admin/system/ops-bridge" },
  { id: "screen-menu-assignment-management", label: "화면-메뉴 귀속 관리", group: "admin", koPath: "/admin/system/screen-menu-assignment-management", enPath: "/en/admin/system/screen-menu-assignment-management" },
  { id: "screen-management", label: "화면 관리", group: "admin", koPath: "/admin/system/screen-management", enPath: "/en/admin/system/screen-management" },
  { id: "screen-builder-dashboard", label: "빌더 대시보드", group: "admin", koPath: "/admin/system/screen-builder-dashboard", enPath: "/en/admin/system/screen-builder-dashboard" },
  { id: "wbs-management", label: "WBS 관리", group: "admin", koPath: "/admin/system/wbs-management", enPath: "/en/admin/system/wbs-management" },
  { id: "home-page-workbench", label: "홈 구성 스튜디오", group: "admin", koPath: "/admin/system/home-page-workbench", enPath: "/en/admin/system/home-page-workbench" },
  { id: "new-page", label: "새 페이지", group: "admin", koPath: "/admin/system/new-page", enPath: "/en/admin/system/new-page" },
  { id: "ip-whitelist", label: "IP 화이트리스트", group: "admin", koPath: "/admin/system/ip_whitelist", enPath: "/en/admin/system/ip_whitelist" },
  { id: "access-history", label: "접속 로그", group: "admin", koPath: "/admin/system/access_history", enPath: "/en/admin/system/access_history" },
  { id: "error-log", label: "에러 로그", group: "admin", koPath: "/admin/system/error-log", enPath: "/en/admin/system/error-log" },
  { id: "login-history", label: "로그인 이력", group: "admin", koPath: "/admin/member/login_history", enPath: "/en/admin/member/login_history" },
  { id: "member-security-history", label: "회원 접근 차단 이력", group: "admin", koPath: "/admin/member/security", enPath: "/en/admin/member/security" },
  { id: "security-history", label: "보안 이력", group: "admin", koPath: "/admin/system/security", enPath: "/en/admin/system/security" },
  { id: "consent-history", label: "약관·동의 이력", group: "admin", koPath: "/admin/system/consent-history", enPath: "/en/admin/system/consent-history" },
  { id: "security-policy", label: "보안 정책", group: "admin", koPath: "/admin/system/security-policy", enPath: "/en/admin/system/security-policy" },
  { id: "notification", label: "알림센터", group: "admin", koPath: "/admin/system/notification", enPath: "/en/admin/system/notification" },
  { id: "performance", label: "성능", group: "admin", koPath: "/admin/system/performance", enPath: "/en/admin/system/performance" },
  { id: "installed-programs", label: "설치 프로그램 관리", group: "admin", koPath: "/admin/system/programs", enPath: "/en/admin/system/programs" },
  { id: "system-resources", label: "시스템 리소스 관리", group: "admin", koPath: "/admin/system/resources", enPath: "/en/admin/system/resources" },
  { id: "operations-log-management", label: "운영 로그 관리", group: "admin", koPath: "/admin/system/logs", enPath: "/en/admin/system/logs" },
  { id: "ai-hangar", label: "AI 격납고", group: "admin", koPath: "/admin/system/ai-hangar", enPath: "/en/admin/system/ai-hangar" },
  { id: "hermes-workflow", label: "Hermes 작업 기억", group: "admin", koPath: "/admin/system/hermes-workflow", enPath: "/en/admin/system/hermes-workflow" },
  { id: "theme-management", label: "테마 관리", group: "admin", koPath: "/admin/system/theme-management", enPath: "/en/admin/system/theme-management" },
  { id: "css-management", label: "CSS 관리", group: "admin", koPath: "/admin/system/css-management", enPath: "/en/admin/system/css-management" },
  { id: "theme", label: "테마 관리", group: "admin", koPath: "/admin/system/theme", enPath: "/en/admin/system/theme" },
  { id: "design-management", label: "디자인 관리", group: "admin", koPath: "/admin/system/design-management", enPath: "/en/admin/system/design-management" },
  { id: "module", label: "모듈 관리", group: "admin", koPath: "/admin/system/module", enPath: "/en/admin/system/module" },
  { id: "event-management", label: "이벤트 관리", group: "admin", koPath: "/admin/system/event-management", enPath: "/en/admin/system/event-management" },
  { id: "function-console", label: "함수 콘솔", group: "admin", koPath: "/admin/system/function-console", enPath: "/en/admin/system/function-console" },
  { id: "api-management", label: "API 관리", group: "admin", koPath: "/admin/system/api-management", enPath: "/en/admin/system/api-management" },
  { id: "controller-management", label: "컨트롤러 관리", group: "admin", koPath: "/admin/system/controller-management", enPath: "/en/admin/system/controller-management" },
  { id: "column-management", label: "컬럼 관리", group: "admin", koPath: "/admin/system/column-management", enPath: "/en/admin/system/column-management" },
  { id: "asset-deficiency-queue", label: "자산 미흡 큐", group: "admin", koPath: "/admin/system/asset-deficiency-queue", enPath: "/en/admin/system/asset-deficiency-queue" },
  { id: "verification-asset-management", label: "검증 자산 관리", group: "admin", koPath: "/admin/system/verification-asset-management", enPath: "/en/admin/system/verification-asset-management" },
  { id: "external-connection-list", label: "외부 연계 목록", group: "admin", koPath: "/admin/external/connection_list", enPath: "/en/admin/external/connection_list" },
  { id: "external-schema", label: "외부 스키마", group: "admin", koPath: "/admin/external/schema", enPath: "/en/admin/external/schema" },
  { id: "external-keys", label: "외부 인증키 관리", group: "admin", koPath: "/admin/external/keys", enPath: "/en/admin/external/keys" },
  { id: "external-usage", label: "API 사용량", group: "admin", koPath: "/admin/external/usage", enPath: "/en/admin/external/usage" },
  { id: "external-logs", label: "외부 연계 로그", group: "admin", koPath: "/admin/external/logs", enPath: "/en/admin/external/logs" },
  { id: "external-webhooks", label: "웹훅 설정", group: "admin", koPath: "/admin/external/webhooks", enPath: "/en/admin/external/webhooks" },
  { id: "external-sync", label: "동기화 실행", group: "admin", koPath: "/admin/external/sync", enPath: "/en/admin/external/sync" },
  { id: "external-monitoring", label: "연계 모니터링", group: "admin", koPath: "/admin/external/monitoring", enPath: "/en/admin/external/monitoring" },
  { id: "external-maintenance", label: "점검 관리", group: "admin", koPath: "/admin/external/maintenance", enPath: "/en/admin/external/maintenance" },
  { id: "external-retry", label: "재시도 관리", group: "admin", koPath: "/admin/external/retry", enPath: "/en/admin/external/retry" },
  { id: "db-sync-deploy", label: "DB 동기화 배포", group: "admin", koPath: "/admin/system/db-sync-deploy", enPath: "/en/admin/system/db-sync-deploy" },
  { id: "security-monitoring", label: "보안 모니터링", group: "admin", koPath: "/admin/system/security-monitoring", enPath: "/en/admin/system/security-monitoring" },
  { id: "blocklist", label: "차단 목록", group: "admin", koPath: "/admin/system/blocklist", enPath: "/en/admin/system/blocklist" },
  { id: "security-audit", label: "보안 감사", group: "admin", koPath: "/admin/system/security-audit", enPath: "/en/admin/system/security-audit" },
  { id: "monitoring-center", label: "운영센터", group: "admin", koPath: "/admin/monitoring/center", enPath: "/en/admin/monitoring/center" },
  { id: "sensor-add", label: "센서 등록", group: "admin", koPath: "/admin/monitoring/sensor_add", enPath: "/en/admin/monitoring/sensor_add" },
  { id: "sensor-edit", label: "센서 설정", group: "admin", koPath: "/admin/monitoring/sensor_edit", enPath: "/en/admin/monitoring/sensor_edit" },
  { id: "sensor-list", label: "센서 목록", group: "admin", koPath: "/admin/monitoring/sensor_list", enPath: "/en/admin/monitoring/sensor_list" },
  { id: "external-connection-add", label: "외부연계 등록", group: "admin", koPath: "/admin/external/connection_add", enPath: "/en/admin/external/connection_add" },
  { id: "external-connection-edit", label: "외부연계 수정", group: "admin", koPath: "/admin/external/connection_edit", enPath: "/en/admin/external/connection_edit" },
  { id: "batch-management", label: "배치 관리", group: "admin", koPath: "/admin/system/batch", enPath: "/en/admin/system/batch" },
  { id: "scheduler-management", label: "스케줄러 관리", group: "admin", koPath: "/admin/system/scheduler", enPath: "/en/admin/system/scheduler" },
  { id: "db-promotion-policy", label: "DB 반영 정책 카탈로그", group: "admin", koPath: "/admin/system/db-promotion-policy", enPath: "/en/admin/system/db-promotion-policy" },
  { id: "backup-config", label: "백업 설정", group: "admin", koPath: "/admin/system/backup_config", enPath: "/en/admin/system/backup_config" },
  { id: "backup-execution", label: "백업 실행", group: "admin", koPath: "/admin/system/backup", enPath: "/en/admin/system/backup" },
  { id: "restore-execution", label: "복구 실행", group: "admin", koPath: "/admin/system/restore", enPath: "/en/admin/system/restore" },
  { id: "package-governance", label: "패키지 거버넌스", group: "admin", koPath: "/admin/system/package-governance", enPath: "/en/admin/system/package-governance" },
  { id: "section-management", label: "섹션 관리", group: "admin", koPath: "/admin/system/section-management", enPath: "/en/admin/system/section-management" },
  { id: "builder-studio", label: "빌더 스튜디오", group: "admin", koPath: "/admin/system/builder-studio", enPath: "/en/admin/system/builder-studio" },
  { id: "component-management", label: "컴포넌트 관리", group: "admin", koPath: "/admin/system/component-management", enPath: "/en/admin/system/component-management" },
  { id: "admin-monitoring-dashboard", label: "모니터링 대시보드", group: "admin", koPath: "/admin/system/monitoring-dashboard", enPath: "/en/admin/system/monitoring-dashboard" },
  { id: "cron-monitoring", label: "크론 모니터링", group: "admin", koPath: "/admin/system/cron-monitoring", enPath: "/en/admin/system/cron-monitoring" },
  { id: "db-monitoring", label: "DB 모니터링", group: "admin", koPath: "/admin/system/db-monitoring", enPath: "/en/admin/system/db-monitoring" },
  { id: "batch-monitoring", label: "배치 모니터링", group: "admin", koPath: "/admin/system/batch-monitoring", enPath: "/en/admin/system/batch-monitoring" },
  { id: "git-build-monitoring", label: "Git/빌드 모니터링", group: "admin", koPath: "/admin/system/git-build-monitoring", enPath: "/en/admin/system/git-build-monitoring" }
] as const satisfies RouteDefinitionsOf;

const ADMIN_SYSTEM_PAGE_UNITS = [
  { id: "system-code-inquiry", exportName: "SystemCodeMigrationPage", loader: () => import("../../../features/system-code/SystemCodeSimplePage") },
  { id: "system-code-inquiry-class", exportName: "SystemCodeMigrationPage", loader: () => import("../../../features/system-code/SystemCodeSimplePage") },
  { id: "system-code-inquiry-group", exportName: "SystemCodeMigrationPage", loader: () => import("../../../features/system-code/SystemCodeSimplePage") },
  { id: "system-code-inquiry-detail", exportName: "SystemCodeMigrationPage", loader: () => import("../../../features/system-code/SystemCodeSimplePage") },
  { id: "system-code-register", exportName: "SystemCodeMigrationPage", loader: () => import("../../../features/system-code/SystemCodeSimplePage") },
  { id: "system-code-register-class", exportName: "SystemCodeMigrationPage", loader: () => import("../../../features/system-code/SystemCodeSimplePage") },
  { id: "system-code-register-group", exportName: "SystemCodeMigrationPage", loader: () => import("../../../features/system-code/SystemCodeSimplePage") },
  { id: "system-code-register-detail", exportName: "SystemCodeMigrationPage", loader: () => import("../../../features/system-code/SystemCodeSimplePage") },
  { id: "page-management", exportName: "PageManagementMigrationPage", loader: () => import("../../../features/page-management/PageManagementMigrationPage") },
  { id: "function-management", exportName: "FunctionManagementMigrationPage", loader: () => import("../../../features/function-management/FunctionManagementMigrationPage") },
  { id: "menu-management", exportName: "MenuManagementMigrationPage", loader: () => import("../../../features/menu-management/MenuManagementMigrationPage") },
  { id: "faq-menu-management", exportName: "FaqMenuManagementMigrationPage", loader: () => import("../../../features/menu-management/FaqMenuManagementMigrationPage") },
  { id: "full-stack-management", exportName: "FullStackManagementMigrationPage", loader: () => import("../../../features/menu-management/FullStackManagementMigrationPage") },
  { id: "infra", exportName: "InfraManagementMigrationPage", loader: () => import("../../../features/system-infra/InfraManagementMigrationPage") },
  { id: "screen-flow-management", exportName: "ScreenFlowManagementMigrationPage", loader: () => import("../../../features/screen-management/ScreenFlowManagementMigrationPage") },
  { id: "system-design-governance", exportName: "SystemDesignGovernancePage", loader: () => import("../../../features/system-design-governance/SystemDesignGovernancePage") },
  { id: "actor-process-governance", exportName: "ActorProcessGovernancePage", loader: () => import("../../../features/actor-process-governance/ActorProcessGovernancePage") },
  { id: "process-orchestration", exportName: "ProcessOrchestrationPage", loader: () => import("../../../features/process-orchestration/ProcessOrchestrationPage") },
  { id: "ops-capability-bridge", exportName: "OpsCapabilityBridgePage", loader: () => import("../../../features/ops-capability-bridge/OpsCapabilityBridgePage") },
  { id: "screen-menu-assignment-management", exportName: "ScreenMenuAssignmentManagementMigrationPage", loader: () => import("../../../features/screen-management/ScreenMenuAssignmentManagementMigrationPage") },
  { id: "screen-management", exportName: "ScreenManagementMigrationPage", loader: () => import("../../../features/screen-management/ScreenManagementMigrationPage") },
  { id: "screen-builder-dashboard", exportName: "ScreenBuilderDashboardPage", loader: () => import("../../../features/screen-builder/ScreenBuilderDashboardPage") },
  { id: "wbs-management", exportName: "WbsManagementMigrationPage", loader: () => import("../../../features/wbs-management/WbsManagementMigrationPage") },
  { id: "home-page-workbench", exportName: "HomePageWorkbenchMigrationPage", loader: () => import("../../../features/home-page-workbench/HomePageWorkbenchMigrationPage") },
  { id: "new-page", exportName: "NewPageMigrationPage", loader: () => import("../../../features/new-page") },
  { id: "ip-whitelist", exportName: "IpWhitelistMigrationPage", loader: () => import("../../../features/ip-whitelist/IpWhitelistMigrationPage") },
  { id: "access-history", exportName: "AccessHistoryMigrationPage", loader: () => import("../../../features/access-history/AccessHistoryMigrationPage") },
  { id: "error-log", exportName: "ErrorLogMigrationPage", loader: () => import("../../../features/error-log/ErrorLogMigrationPage") },
  { id: "login-history", exportName: "LoginHistoryMigrationPage", loader: () => import("../../../features/login-history/LoginHistoryMigrationPage") },
  { id: "member-security-history", exportName: "MemberSecurityHistoryMigrationPage", loader: () => import("../../../features/security-history/MemberSecurityHistoryMigrationPage") },
  { id: "security-history", exportName: "SecurityHistoryMigrationPage", loader: () => import("../../../features/security-history/SecurityHistoryMigrationPage") },
  { id: "consent-history", exportName: "ConsentHistoryMigrationPage", loader: () => import("../../../features/consent-history/ConsentHistoryMigrationPage") },
  { id: "security-policy", exportName: "SecurityPolicyMigrationPage", loader: () => import("../../../features/security-policy/SecurityPolicyMigrationPage") },
  { id: "notification", exportName: "NotificationCenterMigrationPage", loader: () => import("../../../features/notification-center/NotificationCenterMigrationPage") },
  { id: "performance", exportName: "PerformanceMigrationPage", loader: () => import("../../../features/performance/PerformanceMigrationPage") },
  { id: "installed-programs", exportName: "InstalledProgramsMigrationPage", loader: () => import("../../../features/operations-inventory/OperationsInventoryPages") },
  { id: "system-resources", exportName: "SystemResourcesMigrationPage", loader: () => import("../../../features/operations-inventory/OperationsInventoryPages") },
  { id: "operations-log-management", exportName: "OperationsLogManagementMigrationPage", loader: () => import("../../../features/operations-inventory/OperationsInventoryPages") },
  { id: "ai-hangar", exportName: "AiHangarMigrationPage", loader: () => import("../../../features/operations-inventory/OperationsInventoryPages") },
  { id: "hermes-workflow", exportName: "HermesWorkflowMigrationPage", loader: () => import("../../../features/hermes-workflow/HermesWorkflowMigrationPage") },
  { id: "theme-management", exportName: "DesignAssetRegistryPage", loader: () => import("../../../features/design-asset-registry/DesignAssetRegistryPage") },
  { id: "css-management", exportName: "DesignAssetRegistryPage", loader: () => import("../../../features/design-asset-registry/DesignAssetRegistryPage") },
  { id: "theme", exportName: "ThemeManagementMigrationPage", loader: () => import("../../../features/builder-governance/BuilderGovernancePages") },
  { id: "design-management", exportName: "DesignAssetRegistryPage", loader: () => import("../../../features/design-asset-registry/DesignAssetRegistryPage") },
  { id: "module", exportName: "ModuleManagementMigrationPage", loader: () => import("../../../features/module-management/ModuleManagementMigrationPage") },
  { id: "event-management", exportName: "EventManagementMigrationPage", loader: () => import("../../../features/event-management/EventManagementMigrationPage") },
  { id: "function-console", exportName: "FunctionConsoleMigrationPage", loader: () => import("../../../features/function-console/FunctionConsoleMigrationPage") },
  { id: "api-management", exportName: "ApiManagementMigrationPage", loader: () => import("../../../features/api-management/ApiManagementMigrationPage") },
  { id: "controller-management", exportName: "ControllerManagementMigrationPage", loader: () => import("../../../features/controller-management/ControllerManagementMigrationPage") },
  { id: "column-management", exportName: "ColumnManagementMigrationPage", loader: () => import("../../../features/column-management/ColumnManagementMigrationPage") },
  { id: "asset-deficiency-queue", exportName: "AssetDeficiencyQueueMigrationPage", loader: () => import("../../../features/asset-deficiency-queue/AssetDeficiencyQueueMigrationPage") },
  { id: "verification-asset-management", exportName: "VerificationAssetManagementMigrationPage", loader: () => import("../../../features/verification-asset-management/VerificationAssetManagementMigrationPage") },
  { id: "external-connection-list", exportName: "ExternalConnectionListMigrationPage", loader: () => import("../../../features/external-connection-list/ExternalConnectionListMigrationPage") },
  { id: "external-schema", exportName: "ExternalSchemaMigrationPage", loader: () => import("../../../features/external-schema/ExternalSchemaMigrationPage") },
  { id: "external-keys", exportName: "ExternalKeysMigrationPage", loader: () => import("../../../features/external-keys/ExternalKeysMigrationPage") },
  { id: "external-usage", exportName: "ExternalUsageMigrationPage", loader: () => import("../../../features/external-usage/ExternalUsageMigrationPage") },
  { id: "external-logs", exportName: "ExternalLogsMigrationPage", loader: () => import("../../../features/external-logs/ExternalLogsMigrationPage") },
  { id: "external-webhooks", exportName: "ExternalWebhooksMigrationPage", loader: () => import("../../../features/external-webhooks/ExternalWebhooksMigrationPage") },
  { id: "external-sync", exportName: "ExternalSyncMigrationPage", loader: () => import("../../../features/external-sync/ExternalSyncMigrationPage") },
  { id: "external-monitoring", exportName: "ExternalMonitoringMigrationPage", loader: () => import("../../../features/external-monitoring/ExternalMonitoringMigrationPage") },
  { id: "external-maintenance", exportName: "ExternalMaintenanceMigrationPage", loader: () => import("../../../features/external-maintenance/ExternalMaintenanceMigrationPage") },
  { id: "external-retry", exportName: "ExternalRetryMigrationPage", loader: () => import("../../../features/external-retry/ExternalRetryMigrationPage") },
  { id: "security-monitoring", exportName: "SecurityMonitoringMigrationPage", loader: () => import("../../../features/security-monitoring/SecurityMonitoringMigrationPage") },
  { id: "blocklist", exportName: "BlocklistMigrationPage", loader: () => import("../../../features/blocklist/BlocklistMigrationPage") },
  { id: "security-audit", exportName: "SecurityAuditMigrationPage", loader: () => import("../../../features/security-audit/SecurityAuditMigrationPage") },
  { id: "monitoring-center", exportName: "OperationsCenterMigrationPage", loader: () => import("../../../features/operations-center/OperationsCenterMigrationPage") },
  { id: "sensor-add", exportName: "SensorAddMigrationPage", loader: () => import("../../../features/sensor-add/SensorAddMigrationPage") },
  { id: "sensor-edit", exportName: "SensorEditMigrationPage", loader: () => import("../../../features/sensor-edit/SensorEditMigrationPage") },
  { id: "sensor-list", exportName: "SensorListMigrationPage", loader: () => import("../../../features/sensor-list/SensorListMigrationPage") },
  { id: "external-connection-add", exportName: "ExternalConnectionAddMigrationPage", loader: () => import("../../../features/external-connection-add/ExternalConnectionAddMigrationPage") },
  { id: "external-connection-edit", exportName: "ExternalConnectionEditMigrationPage", loader: () => import("../../../features/external-connection-edit/ExternalConnectionEditMigrationPage") },
  { id: "batch-management", exportName: "BatchManagementMigrationPage", loader: () => import("../../../features/batch-management/BatchManagementMigrationPage") },
  { id: "scheduler-management", exportName: "SchedulerManagementMigrationPage", loader: () => import("../../../features/scheduler-management/SchedulerManagementMigrationPage") },
  { id: "db-promotion-policy", exportName: "DbPromotionPolicyMigrationPage", loader: () => import("../../../features/db-promotion-policy/DbPromotionPolicyMigrationPage") },
  { id: "db-sync-deploy", exportName: "DbSyncDeployMigrationPage", loader: () => import("../../../features/db-sync-deploy/DbSyncDeployMigrationPage") },
  { id: "backup-config", exportName: "BackupConfigMigrationPage", loader: () => import("../../../features/backup-config/BackupConfigMigrationPage") },
  { id: "backup-execution", exportName: "BackupConfigMigrationPage", loader: () => import("../../../features/backup-config/BackupConfigMigrationPage") },
  { id: "restore-execution", exportName: "BackupConfigMigrationPage", loader: () => import("../../../features/backup-config/BackupConfigMigrationPage") },
  { id: "package-governance", exportName: "PackageGovernanceScreen", loader: () => import("../../../platform/operations/governance/PackageGovernanceScreen") },
  { id: "section-management", exportName: "DesignAssetRegistryPage", loader: () => import("../../../features/design-asset-registry/DesignAssetRegistryPage") },
  { id: "builder-studio", exportName: "BuilderStudioPage", loader: () => import("../../../features/builder-studio/BuilderStudioPage") },
  { id: "component-management", exportName: "DesignAssetRegistryPage", loader: () => import("../../../features/design-asset-registry/DesignAssetRegistryPage") },
  { id: "admin-monitoring-dashboard", exportName: "MonitoringDashboardPage", loader: () => import("../../../features/admin-monitoring/MonitoringDashboardPage") },
  { id: "cron-monitoring", exportName: "CronMonitoringPage", loader: () => import("../../../features/admin-monitoring/AdminMonitoringOperationsPages") },
  { id: "db-monitoring", exportName: "DbMonitoringPage", loader: () => import("../../../features/db-monitoring/DbMonitoringPage") },
  { id: "batch-monitoring", exportName: "BatchMonitoringPage", loader: () => import("../../../features/admin-monitoring/AdminMonitoringOperationsPages") },
  { id: "git-build-monitoring", exportName: "GitBuildMonitoringPage", loader: () => import("../../../features/admin-monitoring/AdminMonitoringOperationsPages") }
] as const satisfies PageUnitsOf<typeof ADMIN_SYSTEM_ROUTE_DEFINITIONS>;

export const ADMIN_SYSTEM_FAMILY = createRouteFamily(ADMIN_SYSTEM_ROUTE_DEFINITIONS, ADMIN_SYSTEM_PAGE_UNITS, {
  familyId: "admin-system",
  pageFamily: "registry",
  ownershipLane: "SYSTEM",
  installScope: "COMMON_DEF_PROJECT_BIND",
  systemization: {
    manifestOwner: "adminSystemFamily",
    templateProfile: "admin-system-governance-suite",
    frameProfile: "admin-governed-management-layout",
    helpBinding: "admin-system.help",
    accessibilityBinding: "admin-governance-accessibility",
    securityBinding: "admin-system-route-guard"
  },
  authorityScope: {
    actorFamily: "ADMIN",
    dataScope: "GLOBAL",
    actionScopes: ["view", "create", "update", "delete", "execute", "approve", "export"],
    menuPolicy: "admin system menus follow admin governance visibility policy",
    entryPolicy: "admin-governance-only",
    queryPolicy: "system, external, monitoring, and backup queries stay inside admin governance scope",
    actionPolicy: "system/external/backup mutations require the same admin governance guard",
    approvalPolicy: "approval and execution escalation stay inside admin governance flow",
    auditPolicy: "admin system deny and execute paths emit governance audit evidence",
    tracePolicy: "system, external, monitoring, and backup traces stay correlated by pageId",
    denyState: "admin-governance-denied-state"
  },
  commonDefinition: {
    owner: "app/routes/families/adminSystemFamily",
    artifacts: ["route family definition", "admin system page manifests", "admin system validator", "system governance trace baseline"]
  },
  projectBinding: {
    owner: "admin system menu and route placement binding",
    menuBinding: "admin system menu binding",
    routeBinding: "admin system route binding",
    authorityBinding: "admin governance authority narrowing",
    themeBinding: "admin governance presentation binding"
  },
  projectExecutor: {
    owner: "system/external/backup project executor",
    responsibilities: ["system execution", "external integration execution", "backup and restore execution"]
  },
  installDeploy: {
    packagingOwnerPath: "frontend/src/app/routes/families",
    assemblyOwnerPath: "frontend/src/app/routes/families/allRouteFamilies.ts",
    bootstrapPayloadTarget: "/admin/system/code",
    bindingInputs: ["admin system menu binding", "route ownership", "authority narrowing", "integration endpoint selection"],
    validatorChecks: ["system manifest linked", "authority scope aligned", "runtime target known", "monitoring/backup evidence linked"],
    runtimeVerificationTarget: "/admin/system/code",
    compareTarget: "/admin/external/monitoring",
    deploySequence: "frontend build -> package -> restart-18000 -> admin system route verify",
    freshnessVerificationSequence: "npm run build -> package -> restart-18000 -> codex freshness verify -> admin system route verify",
    validator: "admin-system route family aggregate validator",
    rollbackEvidence: "system governance compare and backup evidence",
    auditTrace: "admin system governance and monitoring trace linkage"
  },
  pageContracts: buildManifestBackedRoutePageContracts(ADMIN_SYSTEM_ROUTE_DEFINITIONS, {
    familyId: "admin-system",
    manifestRoot: "adminSystemFamily.manifest",
    menuCodePrefix: "ADMIN_SYSTEM",
    validator: "admin-system route family aggregate validator",
    rollbackEvidence: "system governance compare and backup evidence"
  }),
  pageSystemizationCloseout:
    "CLOSED: page systemization is complete for admin-system; identity, authority scope, contracts, project binding, validator checks, and runtime verification target are explicit.",
  authorityScopeApplicationCloseout:
    "CLOSED: authority scope is consistently applied for admin-system; menu, entry, query, action, approval, audit, and trace surfaces follow the same governed policy.",
  builderInstallDeployCloseout:
    "CLOSED: builder install and deploy closeout is complete for admin-system; install inputs, project bindings, packaging source of truth, runtime target, and evidence surfaces are explicit.",
  projectBindingPatternsCloseout:
    "CLOSED: project binding is explicit for admin-system; common definition, project binding, and project executor lines are separately traceable."
});
