import { useState } from 'react';

type Row = Record<string, any>;
const BASE='/admin/api/system/actor-process';
async function request(path:string,body?:Row){
 const response=await fetch(BASE+path,{credentials:'include',method:body?'POST':'GET',headers:{Accept:'application/json',...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
 if(!(response.headers.get('content-type')||'').includes('application/json'))throw new Error('로그인 상태 또는 API 연결을 확인해 주세요. 입력은 보존됩니다.');
 const data=await response.json();if(!response.ok||data.success===false)throw new Error(response.status===409?'다른 수정이 먼저 저장됐습니다. 입력을 보존했습니다. 최신 정의를 확인해 주세요.':data.message||`저장 실패 (${response.status})`);return data;
}
export function ProcessStructureEditor({processCode,stepCode,onSaved}:{processCode:string;stepCode:string;onSaved:()=>Promise<unknown>}){
 const [mode,setMode]=useState<'process'|'step'|'add'|null>(null),[draft,setDraft]=useState<Row>({}),[version,setVersion]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState('');
 const open=async(next:'process'|'step'|'add')=>{setBusy(true);setError('');setSaved('');try{const d=await request(`/processes/${encodeURIComponent(processCode)}/structure`);setVersion(d.process.processVersion);setDraft(next==='process'?d.process:next==='add'?{stepCode:'',stepName:'',stepOrder:d.steps.length+1,actorCode:'',fromState:'',commandCode:'',toState:'',completionRule:'',inputContract:'{}',outputContract:'{}'}:d.steps.find((s:Row)=>s.stepCode===stepCode)||{});setReason('');setMode(next);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const fields=mode==='process'?[['processName','프로세스명'],['goal','업무 목적'],['startCondition','시작 조건'],['completionCondition','완료 조건']]:[['stepName','절차명'],['stepOrder','절차 순서'],['actorCode','담당 역할 코드'],['fromState','진입 상태'],['commandCode','실행 명령'],['toState','완료 상태'],['completionRule','완료 조건']];
 const save=async()=>{if(busy)return;setBusy(true);setError('');try{const changes=Object.fromEntries(fields.map(([key])=>[key,key==='stepOrder'?Number(draft[key]):draft[key]]));if(mode==='add'){changes.stepCode=draft.stepCode;changes.inputContract=draft.inputContract;changes.outputContract=draft.outputContract;JSON.parse(draft.inputContract);JSON.parse(draft.outputContract);}const result=await request(`/processes/${encodeURIComponent(processCode)}/structure`,{mode,stepCode:mode==='add'?draft.stepCode:stepCode,expectedProcessVersion:version,revisionReason:reason,changes});await onSaved();setSaved(`공식 저장 완료 · 설계 v${result.processVersion}`);setMode(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <div className="structure-editor"><div className="structure-actions"><button disabled={busy||!processCode} onClick={()=>void open('process')}>프로세스 편집</button><button disabled={busy||!stepCode} onClick={()=>void open('step')}>절차 편집·순서 변경</button><button disabled={busy||!processCode} onClick={()=>void open('add')}>＋ 절차 추가</button></div>{error&&<p role="alert">{error}</p>}{saved&&<p role="status">{saved}</p>}{mode&&<div className="structure-backdrop"><section role="dialog" aria-modal="true" aria-label="프로세스·절차 구조 편집" className="structure-dialog"><header><h2>{mode==='process'?'프로세스 편집':mode==='add'?'절차 추가':'절차 편집·순서 변경'}</h2><button disabled={busy} onClick={()=>setMode(null)}>닫기</button></header><p>{processCode} · 설계 v{version} · 프로세스 활성 상태·접근 권한은 직접 수정하지 않습니다.</p><form onSubmit={e=>{e.preventDefault();void save();}}>{mode==='add'&&<label>새 절차 코드<input required pattern="[A-Z][A-Z0-9_]{1,79}" value={draft.stepCode||''} onChange={e=>setDraft({...draft,stepCode:e.target.value})}/></label>}{fields.map(([key,label])=><label key={key}>{label}<input required type={key==='stepOrder'?'number':'text'} min={key==='stepOrder'?1:undefined} value={draft[key]??''} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}{mode==='add'&&(['inputContract','outputContract'] as const).map(key=><label key={key}>{key==='inputContract'?'입력 계약 JSON':'출력 계약 JSON'}<textarea required value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}<label>변경 사유<textarea required value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<p>저장은 공식 정의를 변경합니다. 실제 업무 정의를 테스트용으로 저장하지 마세요. 순서는 화면 이동 연결과 별개입니다.</p><button type="submit" disabled={busy||!reason.trim()||!version}>{busy?'저장·재조회 중…':'공식 저장 후 재조회'}</button></form></section></div>}</div>;
}
