import { useEffect, useRef, useState } from 'react';
import { fetchNewPagePage, fetchFunctionManagementPage } from '../../lib/api/platform';
import type { NewPagePagePayload } from '../../lib/api/platformTypes';
import { submitFormRequest } from '../admin-system/adminSystemShared';
import { buildScreenBuilderPath } from '../screen-builder/screenBuilderPaths';
import { canonicalScreenPath } from '../screen-builder/shared/publishedScreen';

type Binding={routePath?:unknown;screenName?:unknown};
const safe=(v:unknown):v is string=>typeof v==='string'&&v.startsWith('/')&&!v.startsWith('//')&&!v.includes('\\');
export function StepResourcesPanel({processCode,stepCode,bindings,onPageSelected}:{processCode:string;stepCode:string;bindings:Binding[];onPageSelected?:(route:string)=>void}){
 const routes=bindings.filter((b,i,a)=>safe(b.routePath)&&a.findIndex(x=>x.routePath===b.routePath)===i);
 const [opened,setOpened]=useState(false),[route,setRoute]=useState(''),[page,setPage]=useState<NewPagePagePayload>(),[features,setFeatures]=useState<Record<string,unknown>[]>([]),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [code,setCode]=useState(''),[name,setName]=useState(''),[description,setDescription]=useState('');
 const flight=useRef(false);
 useEffect(()=>{if(!opened||!route)return;let current=true;setLoading(true);setPage(undefined);setFeatures([]);setError('');setMessage('');setCode('');setName('');setDescription('');
  (async()=>{try{const p=await fetchNewPagePage(route);if(!p.menuCode||!p.pageId||canonicalScreenPath(p.canonicalMenuUrl||'')!==canonicalScreenPath(route))throw new Error('선택한 화면과 공식 메뉴·페이지 연결이 일치하지 않습니다.');const data=await fetchFunctionManagementPage({menuType:route.startsWith('/admin/')?'ADMIN':'USER',searchMenuCode:p.menuCode});if(current){setPage(p);setFeatures((data.featureRows||[]).filter(r=>r.menuCode===p.menuCode));}}catch(e){if(current)setError(e instanceof Error?e.message:'연결 조회 실패');}finally{if(current)setLoading(false);}})();return()=>{current=false;};
 },[opened,route,processCode,stepCode]);
 async function save(form:HTMLFormElement){if(flight.current||!page)return;flight.current=true;setSaving(true);setError('');setMessage('');try{await submitFormRequest(form);const data=await fetchFunctionManagementPage({menuType:route.startsWith('/admin/')?'ADMIN':'USER',searchMenuCode:page.menuCode});const rows=(data.featureRows||[]).filter(r=>r.menuCode===page.menuCode);setFeatures(rows);if(!rows.some(r=>r.featureCode===code&&r.featureNm===name))throw new Error('저장 요청 후 등록 결과를 확인하지 못했습니다. 입력을 유지합니다. 재등록 전에 공식 기능 목록을 확인하세요.');setMessage(`기능 ${code} 저장·재조회 완료. 권한 부여와 코드 구현은 별도입니다.`);}catch(e){setError(e instanceof Error?e.message:'저장 실패');}finally{flight.current=false;setSaving(false);}}
 return <section className="step-resources" aria-label="선택 절차 페이지·기능·권한"><button className="studio-edit" onClick={()=>{setOpened(!opened);if(!route&&routes[0])setRoute(String(routes[0].routePath));}} aria-expanded={opened}>페이지·기능·권한 연결 ({routes.length}개 화면)</button>{opened&&<div className="resource-content"><p>{processCode} / {stepCode} · 공식 메뉴와 기능 정의를 조회합니다.</p>{!routes.length?<p>연결된 화면이 없습니다. 화면 연결 정의가 먼저 필요합니다.</p>:<><label>연결 페이지<select value={route} disabled={saving} onChange={e=>{setRoute(e.target.value);onPageSelected?.(e.target.value);}}>{routes.map(r=><option key={String(r.routePath)} value={String(r.routePath)}>{String(r.screenName||r.routePath)}</option>)}</select></label>{loading&&<p role="status">페이지·기능·권한 조회 중…</p>}{error&&<p role="alert">{error}</p>}{page&&!loading&&<><dl><dt>페이지 / 메뉴</dt><dd>{page.pageId} / {page.menuCode}</dd><dt>조회에 필요한 기능</dt><dd>{page.requiredViewFeatureCode||'미확인'}</dd></dl><div className="structure-actions"><a href={route} target="_blank" rel="noreferrer">실제 화면 열기 ↗</a><a href={buildScreenBuilderPath({menuCode:page.menuCode,pageId:page.pageId,menuUrl:page.canonicalMenuUrl,menuTitle:page.menuName})}>공식 화면 설계 편집</a><a href={'/admin/system/feature-management?'+new URLSearchParams({menuType:route.startsWith('/admin/')?'ADMIN':'USER',searchMenuCode:page.menuCode!})}>전체 기능 편집</a><a href="/admin/auth/group">권한 그룹 편집</a></div><h3>이 페이지의 기능 {features.length}개</h3><ul>{features.map(f=><li key={String(f.featureCode)}>{String(f.featureNm||f.featureCode)} · {String(f.featureCode)} · 사용 {String(f.useAt||'미확인')}</li>)}</ul>{!features.length&&<p>조회된 기능이 없습니다. 구현 완료를 뜻하지 않습니다.</p>}<h3>조회 권한 그룹</h3><ul>{(page.roleAssignments||[]).map((r,i)=><li key={String(r.authorCode||i)}>{String(r.authorName||r.authorCode||'미확인')} · {r.assigned===true?'조회 권한 연결':r.assigned===false?'조회 권한 미연결':'연결 여부 미확인'}</li>)}</ul>{!page.roleAssignments?.length&&<p>권한 그룹 정보 미제공</p>}<p>이 목록은 VIEW 권한입니다. 생성·수정·삭제 권한과 실제 서버 허용 여부는 별도 검증 대상입니다.</p><details><summary>이 페이지에 기능 등록</summary><form action="/admin/system/feature-management/create" method="post" onSubmit={e=>{e.preventDefault();void save(e.currentTarget);}}><input type="hidden" name="menuType" value={route.startsWith('/admin/')?'ADMIN':'USER'}/><input type="hidden" name="menuCode" value={page.menuCode}/><input type="hidden" name="useAt" value="Y"/><label>기능 코드<input required name="featureCode" pattern="[A-Z][A-Z0-9_]+" value={code} onChange={e=>setCode(e.target.value)}/></label><label>기능명<input required name="featureNm" value={name} onChange={e=>setName(e.target.value)}/></label><label>기능 설명<input required name="featureDc" value={description} onChange={e=>setDescription(e.target.value)}/></label><button disabled={saving||!code.trim()||!name.trim()||!description.trim()}>{saving?'저장·재조회 중…':'기능 정의 저장'}</button></form></details>{message&&<p role="status">{message}</p>}</>}</>}</div>}</section>;
}
