import { useMemo, useState } from "react";
import { BoundScreenActions } from "./BoundScreenActions";

type Row = Record<string, unknown>;
export type WorkDesignView = "list" | "flow" | "screens" | "compare";
type ViewId = WorkDesignView;
type Props = {
  initialView?: WorkDesignView;
  rows: { type: Row; process: Row; step: Row }[];
  processes: Row[];
  selectedProcessCode: string;
  selectedStepCode: string;
  flowEdges: Row[];
  flowError: string;
  revisionHistory: Row[];
  revisionLoading: boolean;
  revisionError: string;
  onViewChange: (view: ViewId) => void;
  onProcessSelect: (processCode: string) => void;
  onStepSelect: (processCode: string, stepCode: string) => void;
  onEdit: (processCode: string, stepCode: string) => void;
};

const text = (row: Row | undefined, ...keys: string[]) => {
  for (const key of keys) if (row?.[key] != null) return String(row[key]);
  return "";
};
const list = (value: unknown): Row[] => Array.isArray(value) ? value.filter(item => item && typeof item === "object") as Row[] : [];
const pretty = (value: unknown) => {
  if (value == null || value === "") return "정의 없음";
  if (typeof value === "string") { try { return JSON.stringify(JSON.parse(value), null, 2); } catch { return value; } }
  return JSON.stringify(value, null, 2);
};
const views: [ViewId, string][] = [["list", "목록"], ["flow", "업무 흐름"], ["screens", "화면 지도"], ["compare", "변경 비교"]];

export function WorkDesignViews(props: Props) {
  const [view, setView] = useState<ViewId>(props.initialView || "list");
  const selected = props.rows.find(row => text(row.process, "processCode") === props.selectedProcessCode && text(row.step, "stepCode") === props.selectedStepCode);
  const selectedProcess = props.processes.find(row => text(row, "processCode") === props.selectedProcessCode);
  const steps = useMemo(() => props.rows.filter(row => text(row.process, "processCode") === props.selectedProcessCode).map(row => row.step), [props.rows, props.selectedProcessCode]);
  const bindings = selected ? list(selected.step.screenBindings) : [];
  const gaps = useMemo(() => props.rows.flatMap(({ type, process, step }) => {
    const problems: string[] = [];
    if (!list(step.screenBindings).length) problems.push("화면 바인딩 없음");
    if (!text(step, "actorCode")) problems.push("담당 역할 미확인");
    if (!text(step, "completionRule")) problems.push("완료 조건 미확인");
    if (!text(step, "inputContract")) problems.push("입력 계약 미확인");
    if (!text(step, "outputContract")) problems.push("출력 계약 미확인");
    return problems.map(issue => ({ type, process, step, issue }));
  }), [props.rows]);
  const changeView = (next: ViewId) => { setView(next); props.onViewChange(next); };

  return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm" aria-label="업무 설계 지도">
    <nav className="flex flex-wrap gap-2 border-b bg-slate-50 p-3" aria-label="업무 설계 보기">
      {views.map(([id, label]) => <button key={id} type="button" aria-pressed={view === id} onClick={() => changeView(id)} className={`min-h-10 rounded-lg border px-4 text-sm font-black ${view === id ? "border-blue-700 bg-[#052b57] text-white" : "border-slate-300 bg-white text-slate-700 hover:border-blue-400"}`}>{label}</button>)}
      <span className="ml-auto self-center text-xs text-slate-500">모든 보기는 현재 정의 카탈로그 기준</span>
    </nav>
    <div className="grid min-h-[430px] xl:grid-cols-[230px_minmax(0,1fr)_310px]">
      <aside className="max-h-[620px] overflow-y-auto border-b bg-slate-50 p-3 xl:border-b-0 xl:border-r" aria-label="업무 탐색">
        {(Array.from(new Set(props.rows.map(row => text(row.type, "workTypeCode"))))).map(typeCode => {
          const group = props.rows.filter(row => text(row.type, "workTypeCode") === typeCode);
          const type = group[0]?.type;
          return <details key={typeCode} open className="mb-3 rounded-lg border border-slate-200 bg-white">
            <summary className="cursor-pointer px-3 py-2 text-sm font-black text-[#052b57]">{text(type, "workTypeName") || typeCode}<span className="ml-2 text-xs font-normal text-slate-500">{typeCode}</span></summary>
            <div className="space-y-1 px-2 pb-2">{Array.from(new Map(group.map(row => [text(row.process, "processCode"), row.process])).values()).map(process => <button key={text(process, "processCode")} type="button" onClick={() => props.onProcessSelect(text(process, "processCode"))} className={`w-full rounded-md px-2 py-2 text-left text-xs ${text(process, "processCode") === props.selectedProcessCode ? "bg-blue-100 font-black text-blue-900" : "hover:bg-slate-100"}`}>
              <span className="block">{text(process, "processName") || text(process, "processCode")}</span><span className="mt-1 block text-[10px] text-slate-500">{text(process, "processCode")} · v{text(process, "processVersion") || "미확인"}</span>
            </button>)}</div>
          </details>;
        })}
      </aside>
      <main className="min-w-0 overflow-x-auto p-4 sm:p-5">
        <header className="mb-4"><p className="text-xs font-black uppercase tracking-wide text-blue-700">{text(selected?.type, "workTypeName")}</p><h2 className="mt-1 text-xl font-black text-[#052b57]">{text(selectedProcess, "processName") || "업무 정의를 선택하세요"}</h2><p className="mt-1 text-sm text-slate-600">{text(selectedProcess, "goal") || "프로세스 목적은 현재 카탈로그 응답에 없거나 미확인입니다."}</p></header>
        {view === "list" && <div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-100"><tr>{["순서·절차", "담당 역할", "상태 전이", "연결 화면", "계약"].map(label => <th key={label} className="p-3">{label}</th>)}</tr></thead><tbody>{props.rows.filter(row => text(row.process, "processCode") === props.selectedProcessCode).map(({ step }) => { const routes = list(step.screenBindings); return <tr key={text(step,"stepCode")} className={`border-t align-top ${text(step,"stepCode")===props.selectedStepCode?"bg-blue-50":""}`}><td className="p-3"><button type="button" onClick={() => props.onStepSelect(props.selectedProcessCode,text(step,"stepCode"))} className="text-left font-bold text-blue-800 underline">{text(step,"stepOrder")}. {text(step,"stepName")}</button><small className="block text-slate-500">{text(step,"stepCode")}</small></td><td className="p-3">{text(step,"actorCode")||"미확인"}</td><td className="p-3">{[text(step,"fromState"),text(step,"commandCode"),text(step,"toState")].filter(Boolean).join(" → ")||"전이 미확인"}<small className="mt-1 block text-slate-500">{text(step,"decisionRule")||"분기 조건 미확인"}</small></td><td className="p-3">{routes.length?routes.map((binding,index)=><div key={`${text(binding,"routePath")}-${index}`} className="mb-2"><a className="block text-blue-700 underline" href={text(binding,"routePath").startsWith("/")?text(binding,"routePath"):undefined}>{text(binding,"screenName")||text(binding,"routePath")||"경로 미확인"}</a><BoundScreenActions routePath={text(binding,"routePath")} screenName={text(binding,"screenName")||text(binding,"routePath")} /></div>):<span className="text-amber-800">MISSING_BINDING</span>}</td><td className="p-3"><button type="button" className="rounded border px-2 py-1 font-bold" onClick={() => props.onEdit(props.selectedProcessCode,text(step,"stepCode"))}>계약 보기·편집</button></td></tr>; })}{!steps.length&&<tr><td colSpan={5} className="p-8 text-center text-slate-500">등록된 절차가 없습니다.</td></tr>}</tbody></table></div>}
        {view === "flow" && <div role="region" className="space-y-3" aria-label="업무 흐름도">{steps.map((step,index)=><div key={text(step,"stepCode")} className="grid gap-2 md:grid-cols-[1fr_170px]"><button type="button" onClick={() => props.onStepSelect(props.selectedProcessCode,text(step,"stepCode"))} className={`rounded-xl border p-4 text-left ${text(step,"stepCode")===props.selectedStepCode?"border-blue-600 bg-blue-50":"border-slate-200 bg-white"}`}><div className="flex flex-wrap items-center justify-between gap-2"><strong>{text(step,"stepOrder")}. {text(step,"stepName")}</strong><span className="text-xs text-slate-500">{text(step,"stepCode")}</span></div><p className="mt-2 text-sm">{text(step,"fromState")||"시작 상태 미확인"} → {text(step,"commandCode")||"명령 미확인"} → {text(step,"toState")||"종료 상태 미확인"}</p><p className="mt-1 text-xs text-slate-600">담당: {text(step,"actorCode")||"미확인"} · 완료: {text(step,"completionRule")||"미확인"}</p>{text(step,"decisionRule")&&<p className="mt-2 rounded bg-amber-50 p-2 text-xs text-amber-900">분기·보완 규칙: {text(step,"decisionRule")}</p>}</button><div className="rounded-xl bg-slate-50 p-3 text-xs"><strong>연결 화면</strong>{list(step.screenBindings).map((binding,i)=><a key={i} className="mt-2 block text-blue-700 underline" href={text(binding,"routePath").startsWith("/")?text(binding,"routePath"):undefined}>{text(binding,"routePath")||"미연결"}</a>)}</div>{index<steps.length-1&&<div className="col-span-full pl-6 text-xl font-black text-slate-400" aria-label="순차 진행">↓</div>}</div>)}{!steps.length&&<p className="p-8 text-center text-slate-500">업무 흐름 정의가 없습니다.</p>}<section className="rounded-xl border border-blue-200 p-4"><h3 className="font-black text-[#052b57]">정본 분기·보완 연결</h3>{props.flowError?<p role="alert" className="mt-2 text-sm text-red-800">{props.flowError}</p>:props.flowEdges.length?<ul className="mt-2 space-y-2">{props.flowEdges.filter(edge=>!text(edge,"processCode")||text(edge,"processCode")===props.selectedProcessCode).map((edge,index)=><li key={`${text(edge,"edgeId")}-${index}`} className="rounded-lg bg-slate-50 p-3 text-sm"><strong>{text(edge,"fromStepName")||text(edge,"fromStepCode")} → {text(edge,"toStepName")||text(edge,"toStepCode")}</strong><span className="ml-2 rounded-full bg-blue-100 px-2 py-1 text-xs">{text(edge,"edgeType")||"유형 미확인"}</span><p className="mt-1 text-xs text-slate-600">조건: {text(edge,"conditionContract")||text(edge,"conditionCode")||"조건 미정의"} · 역할: {text(edge,"actorCode")||"미확인"} · 검토: {text(edge,"reviewStatus")||"미확인"}</p></li>)}</ul>:<p className="mt-2 text-sm text-amber-900">정본 Flow Edge가 없습니다. 절차 순번만으로 분기·보완 경로를 추정하지 않습니다.</p>}</section></div>}
        {view === "screens" && <div role="region" className="space-y-3" aria-label="화면 연결 지도">{steps.flatMap(step => list(step.screenBindings).map(binding => ({step,binding}))).map(({step,binding},index)=><article key={`${text(step,"stepCode")}-${text(binding,"routePath")}-${index}`} className="grid gap-3 rounded-xl border border-slate-200 p-4 md:grid-cols-[minmax(0,1fr)_180px_minmax(0,1fr)]"><div><p className="text-xs font-bold text-slate-500">절차</p><button type="button" onClick={()=>props.onStepSelect(props.selectedProcessCode,text(step,"stepCode"))} className="mt-1 text-left font-black text-blue-800 underline">{text(step,"stepName")} · {text(step,"stepCode")}</button></div><div className="flex items-center justify-center text-sm font-black text-slate-400">화면 연결 →</div><div><p className="text-xs font-bold text-slate-500">{text(binding,"audience")||"대상 미확인"} · {text(binding,"implementationStatus")||"구현 상태 미확인"}</p><a href={text(binding,"routePath").startsWith("/")?text(binding,"routePath"):undefined} className="mt-1 block break-all font-bold text-blue-700 underline">{text(binding,"screenName")||text(binding,"routePath")||"경로 미확인"}</a><p className="mt-1 break-all font-mono text-xs text-slate-500">Route: {text(binding,"routePath")||"경로 미확인"}</p><p className="mt-1 text-xs text-slate-600">API: {text(binding,"apiContract")||text(step,"apiContract")||"미확인"}</p></div><div className="md:col-span-3 grid gap-2 border-t pt-3 sm:grid-cols-2"><ContractPreview title="입력·인계" value={step.inputContract}/><ContractPreview title="출력·인계" value={step.outputContract}/></div></article>)}{!steps.some(step=>list(step.screenBindings).length>0)&&<p className="rounded-xl border border-dashed p-8 text-center text-amber-800">이 프로세스에는 화면 바인딩이 없습니다.</p>}<p className="rounded-lg bg-slate-50 p-3 text-xs text-slate-600">화면 바인딩은 연결 증거입니다. 사용자 화면의 실제 API 실행·권한·저장 확인과 별도로 판단해야 합니다.</p></div>}
        {view === "compare" && <div role="region" className="space-y-4" aria-label="설계 변경 비교"><div className="grid gap-3 sm:grid-cols-3"><Metric label="현재 정의 버전" value={text(selectedProcess,"processVersion")||text(selectedProcess,"version")||"미제공"}/><Metric label="조회된 Revision 이력" value={props.revisionLoading?"조회 중":String(props.revisionHistory.length)}/><Metric label="프로세스 구조 해시" value={text(selectedProcess,"structureHash")||"카탈로그 응답에 미제공"}/></div>{props.revisionError?<div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800">Revision 이력 조회 실패: {props.revisionError}</div>:props.revisionHistory.length?<><div role="status" className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-950">Revision 변경이 확인되었습니다. 테스트 결과가 해당 프로세스 버전에 묶여 있는지 아직 검증하지 않았으므로 관련 테스트는 재검증 필요로 표시합니다.</div><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-100"><tr>{["시각", "절차", "변경", "사유·담당", "버전 변화", "변경 필드", "영향 화면·테스트"].map(item=><th key={item} className="p-3">{item}</th>)}</tr></thead><tbody>{props.revisionHistory.map((entry,index)=>{const affected=props.rows.find(row=>text(row.process,"processCode")===props.selectedProcessCode&&text(row.step,"stepCode")===text(entry,"stepCode"));return <tr key={`${text(entry,"stepCode")}-${text(entry,"createdAt")}-${index}`} className="border-t"><td className="p-3">{text(entry,"createdAt")||"미제공"}</td><td className="p-3">{text(entry,"stepCode")||"프로세스"}</td><td className="p-3">{text(entry,"changeType")||"UPDATE"}</td><td className="p-3">{text(entry,"revisionReason")}<small className="block">{text(entry,"actor")}</small></td><td className="p-3">{text(entry,"beforeProcessVersion")} → {text(entry,"afterProcessVersion")}</td><td className="p-3">{pretty(entry.changedFields)}</td><td className="p-3"><span className="block">테스트 재검증 필요</span>{list(affected?.step.screenBindings).map((binding,routeIndex)=><a className="mt-1 block break-all text-blue-700 underline" key={routeIndex} href={text(binding,"routePath").startsWith("/")?text(binding,"routePath"):undefined}>{text(binding,"routePath")||"화면 경로 미확인"}</a>)}</td></tr>;})}</tbody></table></div></>:<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><strong>변경 이력 데이터가 없습니다.</strong><p className="mt-1">현재 버전 숫자만으로 과거 변경을 만들어내지 않습니다.</p></div>}<div className="rounded-xl border p-4"><h3 className="font-black">변경 영향 확인 기준</h3><p className="mt-1 text-sm text-slate-600">실제 Revision 응답의 변경 필드와 snapshot을 기준으로 영향받는 화면·API·테스트를 대조합니다. 증거가 없는 구현·테스트 상태는 미확인으로 남습니다.</p></div></div>}
      </main>
      <aside className="border-t bg-slate-50 p-4 xl:border-l xl:border-t-0" aria-label="선택 항목 상세">
        <h3 className="text-lg font-black text-[#052b57]">선택 절차</h3>{selected?<><p className="mt-2 text-sm font-bold">{text(selected.step,"stepName")}</p><p className="text-xs text-slate-500">{text(selected.step,"stepCode")}</p><dl className="mt-4 space-y-3 text-sm"><Info label="순서" value={`${text(selected.type,"businessOrder")||"?"} · ${text(selected.process,"processOrder")||"?"} · ${text(selected.step,"stepOrder")||"?"}`}/><Info label="담당 역할" value={text(selected.step,"actorCode")||"미확인"}/><Info label="상태 전이" value={`${text(selected.step,"fromState")||"?"} → ${text(selected.step,"commandCode")||"?"} → ${text(selected.step,"toState")||"?"}`}/><Info label="설계 확인" value={text(selected.step,"designStatus")||"미확인"}/><Info label="구현 확인" value={text(selected.step,"implementationStatus")||"바인딩 상태만 별도 확인"}/><Info label="자동 테스트" value={text(selected.step,"testStatus")||"미확인"}/><Info label="실제 업무 흐름" value={text(selected.step,"runtimeStatus")||"미확인"}/></dl><div className="mt-4 grid gap-2">{bindings.map((binding,index)=><a key={index} className="rounded-lg border bg-white px-3 py-2 text-sm font-bold text-blue-700 underline" href={text(binding,"routePath").startsWith("/")?text(binding,"routePath"):undefined}>{text(binding,"screenName")||text(binding,"routePath")||"경로 미확인"}</a>)}<button type="button" className="rounded-lg bg-[#052b57] px-3 py-2 text-sm font-bold text-white" onClick={()=>props.onEdit(props.selectedProcessCode,props.selectedStepCode)}>공식 Revision 계약 편집</button></div></>:<p className="mt-3 text-sm text-slate-600">절차를 선택하면 입력·출력·상태·화면 연결을 표시합니다.</p>}
      </aside>
    </div>
    <section className="border-t bg-white p-4" aria-label="설계 확인 필요 항목"><div className="flex flex-wrap items-baseline justify-between gap-2"><h3 className="font-black text-[#052b57]">추가 확인이 필요한 설계 항목</h3><span className="text-xs text-slate-500">정의 데이터의 빈 칸을 집계하며 업무 오류로 단정하지 않습니다.</span></div><div className="mt-3 flex flex-wrap gap-2">{Array.from(new Set(gaps.map(item=>item.issue))).map(issue=><span key={issue} className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-900">{issue} · {gaps.filter(item=>item.issue===issue).length}</span>)}{!gaps.length&&<span className="text-sm text-emerald-700">현재 카탈로그 응답에서 빈 필드를 찾지 못했습니다.</span>}</div></section>
  </section>;
}

function ContractPreview({title,value}:{title:string;value:unknown}) { return <details className="min-w-0 rounded-lg bg-slate-50 p-3"><summary className="cursor-pointer text-xs font-black">{title}</summary><pre className="mt-2 max-h-48 overflow-auto whitespace-pre-wrap break-words text-[11px] leading-5 text-slate-700">{pretty(value)}</pre></details>; }
function Info({label,value}:{label:string;value:string}) { return <div><dt className="text-xs font-bold text-slate-500">{label}</dt><dd className="mt-1 break-words font-medium text-slate-800">{value}</dd></div>; }
function Metric({label,value}:{label:string;value:string}) { return <article className="rounded-xl border bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><strong className="mt-1 block break-all">{value}</strong></article>; }
