import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
const source = readFileSync(new URL('../src/features/actor-process-governance/workflowComparison.ts', import.meta.url), 'utf8');
const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ES2022, target: ts.ScriptTarget.ES2022 } }).outputText;
const { compareDefinitions } = await import(`data:text/javascript;base64,${Buffer.from(compiled).toString('base64')}`);
const process = { processCode: 'FIXTURE_A', processName: 'Fixture', domainCode: 'TEST' };
const step = { processCode: 'FIXTURE_A', stepCode: 'S1', stepName: 'Step', stepOrder: 1, actorCode: 'TEST', fromState: 'DRAFT', commandCode: 'GO', toState: 'DONE', inputContract: 'Input', outputContract: 'Output', completionRule: 'Done' };
test('matching process', () => assert.equal(compareDefinitions([process], [{...process}], false)[0].status, 'MATCH'));
test('matching complete step', () => assert.equal(compareDefinitions([step], [{...step}], true)[0].status, 'MATCH'));
test('changed contract detected', () => assert.deepEqual(compareDefinitions([step], [{...step, inputContract:'Changed'}], true)[0].differences, ['inputContract']));
test('missing management definition', () => assert.equal(compareDefinitions([process], [], false)[0].status, 'MISSING_IN_MANAGEMENT'));
test('management-only is scope review, not deletion', () => assert.equal(compareDefinitions([], [process], false)[0].status, 'MANAGEMENT_ONLY_SCOPE_REVIEW'));
test('duplicate management key', () => assert.equal(compareDefinitions([step], [step, {...step}], true)[0].status, 'DUPLICATE'));
test('duplicate reference key', () => assert.equal(compareDefinitions([step, {...step}], [step], true)[1].status, 'DUPLICATE'));
test('same step code in different processes stays separate', () => assert.equal(compareDefinitions([step, {...step, processCode:'FIXTURE_B'}], [step, {...step, processCode:'FIXTURE_B'}], true).filter(r => r.status === 'MATCH').length, 2));
test('missing contract field cannot match', () => { const incomplete = {...step}; delete incomplete.inputContract; assert.notEqual(compareDefinitions([incomplete], [incomplete], true)[0].status, 'MATCH'); });
test('comparison does not change source arrays', () => { const before = JSON.stringify(step); compareDefinitions([step], [step], true); assert.equal(JSON.stringify(step), before); });
