const STATE_CLASSES=new Set(['PROCESS','PROCESS_STATE','FLOW','MATERIAL_FLOW','STATE','OPERATION_STATE','MATERIAL_STATE','ENERGY_STATE','SAFETY_STATE','MAINTENANCE_STATE','QUALITY_STATE','SIGNAL_STATE','CAPACITY_STATE','AVAILABILITY_STATE','ALARM_STATE']);
const COLOR={WARNING:0xff8800,ERROR:0xff0000,ALARM:0xff0000,ACTIVE:0x00ff66,ON:0x00ff66,RUNNING:0x22cc88,AVAILABLE:0x22cc88,UNAVAILABLE:0x777777,NORMAL:0x22cc88};
function contractsFor(c){return Array.isArray(c?.contracts)?c.contracts:(c?[c]:[]);}
function captureInitialState(target){const nodes=[];target?.traverse?.(o=>{const materials=Array.isArray(o.material)?o.material:(o.material?[o.material]:[]);nodes.push({o,position:o.position?.clone?.(),quaternion:o.quaternion?.clone?.(),scale:o.scale?.clone?.(),visible:o.visible,materials:materials.map(m=>({m,color:m.color?.clone?.(),emissive:m.emissive?.clone?.(),emissiveIntensity:m.emissiveIntensity,opacity:m.opacity,transparent:m.transparent,visible:m.visible}))});});return nodes;}
function restoreInitialState(snapshot){for(const x of snapshot||[]){if(x.position&&x.o.position)x.o.position.copy(x.position);if(x.quaternion&&x.o.quaternion)x.o.quaternion.copy(x.quaternion);if(x.scale&&x.o.scale)x.o.scale.copy(x.scale);if(x.visible!==undefined)x.o.visible=x.visible;for(const z of x.materials||[]){const m=z.m;if(z.color&&m.color)m.color.copy(z.color);if(z.emissive&&m.emissive)m.emissive.copy(z.emissive);if(z.emissiveIntensity!==undefined)m.emissiveIntensity=z.emissiveIntensity;if(z.opacity!==undefined)m.opacity=z.opacity;if(z.transparent!==undefined)m.transparent=z.transparent;if(z.visible!==undefined)m.visible=z.visible;}}}
export function candidates(registry,id){return registry.assets.find(a=>a.assetId===id)?.directCompatibleAssets||[];}
export function connect(registry,source,target,rule,id){const a=registry.assets.find(a=>a.assetId===source.assetId),b=registry.assets.find(a=>a.assetId===target.assetId);const p=a?.logicalPorts?.find(x=>x.portId===rule.sourcePortId),q=b?.logicalPorts?.find(x=>x.portId===rule.targetPortId);if(!p||!q||source.id===target.id||p.direction==='INPUT'||q.direction==='OUTPUT'||p.mediumType!==q.mediumType)throw Error('SIMULATION_CONTRACT_REJECT');return {id,connectionId:id,from:source.id,to:target.id,sourceInstanceId:source.id,targetInstanceId:target.id,sourcePortId:p.portId,targetPortId:q.portId,type:p.connectionType,contractSource:'FUNCTIONAL_SIMULATION',physicalPortVerified:false};}
export class MotionController{
 constructor(){this.bindings=new Map();this.state='STOPPED';this.time=0;this.speed=1;this.calls={bind:0,play:0,pause:0,resume:0,stop:0,tick:0,cleanup:0};}
 bind(id,root,contract){this.calls.bind++;const cs=contractsFor(contract);if(!root||!cs.length)return;const items=[];for(const c of cs){const mechanical=!STATE_CLASSES.has(String(c.animationClass||'').toUpperCase());let node=root;if(mechanical&&c.targetNode)node=root.getObjectByName(c.targetNode)||root;if(!node)continue;items.push({node,c,snapshot:captureInitialState(node)});}if(items.length)this.bindings.set(id,{root,items});}
 play(){this.calls.play++;this.state='PLAYING';} pause(){this.calls.pause++;this.state='PAUSED';} resume(){this.calls.resume++;this.state='PLAYING';}
 stop(){this.calls.stop++;this.state='STOPPED';this.time=0;for(const b of this.bindings.values())for(const x of b.items)restoreInitialState(x.snapshot);}
 setSpeed(v){if(!Number.isFinite(v)||v<=0||v>10)throw Error('INVALID_SPEED');this.speed=v;}
 setState(x,state){x.node.traverse?.(o=>{if(!o.material)return;const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats){if(m.emissive?.setHex)m.emissive.setHex(COLOR[state]??COLOR.NORMAL);if(m.emissiveIntensity!=null)m.emissiveIntensity=state==='NORMAL'?0.1:0.8;}});}
 tick(dt){this.calls.tick++;if(this.state!=='PLAYING')return;if(!Number.isFinite(dt)||dt<0)throw Error('INVALID_DT');this.time+=Math.min(dt,.1)*this.speed;for(const b of this.bindings.values())for(const x of b.items){const c=x.c,cls=String(c.animationClass||'').toUpperCase();if(STATE_CLASSES.has(cls)){const states=c.states||c.contract?.states||['NORMAL','ACTIVE'];this.setState(x,states[Math.floor(this.time*2)%states.length]||'ACTIVE');continue;}if(cls==='VISUAL_MECHANICAL'&&!c.motionType){this.setState(x,'ACTIVE');continue;}if(!x.snapshot)continue;const t=c.loop?(1-Math.cos(this.time*(c.speed||1)))/2:Math.min(this.time*(c.speed||1),1),axis=Array.isArray(c.axis)?c.axis:[0,1,0],range=Array.isArray(c.range)?c.range:[0,1],v=range[0]+(range[1]-range[0])*t;x.node.position.copy(x.snapshot.find(s=>s.o===x.node)?.position||x.node.position);x.node.quaternion.copy(x.snapshot.find(s=>s.o===x.node)?.quaternion||x.node.quaternion);if(['LINEAR','CONVEYOR','ROBOT_SEQUENCE'].includes(String(c.motionType).toUpperCase())){x.node.position.x+=axis[0]*v;x.node.position.y+=axis[1]*v;x.node.position.z+=axis[2]*v;}else if(x.node.rotateOnAxis){x.node.rotateOnAxis(new x.node.position.constructor(...axis),v);}}
 }
 cleanup(){this.calls.cleanup++;this.stop();this.bindings.clear();}
}
