[Service]
ExecStart=
ExecStart=/opt/util/ai/vLLM/llama.cpp-tq3/build/bin/llama-server -m /opt/util/ai/vLLM/models/gemma4-e4b-q4_k_m/Gemma4-E4B-q4_k_m.gguf -a gemma4-e4b-gpu-shadow --host 0.0.0.0 --port 24451 --api-key qwer1234 -ngl 99 -c 8192 -np 1 -t 8 -tb 8 --threads-http 4 -ctk q4_0 -ctv q4_0 -fa on --jinja --metrics --slots
