import { useCallback, useEffect, useMemo, useState } from "react";
import { buildLocalizedPath, isEnglish } from "../../lib/navigation/runtime";
import { AdminPageShell } from "../admin-entry/AdminPageShell";

type Member={entityCode:string;entityName:string;entityType:string;countryCode:string;ownershipPercent:string;controlType:string;includedYn:string;exclusionReason:string;evidenceRef:string};
type Elimination={sourceEntityCode:string;counterpartyEntityCode:string;activityCategory:string;grossEmission:string;eliminatedEmission:string;unit:string;evidenceRef:string};
type Boundary={version?:number;boundaryMethod:string;reportingBasis:string;rationale:string;effectiveFrom:string;effectiveUntil:string;status?:string;rowVersion?:number};
type Data={project?:{id?:string;name?:string};versions?:Boundary[];members?:Member[];eliminations?:Elimination[];consolidations?:Record<string,unknown>[]};
const member=():Member=>({entityCode:"",entityName:"",entityType:"LEGAL_ENTITY",countryCode:"KR",ownershipPercent:"100",controlType:"OPERATIONAL",includedYn:"Y",exclusionReason:"",evidenceRef:""});
const elimination=():Elimination=>({sourceEntityCode:"",counterpartyEntityCode:"",activityCategory:"",grossEmission:"0",eliminatedEmission:"0",unit:"tCO2e",evidenceRef:""});
const initial:Boundary={boundaryMethod:"OPERATIONAL_CONTROL",reportingBasis:"ISO 14064-1",rationale:"",effectiveFrom:new Date().toISOString().slice(0,10),effectiveUntil:""};

export function OrganizationalBoundaryPage(){
 const en=isEnglish(),admin=location.pathname.includes("/admin/"),q=new URLSearchParams(location.search),projectId=q.get("projectId")||q.get("id")||"";
 const api=buildLocalizedPath(`/home/api/emission-projects/${encodeURIComponent(projectId)}/organizational-boundary`,`/en/home/api/emission-projects/${encodeURIComponent(projectId)}/organizational-boundary`);
 const [data,setData]=useState<Data>({}),[boundary,setBoundary]=useState<Boundary>(initial),[members,setMembers]=useState<Member[]>([member()]),[rows,setRows]=useState<Elimination[]>([]),[gross,setGross]=useState("0"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const load=useCallback(async()=>{if(!projectId){setMessage(en?"Select a project first.":"프로젝트를 먼저 선택해 주세요.");return;}try{const response=await fetch(api,{credentials:"include"}),body=await response.json();if(!response.ok)throw new Error(body.message||"LOAD_FAILED");setData(body);setBoundary(body.versions?.[0]||initial);setMembers(body.members?.length?body.members:[member()]);setRows(body.eliminations||[]);}catch(e){setMessage(e instanceof Error?e.message:String(e));}},[api,en,projectId]);
 useEffect(()=>{void load();},[load]);
 const run=async(path:string,method:string,body?:unknown)=>{setBusy(true);setMessage("");try{const response=await fetch(api+path,{method,credentials:"include",headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined}),result=await response.json();if(!response.ok||result.success===false)throw new Error(result.message||"REQUEST_FAILED");setMessage(en?"The workflow was updated.":"업무 상태가 반영되었습니다.");await load();}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 const updateMember=(i:number,k:keyof Member,v:string)=>setMembers(all=>all.map((x,n)=>n===i?{...x,[k]:v}:x)),updateRow=(i:number,k:keyof Elimination,v:string)=>setRows(all=>all.map((x,n)=>n===i?{...x,[k]:v}:x));
 const status=boundary.status||"NEW",included=members.filter(x=>x.includedYn==="Y").length,net=useMemo(()=>Number(gross||0)-rows.reduce((s,x)=>s+Number(x.eliminatedEmission||0),0),[gross,rows]),latest=data.consolidations?.[0];
 const page=<main className="min-h-screen bg-[var(--kr-gov-bg-gray,#f5f7fa)] px-4 py-6 lg:px-8"><div className="mx-auto max-w-7xl">
  <nav className="text-sm text-slate-500"><a href={buildLocalizedPath("/emission/project_list","/en/emission/project_list")}>{en?"Emission projects":"배출량 프로젝트"}</a><span className="mx-2">/</span>{en?"Organizational boundary":"조직경계 설정"}</nav>
  <header className="mt-5 rounded-2xl bg-[#06315f] p-6 text-white"><p className="text-sm font-bold text-blue-200">{data.project?.id||projectId} · {status}</p><h1 className="mt-2 text-3xl font-black">{en?"Organizational Boundary & Consolidation":"조직경계 및 연결 산정"}</h1><p className="mt-2 text-blue-100">{data.project?.name||"-"} · {en?"Govern entity inclusion, eliminations and approval in one workflow.":"법인·사업장 포함 판정부터 내부거래 제거와 승인까지 한 업무로 처리합니다."}</p></header>
  <section className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[[en?"Version":"버전",boundary.version||"-"],[en?"Status":"상태",status],[en?"Included":"포함",included],[en?"Excluded":"제외",members.length-included],[en?"Net emissions":"순 배출량",String(latest?.netEmission??net)]].map(([l,v])=><div className="gov-card rounded-xl border bg-white p-4" key={String(l)}><p className="text-sm font-bold text-slate-500">{l}</p><strong className="mt-2 block text-xl text-[#06315f]">{String(v)}</strong></div>)}</section>
  {message&&<div className="mt-4 rounded-lg border border-blue-200 bg-blue-50 p-4 font-bold text-blue-800">{message}</div>}
  <section className="gov-card mt-5 rounded-2xl border bg-white p-6"><h2 className="text-xl font-black text-[#06315f]">1. {en?"Boundary policy":"경계 정책"}</h2><div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Field label={en?"Consolidation approach":"연결 접근법"}><select className="gov-input w-full" value={boundary.boundaryMethod} onChange={e=>setBoundary({...boundary,boundaryMethod:e.target.value})}><option value="OPERATIONAL_CONTROL">{en?"Operational control":"운영 통제"}</option><option value="FINANCIAL_CONTROL">{en?"Financial control":"재무 통제"}</option><option value="EQUITY_SHARE">{en?"Equity share":"지분율"}</option></select></Field><Field label={en?"Reporting basis":"보고 기준"}><input className="gov-input w-full" value={boundary.reportingBasis} onChange={e=>setBoundary({...boundary,reportingBasis:e.target.value})}/></Field><Field label={en?"Effective from":"적용 시작일"}><input type="date" className="gov-input w-full" value={boundary.effectiveFrom} onChange={e=>setBoundary({...boundary,effectiveFrom:e.target.value})}/></Field><Field label={en?"Effective until":"적용 종료일"}><input type="date" className="gov-input w-full" value={boundary.effectiveUntil} onChange={e=>setBoundary({...boundary,effectiveUntil:e.target.value})}/></Field><label className="text-sm font-bold md:col-span-2 lg:col-span-4">{en?"Decision rationale":"선정 근거"}<textarea className="gov-input mt-2 min-h-24 w-full" value={boundary.rationale} onChange={e=>setBoundary({...boundary,rationale:e.target.value})}/></label></div></section>
  <section className="gov-card mt-5 rounded-2xl border bg-white p-4 sm:p-6"><Title text={`2. ${en?"Entities and sites":"법인·사업장 포함 판정"}`} action={()=>setMembers(x=>[...x,member()])} actionText={en?"Add entity":"대상 추가"}/><div className="mt-4 overflow-x-auto rounded-xl border"><table className="w-full min-w-[1120px] table-fixed text-sm"><thead><tr className="bg-slate-100 text-left">{(en?["Code","Entity / Site","Type","Country","Ownership %","Control","Include","Exclusion reason","Evidence",""]:["코드","법인·사업장","유형","국가","지분율(%)","통제 유형","포함 여부","제외 사유","증빙","관리"]).map(x=><th className="break-keep p-3 align-middle" key={x}>{x}</th>)}</tr></thead><tbody>{members.map((x,i)=><tr className="border-b last:border-b-0" key={i}>{(["entityCode","entityName","entityType","countryCode","ownershipPercent","controlType","includedYn","exclusionReason","evidenceRef"] as (keyof Member)[]).map(k=><td className="p-1 align-middle" key={k}>{k==="includedYn"?<select className="gov-input w-full min-w-16" value={x[k]} onChange={e=>updateMember(i,k,e.target.value)}><option>Y</option><option>N</option></select>:<input className="gov-input w-full min-w-28" disabled={k==="exclusionReason"&&x.includedYn==="Y"} type={k==="ownershipPercent"?"number":"text"} value={x[k]} onChange={e=>updateMember(i,k,e.target.value)}/>}</td>)}<td className="p-2 text-center align-middle"><button type="button" className="whitespace-nowrap rounded-lg px-3 py-2 font-bold text-red-700 hover:bg-red-50" onClick={()=>setMembers(a=>a.filter((_,n)=>n!==i))}>{en?"Delete":"삭제"}</button></td></tr>)}</tbody></table></div><div className="mt-4 flex flex-wrap justify-end gap-2"><Button disabled={busy} onClick={()=>run("","PUT",{...boundary,members})}>{en?"Save draft":"임시 저장"}</Button><Button disabled={busy||status!=="DRAFT"} onClick={()=>run("/review-ready","POST")}>{en?"Request review":"검토 요청"}</Button></div></section>
  <section className="gov-card mt-5 rounded-2xl border bg-white p-4 sm:p-6"><Title text={`3. ${en?"Intercompany elimination & consolidation":"내부거래 제거 및 연결 산정"}`} action={()=>setRows(x=>[...x,elimination()])} actionText={en?"Add elimination":"제거 항목 추가"}/><Field label={en?"Gross emissions (tCO2e)":"총 배출량 (tCO2e)"}><input type="number" className="gov-input w-full sm:w-64" value={gross} onChange={e=>setGross(e.target.value)}/></Field><div className="mt-4 overflow-x-auto rounded-xl border"><table className="w-full min-w-[920px] table-fixed text-sm"><thead><tr className="bg-slate-100 text-left">{(en?["Source","Counterparty","Activity","Gross","Eliminated","Unit","Evidence",""]:["발생 법인","상대 법인","활동 구분","총 배출량","제거량","단위","증빙","관리"]).map(x=><th className="break-keep p-3 align-middle" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((x,i)=><tr className="border-b last:border-b-0" key={i}>{(Object.keys(x) as (keyof Elimination)[]).map(k=><td className="p-1 align-middle" key={k}><input className="gov-input w-full min-w-28" type={k.includes("Emission")?"number":"text"} value={x[k]} onChange={e=>updateRow(i,k,e.target.value)}/></td>)}<td className="p-2 text-center align-middle"><button type="button" className="whitespace-nowrap rounded-lg px-3 py-2 font-bold text-red-700 hover:bg-red-50" onClick={()=>setRows(a=>a.filter((_,n)=>n!==i))}>{en?"Delete":"삭제"}</button></td></tr>)}</tbody></table></div><div className="mt-4 flex flex-wrap items-center justify-end gap-3"><strong>{en?"Expected net":"예상 순 배출량"}: {net.toLocaleString()} tCO2e</strong><Button disabled={busy||!["REVIEW_READY","CONSOLIDATED"].includes(status)} onClick={()=>run("/consolidate","POST",{grossEmission:gross,eliminations:rows})}>{en?"Run consolidation":"연결 산정"}</Button></div></section>
  <section className="gov-card mt-5 rounded-2xl border bg-white p-6"><h2 className="text-xl font-black text-[#06315f]">4. {en?"Approval and version lock":"승인 및 버전 잠금"}</h2><p className="mt-2 text-sm text-slate-600">{en?"Approval locks this version; later changes create a new auditable version.":"승인 시 현재 버전이 잠기며 이후 변경은 감사 가능한 새 버전으로 생성됩니다."}</p><div className="mt-4 flex justify-end gap-2"><Button disabled={busy||status!=="CONSOLIDATED"} onClick={()=>run("/decision","POST",{decision:"REJECT"})}>{en?"Reject":"반려"}</Button><Button disabled={busy||status!=="CONSOLIDATED"} onClick={()=>run("/decision","POST",{decision:"APPROVE"})}>{en?"Approve & lock":"승인·잠금"}</Button></div></section>
 </div></main>;
 return admin?<AdminPageShell breadcrumbs={[{label:en?"Home":"홈",href:buildLocalizedPath("/admin/","/en/admin/")},{label:en?"Emission Operations":"탄소배출 운영"},{label:en?"Organizational Boundary":"조직경계 운영"}]} title={en?"Organizational Boundary Operations":"조직경계 운영"} subtitle={en?"Review entity inclusion, consolidation, approval, and version history by project.":"프로젝트별 법인·사업장 포함 판정, 연결 산정, 승인 및 버전 이력을 관리합니다."}>{page}</AdminPageShell>:page;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="mt-4 block text-sm font-bold">{label}<div className="mt-2">{children}</div></label>}
function Title({text,action,actionText}:{text:string;action:()=>void;actionText:string}){return <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-black text-[#06315f]">{text}</h2><button className="gov-btn rounded-lg border px-4 py-2 font-bold" onClick={action}>{actionText}</button></div>}
function Button({children,disabled,onClick}:{children:React.ReactNode;disabled:boolean;onClick:()=>void}){return <button disabled={disabled} className="gov-btn rounded-lg bg-[#174ea6] px-5 py-3 font-bold text-white disabled:opacity-40" onClick={onClick}>{children}</button>}
