import { useCallback, useEffect, useMemo, useState } from "react";
import { buildLocalizedPath, isEnglish } from "../../lib/navigation/runtime";
import { AdminPageShell } from "../admin-entry/AdminPageShell";

type Member={entityCode:string;entityName:string;entityType:string;countryCode:string;ownershipPercent:string;controlType:string;includedYn:string;exclusionReason:string;evidenceRef:string};
type Elimination={sourceEntityCode:string;counterpartyEntityCode:string;activityCategory:string;grossEmission:string;eliminatedEmission:string;unit:string;evidenceRef:string};
type Boundary={version?:number;boundaryMethod:string;reportingBasis:string;rationale:string;effectiveFrom:string;effectiveUntil:string;status?:string;rowVersion?:number};
type Data={tenantId?:string;project?:{id?:string;name?:string};versions?:Boundary[];members?:Member[];eliminations?:Elimination[];consolidations?:Record<string,unknown>[]};
type Execution={found?:boolean;currentStepCode?:string;currentState?:string;executionStatus?:string};
const member=():Member=>({entityCode:"",entityName:"",entityType:"LEGAL_ENTITY",countryCode:"KR",ownershipPercent:"100",controlType:"OPERATIONAL",includedYn:"Y",exclusionReason:"",evidenceRef:""});
const elimination=():Elimination=>({sourceEntityCode:"",counterpartyEntityCode:"",activityCategory:"",grossEmission:"0",eliminatedEmission:"0",unit:"tCO2e",evidenceRef:""});
const initial:Boundary={boundaryMethod:"OPERATIONAL_CONTROL",reportingBasis:"ISO 14064-1",rationale:"",effectiveFrom:new Date().toISOString().slice(0,10),effectiveUntil:""};

async function jsonRequest(url:string,init?:RequestInit){const response=await fetch(url,{credentials:"include",...init}),contentType=response.headers.get("content-type")||"";if(!contentType.includes("application/json"))throw new Error(`서버 응답 형식이 올바르지 않습니다. (${response.status})`);const body=await response.json();if(!response.ok||body.success===false)throw new Error(body.message||`요청 처리에 실패했습니다. (${response.status})`);return body;}

export function OrganizationalBoundaryPage(){
 const en=isEnglish(),admin=location.pathname.includes("/admin/"),q=new URLSearchParams(location.search),projectId=q.get("projectId")||q.get("id")||"";
 const api=buildLocalizedPath(`/home/api/emission-projects/${encodeURIComponent(projectId)}/organizational-boundary`,`/en/home/api/emission-projects/${encodeURIComponent(projectId)}/organizational-boundary`);
 const [data,setData]=useState<Data>({}),[execution,setExecution]=useState<Execution>({}),[boundary,setBoundary]=useState<Boundary>(initial),[members,setMembers]=useState<Member[]>([member()]),[rows,setRows]=useState<Elimination[]>([]),[gross,setGross]=useState("0"),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const load=useCallback(async()=>{if(!projectId){setError(en?"Select a project first.":"프로젝트를 먼저 선택해 주세요.");return;}setError("");try{const body=await jsonRequest(api) as Data;const executionBody=await jsonRequest(`${buildLocalizedPath("/home/api/process-executions","/en/home/api/process-executions")}?${new URLSearchParams({tenantId:body.tenantId||"",projectId,processCode:"ORGANIZATIONAL_BOUNDARY"})}`).catch(()=>({found:false}));setData(body);setExecution(executionBody);setBoundary(body.versions?.[0]||initial);setMembers(body.members?.length?body.members:[member()]);setRows(body.eliminations||[]);const last=body.consolidations?.[0];if(last?.grossEmission!=null)setGross(String(last.grossEmission));}catch(e){setError(e instanceof Error?e.message:String(e));}},[api,en,projectId]);
 useEffect(()=>{void load();},[load]);
 const run=async(path:string,method:string,body?:unknown)=>{setBusy(true);setMessage("");setError("");try{await jsonRequest(api+path,{method,headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});setMessage(en?"The workflow was updated.":"업무 상태와 다음 액터 인계가 반영되었습니다.");await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 const updateMember=(i:number,k:keyof Member,v:string)=>setMembers(all=>all.map((x,n)=>n===i?{...x,[k]:v}:x)),updateRow=(i:number,k:keyof Elimination,v:string)=>setRows(all=>all.map((x,n)=>n===i?{...x,[k]:v}:x));
 const status=boundary.status||"NEW",included=members.filter(x=>x.includedYn==="Y").length,net=useMemo(()=>Number(gross||0)-rows.reduce((s,x)=>s+Number(x.eliminatedEmission||0),0),[gross,rows]),latest=data.consolidations?.[0];
 const stages=[{code:"ORGANIZATIONAL_BOUNDARY_S1",label:en?"Collect entities":"법인·사업장 수집"},{code:"ORGANIZATIONAL_BOUNDARY_S2",label:en?"Decide inclusion":"포함 여부 판정"},{code:"ORGANIZATIONAL_BOUNDARY_S3",label:en?"Consolidate":"연결 산정"},{code:"ORGANIZATIONAL_BOUNDARY_S4",label:en?"Approve and lock":"승인·잠금"}],currentStage=execution.currentStepCode||(!execution.found?"ORGANIZATIONAL_BOUNDARY_S1":""),currentIndex=stages.findIndex(x=>x.code===currentStage);
 const validateBoundary=()=>{if(!boundary.rationale.trim())return en?"Enter the boundary decision rationale.":"경계 선정 근거를 입력하세요.";if(!members.length)return en?"Add at least one entity.":"법인·사업장을 한 개 이상 추가하세요.";for(const x of members){if(!x.entityCode.trim()||!x.entityName.trim())return en?"Every entity requires a code and name.":"모든 법인·사업장에 코드와 이름이 필요합니다.";if(x.includedYn==="N"&&!x.exclusionReason.trim())return en?"Excluded entities require a reason.":"제외 대상에는 제외 사유가 필요합니다.";}return "";};
 const save=()=>{const issue=validateBoundary();if(issue){setError(issue);return;}void run("","PUT",{...boundary,members});};
 const validateEliminations=()=>{for(const x of rows){if(!x.sourceEntityCode||!x.counterpartyEntityCode||x.sourceEntityCode===x.counterpartyEntityCode)return en?"Each elimination requires different source and counterparty entities.":"내부거래 제거에는 서로 다른 발생 법인과 상대 법인이 필요합니다.";if(!x.activityCategory||!x.evidenceRef)return en?"Each elimination requires activity and evidence.":"모든 제거 항목에 활동 구분과 증빙이 필요합니다.";}return "";};
 const consolidate=()=>{const issue=validateEliminations();if(issue){setError(issue);return;}void run("/consolidate","POST",{grossEmission:gross,eliminations:rows});};
 const page=<main className="min-h-screen bg-[var(--kr-gov-bg-gray,#f5f7fa)] px-4 py-6 lg:px-8"><div className="mx-auto max-w-7xl">
  <nav className="text-sm text-slate-500"><a href={buildLocalizedPath("/emission/project_list","/en/emission/project_list")}>{en?"Emission projects":"배출량 프로젝트"}</a><span className="mx-2">/</span>{en?"Organizational boundary":"조직경계 설정"}</nav>
  <header className="mt-5 rounded-2xl bg-[#06315f] p-6 text-white"><p className="text-sm font-bold text-blue-200">{data.project?.id||projectId} · {status}</p><h1 className="mt-2 text-3xl font-black">{en?"Organizational Boundary & Consolidation":"조직경계 및 연결 산정"}</h1><p className="mt-2 text-blue-100">{data.project?.name||"-"} · {en?"Govern entity inclusion, eliminations and approval in one workflow.":"법인·사업장 포함 판정부터 내부거래 제거와 승인까지 한 업무로 처리합니다."}</p></header>
  <section aria-label={en?"Process stages":"업무 실행 순서"} className="mt-5 grid gap-2 md:grid-cols-4">{stages.map((stage,index)=><article className={`rounded-xl border p-4 ${index<currentIndex||execution.executionStatus==="COMPLETED"?"border-emerald-200 bg-emerald-50":index===currentIndex?"border-blue-500 bg-blue-50":"border-slate-200 bg-white"}`} key={stage.code}><p className="text-xs font-black text-slate-500">{index+1} · {stage.code}</p><strong className="mt-2 block text-sm text-[#06315f]">{stage.label}</strong><span className="mt-2 inline-block text-xs font-bold">{index<currentIndex||execution.executionStatus==="COMPLETED"?(en?"Complete":"완료"):index===currentIndex?(en?"Current task":"현재 업무"):(en?"Waiting":"대기")}</span></article>)}</section>
  <section className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[[en?"Version":"버전",boundary.version||"-"],[en?"Status":"상태",status],[en?"Included":"포함",included],[en?"Excluded":"제외",members.length-included],[en?"Net emissions":"순 배출량",String(latest?.netEmission??net)]].map(([l,v])=><div className="gov-card rounded-xl border bg-white p-4" key={String(l)}><p className="text-sm font-bold text-slate-500">{l}</p><strong className="mt-2 block text-xl text-[#06315f]">{String(v)}</strong></div>)}</section>
  {(message||error)&&<div aria-live="polite" className={`mt-4 rounded-lg border p-4 font-bold ${error?"border-red-200 bg-red-50 text-red-700":"border-blue-200 bg-blue-50 text-blue-800"}`}>{error||message}</div>}
  <section className="gov-card mt-5 rounded-2xl border bg-white p-6"><h2 className="text-xl font-black text-[#06315f]">1. {en?"Boundary policy":"경계 정책"}</h2><div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Field label={en?"Consolidation approach":"연결 접근법"}><select className="gov-input w-full" value={boundary.boundaryMethod} onChange={e=>setBoundary({...boundary,boundaryMethod:e.target.value})}><option value="OPERATIONAL_CONTROL">{en?"Operational control":"운영 통제"}</option><option value="FINANCIAL_CONTROL">{en?"Financial control":"재무 통제"}</option><option value="EQUITY_SHARE">{en?"Equity share":"지분율"}</option></select></Field><Field label={en?"Reporting basis":"보고 기준"}><input className="gov-input w-full" value={boundary.reportingBasis} onChange={e=>setBoundary({...boundary,reportingBasis:e.target.value})}/></Field><Field label={en?"Effective from":"적용 시작일"}><input type="date" className="gov-input w-full" value={boundary.effectiveFrom} onChange={e=>setBoundary({...boundary,effectiveFrom:e.target.value})}/></Field><Field label={en?"Effective until":"적용 종료일"}><input type="date" className="gov-input w-full" value={boundary.effectiveUntil} onChange={e=>setBoundary({...boundary,effectiveUntil:e.target.value})}/></Field><label className="text-sm font-bold md:col-span-2 lg:col-span-4">{en?"Decision rationale":"선정 근거"}<textarea className="gov-input mt-2 min-h-24 w-full" value={boundary.rationale} onChange={e=>setBoundary({...boundary,rationale:e.target.value})}/></label></div></section>
  <section className="gov-card mt-5 rounded-2xl border bg-white p-4 sm:p-6"><Title text={`2. ${en?"Entities and sites":"법인·사업장 포함 판정"}`} action={()=>setMembers(x=>[...x,member()])} actionText={en?"Add entity":"대상 추가"}/><div className="mt-4 overflow-x-auto rounded-xl border"><table className="w-full min-w-[1120px] table-fixed text-sm"><thead><tr className="bg-slate-100 text-left">{(en?["Code","Entity / Site","Type","Country","Ownership %","Control","Include","Exclusion reason","Evidence",""]:["코드","법인·사업장","유형","국가","지분율(%)","통제 유형","포함 여부","제외 사유","증빙","관리"]).map(x=><th className="break-keep p-3 align-middle" key={x}>{x}</th>)}</tr></thead><tbody>{members.map((x,i)=><tr className="border-b last:border-b-0" key={i}>{(["entityCode","entityName","entityType","countryCode","ownershipPercent","controlType","includedYn","exclusionReason","evidenceRef"] as (keyof Member)[]).map(k=><td className="p-1 align-middle" key={k}>{k==="entityType"?<select className="gov-input w-full min-w-28" value={x[k]} onChange={e=>updateMember(i,k,e.target.value)}><option value="LEGAL_ENTITY">{en?"Legal entity":"법인"}</option><option value="SITE">{en?"Site":"사업장"}</option><option value="JV">JV</option></select>:k==="controlType"?<select className="gov-input w-full min-w-28" value={x[k]} onChange={e=>updateMember(i,k,e.target.value)}><option value="OPERATIONAL">{en?"Operational":"운영 통제"}</option><option value="FINANCIAL">{en?"Financial":"재무 통제"}</option><option value="EQUITY">{en?"Equity":"지분"}</option><option value="NONE">{en?"None":"없음"}</option></select>:k==="includedYn"?<select className="gov-input w-full min-w-16" value={x[k]} onChange={e=>updateMember(i,k,e.target.value)}><option value="Y">{en?"Include":"포함"}</option><option value="N">{en?"Exclude":"제외"}</option></select>:<input className="gov-input w-full min-w-28" disabled={k==="exclusionReason"&&x.includedYn==="Y"} max={k==="ownershipPercent"?100:undefined} min={k==="ownershipPercent"?0:undefined} type={k==="ownershipPercent"?"number":"text"} value={x[k]} onChange={e=>updateMember(i,k,e.target.value)}/>}</td>)}<td className="p-2 text-center align-middle"><button type="button" className="whitespace-nowrap rounded-lg px-3 py-2 font-bold text-red-700 hover:bg-red-50" onClick={()=>setMembers(a=>a.filter((_,n)=>n!==i))}>{en?"Delete":"삭제"}</button></td></tr>)}</tbody></table></div><div className="mt-4 flex flex-wrap justify-end gap-2"><Button disabled={busy} onClick={save}>{en?"Save draft":"임시 저장"}</Button><Button disabled={busy||status!=="DRAFT"} onClick={()=>run("/review-ready","POST")}>{en?"Request review":"검토 요청"}</Button></div></section>
  <section className="gov-card mt-5 rounded-2xl border bg-white p-4 sm:p-6"><Title text={`3. ${en?"Intercompany elimination & consolidation":"내부거래 제거 및 연결 산정"}`} action={()=>setRows(x=>[...x,elimination()])} actionText={en?"Add elimination":"제거 항목 추가"}/><Field label={en?"Gross emissions (tCO2e)":"총 배출량 (tCO2e)"}><input type="number" min="0" className="gov-input w-full sm:w-64" value={gross} onChange={e=>setGross(e.target.value)}/></Field><div className="mt-4 overflow-x-auto rounded-xl border"><table className="w-full min-w-[920px] table-fixed text-sm"><thead><tr className="bg-slate-100 text-left">{(en?["Source","Counterparty","Activity","Gross","Eliminated","Unit","Evidence",""]:["발생 법인","상대 법인","활동 구분","총 배출량","제거량","단위","증빙","관리"]).map(x=><th className="break-keep p-3 align-middle" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((x,i)=><tr className="border-b last:border-b-0" key={i}>{(Object.keys(x) as (keyof Elimination)[]).map(k=><td className="p-1 align-middle" key={k}><input className="gov-input w-full min-w-28" min={k.includes("Emission")?0:undefined} type={k.includes("Emission")?"number":"text"} value={x[k]} onChange={e=>updateRow(i,k,e.target.value)}/></td>)}<td className="p-2 text-center align-middle"><button type="button" className="whitespace-nowrap rounded-lg px-3 py-2 font-bold text-red-700 hover:bg-red-50" onClick={()=>setRows(a=>a.filter((_,n)=>n!==i))}>{en?"Delete":"삭제"}</button></td></tr>)}</tbody></table></div><div className="mt-4 flex flex-wrap items-center justify-end gap-3"><strong>{en?"Expected net":"예상 순 배출량"}: {net.toLocaleString()} tCO2e</strong><Button disabled={busy||!["REVIEW_READY","CONSOLIDATED"].includes(status)} onClick={consolidate}>{en?"Run consolidation":"연결 산정"}</Button></div></section>
  <section className="gov-card mt-5 rounded-2xl border bg-white p-6"><h2 className="text-xl font-black text-[#06315f]">4. {en?"Approval and version lock":"승인 및 버전 잠금"}</h2><p className="mt-2 text-sm text-slate-600">{en?"Approval locks this version; later changes create a new auditable version.":"승인 시 현재 버전이 잠기며 이후 변경은 감사 가능한 새 버전으로 생성됩니다."}</p><div className="mt-4 flex justify-end gap-2"><Button disabled={busy||status!=="CONSOLIDATED"} onClick={()=>run("/decision","POST",{decision:"REJECT"})}>{en?"Reject":"반려"}</Button><Button disabled={busy||status!=="CONSOLIDATED"} onClick={()=>run("/decision","POST",{decision:"APPROVE"})}>{en?"Approve & lock":"승인·잠금"}</Button></div></section>
 </div></main>;
 return admin?<AdminPageShell breadcrumbs={[{label:en?"Home":"홈",href:buildLocalizedPath("/admin/","/en/admin/")},{label:en?"Emission Operations":"탄소배출 운영"},{label:en?"Organizational Boundary":"조직경계 운영"}]} sidebarVariant="emission" title={en?"Organizational Boundary Operations":"조직경계 운영"} subtitle={en?"Review entity inclusion, consolidation, approval, and version history by project.":"프로젝트별 법인·사업장 포함 판정, 연결 산정, 승인 및 버전 이력을 관리합니다."}>{page}</AdminPageShell>:page;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="mt-4 block text-sm font-bold">{label}<div className="mt-2">{children}</div></label>}
function Title({text,action,actionText}:{text:string;action:()=>void;actionText:string}){return <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-black text-[#06315f]">{text}</h2><button className="gov-btn rounded-lg border px-4 py-2 font-bold" onClick={action}>{actionText}</button></div>}
function Button({children,disabled,onClick}:{children:React.ReactNode;disabled:boolean;onClick:()=>void}){return <button disabled={disabled} className="gov-btn rounded-lg bg-[#174ea6] px-5 py-3 font-bold text-white disabled:opacity-40" onClick={onClick}>{children}</button>}
