use strict;
use warnings;
my $path = "/opt/Resonance/projects/carbonet-frontend/source/src/features/emission-survey-report/EmissionSurveyReportMigrationPage.tsx";
open my $fh, '<:raw', $path or die $!;
local $/;
my $s = <$fh>;
close $fh;
$s =~ s/\.lca-sheet\{box-shadow:none!important;border:none!important;border-radius:0!important;margin:0!important;max-width:none!important;width:100%!important;box-sizing:border-box!important;padding:0!important;font-size:10px!important;line-height:1\.35!important\}/.lca-sheet{box-shadow:none!important;border:none!important;border-radius:0!important;margin:0!important;max-width:none!important;width:100%!important;box-sizing:border-box!important;padding:0!important;font-size:16px!important;line-height:1.35!important}/;
$s =~ s/\.lca-sheet header\{margin-bottom:5px!important\}/.lca-sheet header{min-height:25px!important;margin-bottom:8px!important}/;
$s =~ s/\.lca-sheet h2\{font-size:13\.5px!important;line-height:1\.2!important;margin-bottom:5px!important\}/.lca-sheet h2{font-size:18px!important;line-height:1.2!important;margin-bottom:7px!important}/;
$s =~ s/\.lca-sheet p\{font-size:10\.2px!important;line-height:1\.45!important\}/.lca-sheet p{font-size:16px!important;line-height:1.45!important}/;
$s =~ s/\.lca-section\{break-inside:avoid;page-break-inside:avoid;margin-top:9px!important\}/.lca-section{break-inside:avoid;page-break-inside:avoid;margin-top:12px!important}/;
$s =~ s/\.lca-table\{break-inside:auto;page-break-inside:auto;font-size:10px!important;width:100%!important\}/.lca-table{break-inside:auto;page-break-inside:auto;font-size:16px!important;width:100%!important}/;
$s =~ s/padding:4px 6px!important;font-size:10px!important;line-height:1\.25!important/padding:6px 8px!important;font-size:16px!important;line-height:1.28!important/g;
open my $out, '>:raw', $path or die $!;
print $out $s;
close $out;
