use strict;
use warnings;
my $path = "/opt/Resonance/projects/carbonet-frontend/source/src/features/emission-survey-report/EmissionSurveyReportMigrationPage.tsx";
open my $fh, '<:raw', $path or die $!;
local $/;
my $s = <$fh>;
close $fh;
$s =~ s/\@page\{size:A4;margin:15px;\}/\@page{size:A4;margin:30px;}/;
open my $out, '>:raw', $path or die $!;
print $out $s;
close $out;
