use strict;
use warnings;
my $path = "/opt/Resonance/projects/carbonet-frontend/source/src/features/emission-survey-report/EmissionSurveyReportMigrationPage.tsx";
open my $fh, '<:raw', $path or die $!;
local $/;
my $s = <$fh>;
close $fh;
$s =~ s/font-size:9px!important\}\.lca-sheet header/font-size:8px!important;line-height:1.2!important}.lca-sheet header/;
$s =~ s/\.lca-sheet header\{margin-bottom:8px!important\}/.lca-sheet header{margin-bottom:5px!important}/;
$s =~ s/\.lca-sheet h2\{font-size:13px!important;line-height:1\.2!important;margin-bottom:5px!important\}/.lca-sheet h2{font-size:11px!important;line-height:1.15!important;margin-bottom:3px!important}/;
$s =~ s/\.lca-sheet p\{font-size:10px!important;line-height:1\.45!important\}/.lca-sheet p{font-size:8px!important;line-height:1.25!important}/;
$s =~ s/\.lca-section\{break-inside:avoid;page-break-inside:avoid;margin-top:10px!important\}/.lca-section{break-inside:avoid;page-break-inside:avoid;margin-top:6px!important}/;
$s =~ s/\.lca-table\{break-inside:auto;page-break-inside:auto;font-size:9px!important\}/.lca-table{break-inside:auto;page-break-inside:auto;font-size:8px!important}/;
$s =~ s/padding:3px 5px!important;font-size:9px!important;line-height:1\.25!important/padding:2px 4px!important;font-size:8px!important;line-height:1.15!important/g;
$s =~ s/rounded-\[26px\] border border-white bg-white p-8 shadow/rounded-[18px] border border-white bg-white p-5 text-[11px] shadow/;
$s =~ s/text-center text-2xl/text-center text-xl/g;
$s =~ s/gap-2 text-3xl/gap-2 text-2xl/;
$s =~ s/mb-2 text-base/mb-1 text-sm/g;
$s =~ s/className="lca-section mt-5"/className="lca-section mt-3"/g;
$s =~ s/className="lca-section mt-4"/className="lca-section mt-3"/g;
$s =~ s/className="lca-section lca-page-2 mt-4"/className="lca-section lca-page-2 mt-0"/;
$s =~ s/leading-6 text-slate-800/leading-5 text-slate-800/g;
$s =~ s/mt-2 leading-6/mt-1 leading-5/g;
$s =~ s/px-2 py-1\.5 text-center text-\[11px\]/px-1.5 py-1 text-center text-[10px]/g;
$s =~ s/px-2 py-1\.5 text-\[11px\]/px-1.5 py-1 text-[10px]/g;
$s =~ s/px-2 py-1\.5 text-\[11px\] font-semibold leading-6/px-1.5 py-1 text-[10px] font-semibold leading-5/g;
open my $out, '>:raw', $path or die $!;
print $out $s;
close $out;
