use strict;
use warnings;
my $path = '/opt/Resonance/projects/carbonet-frontend/source/src/features/emission-survey-report/EmissionSurveyReportMigrationPage.tsx';
open my $fh, '<:raw', $path or die $!;
local $/;
my $s = <$fh>;
close $fh;
$s =~ s/px-3 py-2 text-center text-\[13px\]/px-2 py-1.5 text-center text-[11px]/g;
$s =~ s/px-3 py-2 text-\[13px\]/px-2 py-1.5 text-[11px]/g;
$s =~ s/px-3 py-2 text-\[13px\] font-semibold leading-6/px-2 py-1.5 text-[11px] font-semibold leading-5/g;
$s =~ s/\@page\{size:A4;margin:0;\}/\@page{size:A4;margin:30px 8mm 8mm 8mm;}/;
$s =~ s/html,body\{background:#fff!important\}/html,body{background:#fff!important;font-size:9px!important}/;
$s =~ s/\.lca-sheet\{box-shadow:none!important;border:none!important;border-radius:0!important;margin:0!important;max-width:none!important;padding:20mm 10mm!important\}/.lca-sheet{box-shadow:none!important;border:none!important;border-radius:0!important;margin:0!important;max-width:none!important;padding:0!important;font-size:9px!important}.lca-sheet header{margin-bottom:8px!important}.lca-sheet h2{font-size:13px!important;line-height:1.2!important;margin-bottom:5px!important}.lca-sheet p{font-size:10px!important;line-height:1.45!important}/;
$s =~ s/\.lca-section\{break-inside:avoid;page-break-inside:avoid\}/.lca-section{break-inside:avoid;page-break-inside:avoid;margin-top:10px!important}.lca-page-2{break-before:page!important;page-break-before:always!important;margin-top:0!important}/;
$s =~ s/\.lca-table\{break-inside:auto;page-break-inside:auto\}/.lca-table{break-inside:auto;page-break-inside:auto;font-size:9px!important}/;
$s =~ s/\.lca-table th\{background:#d9d9d9!important;color:#0f172a!important;/.lca-table th{background:#d9d9d9!important;color:#0f172a!important;padding:3px 5px!important;font-size:9px!important;line-height:1.25!important;/;
$s =~ s/\.lca-table td\.bg-/\.lca-table td{padding:3px 5px!important;font-size:9px!important;line-height:1.25!important}.lca-table td.bg-/;
$s =~ s/p-8 shadow-/p-6 text-[12px] shadow-/;
$s =~ s/text-3xl font-black tracking/text-2xl font-black tracking/;
$s =~ s/text-center text-3xl/text-center text-2xl/;
$s =~ s/lca-section mt-8/lca-section mt-5/g;
$s =~ s/lca-section mt-7/lca-section mt-4/g;
$s =~ s/mb-3 text-xl font-black/mb-2 text-base font-black/g;
$s =~ s/className=\{`\$\{tableHeaderClass\} w-\[24%\]`\}/'className={`${tableHeaderClass} w-[24%] text-left`}'/e;
$s =~ s/className=\{tableHeaderClass\}>\{en \? "Description"/'className={`${tableHeaderClass} text-left`}>{en ? "Description"'/e;
$s =~ s/<section className="lca-section mt-4">\s*<h2 className="mb-2 text-base font-black text-slate-950">\{en \? "Summary"/'<section className="lca-section lca-page-2 mt-4">\n          <h2 className="mb-2 text-base font-black text-slate-950">{en ? "Summary"'/se;
$s =~ s/leading-8 text-slate-800/leading-6 text-slate-800/g;
$s =~ s/mt-3 leading-6 text-slate-800/mt-2 leading-6 text-slate-800/g;
$s =~ s/className="leading-7"/className="leading-5"/g;
open my $out, '>:raw', $path or die $!;
print {$out} $s;
close $out;
