use strict;
use warnings;
my $path = "/opt/Resonance/projects/carbonet-frontend/source/src/features/emission-survey-report/EmissionSurveyReportMigrationPage.tsx";
open my $fh, '<:raw', $path or die $!;
local $/;
my $s = <$fh>;
close $fh;
$s =~ s/\@page\{size:A4;margin:[^}]+\}/\@page{size:A4;margin:30px;}/g;
$s =~ s/main\{padding:0!important\}\.lca-sheet/main{padding:30px!important;box-sizing:border-box!important}.lca-sheet/;
$s =~ s/width:100%!important;box-sizing:border-box!important;padding:0!important;font-size:12px!important/width:100%!important;box-sizing:border-box!important;padding:0!important;font-size:12px!important/;
open my $out, '>:raw', $path or die $!;
print $out $s;
close $out;
