use strict;
use warnings;
my $path = "/opt/Resonance/projects/carbonet-frontend/source/src/features/emission-survey-report/EmissionSurveyReportMigrationPage.tsx";
open my $fh, '<:raw', $path or die $!;
local $/;
my $s = <$fh>;
close $fh;
$s =~ s/font-size:8px!important;line-height:1\.2!important\}/font-size:8.8px!important;line-height:1.28!important}/;
$s =~ s/\.lca-sheet h2\{font-size:11px!important;line-height:1\.15!important;margin-bottom:3px!important\}/.lca-sheet h2{font-size:12.5px!important;line-height:1.2!important;margin-bottom:4px!important}/;
$s =~ s/\.lca-sheet p\{font-size:8px!important;line-height:1\.25!important\}/.lca-sheet p{font-size:9px!important;line-height:1.35!important}/;
$s =~ s/\.lca-section\{break-inside:avoid;page-break-inside:avoid;margin-top:6px!important\}/.lca-section{break-inside:avoid;page-break-inside:avoid;margin-top:8px!important}/;
$s =~ s/\.lca-table\{break-inside:auto;page-break-inside:auto;font-size:8px!important\}/.lca-table{break-inside:auto;page-break-inside:auto;font-size:8.8px!important}/;
$s =~ s/padding:2px 4px!important;font-size:8px!important;line-height:1\.15!important/padding:3px 5px!important;font-size:8.8px!important;line-height:1.2!important/g;
$s =~ s/rounded-\[18px\] border border-white bg-white p-5 text-\[11px\] shadow/rounded-[20px] border border-white bg-white p-6 text-[12px] shadow/;
$s =~ s/text-center text-xl/text-center text-2xl/g;
$s =~ s/gap-2 text-2xl/gap-2 text-3xl/;
$s =~ s/mb-1 text-sm/mb-2 text-base/g;
$s =~ s/className="lca-section mt-3"/className="lca-section mt-4"/g;
$s =~ s/className="lca-section lca-page-2 mt-0"/className="lca-section lca-page-2 mt-0"/;
$s =~ s/leading-5 text-slate-800/leading-6 text-slate-800/g;
$s =~ s/mt-1 leading-5/mt-2 leading-6/g;
$s =~ s/px-1\.5 py-1 text-center text-\[10px\]/px-2 py-1.5 text-center text-[11px]/g;
$s =~ s/px-1\.5 py-1 text-\[10px\]/px-2 py-1.5 text-[11px]/g;
$s =~ s/px-1\.5 py-1 text-\[10px\] font-semibold leading-5/px-2 py-1.5 text-[11px] font-semibold leading-5/g;
open my $out, '>:raw', $path or die $!;
print $out $s;
close $out;
