use strict;
use warnings;
my $path = "/opt/Resonance/projects/carbonet-frontend/source/src/features/emission-survey-report/EmissionSurveyReportMigrationPage.tsx";
open my $fh, '<:raw', $path or die $!;
local $/;
my $s = <$fh>;
close $fh;
$s =~ s/"Pretendard GOV"/\\"Pretendard GOV\\"/g;
$s =~ s/"Noto Sans KR"/\\"Noto Sans KR\\"/g;
$s =~ s/(\.lca-table td\.bg-\\\[\\\#f2f2f2\\\],\.lca-table td\[class\*='bg\[\#f2f2f2\]'\]\{background:#f2f2f2!important;)/$1font-weight:500!important;/;
open my $out, '>:raw', $path or die $!;
print $out $s;
close $out;
