apiVersion: v1
data:
  CARBONET_ECOINVENT_CLIENT_ID: ""
  CARBONET_ECOINVENT_CLIENT_SECRET: ""
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"CARBONET_ECOINVENT_CLIENT_ID":"","CARBONET_ECOINVENT_CLIENT_SECRET":""},"kind":"Secret","metadata":{"annotations":{},"name":"carbonet-runtime-ecoinvent-secret","namespace":"carbonet-prod"}}
  creationTimestamp: "2026-05-13T13:38:57Z"
  name: carbonet-runtime-ecoinvent-secret
  namespace: carbonet-prod
  resourceVersion: "6251"
  uid: d3c59a61-e9aa-460b-b970-d879a09ba131
type: Opaque
