apiVersion: v1
data:
  DB_PASSWORD: ""
  DB_URL: amRiYzpjdWJyaWQ6Y3VicmlkLWNhcmJvbmV0LmNhcmJvbmV0LXByb2Quc3ZjLmNsdXN0ZXIubG9jYWw6MzMwMDA6Y2FyYm9uZXQ6Ojo/Y2hhcnNldD1VVEYtOA==
  DB_USERNAME: ZGJh
  SPRING_DATASOURCE_PASSWORD: ""
  SPRING_DATASOURCE_USERNAME: ZGJh
  TOKEN_ACCESS_SECRET: YTVkMzlhZDRlN2I0ZjMzMzY0YWYzN2YwZjgyNDhiZmUyN2Q2NmE1ODc0MjRiMWE3ZmJiYmM0MGI5Y2Y0NWYyYw==
  TOKEN_REFRESH_SECRET: NTJmODgzMzhjYTgwMTUyOTg4Y2JhYjBkYmUxMjM5NWUzYjg3M2I3MzNkNTY3Y2Q2ZmQzNWNmYzdiMmQ2ZTMzMQ==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"DB_PASSWORD":"","DB_URL":"amRiYzpjdWJyaWQ6Y3VicmlkLWNhcmJvbmV0LmNhcmJvbmV0LXByb2Quc3ZjLmNsdXN0ZXIubG9jYWw6MzMwMDA6Y2FyYm9uZXQ6Ojo/Y2hhcnNldD1VVEYtOA==","DB_USERNAME":"ZGJh","SPRING_DATASOURCE_PASSWORD":"","SPRING_DATASOURCE_USERNAME":"ZGJh","TOKEN_ACCESS_SECRET":"YTVkMzlhZDRlN2I0ZjMzMzY0YWYzN2YwZjgyNDhiZmUyN2Q2NmE1ODc0MjRiMWE3ZmJiYmM0MGI5Y2Y0NWYyYw==","TOKEN_REFRESH_SECRET":"NTJmODgzMzhjYTgwMTUyOTg4Y2JhYjBkYmUxMjM5NWUzYjg3M2I3MzNkNTY3Y2Q2ZmQzNWNmYzdiMmQ2ZTMzMQ=="},"kind":"Secret","metadata":{"annotations":{},"name":"carbonet-runtime-secret","namespace":"carbonet-prod"}}
  creationTimestamp: "2026-05-13T13:38:57Z"
  name: carbonet-runtime-secret
  namespace: carbonet-prod
  resourceVersion: "6250"
  uid: 6ec30fb1-3c6a-4c53-be7e-3b7af9d8e652
type: Opaque
