import {useEffect,useState} from 'react';
import contract from './emission-current-contract.json';
import {validateEmissionCurrentContract} from './validateEmissionCurrentContract';
function CurrentContractQa(){const [result,setResult]=useState<any>(null),[error,setError]=useState('');async function run(){try{const id=new URLSearchParams(location.search).get('projectId')||new URLSearchParams(location.search).get('id')||'';if(!id)throw Error('프로젝트를 선택하세요.');const r=await fetch('/home/api/emission-projects/'+encodeURIComponent(id)+'/completion',{credentials:'include'});if(!r.ok)throw Error('조회 실패 '+r.status);setResult(validateEmissionCurrentContract(id,await r.json()));setError('')}catch(e){setError(String(e));setResult(null)}}return <div><button type="button" className="border rounded px-3 py-2" onClick={()=>void run()}>현재 계약 자동 검증</button>{error&&<p role="alert">{error}</p>}{result&&<div data-current-contract-qa-result><p>현재 스냅샷: {result.pass?'PASS':'FAIL'} · {result.projectId} · 입력 버전 {result.identity?.input_revision}</p><ul>{result.checks.map((c:any)=><li key={c.id}>{c.id} {c.name}: {c.pass?'PASS':'FAIL'}</li>)}</ul><p>역할 릴레이·중복 실행·이력 검증은 별도 증거가 필요합니다. 이 버튼은 E2E 완료를 변경하지 않습니다.</p></div>}</div>}
export {contract as emissionCurrentContract};
export function emissionContractPage(route:string){return contract.pages.find(p=>p.path===route.split(/[?#]/)[0].replace(/^\/en\//,'/'));}
export function emissionContractHelp(route:string,pageId:string){const p=emissionContractPage(route);return p?{pageId,title:p.name+' 도움말',summary:contract.completionRule,items:[{id:'flow',title:'현재 화면의 업무',body:p.action},{id:'identity',title:'입력·출력 연결',body:p.input+' → '+p.output+' / '+contract.identity},...contract.rules.map(r=>({id:r.id,title:r.id,body:r.text}))]}:null;}
export function EmissionContractCard({route,mode='설계'}:{route:string;mode?:string}){const p=emissionContractPage(route);if(!p)return null;return <section className="rounded border border-slate-300 bg-white p-4 text-sm" data-emission-contract-card={mode} data-contract-version={contract.version}><h3 className="font-bold">{p.name} · {mode} 계약</h3><p>{contract.completionRule}</p><dl><dt>프로세스·역할</dt><dd>{contract.processId} · {p.actor}</dd><dt>입력 → 출력</dt><dd>{p.input} → {p.output}</dd><dt>실행 순서</dt><dd>{p.action}</dd></dl><details><summary>공통 완료 규칙 8개</summary><ol>{contract.rules.map(r=><li key={r.id}>{r.id} {r.text}</li>)}</ol></details>{mode==='QA'&&<><CurrentContractQa/><ol>{contract.qa.map(q=><li key={q}>{q}</li>)}</ol><p>기준선 릴레이 판정: {contract.gate} (PRJ-2026-F024B4). 다른 프로젝트나 변경된 버전의 E2E 통과를 뜻하지 않습니다.</p></>}<small>계약 버전 {contract.version} · emission-current-contract.json</small></section>}
export function CurrentEmissionContract({route}:{route:string}){const page=emissionContractPage(route),id=new URLSearchParams(location.search).get('projectId')||new URLSearchParams(location.search).get('id')||'';const[data,setData]=useState<any>(null),[error,setError]=useState('');async function load(){try{const r=await fetch('/home/api/emission-projects/'+encodeURIComponent(id)+'/completion',{credentials:'include'});if(!r.ok)throw Error('현재 계약 조회 실패 '+r.status);setData(await r.json());setError('')}catch(e){setError(String(e));setData(null)}}useEffect(()=>{if(!page||!id)return;void load();const refresh=()=>void load();window.addEventListener('emission-current-contract-refresh',refresh);window.addEventListener('focus',refresh);const t=setInterval(refresh,5000);return()=>{clearInterval(t);window.removeEventListener('emission-current-contract-refresh',refresh);window.removeEventListener('focus',refresh)}},[route,id]);// Presentation only: the detail body already renders the project ID.
if(!page||!id)return null;
if(['/emission/project/detail','/emission/calculation'].includes(route.split(/[?#]/)[0].replace(/^\/en\//,'/').replace(/\/$/,'')))return null;
const c=data?.currentContract;return <section className="mx-auto my-4 max-w-[1280px] border-y border-slate-300 bg-white px-6 py-3 text-sm" data-current-emission-contract=""><p><strong>{id}</strong> · 입력 버전 {c?.input_revision??'—'} · 제출 {c?.submission_id??'—'} · 산정 {c?.calculation_id??'—'} · 승인 요청 {c?.approval_request_id??'—'} · {c?.request_status||'미요청'} · 프로세스 {data?.processComplete?'완료':'미완료'}</p>{error&&<p role="alert">{error}</p>}<p>{contract.completionRule}</p><nav className="mt-2 flex flex-wrap gap-4">{contract.pages.map(p=><a className="underline" key={p.path} href={p.path+'?projectId='+encodeURIComponent(id)}>{p.name}</a>)}<button onClick={()=>void load()} type="button">현재 상태 새로고침</button></nav></section>}
