app:
  resonanceOidcEnabled: true
  resonanceOidcDisplayName: ${AUTH_OIDC_DISPLAY_NAME}

auth:
  session:
    secret: ${AUTH_SESSION_SECRET}
  providers:
    guest: null
    oidc:
      production:
        metadataUrl: ${AUTH_OIDC_METADATA_URL}
        clientId: ${AUTH_OIDC_CLIENT_ID}
        clientSecret: ${AUTH_OIDC_CLIENT_SECRET}
        prompt: auto
        additionalScopes:
          - groups
