import { FormEvent, useEffect, useState } from "react";
import { buildLocalizedPath } from "../../lib/navigation/runtime";

type Project={id:string;name:string;site:string;step:string};
type RequestItem={id:number;title:string;detail:string;requestedItems:string;requester:string;assignee:string;dueDate:string;status:string};
type Payload={items:RequestItem[];dataOwners:{id:string}[]};

async function json(url:string,init?:RequestInit){const response=await fetch(url,{credentials:"include",headers:{"Content-Type":"application/json",Accept:"application/json",...(init?.headers||{})},...init});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.message||"요청 처리에 실패했습니다.");return body;}

export function EmissionDataRequestFunctionalPage(){
 const params=new URLSearchParams(location.search);
 const [projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(params.get("projectId")||"");
 const [payload,setPayload]=useState<Payload>({items:[],dataOwners:[]}),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const [form,setForm]=useState({title:"월별 활동자료 및 증빙 제출 요청",detail:"산정기간의 활동자료를 입력하고 원본 증빙을 함께 제출해 주세요.",requestedItems:"연료 사용량, 전력 사용량, 생산량, 계량기·고지서 증빙",assignee:"",dueDate:""});
 const api=(path:string)=>buildLocalizedPath(`/home/api${path}`,`/en/home/api${path}`);
 useEffect(()=>{json(api("/emission-projects?size=100")).then(v=>{setProjects(v.items||[]);if(!projectId&&v.items?.[0])setProjectId(v.items[0].id)}).catch(e=>setError(e.message))},[]);
 const load=()=>projectId?json(api(`/emission-projects/${projectId}/activity-requests`)).then(v=>{setPayload(v);if(!form.assignee&&v.dataOwners?.[0])setForm(f=>({...f,assignee:v.dataOwners[0].id}))}).catch(e=>setError(e.message)):Promise.resolve();
 useEffect(()=>{void load()},[projectId]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{await json(api(`/emission-projects/${projectId}/activity-requests`),{method:"POST",body:JSON.stringify(form)});await load()}catch(x){setError((x as Error).message)}finally{setBusy(false)}};
 const start=async(id:number)=>{setBusy(true);try{await json(api(`/emission-projects/${projectId}/activity-requests/${id}/start`),{method:"POST",body:"{}"});await load()}catch(x){setError((x as Error).message)}finally{setBusy(false)}};
 return <div className="min-h-screen bg-slate-50 text-slate-900"><header className="border-b-2 border-[#003764] bg-white"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4"><a className="text-xl font-black text-[#003764]" href={buildLocalizedPath("/home","/en/home")}>CCUS 통합 플랫폼</a><a className="font-bold text-[#246beb]" href={buildLocalizedPath("/emission/my-tasks","/en/emission/my-tasks")}>내 업무</a></div></header><main className="mx-auto max-w-7xl px-4 py-8">
  <p className="text-sm font-bold text-slate-500">탄소배출 관리 / 활동자료</p><h1 className="mt-2 text-3xl font-black">자료 제출 요청</h1><p className="mt-3 text-slate-600">기업 담당자가 사업장 자료 담당자에게 제출 범위와 마감일을 지정합니다. 요청은 담당자의 내 업무에 즉시 연결됩니다.</p>
  {error&&<div className="mt-5 rounded-lg border border-red-300 bg-red-50 p-4 font-bold text-red-700">{error}</div>}
  <section className="mt-6 rounded-xl border bg-white p-5"><label className="font-bold">대상 프로젝트<select className="mt-2 h-12 w-full rounded-lg border px-3" value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">선택</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name} · {p.site} · {p.step}</option>)}</select></label></section>
  <div className="mt-6 grid gap-6 lg:grid-cols-[420px_1fr]"><form className="rounded-xl border bg-white p-5" onSubmit={submit}><h2 className="text-xl font-black">새 요청</h2>{[["title","요청 제목"],["detail","요청 내용"],["requestedItems","요청 항목"]].map(([key,label])=><label className="mt-4 block font-bold" key={key}>{label}<textarea className="mt-2 min-h-20 w-full rounded-lg border p-3 font-normal" value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label className="mt-4 block font-bold">담당자<select required className="mt-2 h-11 w-full rounded-lg border px-3 font-normal" value={form.assignee} onChange={e=>setForm({...form,assignee:e.target.value})}><option value="">사업장 자료 담당자 선택</option>{payload.dataOwners.map(a=><option key={a.id}>{a.id}</option>)}</select></label><label className="mt-4 block font-bold">제출 마감일<input required type="date" className="mt-2 h-11 w-full rounded-lg border px-3 font-normal" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><button disabled={busy||!projectId} className="mt-5 h-12 w-full rounded-lg bg-[#246beb] font-black text-white disabled:bg-slate-300">요청 등록</button></form>
  <section className="overflow-hidden rounded-xl border bg-white"><div className="border-b p-5"><h2 className="text-xl font-black">요청 및 처리 현황</h2><p className="mt-1 text-sm text-slate-500">요청→진행 중→제출 상태가 업무 결과에 따라 변경됩니다.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead className="bg-slate-100 text-left"><tr><th className="p-3">요청</th><th className="p-3">담당자</th><th className="p-3">마감</th><th className="p-3">상태</th><th className="p-3">업무</th></tr></thead><tbody>{payload.items.map(r=><tr key={r.id} className="border-t"><td className="p-3"><strong>{r.title}</strong><p className="mt-1 text-slate-500">{r.requestedItems}</p></td><td className="p-3">{r.assignee}</td><td className="p-3">{r.dueDate}</td><td className="p-3 font-bold">{r.status}</td><td className="p-3">{r.status==="REQUESTED"?<button className="rounded-lg border border-blue-600 px-3 py-2 font-bold text-blue-700" onClick={()=>start(r.id)}>업무 시작</button>:r.status==="IN_PROGRESS"?<a className="font-bold text-blue-700 underline" href={buildLocalizedPath(`/emission/activity-data?projectId=${projectId}`,`/en/emission/activity-data?projectId=${projectId}`)}>자료 입력</a>:"처리 완료"}</td></tr>)}{!payload.items.length&&<tr><td colSpan={5} className="p-12 text-center text-slate-500">등록된 요청이 없습니다.</td></tr>}</tbody></table></div></section></div>
 </main></div>;
}
