import { FormEvent, useEffect, useMemo, useState } from "react";
import { buildLocalizedPath } from "../../lib/navigation/runtime";

type Project={id:string;name:string;site:string;step:string};
type RequestItem={id:number;title:string;detail:string;requestedItems:string;requester:string;assignee:string;dueDate:string;status:string;submissionId?:number;correctionReason?:string;correctionDueDate?:string;correctionCount?:number;acceptedBy?:string;acceptedAt?:string};
type EventItem={id:number;requestId:number;code:string;previousStatus?:string;newStatus:string;actor:string;note?:string;createdAt:string};
type Payload={items:RequestItem[];dataOwners:{id:string}[];actorRoles:string[];events:EventItem[]};

const statusLabel:Record<string,string>={REQUESTED:"요청",IN_PROGRESS:"수집 중",SUBMITTED:"접수 검토",CORRECTION_REQUIRED:"보완 필요",ACCEPTED:"접수 완료",CLOSED:"종료",CANCELLED:"취소"};
async function json(url:string,init?:RequestInit){const response=await fetch(url,{credentials:"include",headers:{"Content-Type":"application/json",Accept:"application/json",...(init?.headers||{})},...init});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.message||"요청 처리에 실패했습니다.");return body;}

export function EmissionDataRequestFunctionalPage(){
 const params=new URLSearchParams(location.search);
 const [projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(params.get("projectId")||"");
 const [payload,setPayload]=useState<Payload>({items:[],dataOwners:[],actorRoles:[],events:[]}),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const [form,setForm]=useState({title:"월별 활동자료 및 증빙 제출 요청",detail:"산정기간의 활동자료를 입력하고 원본 증빙을 함께 제출해 주세요.",requestedItems:"연료 사용량, 전력 사용량, 생산량, 계량기·고지서 증빙",assignee:"",dueDate:""});
 const [correction,setCorrection]=useState<Record<number,{reason:string;dueDate:string}>>({});
 const api=(path:string)=>buildLocalizedPath(`/home/api${path}`,`/en/home/api${path}`);
 const canManage=payload.actorRoles?.includes("COMPANY_MANAGER");
 const summary=useMemo(()=>({open:payload.items.filter(i=>!["ACCEPTED","CLOSED","CANCELLED"].includes(i.status)).length,review:payload.items.filter(i=>i.status==="SUBMITTED").length,correction:payload.items.filter(i=>i.status==="CORRECTION_REQUIRED").length}),[payload.items]);
 useEffect(()=>{json(api("/emission-projects?size=100")).then(v=>{setProjects(v.items||[]);if(!projectId&&v.items?.[0])setProjectId(v.items[0].id)}).catch(e=>setError(e.message))},[]);
 const load=()=>projectId?json(api(`/emission-projects/${projectId}/activity-requests`)).then(v=>{setPayload(v);if(!form.assignee&&v.dataOwners?.[0])setForm(f=>({...f,assignee:v.dataOwners[0].id}))}).catch(e=>setError(e.message)):Promise.resolve();
 useEffect(()=>{void load()},[projectId]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");setMessage("");try{await json(api(`/emission-projects/${projectId}/activity-requests`),{method:"POST",body:JSON.stringify(form)});setMessage("담당자에게 제출 요청과 마감 알림을 전송했습니다.");await load()}catch(x){setError((x as Error).message)}finally{setBusy(false)}};
 const start=async(id:number)=>{setBusy(true);setError("");try{await json(api(`/emission-projects/${projectId}/activity-requests/${id}/start`),{method:"POST",body:"{}"});await load()}catch(x){setError((x as Error).message)}finally{setBusy(false)}};
 const decide=async(id:number,decision:"ACCEPT"|"REQUEST_CORRECTION")=>{const value=correction[id]||{reason:"",dueDate:""};setBusy(true);setError("");setMessage("");try{const result=await json(api(`/emission-projects/${projectId}/activity-requests/${id}/decision`),{method:"POST",body:JSON.stringify({decision,...value})});setMessage(decision==="ACCEPT"?(result.calculationOpened?"모든 요청을 접수했습니다. 산정 업무가 열렸습니다.":`접수했습니다. 남은 요청 ${result.remainingRequests}건을 처리해 주세요.`):"보완 요청과 새 마감일을 담당자에게 전송했습니다.");await load()}catch(x){setError((x as Error).message)}finally{setBusy(false)}};
 return <div className="min-h-screen bg-slate-50 text-slate-900"><header className="border-b-2 border-[#003764] bg-white"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4"><a className="text-xl font-black text-[#003764]" href={buildLocalizedPath("/home","/en/home")}>CCUS 통합 플랫폼</a><a className="font-bold text-[#246beb]" href={buildLocalizedPath("/emission/my-tasks","/en/emission/my-tasks")}>내 업무</a></div></header><main className="mx-auto max-w-7xl px-4 py-8">
  <p className="text-sm font-bold text-slate-500">탄소배출 관리 / 활동자료</p><h1 className="mt-2 text-3xl font-black">자료 제출 요청·접수</h1><p className="mt-3 text-slate-600">요청, 수집, 품질검사, 제출, 보완, 재제출, 관리자 접수를 하나의 이력으로 관리합니다. 모든 활성 요청이 접수되어야 산정 업무가 열립니다.</p>
  {error&&<div className="mt-5 rounded-lg border border-red-300 bg-red-50 p-4 font-bold text-red-700">{error}</div>}{message&&<div className="mt-5 rounded-lg border border-blue-300 bg-blue-50 p-4 font-bold text-blue-800">{message}</div>}
  <section className="mt-6 rounded-xl border bg-white p-5"><label className="font-bold">대상 프로젝트<select className="mt-2 h-12 w-full rounded-lg border px-3" value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">선택</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name} · {p.site} · {p.step}</option>)}</select></label></section>
  <section className="mt-4 grid gap-3 sm:grid-cols-3">{[["진행 요청",summary.open],["접수 검토",summary.review],["보완 필요",summary.correction]].map(([label,value])=><div className="rounded-xl border bg-white p-4" key={String(label)}><p className="text-sm font-bold text-slate-500">{label}</p><p className="mt-1 text-2xl font-black">{value}건</p></div>)}</section>
  <div className={`mt-6 grid gap-6 ${canManage?"lg:grid-cols-[420px_1fr]":""}`}>{canManage&&<form className="rounded-xl border bg-white p-5" onSubmit={submit}><h2 className="text-xl font-black">새 요청</h2>{[["title","요청 제목"],["detail","요청 내용"],["requestedItems","요청 항목"]].map(([key,label])=><label className="mt-4 block font-bold" key={key}>{label}<textarea className="mt-2 min-h-20 w-full rounded-lg border p-3 font-normal" value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label className="mt-4 block font-bold">담당자<select required className="mt-2 h-11 w-full rounded-lg border px-3 font-normal" value={form.assignee} onChange={e=>setForm({...form,assignee:e.target.value})}><option value="">사업장 자료 담당자 선택</option>{payload.dataOwners.map(a=><option key={a.id}>{a.id}</option>)}</select></label><label className="mt-4 block font-bold">제출 마감일<input required type="date" className="mt-2 h-11 w-full rounded-lg border px-3 font-normal" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><button disabled={busy||!projectId} className="mt-5 h-12 w-full rounded-lg bg-[#246beb] font-black text-white disabled:bg-slate-300">요청·알림 전송</button></form>}
  <section className="overflow-hidden rounded-xl border bg-white"><div className="border-b p-5"><h2 className="text-xl font-black">요청 및 처리 현황</h2><p className="mt-1 text-sm text-slate-500">보완 사유와 마감, 제출 버전, 접수 결과를 요청 단위로 추적합니다.</p></div><div className="divide-y">{payload.items.map(r=><article key={r.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong className="text-lg">{r.title}</strong><p className="mt-1 text-sm text-slate-600">{r.requestedItems}</p><p className="mt-2 text-xs text-slate-500">담당 {r.assignee} · 마감 {r.dueDate} · 보완 {r.correctionCount||0}회 {r.submissionId?`· 제출 #${r.submissionId}`:""}</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-sm font-black text-blue-800">{statusLabel[r.status]||r.status}</span></div>{r.correctionReason&&<div className="mt-3 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm"><strong>보완 사유</strong> {r.correctionReason}<span className="ml-2 text-slate-600">재제출 마감 {r.correctionDueDate}</span></div>}<div className="mt-4 flex flex-wrap gap-2">{["REQUESTED","CORRECTION_REQUIRED"].includes(r.status)&&<button className="rounded-lg border border-blue-600 px-3 py-2 font-bold text-blue-700" onClick={()=>start(r.id)}>업무 시작</button>}{r.status==="IN_PROGRESS"&&<a className="rounded-lg bg-blue-700 px-3 py-2 font-bold text-white" href={buildLocalizedPath(`/emission/activity-data?projectId=${projectId}&requestId=${r.id}`,`/en/emission/activity-data?projectId=${projectId}&requestId=${r.id}`)}>입력·업로드·품질검사</a>}{canManage&&r.status==="SUBMITTED"&&<button disabled={busy} className="rounded-lg bg-blue-700 px-3 py-2 font-bold text-white" onClick={()=>decide(r.id,"ACCEPT")}>접수하고 다음 단계 확인</button>}</div>{canManage&&r.status==="SUBMITTED"&&<div className="mt-3 grid gap-2 rounded-lg bg-slate-50 p-3 sm:grid-cols-[1fr_170px_auto]"><input className="h-10 rounded-lg border px-3" placeholder="보완 사유(필수)" value={correction[r.id]?.reason||""} onChange={e=>setCorrection({...correction,[r.id]:{reason:e.target.value,dueDate:correction[r.id]?.dueDate||""}})}/><input type="date" className="h-10 rounded-lg border px-3" value={correction[r.id]?.dueDate||""} onChange={e=>setCorrection({...correction,[r.id]:{reason:correction[r.id]?.reason||"",dueDate:e.target.value}})}/><button disabled={busy||!correction[r.id]?.reason||!correction[r.id]?.dueDate} className="rounded-lg border border-amber-600 px-3 font-bold text-amber-800 disabled:opacity-40" onClick={()=>decide(r.id,"REQUEST_CORRECTION")}>보완 요청</button></div>}</article>)}{!payload.items.length&&<p className="p-12 text-center text-slate-500">등록된 요청이 없습니다.</p>}</div></section></div>
  <section className="mt-6 rounded-xl border bg-white p-5"><h2 className="text-xl font-black">업무 이력</h2><ol className="mt-4 space-y-3">{payload.events.slice(0,20).map(e=><li className="grid gap-1 border-l-4 border-blue-300 pl-3 text-sm sm:grid-cols-[180px_1fr]" key={e.id}><span className="font-bold">{e.code} · {e.actor}</span><span>{e.previousStatus?`${statusLabel[e.previousStatus]||e.previousStatus} → `:""}{statusLabel[e.newStatus]||e.newStatus}{e.note?` · ${e.note}`:""}</span></li>)}{!payload.events.length&&<li className="text-sm text-slate-500">아직 이력이 없습니다.</li>}</ol></section>
 </main></div>;
}
