import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { buildLocalizedPath } from "../../lib/navigation/runtime";
import { CommonPageContainer } from "../../components/common-design/CommonDesignPrimitives";
import { EmissionPageIntro } from "../emission-common/EmissionPageIntro";

type Project={id:string;name:string;site:string;step:string};
type RequestItem={id:number;title:string;detail:string;requestedItems:string;requester:string;assignee:string;dueDate:string;status:string;submissionId?:number;correctionReason?:string;correctionDueDate?:string;correctionCount?:number;acceptedBy?:string;acceptedAt?:string};
type EventItem={id:number;requestId:number;code:string;previousStatus?:string;newStatus:string;actor:string;note?:string;createdAt:string};
type Payload={items:RequestItem[];dataOwners:{id:string}[];actorRoles:string[];events:EventItem[];canManage:boolean};

const statusLabel:Record<string,string>={REQUESTED:"요청",IN_PROGRESS:"수집 중",SUBMITTED:"접수 검토",CORRECTION_REQUIRED:"보완 필요",ACCEPTED:"접수 완료",CLOSED:"종료",CANCELLED:"취소"};
const emptyPayload:Payload={items:[],dataOwners:[],actorRoles:[],events:[],canManage:false};
async function json(url:string,init?:RequestInit){const response=await fetch(url,{credentials:"include",headers:{"Content-Type":"application/json",Accept:"application/json",...(init?.headers||{})},...init});const body=await response.json().catch(()=>({}));if(response.status===401){const back=encodeURIComponent(location.pathname+location.search);location.assign(buildLocalizedPath(`/signin/loginView?returnUrl=${back}`,`/en/signin/loginView?returnUrl=${back}`));throw new Error("로그인이 필요합니다.");}if(!response.ok)throw new Error(body.message||"요청 처리에 실패했습니다.");return body;}
const defaultDueDate=()=>{const date=new Date();date.setDate(date.getDate()+7);return date.toISOString().slice(0,10)};

export function EmissionDataRequestFunctionalPage(){
 const params=new URLSearchParams(location.search);
 const [projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(params.get("projectId")||"");
 const [payload,setPayload]=useState<Payload>(emptyPayload),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[projectsLoading,setProjectsLoading]=useState(true);
 const loadSequence=useRef(0);
 const [form,setForm]=useState({title:"월별 활동자료 및 증빙 제출 요청",detail:"산정기간의 활동자료를 입력하고 원본 증빙을 함께 제출해 주세요.",requestedItems:"연료 사용량, 전력 사용량, 생산량, 계량기·고지서 증빙",assignee:"",dueDate:defaultDueDate(),collectionFrequency:"월별",measurementMethod:"계량기·고지서 원본 확인",evidenceRequirements:"계량기 사진 또는 고지서, 기간·단위 표시"});
 const [assigneeSearch,setAssigneeSearch]=useState(""),[assigneePickerOpen,setAssigneePickerOpen]=useState(false);
 const [correction,setCorrection]=useState<Record<number,{reason:string;dueDate:string}>>({});
 const api=(path:string)=>buildLocalizedPath(`/home/api${path}`,`/en/home/api${path}`);
 const canCreate=payload.canManage||payload.actorRoles?.includes("COMPANY_MANAGER");
 const canReview=payload.canManage||payload.actorRoles?.some(role=>["COMPANY_MANAGER","APPROVER"].includes(role));
 const summary=useMemo(()=>({open:payload.items.filter(i=>!["ACCEPTED","CLOSED","CANCELLED"].includes(i.status)).length,review:payload.items.filter(i=>i.status==="SUBMITTED").length,correction:payload.items.filter(i=>i.status==="CORRECTION_REQUIRED").length}),[payload.items]);
 useEffect(()=>{let active=true;setProjectsLoading(true);json(api("/emission-projects?page=1&size=100")).then(v=>{if(!active)return;const available=Array.isArray(v.items)?v.items:[];setProjects(available);if(!projectId&&available[0])selectProject(available[0].id)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setProjectsLoading(false)});return()=>{active=false}},[]);
 function selectProject(id:string){loadSequence.current++;setPayload(emptyPayload);setError("");setMessage("");setCorrection({});setForm(f=>({...f,assignee:""}));setProjectId(id);const url=new URL(location.href);if(id)url.searchParams.set("projectId",id);else url.searchParams.delete("projectId");history.replaceState(history.state,"",url.pathname+url.search+url.hash);}
 const load=async(targetId=projectId)=>{if(!targetId){setPayload(emptyPayload);return;}const sequence=++loadSequence.current;setLoading(true);setPayload(emptyPayload);setError("");try{const v=await json(api(`/emission-projects/${encodeURIComponent(targetId)}/activity-requests`));if(sequence!==loadSequence.current||targetId!==projectId)return;setPayload(v);setForm(f=>({...f,assignee:v.dataOwners?.some((owner:{id:string})=>owner.id===f.assignee)?f.assignee:(v.dataOwners?.[0]?.id||"")}));}catch(e){if(sequence===loadSequence.current&&targetId===projectId){setPayload(emptyPayload);setError((e as Error).message)}}finally{if(sequence===loadSequence.current)setLoading(false)}};
 useEffect(()=>{setPayload(emptyPayload);setError("");setMessage("");setCorrection({});if(projectId)void load(projectId);else setLoading(false);return()=>{loadSequence.current++}},[projectId]);
 const submit=async(e:FormEvent)=>{e.preventDefault();if(busy||!projectId)return;setBusy(true);setError("");setMessage("");try{const detail=[form.detail.trim(),"",`[수집 계획] 주기: ${form.collectionFrequency} / 측정 방법: ${form.measurementMethod} / 증빙: ${form.evidenceRequirements}`].filter(Boolean).join("\n");await json(api(`/emission-projects/${encodeURIComponent(projectId)}/activity-requests`),{method:"POST",body:JSON.stringify({...form,detail})});setMessage("담당자에게 제출 요청과 마감 알림을 전송했습니다.");await load(projectId)}catch(x){setError((x as Error).message)}finally{setBusy(false)}};
 const start=async(id:number)=>{setBusy(true);setError("");try{await json(api(`/emission-projects/${projectId}/activity-requests/${id}/start`),{method:"POST",body:"{}"});await load()}catch(x){setError((x as Error).message)}finally{setBusy(false)}};
 const decide=async(id:number,decision:"ACCEPT"|"REQUEST_CORRECTION")=>{const value=correction[id]||{reason:"",dueDate:""};setBusy(true);setError("");setMessage("");try{const result=await json(api(`/emission-projects/${projectId}/activity-requests/${id}/decision`),{method:"POST",body:JSON.stringify({decision,...value})});setMessage(decision==="ACCEPT"?(result.calculationOpened?"모든 요청을 접수했습니다. 산정 업무가 열렸습니다.":`접수했습니다. 남은 요청 ${result.remainingRequests}건을 처리해 주세요.`):"보완 요청과 새 마감일을 담당자에게 전송했습니다.");await load()}catch(x){setError((x as Error).message)}finally{setBusy(false)}};
 return <CommonPageContainer className="text-slate-900">
  <EmissionPageIntro category="탄소배출 관리 / 활동자료" title="자료 제출 요청·접수" description="요청, 수집, 품질검사, 제출, 보완, 재제출, 관리자 접수를 하나의 이력으로 관리합니다. 모든 활성 요청이 접수되어야 산정 업무가 열립니다." actions={<a className="krds-button rounded border bg-white px-4 py-2 font-bold" href={buildLocalizedPath("/emission/project_list","/en/emission/project_list")}>배출량 프로젝트</a>}/>
  {error&&<div className="mt-5 rounded-lg border border-red-300 bg-red-50 p-4 font-bold text-red-700">{error}</div>}{message&&<div className="mt-5 rounded-lg border border-blue-300 bg-blue-50 p-4 font-bold text-blue-800">{message}</div>}
  <section className="mt-6 rounded-xl border bg-white p-5"><label className="font-bold">대상 프로젝트<select className="krds-control mt-2 h-12 w-full rounded-lg border px-3" value={projectId} disabled={projectsLoading||busy} onChange={e=>selectProject(e.target.value)}><option value="">{projectsLoading?"프로젝트 불러오는 중":"프로젝트 선택"}</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name} · {p.site} · {p.step}</option>)}</select></label>{projectId&&<p className="mt-2 text-xs text-slate-500">선택 프로젝트 ID: {projectId} · 새로고침 후에도 선택이 유지됩니다.</p>}</section>
  <section className="mt-4 grid gap-3 sm:grid-cols-3">{[["진행 요청",summary.open],["접수 검토",summary.review],["보완 필요",summary.correction]].map(([label,value])=><div className="rounded-xl border bg-white p-4" key={String(label)}><p className="text-sm font-bold text-slate-500">{label}</p><p className="mt-1 text-2xl font-black">{value}건</p></div>)}</section>
  <div className={`mt-6 grid gap-6 ${canCreate?"lg:grid-cols-[420px_1fr]":""}`}>{canCreate&&<form className="rounded-xl border bg-white p-5" onSubmit={submit}><h2 className="text-xl font-black">새 요청</h2>{[["title","요청 제목"],["detail","요청 내용"],["requestedItems","요청 항목"]].map(([key,label])=><label className="mt-4 block font-bold" key={key}>{label}<textarea className="mt-2 min-h-20 w-full rounded-lg border p-3 font-normal" value={(form as any)[key]} onChange={e=>setForm(current=>({...current,[key]:e.target.value}))}/></label>)}<fieldset className="mt-4 rounded-lg border p-3"><legend className="px-1 font-bold">수집 계획</legend><label className="block text-sm font-bold">수집 주기<select className="mt-1 h-10 w-full rounded-lg border px-3 font-normal" value={form.collectionFrequency} onChange={e=>setForm(current=>({...current,collectionFrequency:e.target.value}))}>{["매월","분기별","반기별","연간","일회성"].map(x=><option key={x}>{x}</option>)}</select></label><label className="mt-3 block text-sm font-bold">측정·수집 방법<input className="mt-1 h-10 w-full rounded-lg border px-3 font-normal" value={form.measurementMethod} onChange={e=>setForm(current=>({...current,measurementMethod:e.target.value}))}/></label><label className="mt-3 block text-sm font-bold">필수 증빙<input className="mt-1 h-10 w-full rounded-lg border px-3 font-normal" value={form.evidenceRequirements} onChange={e=>setForm(current=>({...current,evidenceRequirements:e.target.value}))}/></label></fieldset><div className="mt-4"><span className="block font-bold">담당자</span><div className="mt-1 flex gap-2"><input aria-label="선택된 담당자" readOnly required value={form.assignee} placeholder="담당자를 선택하세요" className="h-11 min-w-0 flex-1 rounded-lg border bg-slate-50 px-3 font-normal"/><button type="button" className="rounded-lg border border-blue-700 px-4 font-bold text-blue-800" onClick={()=>{setAssigneeSearch("");setAssigneePickerOpen(true)}}>담당자 검색</button></div></div><label className="mt-4 block font-bold">제출 마감일<input required type="date" className="mt-2 h-11 w-full rounded-lg border px-3 font-normal" value={form.dueDate} onChange={e=>setForm(current=>({...current,dueDate:e.target.value}))}/></label><button disabled={busy||loading||!projectId||!form.assignee} className="mt-5 h-12 w-full rounded-lg bg-[#246beb] font-black text-white disabled:bg-slate-300">{busy?"전송 중…":"요청·알림 전송"}</button></form>}
  <section className="overflow-hidden rounded-xl border bg-white"><div className="border-b p-5"><h2 className="text-xl font-black">요청 및 처리 현황</h2><p className="mt-1 text-sm text-slate-500">보완 사유와 마감, 제출 버전, 접수 결과를 요청 단위로 추적합니다.</p></div><div className="divide-y">{loading?<p className="p-12 text-center text-slate-500">요청 현황을 불러오는 중입니다…</p>:payload.items.map(r=><article key={r.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong className="text-lg">{r.title}</strong><p className="mt-1 text-sm text-slate-600">{r.requestedItems}</p>{r.detail&&<p className="mt-2 whitespace-pre-wrap rounded-lg bg-slate-50 p-3 text-sm text-slate-700">{r.detail}</p>}<p className="mt-2 text-xs text-slate-500">담당 {r.assignee} · 마감 {r.dueDate} · 보완 {r.correctionCount||0}회 {r.submissionId?`· 제출 #${r.submissionId}`:""}</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-sm font-black text-blue-800">{statusLabel[r.status]||r.status}</span></div>{r.correctionReason&&<div className="mt-3 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm"><strong>보완 사유</strong> {r.correctionReason}<span className="ml-2 text-slate-600">재제출 마감 {r.correctionDueDate}</span></div>}<div className="mt-4 flex flex-wrap gap-2">{["REQUESTED","CORRECTION_REQUIRED"].includes(r.status)&&<button disabled={busy} className="rounded-lg border border-blue-600 px-3 py-2 font-bold text-blue-700 disabled:opacity-50" onClick={()=>start(r.id)}>업무 시작</button>}{r.status==="IN_PROGRESS"&&<a className="rounded-lg bg-blue-700 px-3 py-2 font-bold text-white" href={buildLocalizedPath(`/emission/activity-data?projectId=${projectId}&requestId=${r.id}`,`/en/emission/activity-data?projectId=${projectId}&requestId=${r.id}`)}>입력·업로드·품질검사</a>}{canReview&&r.status==="SUBMITTED"&&<button disabled={busy} className="rounded-lg bg-blue-700 px-3 py-2 font-bold text-white" onClick={()=>decide(r.id,"ACCEPT")}>접수하고 다음 단계 확인</button>}</div>{canReview&&r.status==="SUBMITTED"&&<div className="mt-3 grid gap-2 rounded-lg bg-slate-50 p-3 sm:grid-cols-[1fr_170px_auto]"><input className="h-10 rounded-lg border px-3" placeholder="보완 사유(필수)" value={correction[r.id]?.reason||""} onChange={e=>setCorrection(current=>({...current,[r.id]:{reason:e.target.value,dueDate:current[r.id]?.dueDate||defaultDueDate()}}))}/><input type="date" className="h-10 rounded-lg border px-3" value={correction[r.id]?.dueDate||""} onChange={e=>setCorrection(current=>({...current,[r.id]:{reason:current[r.id]?.reason||"",dueDate:e.target.value}}))}/><button disabled={busy||!correction[r.id]?.reason||!correction[r.id]?.dueDate} className="rounded-lg border border-amber-600 px-3 font-bold text-amber-800 disabled:opacity-40" onClick={()=>decide(r.id,"REQUEST_CORRECTION")}>보완 요청</button></div>}</article>)}{!loading&&projectId&&!payload.items.length&&<p className="p-12 text-center text-slate-500">등록된 요청이 없습니다.</p>}{!projectId&&<p className="p-12 text-center text-slate-500">프로젝트를 선택하세요.</p>}</div></section></div>
  <section className="mt-6 rounded-xl border bg-white p-5"><h2 className="text-xl font-black">업무 이력</h2><ol className="mt-4 space-y-3">{payload.events.slice(0,20).map(e=><li className="grid gap-1 border-l-4 border-blue-300 pl-3 text-sm sm:grid-cols-[180px_1fr]" key={e.id}><span className="font-bold">{e.code} · {e.actor}</span><span>{e.createdAt?new Date(e.createdAt).toLocaleString("ko-KR"):"시각 미기록"} · {e.previousStatus?`${statusLabel[e.previousStatus]||e.previousStatus} → `:""}{statusLabel[e.newStatus]||e.newStatus}{e.note?` · ${e.note}`:""}</span></li>)}{!payload.events.length&&<li className="text-sm text-slate-500">아직 이력이 없습니다.</li>}</ol></section>
  {assigneePickerOpen&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/50 p-4" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setAssigneePickerOpen(false)}}><section role="dialog" aria-modal="true" aria-labelledby="assignee-picker-title" className="w-full max-w-lg rounded-xl bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><h2 id="assignee-picker-title" className="text-xl font-black">사업장 자료 담당자 선택</h2><button type="button" aria-label="닫기" className="rounded border px-3 py-1" onClick={()=>setAssigneePickerOpen(false)}>닫기</button></div><p className="mt-1 text-sm text-slate-600">이 프로젝트에 자료 담당자로 배정된 계정만 표시합니다.</p><input autoFocus value={assigneeSearch} onChange={e=>setAssigneeSearch(e.target.value)} placeholder="계정 ID 검색" className="mt-4 h-11 w-full rounded-lg border px-3"/><ul className="mt-3 max-h-64 divide-y overflow-auto">{payload.dataOwners.filter(a=>a.id.toLocaleLowerCase().includes(assigneeSearch.trim().toLocaleLowerCase())).map(a=><li key={a.id}><button type="button" className="w-full rounded px-3 py-3 text-left hover:bg-blue-50" onClick={()=>{setForm(current=>({...current,assignee:a.id}));setAssigneePickerOpen(false)}}><strong>{a.id}</strong><span className="ml-2 text-sm text-slate-500">사업장 자료 담당자</span></button></li>)}{!payload.dataOwners.length&&<li className="p-4 text-sm text-amber-800">프로젝트에 자료 담당자가 지정되어 있지 않습니다. 프로젝트 권한을 먼저 설정해야 합니다.</li>}{payload.dataOwners.length>0&&!payload.dataOwners.some(a=>a.id.toLocaleLowerCase().includes(assigneeSearch.trim().toLocaleLowerCase()))&&<li className="p-4 text-sm text-slate-500">검색 결과가 없습니다.</li>}</ul></section></div>}
 </CommonPageContainer>;
}
