#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"; NS="${CARBONET_K8S_NAMESPACE:-carbonet-prod}"; DB="${POSTGRES_DB:-carbonet}"; U="${POSTGRES_ADMIN_USER:-postgres}"
CONTROLLER="$ROOT/modules/resonance-common/carbonet-common-core/src/main/java/egovframework/com/feature/home/web/EmissionProjectRegistryController.java"; SERVICE="$ROOT/modules/resonance-common/carbonet-common-core/src/main/java/egovframework/com/feature/home/service/EmissionProjectRegistryService.java"; VERIFY="$ROOT/modules/resonance-common/carbonet-common-core/src/main/java/egovframework/com/feature/admin/web/ReportVerificationRegistryController.java"; ROUTES="$ROOT/projects/carbonet-frontend/source/src/app/routes/families/emissionMonitoringFamily.ts"
for p in '/reports' '/finalize' '/issue' '/download'; do grep -Fq "$p" "$CONTROLLER" || { echo "[report-evidence] FAIL controller=$p" >&2;exit 1;};done
for p in createReport finalizeReport issueReportCertificate recordReportDownload verifyReportCertificate; do grep -Fq "$p" "$SERVICE"||{ echo "[report-evidence] FAIL service=$p" >&2;exit 1;};done
for p in verify verifyOcr; do grep -Fq "$p" "$VERIFY"||exit 1;done
for p in /emission/report_submit /emission/report-download /admin/emission/report-certificates /admin/emission/survey-report /admin/emission/survey-report-verify; do grep -Fq "$p" "$ROUTES"||{ echo "[report-evidence] FAIL route=$p" >&2;exit 1;};done
leader="";while read -r pod;do [[ "$(kubectl -n "$NS" exec "$pod" -c patroni -- psql -h 127.0.0.1 -U "$U" -d "$DB" -Atqc 'select pg_is_in_recovery()' 2>/dev/null||true)" == f ]]&&{ leader="$pod";break;};done < <(kubectl -n "$NS" get pods -l app=postgres-patroni -o name|sed 's#pod/##');[[ -n "$leader" ]]||exit 1
sql="do \$\$ declare missing integer;invalid integer;uncovered integer;begin select count(*) into missing from (values('emission_project_report'),('emission_report_certificate_audit'),('emission_report_access_ledger'),('emission_calculation_run'),('emission_activity_submission'))r(n) where to_regclass(n)is null;select count(*) into invalid from framework_professional_screen_contract where process_code='REPORT_CERTIFICATION' and(contract_status<>'VERIFIED'or not api_verified or not database_verified or not authority_verified or not responsive_verified or not accessibility_verified or not exception_states_verified);select count(*) into uncovered from framework_process_step s cross join lateral unnest(array_remove(array[s.user_path,s.admin_path],null))route left join framework_common_design_asset_coverage c on c.route_path=lower(split_part(route,'?',1)) where s.process_code='REPORT_CERTIFICATION' and coalesce(c.common_assets_ready,false)=false;if missing>0 or invalid>0 or uncovered>0 then raise exception 'report evidence failed tables=% contracts=% routes=%',missing,invalid,uncovered;end if;update framework_development_job set job_status='COMPLETED',approval_status='APPROVED',quality_status='PASSED',evidence_ref='verified:report-source+schema+route+common-assets',last_error=null,completed_at=current_timestamp,updated_at=current_timestamp where process_code='REPORT_CERTIFICATION' and job_type in('DESIGN','DATABASE','API','BACKEND','API_QUALITY','DATABASE_QUALITY','FRONTEND_USER','FRONTEND_ADMIN','DESIGN_PREFLIGHT','COMPONENT_COMMON','CLASS_PROPERTY_COMMON','UI_QUALITY','SEARCH');update framework_process_artifact set delivery_status='VERIFIED',evidence_ref='verified:report-source+schema+route+common-assets',updated_at=current_timestamp where process_code='REPORT_CERTIFICATION';end \$\$;select count(*)filter(where job_status in('COMPLETED','VERIFIED'))||'|'||count(*) from framework_development_job where process_code='REPORT_CERTIFICATION' and required;"
r="$(kubectl -n "$NS" exec "$leader" -c patroni -- psql -h 127.0.0.1 -U "$U" -d "$DB" -At -v ON_ERROR_STOP=1 -c "$sql")";echo "[report-evidence] PASS completed-required=$r source=verified schema=verified routes=verified common-assets=verified"
