#!/usr/bin/env bash
#===========================================
# DB Auto Backup Script
# Exports DB to Git, commits, and pushes
# With size limits and cleanup
#===========================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="/opt/Resonance"
EXPORT_SCRIPT="$SCRIPT_DIR/export-cubrid-to-git.py"
DATA_DIR="$ROOT_DIR/db/data"

# Configuration
MAX_BACKUP_SIZE_MB=100
MAX_EXPORTS=10  # Keep only last N exports
MAX_AGE_DAYS=7  # Delete exports older than N days

log() { echo "[$(date '+%Y-%m-%dT%H:%M:%S')] [BACKUP] $*"; }

#===========================================
# Check backup size
#===========================================
check_size() {
    local size_mb=$(du -sm "$DATA_DIR" 2>/dev/null | cut -f1 || echo "0")
    log "Current backup size: ${size_mb}MB"

    if [[ $size_mb -gt $MAX_BACKUP_SIZE_MB ]]; then
        log "ERROR: Backup size exceeds limit of ${MAX_BACKUP_SIZE_MB}MB"
        return 1
    fi
    return 0
}

#===========================================
# Clean up old exports
#===========================================
cleanup_old_exports() {
    log "=== Cleaning up old exports ==="

    # Count exports
    local export_count
    export_count=$(ls -d "$DATA_DIR"/*/ 2>/dev/null | wc -l)

    log "Current exports: $export_count"

    if [[ $export_count -gt $MAX_EXPORTS ]]; then
        log "Removing old exports (keeping $MAX_EXPORTS)..."

        # Keep only the N most recent
        ls -dt "$DATA_DIR"/*/ 2>/dev/null | tail -n +$((MAX_EXPORTS + 1)) | while read dir; do
            log "Removing: $(basename "$dir")"
            rm -rf "$dir"
        done
    fi

    # Remove exports older than MAX_AGE_DAYS
    find "$DATA_DIR" -type d -name "2*" -mtime +$MAX_AGE_DAYS 2>/dev/null | while read dir; do
        log "Removing old: $(basename "$dir")"
        rm -rf "$dir"
    done
}

#===========================================
# Export DB to Git
#===========================================
export_db() {
    log "Exporting database to Git..."

    # Check CUBRID connection
    if ! kubectl exec cubrid-carbonet-0 -n carbonet-prod -- \
        csql -u dba carbonet -c "SELECT 1;" >/dev/null 2>&1; then
        log "WARNING: CUBRID not accessible, skipping export"
        return 1
    fi

    # Run export
    python3 "$EXPORT_SCRIPT" 2>&1 | grep -v DeprecationWarning

    log "Export complete"
}

#===========================================
# Commit to Git
#===========================================
commit_to_git() {
    cd "$ROOT_DIR"

    # Check for changes
    if [[ -z "$(git status --porcelain db/)" ]]; then
        log "No changes to commit"
        return 0
    fi

    # Get export timestamp
    local export_id
    export_id=$(ls -dt "$DATA_DIR"/*/ 2>/dev/null | head -1 | xargs basename 2>/dev/null || echo "unknown")

    git add db/

    git config --local user.email "db-auto-backup@resonance"
    git config --local user.name "DB Auto Backup"

    local commit_msg="chore(db): auto-backup $(date -u +%Y-%m-%dT%H:%M:%S)

Export ID: $export_id
Backup Size: $(du -sm "$DATA_DIR" 2>/dev/null | cut -f1 || echo "?")MB
Trigger: ${TRIGGER_SOURCE:-manual}

Auto-generated by DB GitOps Auto-Backup"

    git commit -m "$commit_msg"
    log "Committed: $(git rev-parse --short HEAD)"
}

#===========================================
# Push to remote
#===========================================
push_to_remote() {
    cd "$ROOT_DIR"

    # Check if remote has token
    if git remote get-url origin 2>/dev/null | grep -q "ghp_"; then
        log "Pushing to remote..."
        git push origin main 2>&1 || log "Push failed"
    else
        log "No GitHub token configured, skipping push"
    fi
}

#===========================================
# Full backup cycle
#===========================================
run_backup() {
    local start_time=$(date +%s)

    log "=== Starting Backup Cycle ==="
    log "Trigger: ${TRIGGER_SOURCE:-manual}"

    # Pre-flight checks
    check_size || {
        log "Size check failed, cleaning up and retrying..."
        cleanup_old_exports
        check_size || {
            log "ERROR: Size still exceeds limit after cleanup"
            return 1
        }
    }

    # Export
    export_db || log "Export failed, continuing with existing data"

    # Commit
    commit_to_git

    # Push
    push_to_remote

    # Cleanup
    cleanup_old_exports

    local end_time=$(date +%s)
    local duration=$((end_time - start_time))

    log "=== Backup Complete: ${duration}s ==="
}

#===========================================
# Status
#===========================================
status() {
    echo "=== DB Auto Backup Status ==="
    echo ""
    echo "Configuration:"
    echo "  Max backup size: ${MAX_BACKUP_SIZE_MB}MB"
    echo "  Max exports: ${MAX_EXPORTS}"
    echo "  Max age: ${MAX_AGE_DAYS} days"
    echo ""
    echo "Current backup size:"
    du -sh "$DATA_DIR" 2>/dev/null || echo "  No data"
    echo ""
    echo "Exports:"
    ls -dt "$DATA_DIR"/*/ 2>/dev/null | head -5 | while read dir; do
        echo "  $(basename "$dir") - $(du -sh "$dir" | cut -f1)"
    done || echo "  None"
    echo ""
    echo "Git status:"
    cd "$ROOT_DIR"
    echo "  Last commit: $(git log -1 --oneline 2>/dev/null || echo 'none')"
    echo "  Remote: $(git remote get-url origin 2>/dev/null | head -c 50)..."
}

#===========================================
# Main
#===========================================
TRIGGER_SOURCE="${TRIGGER_SOURCE:-manual}"

case "${1:-}" in
    backup|run)
        run_backup
        ;;
    status|info)
        status
        ;;
    cleanup)
        cleanup_old_exports
        ;;
    check)
        check_size
        ;;
    *)
        echo "DB Auto Backup Script"
        echo ""
        echo "Usage: $0 {backup|status|cleanup|check}"
        echo ""
        echo "Environment:"
        echo "  TRIGGER_SOURCE=manual|cron|github-actions"
        ;;
esac