#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
service="$root/modules/resonance-common/carbonet-common-core/src/main/java/egovframework/com/feature/home/service/EmissionProjectRegistryService.java"
controller="$root/modules/resonance-common/carbonet-common-core/src/main/java/egovframework/com/feature/home/web/EmissionProjectRegistryController.java"
ui="$root/projects/carbonet-frontend/source/src/features/work-assignment/WorkAssignmentPage.tsx"
process_migration="$root/apps/carbonet-api/src/main/resources/db/migration/postgresql/V20260804170000__implement_tenant_work_assignment_process.sql"
registry_migration="$root/apps/carbonet-api/src/main/resources/db/migration/postgresql/V20260804190000__generalize_project_process_assignments.sql"

grep -Fq 'WORK_ASSIGNMENT_MANAGER_REQUIRED' "$service"
grep -Fq 'TENANT_ACCOUNT_NOT_ELIGIBLE' "$service"
grep -Fq 'framework_work_assignment_audit' "$service"
grep -Fq 'framework_process_definition' "$service"
grep -Fq 'framework_actor_definition' "$service"
grep -Fq 'framework_project_process_step_assignment' "$service"
grep -Fq 'framework_business_work_type' "$service"
grep -Fq 'w.sort_order' "$service"
grep -Fq 'seq.workflow_order' "$service"
grep -Fq 'topo.execution_wave' "$service"
grep -Fq 'topo.lane_order' "$service"
grep -Fq '/home/api/work-assignments' "$controller"
grep -Fq 'assignment-swimlane' "$ui"
grep -Fq 'workTypeCode' "$ui"
grep -Fq 'processAccountId' "$ui"
grep -Fq 'framework_project_process_step_assignment' "$registry_migration"
grep -Fq 'WORK_ASSIGNMENT-HAPPY' "$process_migration"
grep -Fq 'WORK_ASSIGNMENT-AUTH' "$process_migration"
grep -Fq 'WORK_ASSIGNMENT-ISOLATION' "$process_migration"
grep -Fq 'WORK_ASSIGNMENT-VALIDATION' "$process_migration"
grep -Fq 'WORK_ASSIGNMENT-RECOVERY' "$process_migration"

echo '[work-assignment] PASS catalog=all-work-types+all-processes+all-actors processOwner=required stepAssignment=generic executableTaskSync=conditional safetyTests=5 api=GET+POST tenantIsolation=server ui=swimlane-integrated audit=append-only'
