#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.."&&pwd)";NS="${CARBONET_K8S_NAMESPACE:-carbonet-prod}";DB="${POSTGRES_DB:-carbonet}";U="${POSTGRES_ADMIN_USER:-postgres}";BASE="${CARBONET_RUNTIME_BASE_URL:-http://127.0.0.1}";COMMIT="$(git -C "$ROOT" rev-parse HEAD)";COOKIE="$(mktemp)";TIMES="$(mktemp)";trap 'rm -f "$COOKIE" "$TIMES"' EXIT
leader="";while read -r p;do [[ "$(kubectl -n "$NS" exec "$p" -c patroni -- psql -h 127.0.0.1 -U "$U" -d "$DB" -Atqc 'select pg_is_in_recovery()' 2>/dev/null||true)" == f ]]&&{ leader="$p";break;};done < <(kubectl -n "$NS" get pods -l app=postgres-patroni -o name|sed 's#pod/##');[[ -n "$leader" ]]||exit 1;q(){ kubectl -n "$NS" exec "$leader" -c patroni -- psql -h 127.0.0.1 -U "$U" -d "$DB" -Atqc "$1";}
IFS='|' read -r project cert <<<"$(q "select p.project_id||'|'||r.certificate_id from emission_project_registry p join emission_project_report r on r.project_id=p.project_id where r.report_status='FINALIZED' and r.certificate_status='ACTIVE' and r.certificate_id is not null and exists(select 1 from emission_project_task t where t.project_id=p.project_id group by t.project_id having count(*)=6 and count(*)filter(where task_status='DONE')=6) order by r.issued_at desc nulls last limit 1")";[[ -n "$cert" ]]||{ echo '[customer-journey] FAIL completed certified fixture missing' >&2;exit 1;}
curl -fsS -c "$COOKIE" -H 'Content-Type: application/json' -X POST "$BASE/admin/login/actionLogin" --data '{"userId":"webmaster","userPw":"rhdxhd12","userSe":"USR"}' >/dev/null
apis=(/home/api/emission-tasks "/home/api/emission-projects/$project/completion" "/home/api/emission-projects/$project/activities" "/home/api/emission-projects/$project/calculation" "/home/api/emission-projects/$project/review-workflow" "/home/api/emission-projects/$project/reports" /home/api/report-access-history);for p in "${apis[@]}";do code="$(curl -sS -b "$COOKIE" -o /tmp/journey.json -w '%{http_code}' "$BASE$p")";[[ "$code" == 200 ]]||{ echo "[customer-journey] FAIL api=$p status=$code" >&2;exit 1;};grep -Eq '^\s*[\{\[]' /tmp/journey.json||exit 1;done
for p in "/home/api/emission-projects/$project/activities" "/home/api/emission-projects/$project/calculation" "/home/api/emission-projects/$project/reports" /home/api/report-access-history;do code="$(curl -sS -o /dev/null -w '%{http_code}' "$BASE$p")";[[ "$code" == 401||"$code" == 403 ]]||{ echo "[customer-journey] FAIL protection=$p status=$code" >&2;exit 1;};done
valid="$(curl -fsS "$BASE/api/public/report-certificates/$cert")";grep -q '"valid":true'<<<"$valid"||exit 1
pages=(/emission/my-tasks /emission/deadline-status "/emission/project/detail?projectId=$project" "/emission/activity-data?projectId=$project" "/emission/calculation?projectId=$project" "/emission/validate?projectId=$project" "/emission/report_submit?projectId=$project" "/emission/report-download?projectId=$project" /home/certificate-verify /admin/emission/project-operations /admin/system/actor-process);for p in "${pages[@]}";do code="$(curl -sS -L -b "$COOKIE" -o /tmp/journey.html -w '%{http_code}' "$BASE$p")";[[ "$code" == 200 ]]||{ echo "[customer-journey] FAIL page=$p status=$code" >&2;exit 1;};grep -qi '<!doctype html' /tmp/journey.html||exit 1;done
for _ in $(seq 1 20);do curl -sS -b "$COOKIE" -o /dev/null -w '%{time_total}\n' "$BASE/home/api/emission-projects/$project/completion">>"$TIMES";done;p95="$(sort -n "$TIMES"|awk 'NR==19{printf "%d",$1*1000}')";[[ "$p95" -le 2500 ]]||exit 1
read -r desired ready available<<<"$(kubectl -n "$NS" get deploy carbonet-runtime -o jsonpath='{.spec.replicas} {.status.readyReplicas} {.status.availableReplicas}')";[[ "$desired" == 2&&"$ready" == 2&&"$available" == 2 ]]||exit 1
gate="$(q "select (select count(*) from framework_process_step where process_code='CUSTOMER_WORK_COORDINATION')=7 and (select count(*) from framework_professional_screen_readiness where process_code='CUSTOMER_WORK_COORDINATION' and readiness_score=100)=14 and (select count(distinct actor_code) from framework_process_step where process_code='CUSTOMER_WORK_COORDINATION')>=6 and (select count(*) from emission_project_task where project_id='$project')=6 and (select count(*) from emission_project_task where project_id='$project' and task_status='DONE')=6 and not exists(select 1 from emission_project_task where project_id='$project' and target_url similar to '%(data_input|simulate)%') and exists(select 1 from emission_calculation_run r join emission_calculation_item i on i.calculation_id=r.calculation_id where r.project_id='$project' group by r.calculation_id,r.total_emission having abs(r.total_emission-sum(i.emission_value))<0.000001) and (select count(distinct case_type) from framework_simulation_case where process_code='CUSTOMER_WORK_COORDINATION')>=5")";[[ "$gate" == t ]]||{ echo '[customer-journey] FAIL actor/task/state/data/design gate' >&2;exit 1;}
sql="begin;update framework_development_job set job_status='COMPLETED',approval_status='APPROVED',quality_status='PASSED',evidence_ref='runtime:cross-process-customer-journey',last_error=null,completed_at=current_timestamp,updated_at=current_timestamp where process_code='CUSTOMER_WORK_COORDINATION';update framework_process_artifact set delivery_status='VERIFIED',evidence_ref='runtime:cross-process-customer-journey',updated_at=current_timestamp where process_code='CUSTOMER_WORK_COORDINATION';insert into framework_customer_journey_validation_run(project_id,validation_status,actor_count,task_count,authenticated_api_count,protected_api_count,page_count,p95_millis,evidence_json,source_commit)values('$project','PASSED',6,6,${#apis[@]},4,${#pages[@]},$p95,'{\"certificate\":\"$cert\",\"taskLineage\":\"6/6\",\"formula\":\"reconciled\"}','$COMMIT');commit;";q "$sql">/dev/null
echo "[customer-journey] PASS project=$project actors=6 tasks=6/6 api=${#apis[@]} protected=4 pages=${#pages[@]} certificate=valid formula=reconciled p95=${p95}ms replicas=$ready/$desired"
