#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
MIGRATION="$ROOT/apps/carbonet-api/src/main/resources/db/migration/postgresql/V20260721130000__orchestrate_contract_driven_process_completion.sql"
LOCK_GUARD="$ROOT/apps/carbonet-api/src/main/resources/db/migration/postgresql/V20260721131000__respect_locked_processes_in_contract_completion.sql"
RETRY_GUARD="$ROOT/apps/carbonet-api/src/main/resources/db/migration/postgresql/V20260721132000__reuse_failed_contract_completion_jobs.sql"
BOUNDED_RETRY="$ROOT/apps/carbonet-api/src/main/resources/db/migration/postgresql/V20260721133000__bound_contract_completion_retries.sql"
GENERATOR_SPEC="$ROOT/apps/carbonet-api/src/main/resources/db/migration/postgresql/V20260721134000__complete_contract_job_generator_spec.sql"
RUNTIME_RETRY="$ROOT/apps/carbonet-api/src/main/resources/db/migration/postgresql/V20260721135000__retry_contract_jobs_after_runtime_gate_fix.sql"
RACE_GUARD="$ROOT/apps/carbonet-api/src/main/resources/db/migration/postgresql/V20260721136000__close_contract_completion_races_and_page_gaps.sql"
PAGE_GUARD="$ROOT/apps/carbonet-api/src/main/resources/db/migration/postgresql/V20260721137000__require_step_page_contract_and_verified_quality.sql"
DESIGN_FACTORY="$ROOT/apps/carbonet-api/src/main/resources/db/migration/postgresql/V20260721138000__self_heal_orchestration_step_screen_contracts.sql"
ORCHESTRATOR="$ROOT/ops/scripts/run-project-auto-completion-orchestrator.sh"

test -s "$MIGRATION"
grep -Fq 'framework_contract_completion_queue' "$MIGRATION"
grep -Fq 'framework_run_contract_completion' "$MIGRATION"
grep -Fq "completion_status='VERIFIED'" "$MIGRATION"
grep -Fq "quality_status='VERIFIED'" "$MIGRATION"
grep -Fq "nullif(j.evidence_ref,'') IS NOT NULL" "$MIGRATION"
grep -Fq 'CONTRACT_DRIVEN_VERTICAL_COMPLETION_V1' "$MIGRATION"
grep -Fq 'framework_run_contract_completion' "$ORCHESTRATOR"
grep -Fq 'NOT p.definition_locked' "$LOCK_GUARD"
grep -Fq 'ON CONFLICT(process_code,step_code,job_type,target_path)' "$RETRY_GUARD"
grep -Fq "job_status='RETRY'" "$RETRY_GUARD"
grep -Fq 'attempt_count<framework_development_job.max_attempts' "$BOUNDED_RETRY"
grep -Fq "'generatorRequired',true" "$GENERATOR_SPEC"
grep -Fq "'requirement'" "$GENERATOR_SPEC"
grep -Fq 'SPEC_REPAIR_RETRY' "$GENERATOR_SPEC"
grep -Fq 'build/resources/main/static/react-app' "$ROOT/ops/scripts/resonance-k8s-build-deploy-80-v2.sh"
grep -Fq 'compiled classes preserved' "$ROOT/ops/scripts/resonance-k8s-build-deploy-80-v2.sh"
grep -Fq 'SERVER_CONTEXT_FIELDS' "$ROOT/ops/scripts/fast-process-package-test.py"
grep -Fq 'executable_tests' "$ROOT/ops/scripts/generate-full-stack-design-packages.py"
grep -Fq 'RUNTIME_GATE_REPAIR' "$RUNTIME_RETRY"
grep -Fq 'REQUIRED_PAGE_DESIGN_MISSING' "$RACE_GUARD"
grep -Fq 'ORPHAN_RESULT_RECONCILED' "$RACE_GUARD"
grep -Fq "updated_at < current_timestamp - interval" "$ORCHESTRATOR"
grep -Fq 'attempt_count=greatest(0,attempt_count-1)' "$ORCHESTRATOR"
grep -Fq 'dispatcher_failed=0' "$ORCHESTRATOR"
grep -Fq 'designed_page_count, 0) = 0' "$PAGE_GUARD"
grep -Eq 'PASSED.*character varying' "$PAGE_GUARD"
grep -Fq "quality_status='VERIFIED'" "$ROOT/ops/scripts/run-process-development-worker.sh"
grep -Fq 'framework_ensure_step_screen_contract' "$DESIGN_FACTORY"
grep -Fq "framework_ensure_step_screen_contract('" "$ROOT/ops/scripts/run-process-development-worker.sh"
grep -Fq 'DESIGN_FACTORY_RETRY' "$ORCHESTRATOR"
grep -Fq 'DESIGN_PREFLIGHT_RETRY' "$ORCHESTRATOR"

echo '[contract-completion] PASS deterministic queue, fail-closed verification, orchestrator integration'
