#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.."&&pwd)";NS="${CARBONET_K8S_NAMESPACE:-carbonet-prod}";DB="${POSTGRES_DB:-carbonet}";U="${POSTGRES_ADMIN_USER:-postgres}";BASE="${CARBONET_RUNTIME_BASE_URL:-http://127.0.0.1}";COOKIE="$(mktemp)";TIMES="$(mktemp)";API_BODY="$(mktemp)";PAGE_BODY="$(mktemp)";trap 'rm -f "$COOKIE" "$TIMES" "$API_BODY" "$PAGE_BODY"' EXIT
leader="";while read -r pod;do [[ "$(kubectl -n "$NS" exec "$pod" -c patroni -- psql -h 127.0.0.1 -U "$U" -d "$DB" -Atqc 'select pg_is_in_recovery()' 2>/dev/null||true)" == f ]]&&{ leader="$pod";break;};done < <(kubectl -n "$NS" get pods -l app=postgres-patroni -o name|sed 's#pod/##');[[ -n "$leader" ]]||exit 1
q(){ kubectl -n "$NS" exec "$leader" -c patroni -- psql -h 127.0.0.1 -U "$U" -d "$DB" -Atqc "$1";};IFS='|' read -r project report cert hash <<<"$(q "select project_id||'|'||report_id||'|'||certificate_id||'|'||integrity_hash from emission_project_report where report_status='FINALIZED' and certificate_status='ACTIVE' and certificate_id is not null order by issued_at desc nulls last limit 1")";[[ -n "$cert" ]]||{ echo '[report-runtime] FAIL active certificate missing' >&2;exit 1;}
curl -fsS -c "$COOKIE" -H 'Content-Type: application/json' -X POST "$BASE/admin/login/actionLogin" --data '{"userId":"webmaster","userPw":"rhdxhd12","userSe":"USR"}' >/dev/null
apis=("/home/api/emission-projects/$project/reports" "/home/api/emission-projects/$project/completion" "/home/api/report-access-history");for p in "${apis[@]}";do code="$(curl -sS -b "$COOKIE" -o "$API_BODY" -w '%{http_code}' "$BASE$p")";[[ "$code" == 200 ]]||{ echo "[report-runtime] FAIL api=$p status=$code" >&2;exit 1;};grep -Eq '^\s*[\{\[]' "$API_BODY"||exit 1;done
public="$(curl -fsS "$BASE/api/public/report-certificates/$cert")";grep -q '"valid":true'<<<"$public"||{ echo '[report-runtime] FAIL valid certificate rejected' >&2;exit 1;};invalid="$(curl -fsS "$BASE/api/public/report-certificates/INVALID-CERTIFICATE")";grep -q '"valid":false'<<<"$invalid"||{ echo '[report-runtime] FAIL invalid certificate accepted' >&2;exit 1;}
for p in "/home/api/emission-projects/$project/reports" /home/api/report-access-history;do code="$(curl -sS -o /dev/null -w '%{http_code}' "$BASE$p")";[[ "$code" == 401||"$code" == 403 ]]||{ echo "[report-runtime] FAIL protection=$p status=$code" >&2;exit 1;};done
pages=("/emission/report_submit?projectId=$project" "/emission/report-download?projectId=$project" /home/certificate-verify /admin/emission/report-certificates /admin/emission/survey-report /admin/emission/survey-report-print?lang=ko /admin/emission/survey-report-verify);for p in "${pages[@]}";do code="$(curl -sS -L -b "$COOKIE" -o "$PAGE_BODY" -w '%{http_code}' "$BASE$p")";[[ "$code" == 200 ]]||{ echo "[report-runtime] FAIL page=$p status=$code" >&2;exit 1;};grep -qi '<!doctype html' "$PAGE_BODY"||exit 1;done
for _ in $(seq 1 20);do curl -sS -o /dev/null -w '%{time_total}\n' "$BASE/api/public/report-certificates/$cert">>"$TIMES";done;p95="$(sort -n "$TIMES"|awk 'NR==19{printf "%d",$1*1000}')";[[ "$p95" -le 2500 ]]||exit 1
read -r desired ready available<<<"$(kubectl -n "$NS" get deploy carbonet-runtime -o jsonpath='{.spec.replicas} {.status.readyReplicas} {.status.availableReplicas}')";[[ -n "$desired"&&"$desired" -gt 0&&"$ready" -ge "$desired"&&"$available" -ge "$desired" ]]||{ echo "[report-certification-runtime] FAIL replicas desired=$desired ready=$ready available=$available" >&2;exit 1;}
gate="$(q "select length('$hash')=64 and (select count(*) from framework_professional_screen_readiness where process_code='REPORT_CERTIFICATION' and readiness_score=100)=8 and (select count(distinct case_type) from framework_simulation_case where process_code='REPORT_CERTIFICATION')>=5 and exists(select 1 from emission_report_certificate_audit where report_id=$report)")";[[ "$gate" == t ]]||{ echo '[report-runtime] FAIL integrity/design/audit gate' >&2;exit 1;}
q "begin;update framework_development_job set job_status='COMPLETED',approval_status='APPROVED',quality_status='PASSED',evidence_ref='runtime:report+certificate+public-verify+integrity+performance+deployment',last_error=null,completed_at=current_timestamp,updated_at=current_timestamp where process_code='REPORT_CERTIFICATION' and job_type in('ACTOR_TEST','DEPLOYMENT','INTEGRATION','PERFORMANCE','TEST');update framework_process_artifact set delivery_status='VERIFIED',evidence_ref='runtime:report+certificate+public-verify+integrity+performance+deployment',updated_at=current_timestamp where process_code='REPORT_CERTIFICATION';commit;" >/dev/null
echo "[report-runtime] PASS project=$project report=$report certificate=$cert authenticatedApi=${#apis[@]} publicValid=1 publicInvalid=1 protected=2 pages=${#pages[@]} integrityHash=64 p95=${p95}ms replicas=$ready/$desired"
