#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.."&&pwd)";NS="${CARBONET_K8S_NAMESPACE:-carbonet-prod}";DB="${POSTGRES_DB:-carbonet}";U="${POSTGRES_ADMIN_USER:-postgres}";BASE="${CARBONET_RUNTIME_BASE_URL:-http://127.0.0.1}";COMMIT="$(git -C "$ROOT" rev-parse HEAD)";COOKIE="$(mktemp)";TIMES="$(mktemp)";API_BODY="$(mktemp)";PAGE_BODY="$(mktemp)";trap 'rm -f "$COOKIE" "$TIMES" "$API_BODY" "$PAGE_BODY"' EXIT
leader="";while read -r p;do [[ "$(kubectl -n "$NS" exec "$p" -c patroni -- psql -h 127.0.0.1 -U "$U" -d "$DB" -Atqc 'select pg_is_in_recovery()' 2>/dev/null||true)" == f ]]&&{ leader="$p";break;};done < <(kubectl -n "$NS" get pods -l app=postgres-patroni -o name|sed 's#pod/##');[[ -n "$leader" ]]||exit 1;q(){ kubectl -n "$NS" exec "$leader" -c patroni -- psql -h 127.0.0.1 -U "$U" -d "$DB" -Atqc "$1";}
IFS='|' read -r project cert report_id <<<"$(q "select p.project_id||'|'||r.certificate_id||'|'||r.report_id from emission_project_registry p join emission_project_report r on r.project_id=p.project_id where r.report_status='FINALIZED' and r.certificate_status='ACTIVE' and r.certificate_id is not null and exists(select 1 from emission_project_task t where t.project_id=p.project_id group by t.project_id having count(*)=7 and count(*)filter(where task_status='DONE')>=6) order by r.issued_at desc nulls last limit 1")";[[ -n "$cert" ]]||{ echo '[customer-journey] FAIL certified seven-step fixture missing' >&2;exit 1;}
curl -fsS -c "$COOKIE" -H 'Content-Type: application/json' -X POST "$BASE/admin/login/actionLogin" --data '{"userId":"webmaster","userPw":"rhdxhd12","userSe":"USR"}' >/dev/null

# Drive the newly added regulatory submission leg through the real API when the fixture is not accepted yet.
regulatory_id="$(q "select coalesce(max(regulatory_submission_id),0) from emission_regulatory_submission where project_id='$project' and status='ACCEPTED'")"
if [[ "$regulatory_id" == 0 ]]; then
  deadline="$(date -d '+30 days' +%F)"; request_id="customer-journey-$project"
  body="$(curl -fsS -b "$COOKIE" -H 'Content-Type: application/json' -X POST "$BASE/home/api/emission-projects/$project/regulatory-submissions" --data "{\"reportId\":$report_id,\"clientRequestId\":\"$request_id\",\"authorityCode\":\"MOE\",\"authorityName\":\"환경부\",\"reportingProgram\":\"자동 검증 정기보고\",\"reportingPeriod\":\"$(date +%Y)\",\"legalBasis\":\"탄소중립기본법 및 배출량 산정·보고 지침\",\"channel\":\"SYSTEM\",\"deadline\":\"$deadline\",\"note\":\"customer journey runtime validation\"}")"
  regulatory_id="$(python3 -c 'import json,sys;print(json.load(sys.stdin)["id"])'<<<"$body")"
  curl -fsS -b "$COOKIE" -H 'Content-Type: application/json' -X POST "$BASE/home/api/emission-projects/$project/regulatory-submissions/$regulatory_id/transition" --data '{"action":"SUBMIT"}' >/dev/null
  curl -fsS -b "$COOKIE" -H 'Content-Type: application/json' -X POST "$BASE/home/api/emission-projects/$project/regulatory-submissions/$regulatory_id/transition" --data "{\"action\":\"RECORD_RECEIPT\",\"receiptNo\":\"AUTO-$project\"}" >/dev/null
  curl -fsS -b "$COOKIE" -H 'Content-Type: application/json' -X POST "$BASE/home/api/emission-projects/$project/regulatory-submissions/$regulatory_id/transition" --data '{"action":"ACCEPT"}' >/dev/null
fi
apis=(/home/api/emission-tasks "/home/api/emission-projects/$project/completion" "/home/api/emission-projects/$project/activities" "/home/api/emission-projects/$project/calculation" "/home/api/emission-projects/$project/review-workflow" "/home/api/emission-projects/$project/reports" "/home/api/emission-projects/$project/regulatory-submissions" /home/api/report-access-history);for p in "${apis[@]}";do code="$(curl -sS -b "$COOKIE" -o "$API_BODY" -w '%{http_code}' "$BASE$p")";[[ "$code" == 200 ]]||{ echo "[customer-journey] FAIL api=$p status=$code" >&2;exit 1;};grep -Eq '^\s*[\{\[]' "$API_BODY"||exit 1;done
curl -fsS -b "$COOKIE" "$BASE/home/api/emission-tasks" >"$API_BODY"
python3 - "$API_BODY" <<'PY'
import json,sys
payload=json.load(open(sys.argv[1],encoding="utf-8"))
if payload.get("allVisible") is not True or payload.get("accountActors") != ["*"]:
    raise SystemExit("administrator process visibility contract failed")
member_codes={row.get("processCode") for row in payload.get("processCatalog",[]) if str(row.get("domainCode","")).upper()=="MEMBER"}
member_steps=[row for row in payload.get("processCatalogSteps",[]) if row.get("processCode") in member_codes]
if len(member_codes)!=17 or len(member_steps)<68:
    raise SystemExit(f"member guide catalog mismatch processes={len(member_codes)} steps={len(member_steps)}")
if any(not row.get("userPath") or not row.get("adminPath") for row in member_steps):
    raise SystemExit("member guide route gap")
PY
while IFS= read -r target;do [[ -n "$target" ]]||continue;code="$(curl -sS -L -b "$COOKIE" -o /dev/null -w '%{http_code}' "$BASE$target")";[[ "$code" == 200 ]]||{ echo "[customer-journey] FAIL member-guide-page=$target status=$code" >&2;exit 1;};done < <(python3 - "$API_BODY" <<'PY'
import json,sys
p=json.load(open(sys.argv[1],encoding="utf-8"));codes={r.get("processCode") for r in p.get("processCatalog",[]) if str(r.get("domainCode","")).upper()=="MEMBER"}
print("\n".join(sorted({path for r in p.get("processCatalogSteps",[]) if r.get("processCode") in codes for path in (r.get("userPath"),r.get("adminPath")) if path})))
PY
)
for p in "/home/api/emission-projects/$project/activities" "/home/api/emission-projects/$project/calculation" "/home/api/emission-projects/$project/reports" "/home/api/emission-projects/$project/regulatory-submissions" /home/api/report-access-history;do code="$(curl -sS -o /dev/null -w '%{http_code}' "$BASE$p")";[[ "$code" == 401||"$code" == 403 ]]||{ echo "[customer-journey] FAIL protection=$p status=$code" >&2;exit 1;};done
valid="$(curl -fsS "$BASE/api/public/report-certificates/$cert")";grep -q '"valid":true'<<<"$valid"||exit 1
pages=(/emission/my-tasks /emission/deadline-status "/emission/project/detail?projectId=$project" "/emission/activity-data?projectId=$project" "/emission/calculation?projectId=$project" "/emission/validate?projectId=$project" "/emission/report_submit?projectId=$project" "/emission/report-submission?projectId=$project" "/emission/report-download?projectId=$project" /home/certificate-verify /admin/emission/project-operations "/admin/emission/regulatory-submissions?projectId=$project" /admin/system/actor-process);for p in "${pages[@]}";do code="$(curl -sS -L -b "$COOKIE" -o "$PAGE_BODY" -w '%{http_code}' "$BASE$p")";[[ "$code" == 200 ]]||{ echo "[customer-journey] FAIL page=$p status=$code" >&2;exit 1;};grep -qi '<!doctype html' "$PAGE_BODY"||exit 1;done
for _ in $(seq 1 20);do curl -sS -b "$COOKIE" -o /dev/null -w '%{time_total}\n' "$BASE/home/api/emission-projects/$project/completion">>"$TIMES";done;p95="$(sort -n "$TIMES"|awk 'NR==19{printf "%d",$1*1000}')";[[ "$p95" -le 2500 ]]||exit 1
read -r desired ready available<<<"$(kubectl -n "$NS" get deploy carbonet-runtime -o jsonpath='{.spec.replicas} {.status.readyReplicas} {.status.availableReplicas}')";[[ -n "$desired"&&"$desired" -gt 0&&"$ready" == "$desired"&&"$available" == "$desired" ]]||{ echo "[customer-work-journey] FAIL replicas desired=$desired ready=$ready available=$available" >&2;exit 1;}
gate="$(q "select (select count(*) from framework_process_step where process_code='CUSTOMER_WORK_COORDINATION')=7 and (select count(*) from framework_professional_screen_readiness where process_code='CUSTOMER_WORK_COORDINATION' and readiness_score=100)=14 and (select count(distinct actor_code) from framework_process_step where process_code='CUSTOMER_WORK_COORDINATION')>=6 and (select count(*) from emission_project_task where project_id='$project')=7 and (select count(*) from emission_project_task where project_id='$project' and task_status='DONE')=7 and exists(select 1 from emission_regulatory_submission where project_id='$project' and status='ACCEPTED' and external_receipt_no is not null and length(package_hash)=64) and not exists(select 1 from emission_project_task where project_id='$project' and target_url similar to '%(data_input|simulate)%') and exists(select 1 from emission_calculation_run r join emission_calculation_item i on i.calculation_id=r.calculation_id where r.project_id='$project' group by r.calculation_id,r.total_emission having abs(r.total_emission-sum(i.emission_value))<0.000001) and (select count(distinct case_type) from framework_simulation_case where process_code='CUSTOMER_WORK_COORDINATION')>=5")";[[ "$gate" == t ]]||{ echo '[customer-journey] FAIL actor/task/state/data/design gate' >&2;exit 1;}
sql="begin;update framework_development_job set job_status='COMPLETED',approval_status='APPROVED',quality_status='PASSED',evidence_ref='runtime:cross-process-customer-journey',last_error=null,completed_at=current_timestamp,updated_at=current_timestamp where process_code='CUSTOMER_WORK_COORDINATION';update framework_process_artifact set delivery_status='VERIFIED',evidence_ref='runtime:cross-process-customer-journey',updated_at=current_timestamp where process_code='CUSTOMER_WORK_COORDINATION';insert into framework_customer_journey_validation_run(project_id,validation_status,actor_count,task_count,authenticated_api_count,protected_api_count,page_count,p95_millis,evidence_json,source_commit)values('$project','PASSED',6,7,${#apis[@]},5,${#pages[@]},$p95,'{\"certificate\":\"$cert\",\"regulatorySubmissionId\":$regulatory_id,\"taskLineage\":\"7/7\",\"formula\":\"reconciled\"}','$COMMIT');commit;";q "$sql">/dev/null
echo "[customer-journey] PASS project=$project actors=6 tasks=7/7 api=${#apis[@]} protected=5 pages=${#pages[@]} certificate=valid regulatory=accepted formula=reconciled p95=${p95}ms replicas=$ready/$desired"
