-- Carbonet menu permission diagnostics
-- Review duplicate active menu URLs and duplicate VIEW feature mappings

-- 1) Active menu URLs mapped by more than one menu code
SELECT
    MENU_URL,
    COUNT(*) AS MENU_CODE_COUNT,
    LISTAGG(MENU_CODE, ', ') WITHIN GROUP (ORDER BY MENU_CODE) AS MENU_CODES
FROM COMTNMENUINFO
WHERE COALESCE(USE_AT, 'Y') = 'Y'
  AND COALESCE(MENU_URL, '') <> ''
GROUP BY MENU_URL
HAVING COUNT(*) > 1
ORDER BY MENU_URL;

-- 2) Active VIEW features mapped more than once for the same runtime menu URL
SELECT
    M.MENU_URL,
    COUNT(DISTINCT M.MENU_CODE) AS MENU_CODE_COUNT,
    LISTAGG(DISTINCT M.MENU_CODE, ', ') WITHIN GROUP (ORDER BY M.MENU_CODE) AS MENU_CODES,
    COUNT(DISTINCT F.FEATURE_CODE) AS VIEW_FEATURE_COUNT,
    LISTAGG(DISTINCT F.FEATURE_CODE, ', ') WITHIN GROUP (ORDER BY F.FEATURE_CODE) AS VIEW_FEATURE_CODES
FROM COMTNMENUINFO M
JOIN COMTNMENUFUNCTIONINFO F
  ON F.MENU_CODE = M.MENU_CODE
WHERE COALESCE(M.USE_AT, 'Y') = 'Y'
  AND COALESCE(F.USE_AT, 'Y') = 'Y'
  AND COALESCE(M.MENU_URL, '') <> ''
  AND F.FEATURE_CODE LIKE '%\_VIEW' ESCAPE '\'
GROUP BY M.MENU_URL
HAVING COUNT(DISTINCT F.FEATURE_CODE) > 1
ORDER BY M.MENU_URL;

-- 3) Detail rows for duplicate runtime URLs
SELECT
    M.MENU_URL,
    M.MENU_CODE,
    F.FEATURE_CODE,
    F.FEATURE_NM,
    COALESCE(M.USE_AT, 'Y') AS MENU_USE_AT,
    COALESCE(F.USE_AT, 'Y') AS FEATURE_USE_AT
FROM COMTNMENUINFO M
LEFT JOIN COMTNMENUFUNCTIONINFO F
  ON F.MENU_CODE = M.MENU_CODE
WHERE COALESCE(M.USE_AT, 'Y') = 'Y'
  AND COALESCE(M.MENU_URL, '') IN (
      SELECT MENU_URL
      FROM COMTNMENUINFO
      WHERE COALESCE(USE_AT, 'Y') = 'Y'
        AND COALESCE(MENU_URL, '') <> ''
      GROUP BY MENU_URL
      HAVING COUNT(*) > 1
  )
ORDER BY M.MENU_URL, M.MENU_CODE, F.FEATURE_CODE;

-- 4) Suggested cleanup candidate rows
-- Review these rows manually before update/delete.
SELECT
    M.MENU_URL,
    M.MENU_CODE,
    F.FEATURE_CODE,
    F.FEATURE_NM,
    CASE
        WHEN F.FEATURE_CODE LIKE '%\_VIEW' ESCAPE '\' THEN 'REVIEW_VIEW_MAPPING'
        ELSE 'REVIEW_MENU_DUPLICATION'
    END AS CLEANUP_HINT
FROM COMTNMENUINFO M
LEFT JOIN COMTNMENUFUNCTIONINFO F
  ON F.MENU_CODE = M.MENU_CODE
WHERE COALESCE(M.USE_AT, 'Y') = 'Y'
  AND COALESCE(M.MENU_URL, '') <> ''
  AND (
      COALESCE(M.MENU_URL, '') IN (
          SELECT MENU_URL
          FROM COMTNMENUINFO
          WHERE COALESCE(USE_AT, 'Y') = 'Y'
            AND COALESCE(MENU_URL, '') <> ''
          GROUP BY MENU_URL
          HAVING COUNT(*) > 1
      )
      OR M.MENU_URL IN (
          SELECT M2.MENU_URL
          FROM COMTNMENUINFO M2
          JOIN COMTNMENUFUNCTIONINFO F2
            ON F2.MENU_CODE = M2.MENU_CODE
          WHERE COALESCE(M2.USE_AT, 'Y') = 'Y'
            AND COALESCE(F2.USE_AT, 'Y') = 'Y'
            AND COALESCE(M2.MENU_URL, '') <> ''
            AND F2.FEATURE_CODE LIKE '%\_VIEW' ESCAPE '\'
          GROUP BY M2.MENU_URL
          HAVING COUNT(DISTINCT F2.FEATURE_CODE) > 1
      )
  )
ORDER BY M.MENU_URL, M.MENU_CODE, F.FEATURE_CODE;
