import { useMemo, useState } from "react";
import { buildLocalizedPath, isEnglish } from "../../lib/navigation/runtime";
import { ROUTE_SOURCE_INVENTORY } from "../builder-studio/routeSourceInventory";
import { AdminPageShell } from "../admin-entry/AdminPageShell";
import { GovernanceCompressionNav } from "../admin-system/GovernanceCompressionNav";
import { SYSTEM_DESIGN_DOMAINS, REQUIRED_DESIGN_DIMENSIONS } from "./systemDesignContracts";

export function SystemDesignGovernancePage(){
  const en=isEnglish();const[selected,setSelected]=useState("emission");const domain=SYSTEM_DESIGN_DOMAINS.find(x=>x.id===selected)!;
  const routes=useMemo(()=>ROUTE_SOURCE_INVENTORY.filter(row=>domain.pathPrefixes.some(prefix=>row.koPath.startsWith(prefix))),[domain]);
  const placeholders=routes.filter(row=>/Placeholder|AdminTemplateFrame/.test(row.effectiveExportName));
  const stagePaths=new Set(domain.stages.flatMap(stage=>[stage.userPath.split("?")[0],stage.adminPath.split("?")[0]]));
  const linked=routes.filter(row=>stagePaths.has(row.koPath)).length;
  const completeStages=domain.stages.filter(stage=>stage.userPath&&stage.adminPath&&stage.apiContract&&stage.dataOwner&&stage.authority).length;
  const score=domain.stages.length?Math.round((completeStages/domain.stages.length)*100):0;
  const L=en?{title:"System Design Completeness",desc:"Verify business, menu, screen, capability, API, data, authority and workflow contracts before page development.",domain:"Business domain",routes:"Registered routes",stages:"Workflow stages",linked:"Linked pages",placeholder:"Weak pages",coverage:"Design coverage",matrix:"End-to-end workflow contract",gaps:"Implementation gates",user:"User page",admin:"Admin response",api:"API contract",data:"Data owner",authority:"Authority",capability:"Capabilities",next:"Next stage",none:"No detailed workflow contract has been approved for this domain yet.",manage:"Related governance",menu:"Menu management",page:"Page management",feature:"Feature management",flow:"Screen flow",ready:"Declared",missing:"Missing"}:{title:"시스템 설계 완성도",desc:"페이지 개발 전에 업무·메뉴·화면·기능·API·데이터·권한·워크플로 계약과 누락을 먼저 검증합니다.",domain:"업무 영역",routes:"등록 라우트",stages:"업무 단계",linked:"연결 화면",placeholder:"미흡 화면",coverage:"설계 충족률",matrix:"종단 간 업무 계약",gaps:"구현 완료 조건",user:"사용자 화면",admin:"관리자 대응",api:"API 계약",data:"데이터 원본",authority:"권한",capability:"기능",next:"다음 단계",none:"이 업무 영역은 아직 상세 업무 계약이 승인되지 않았습니다.",manage:"연관 관리 화면",menu:"메뉴 관리",page:"페이지 관리",feature:"기능 관리",flow:"화면 흐름",ready:"정의됨",missing:"누락"};
  return <AdminPageShell breadcrumbs={[{label:en?"Home":"홈",href:buildLocalizedPath("/admin/","/en/admin/")},{label:en?"System":"시스템"},{label:L.title}]} title={L.title}><GovernanceCompressionNav activeId="design" en={en}/><div className="space-y-5">
    <section className="rounded-2xl border border-blue-200 bg-gradient-to-r from-[#052b57] to-[#174ea6] p-6 text-white"><p className="text-sm font-bold text-blue-200">Design before development</p><h2 className="mt-2 text-2xl font-black">{L.title}</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-blue-50">{L.desc}</p></section>
    <section className="grid gap-3 lg:grid-cols-7">{SYSTEM_DESIGN_DOMAINS.map(item=><button key={item.id} onClick={()=>setSelected(item.id)} className={`rounded-xl border p-4 text-left font-bold ${selected===item.id?"border-blue-600 bg-blue-50 text-blue-800":"bg-white text-slate-700"}`}>{en?item.nameEn:item.nameKo}</button>)}</section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[[L.routes,routes.length],[L.stages,domain.stages.length],[L.linked,linked],[L.placeholder,placeholders.length],[L.coverage,`${score}%`]].map(([k,v])=><article key={k} className="rounded-xl border bg-white p-5"><p className="text-sm font-bold text-slate-500">{k}</p><strong className="mt-2 block text-3xl text-[#052b57]">{v}</strong></article>)}</section>
    <section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black text-slate-900">{L.matrix}</h2><p className="mt-1 text-sm text-slate-500">{en?domain.nameEn:domain.nameKo}</p></div><div className="flex flex-wrap gap-2">{REQUIRED_DESIGN_DIMENSIONS.map(x=><span key={x} className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">{x}</span>)}</div></div>
      {domain.stages.length?<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[1200px] text-left text-sm"><thead className="bg-slate-100"><tr>{[L.stages,L.user,L.admin,L.capability,L.api,L.data,L.authority,L.next].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{domain.stages.map(stage=><tr key={stage.id} className="border-t align-top"><td className="p-3 font-black text-slate-900">{en?stage.nameEn:stage.nameKo}</td><td className="p-3"><a className="font-bold text-blue-700" href={buildLocalizedPath(stage.userPath,`/en${stage.userPath}`)}>{stage.userPath}</a></td><td className="p-3"><a className="font-bold text-blue-700" href={buildLocalizedPath(stage.adminPath,`/en${stage.adminPath}`)}>{stage.adminPath}</a></td><td className="p-3"><div className="flex flex-wrap gap-1">{stage.capabilities.map(x=><span key={x} className="rounded bg-blue-50 px-2 py-1 text-xs text-blue-700">{x}</span>)}</div></td><td className="p-3 font-mono text-xs">{stage.apiContract}</td><td className="p-3 font-mono text-xs">{stage.dataOwner}</td><td className="p-3 text-xs font-bold">{stage.authority}</td><td className="p-3">{stage.nextStage||"-"}</td></tr>)}</tbody></table></div>:<p className="mt-5 rounded-xl bg-amber-50 p-5 font-bold text-amber-800">{L.none}</p>}
    </section>
    <section className="grid gap-4 lg:grid-cols-[1fr_1.25fr]"><article className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-black">{L.gaps}</h2><div className="mt-4 space-y-2">{REQUIRED_DESIGN_DIMENSIONS.map((item,index)=>{const ready=domain.stages.length>0&&index<8;return <div key={item} className="flex items-center justify-between rounded-lg bg-slate-50 px-4 py-3"><span className="font-bold">{item}</span><span className={`rounded-full px-2 py-1 text-xs font-black ${ready?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-800"}`}>{ready?L.ready:L.missing}</span></div>})}</div></article><article className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-black">{L.manage}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{[[L.menu,"/admin/system/menu","account_tree"],[L.page,"/admin/system/page-management","web_asset"],[L.feature,"/admin/system/feature-management","extension"],[L.flow,"/admin/system/screen-flow-management","timeline"]].map(([label,path,icon])=><a key={path} href={buildLocalizedPath(path,`/en${path}`)} className="rounded-xl border p-5 hover:border-blue-500 hover:bg-blue-50"><span className="material-symbols-outlined text-blue-700">{icon}</span><strong className="mt-2 block">{label}</strong></a>)}</div><div className="mt-5 rounded-xl bg-slate-900 p-4 text-sm text-slate-100"><strong>{routes.length}</strong> routes inspected · <strong>{placeholders.length}</strong> weak implementations · <strong>{domain.stages.length}</strong> governed stages</div></article></section>
  </div></AdminPageShell>;
}
