INSERT INTO COMTCCMMNCODE (
    CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, CL_CODE, FRST_REGIST_PNTTM, FRST_REGISTER_ID
)
SELECT 'ECOGEO', 'ecoinvent 지역', 'ecoinvent geography priority', 'Y', 'EMM', CURRENT_DATETIME, 'SYSTEM'
FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTCCMMNCODE WHERE CODE_ID = 'ECOGEO'
);

INSERT INTO COMTCCMMNDETAILCODE (
    CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID
)
SELECT 'ECOGEO', 'KR', 'KR', 'Korea', 'Y', CURRENT_DATETIME, 'SYSTEM'
FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTCCMMNDETAILCODE WHERE CODE_ID = 'ECOGEO' AND CODE = 'KR');

INSERT INTO COMTCCMMNDETAILCODE (
    CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID
)
SELECT 'ECOGEO', 'ROW', 'RoW', 'Rest-of-World', 'Y', CURRENT_DATETIME, 'SYSTEM'
FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTCCMMNDETAILCODE WHERE CODE_ID = 'ECOGEO' AND CODE = 'ROW');

INSERT INTO COMTCCMMNDETAILCODE (
    CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID
)
SELECT 'ECOGEO', 'RER', 'RER', 'Europe region', 'Y', CURRENT_DATETIME, 'SYSTEM'
FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTCCMMNDETAILCODE WHERE CODE_ID = 'ECOGEO' AND CODE = 'RER');

INSERT INTO COMTCCMMNDETAILCODE (
    CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID
)
SELECT 'ECOGEO', 'GLO', 'GLO', 'Global', 'Y', CURRENT_DATETIME, 'SYSTEM'
FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTCCMMNDETAILCODE WHERE CODE_ID = 'ECOGEO' AND CODE = 'GLO');

INSERT INTO COMTCCMMNDETAILCODE (
    CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID
)
SELECT 'ECOGEO', 'EU', 'EU', 'European Union', 'Y', CURRENT_DATETIME, 'SYSTEM'
FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTCCMMNDETAILCODE WHERE CODE_ID = 'ECOGEO' AND CODE = 'EU');

INSERT INTO COMTCCMMNDETAILCODE (
    CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID
)
SELECT 'ECOGEO', 'JP', 'JP', 'Japan', 'Y', CURRENT_DATETIME, 'SYSTEM'
FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTCCMMNDETAILCODE WHERE CODE_ID = 'ECOGEO' AND CODE = 'JP');

INSERT INTO COMTCCMMNDETAILCODE (
    CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID
)
SELECT 'ECOGEO', 'CH', 'CH', 'Switzerland', 'Y', CURRENT_DATETIME, 'SYSTEM'
FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTCCMMNDETAILCODE WHERE CODE_ID = 'ECOGEO' AND CODE = 'CH');

INSERT INTO COMTCCMMNDETAILCODE (
    CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID
)
SELECT 'ECOGEO', 'IN', 'IN', 'India', 'Y', CURRENT_DATETIME, 'SYSTEM'
FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTCCMMNDETAILCODE WHERE CODE_ID = 'ECOGEO' AND CODE = 'IN');
