ALTER TABLE COMTNENTRPRSMBER ADD COLUMN PROJECT_ID VARCHAR(80);
UPDATE COMTNENTRPRSMBER SET PROJECT_ID = 'carbonet' WHERE PROJECT_ID IS NULL;

ALTER TABLE ACCESS_EVENT ADD COLUMN PROJECT_ID VARCHAR(80);
ALTER TABLE AUDIT_EVENT ADD COLUMN PROJECT_ID VARCHAR(80);

COMMIT;
