import { useState } from "react";
type Preview={columns:string[];sample:string[][];rowCount:number;sheetName:string};
const fields=["활동자료명","구분","기간 (YYYY-MM)","활동량","단위","증빙·비고"];
export function ActivityColumnMapping({api,siteId,onSaved}:{api:string;siteId:string;onSaved:()=>Promise<void>}) {
 const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<Preview|null>(null),[mapping,setMapping]=useState<number[]>([-1,-1,-1,-1,-1,-1]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[saved,setSaved]=useState(false);
 async function inspect(next:File){setFile(next);setPreview(null);setSaved(false);setError("");setBusy(true);try {const fd=new FormData();fd.append("file",next);const r=await fetch(`${api}/upload-preview`,{method:"POST",credentials:"include",body:fd});const b=await r.json();if(!r.ok)throw Error(b.message||"파일을 확인하지 못했습니다.");setPreview(b);setMapping([-1,-1,-1,-1,-1,-1]);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function save(){if(!file||!siteId||!preview)return;setBusy(true);setError("");try {const fd=new FormData();fd.append("file",file);fd.append("siteId",siteId);fd.append("mapping",JSON.stringify(mapping));const r=await fetch(`${api}/upload`,{method:"POST",credentials:"include",body:fd});const b=await r.json();if(!r.ok)throw Error(b.message||"저장하지 못했습니다.");setSaved(true);setError(`${b.count}행 저장 완료`);await onSaved();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 const ready=Boolean(siteId&&preview&&!saved&&mapping.every(i=>i>=0)&&new Set(mapping).size===6);
 return <section className="mt-5 rounded-xl border bg-white p-6"><h2 className="text-xl font-bold">원본 파일 열 매핑</h2><p className="mt-2 text-sm text-slate-600">① 사업장 선택 → ② 파일 미리보기 → ③ 열 연결 → ④ 저장. 첫 시트의 첫 행을 제목으로 사용합니다. 최대 5MB·2,000행.</p>
 <label className="mt-4 block font-bold">xlsx 파일<input className="mt-2 block" type="file" accept=".xlsx" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void inspect(f);}}/></label>
 {preview&&<><p className="mt-4">{preview.sheetName} · 원본 {preview.rowCount}행 · 빈 행은 제외</p><div className="mt-4 grid gap-4 md:grid-cols-3">{fields.map((field,i)=><label className="text-sm font-bold" key={field}>{field}<select className="mt-2 h-11 w-full rounded border px-3" value={mapping[i]} disabled={busy||saved} onChange={e=>setMapping(values=>values.map((v,j)=>i===j?Number(e.target.value):v))}><option value={-1}>원본 열 선택</option>{preview.columns.map((label,c)=><option value={c} key={c}>{c+1}열 · {label||"제목 없음"}</option>)}</select></label>)}</div>
 <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><caption className="p-2 text-left">연결 결과 미리보기 (최대 5행)</caption><thead><tr>{fields.map(f=><th className="border-b bg-slate-50 p-3" key={f}>{f}</th>)}</tr></thead><tbody>{preview.sample.map((row,i)=><tr key={i}>{mapping.map((column,j)=><td className="border-b p-3" key={j}>{column<0?"열을 선택하세요":row[column]}</td>)}</tr>)}</tbody></table></div>
 <p className="mt-3 text-sm text-slate-600">선택한 사업장에 모든 행이 저장됩니다. 사업장이 다른 자료는 파일을 나눠 등록하세요. 원본 파일과 열 연결 내역도 보존됩니다.</p><button className="mt-4 min-h-11 rounded bg-blue-800 px-5 font-bold text-white disabled:opacity-40" disabled={!ready||busy} onClick={()=>void save()}>{busy?"처리 중…":saved?"저장 완료":"검사 후 전체 저장"}</button></>}
 {error&&<p className="mt-4 rounded border p-3" role="status">{error}</p>}
 </section>;
}
