import { FormEvent, useEffect, useMemo, useState } from "react";
import { useAsyncValue } from "../../app/hooks/useAsyncValue";
import { fetchHomePayload } from "../../lib/api/appBootstrap";
import { buildLocalizedPath, isEnglish } from "../../lib/navigation/runtime";
import { HeaderBrand, HeaderDesktopNav, HomeInlineStyles } from "../home-entry/HomeEntrySections";
import { LOCALIZED_CONTENT } from "../home-entry/homeEntryContent";

type Factor={id:string;name:string;category:string;unit:string;value:number;source:string};
type Item={id:number;name:string;category:string;period:string;quantity:number;unit:string;note:string;factorId?:string;factorName?:string;factorValue?:number;mappingStatus:string};
type Payload={project:{id:string;name:string;site:string};items:Item[];factors:Factor[]};
const empty={name:"",category:"연료",period:new Date().toISOString().slice(0,7),quantity:"",unit:"L",note:""};

export function EmissionDataInputMigrationPage(){
 const en=isEnglish(),content=LOCALIZED_CONTENT[en?"en":"ko"],home=useAsyncValue(()=>fetchHomePayload(),[en]);
 const params=new URLSearchParams(location.search),projectId=params.get("projectId")||""; const initialTab=params.get("mode")==="upload"?"upload":params.get("tab")==="mapping"?"mapping":"ledger";
 const [tab,setTab]=useState(initialTab),[data,setData]=useState<Payload|null>(null),[form,setForm]=useState(empty),[keyword,setKeyword]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const api=buildLocalizedPath(`/home/api/emission-projects/${encodeURIComponent(projectId)}/activities`,`/en/home/api/emission-projects/${encodeURIComponent(projectId)}/activities`);
 async function load(){if(!projectId)return;const r=await fetch(`${api}?keyword=${encodeURIComponent(keyword)}`,{credentials:"include"});if(!r.ok)throw new Error(en?"Could not load activity data.":"활동자료를 불러오지 못했습니다.");setData(await r.json());}
 useEffect(()=>{load().catch(e=>setMessage(e.message));},[projectId]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch(api,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const b=await r.json();if(!r.ok)throw new Error(b.message);setForm(empty);setMessage(en?"Activity data saved.":"활동자료를 저장했습니다.");await load();}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function upload(file:File){setBusy(true);setMessage("");try{const fd=new FormData();fd.append("file",file);const r=await fetch(`${api}/upload`,{method:"POST",credentials:"include",body:fd});const b=await r.json();if(!r.ok)throw new Error(b.message);setMessage(en?`${b.count} rows uploaded.`:`${b.count}건을 업로드했습니다.`);await load();}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function map(id:number,factorId:string){const r=await fetch(`${api}/${id}/factor`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({factorId})});const b=await r.json();if(!r.ok)throw new Error(b.message);await load();}
 async function autoMap(){setBusy(true);try{const r=await fetch(`${api}/auto-map`,{method:"POST",credentials:"include"});const b=await r.json();if(!r.ok)throw new Error(b.message);setMessage(en?`${b.count} rows mapped.`:`${b.count}건을 자동 매핑했습니다.`);await load();}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 const totals=useMemo(()=>({all:data?.items.length||0,mapped:data?.items.filter(i=>i.factorId).length||0,emission:data?.items.reduce((s,i)=>s+Number(i.quantity||0)*Number(i.factorValue||0),0)||0}),[data]);
 const input="mt-2 h-11 w-full rounded-lg border border-slate-300 bg-white px-3 outline-none focus:border-blue-600";
 if(!projectId)return <div className="p-10 font-bold text-red-700">{en?"Open this screen from a project detail page.":"프로젝트 상세 화면에서 활동자료를 열어 주세요."}</div>;
 return <><HomeInlineStyles en={en}/><div className="min-h-screen bg-[#f5f7fa]"><header className="border-b-2 border-[#001e40] bg-white"><div className="mx-auto flex h-16 max-w-7xl items-center px-4 lg:px-8"><HeaderBrand content={content} en={en}/><HeaderDesktopNav en={en} homeMenu={home.value?.homeMenu||[]}/></div></header><main className="mx-auto max-w-7xl px-4 py-8 lg:px-8">
  <nav className="text-sm text-slate-500"><a href={buildLocalizedPath(`/emission/project/detail?id=${projectId}`,`/en/emission/project/detail?id=${projectId}`)}>{data?.project.name||projectId}</a><span className="mx-2">/</span>{en?"Activity Data":"활동자료 관리"}</nav><div className="mt-4 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="font-bold text-blue-700">{data?.project.site}</p><h1 className="text-3xl font-black text-[#052b57]">{en?"Activity Data Management":"활동자료 관리"}</h1></div><div className="flex flex-wrap gap-2"><form className="flex" onSubmit={e=>{e.preventDefault();load().catch(err=>setMessage(err.message));}}><input className="h-12 rounded-l-lg border border-r-0 px-3" placeholder={en?"Search activity":"활동자료 검색"} value={keyword} onChange={e=>setKeyword(e.target.value)}/><button className="rounded-r-lg border bg-white px-3 font-bold">{en?"Search":"검색"}</button></form>{[["ledger",en?"Ledger":"자료 목록"],["upload",en?"Excel Upload":"엑셀 업로드"],["mapping",en?"Factor Mapping":"배출계수 매핑"]].map(([v,l])=><button className={`rounded-lg px-4 py-3 font-bold ${tab===v?"bg-[#246beb] text-white":"border bg-white"}`} key={v} onClick={()=>setTab(v)}>{l}</button>)}</div></div>
  <section className="mt-5 grid gap-4 sm:grid-cols-3">{[[en?"Total rows":"전체 자료",totals.all],[en?"Mapped rows":"매핑 완료",`${totals.mapped}/${totals.all}`],[en?"Estimated emissions":"예상 배출량",`${totals.emission.toFixed(3)} tCO₂e`]].map(([l,v])=><div className="rounded-xl border bg-white p-5" key={l}><p className="text-sm font-bold text-slate-500">{l}</p><strong className="mt-2 block text-2xl text-[#052b57]">{v}</strong></div>)}</section>{message&&<p className="mt-4 rounded-lg bg-blue-50 p-3 font-bold text-blue-800">{message}</p>}
  {tab==="ledger"&&<><form className="mt-5 rounded-xl border bg-white p-5" onSubmit={save}><h2 className="text-xl font-black text-[#052b57]">{en?"Add activity data":"활동자료 입력"}</h2><div className="mt-4 grid gap-4 md:grid-cols-3"><label className="text-sm font-bold">{en?"Activity name":"활동자료명"}<input className={input} required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="text-sm font-bold">{en?"Category":"구분"}<select className={input} value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{["연료","전력","에너지","공정","운송","폐기물"].map(v=><option key={v}>{v}</option>)}</select></label><label className="text-sm font-bold">{en?"Period":"기간"}<input className={input} type="month" value={form.period} onChange={e=>setForm({...form,period:e.target.value})}/></label><label className="text-sm font-bold">{en?"Quantity":"활동량"}<input className={input} min="0" required step="any" type="number" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label className="text-sm font-bold">{en?"Unit":"단위"}<select className={input} value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}>{["L","Nm3","kWh","ton","kg","km"].map(v=><option key={v}>{v}</option>)}</select></label><label className="text-sm font-bold">{en?"Evidence note":"증빙 비고"}<input className={input} value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label></div><div className="mt-4 text-right"><button className="rounded-lg bg-[#246beb] px-6 py-3 font-bold text-white" disabled={busy}>{en?"Save":"저장"}</button></div></form><ActivityTable data={data} en={en}/></>}
  {tab==="upload"&&<section className="mt-5 rounded-xl border bg-white p-7"><h2 className="text-xl font-black text-[#052b57]">{en?"Excel Upload":"엑셀 업로드"}</h2><p className="mt-2 text-sm text-slate-600">{en?"First sheet columns: name, category, period, quantity, unit, note":"첫 시트의 컬럼 순서: 활동자료명, 구분, 기간, 활동량, 단위, 비고"}</p><label className="mt-6 flex min-h-44 cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-blue-300 bg-blue-50"><strong>{busy?(en?"Uploading...":"업로드 중..."):(en?"Select an .xlsx file":".xlsx 파일 선택")}</strong><input accept=".xlsx" className="sr-only" disabled={busy} onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])} type="file"/></label><ActivityTable data={data} en={en}/></section>}
  {tab==="mapping"&&<section className="mt-5 rounded-xl border bg-white p-6"><div className="flex justify-between"><div><h2 className="text-xl font-black text-[#052b57]">{en?"Emission Factor Mapping":"배출계수 매핑"}</h2><p className="mt-1 text-sm text-slate-600">{en?"Review every suggested factor before calculation.":"자동 추천 결과를 확인하고 필요한 경우 직접 변경합니다."}</p></div><button className="rounded-lg bg-[#246beb] px-5 py-3 font-bold text-white" disabled={busy} onClick={autoMap}>{en?"Auto map all":"전체 자동 매핑"}</button></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead className="bg-slate-100 text-sm"><tr><th className="p-3">{en?"Activity":"활동자료"}</th><th>{en?"Quantity":"활동량"}</th><th>{en?"Emission factor":"배출계수"}</th><th>{en?"Source":"출처"}</th></tr></thead><tbody>{data?.items.map(item=><tr className="border-b" key={item.id}><td className="p-3 font-bold">{item.name}<small className="block text-slate-500">{item.category}</small></td><td>{item.quantity} {item.unit}</td><td><select className="h-10 min-w-72 rounded border px-2" value={item.factorId||""} onChange={e=>map(item.id,e.target.value).catch(err=>setMessage(err.message))}><option value="">{en?"Not mapped":"미매핑"}</option>{data.factors.map(f=><option key={f.id} value={f.id}>{f.name} · {f.value}/{f.unit}</option>)}</select></td><td>{data.factors.find(f=>f.id===item.factorId)?.source||"-"}</td></tr>)}</tbody></table></div></section>}
 </main></div></>;
}
function ActivityTable({data,en}:{data:Payload|null;en:boolean}){return <div className="mt-5 overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[900px] text-left"><thead className="bg-slate-100 text-sm"><tr>{(en?["Activity","Category","Period","Quantity","Evidence","Mapping"]:["활동자료","구분","기간","활동량","증빙","매핑"]).map(v=><th className="p-3" key={v}>{v}</th>)}</tr></thead><tbody>{data?.items.map(i=><tr className="border-b" key={i.id}><td className="p-3 font-bold">{i.name}</td><td>{i.category}</td><td>{i.period}</td><td>{i.quantity} {i.unit}</td><td>{i.note||"-"}</td><td><span className={`rounded-full px-2 py-1 text-xs font-bold ${i.factorId?"bg-green-100 text-green-800":"bg-orange-100 text-orange-800"}`}>{i.factorName||(en?"Unmapped":"미매핑")}</span></td></tr>)}{!data?.items.length&&<tr><td className="p-8 text-center text-slate-500" colSpan={6}>{en?"No activity data.":"등록된 활동자료가 없습니다."}</td></tr>}</tbody></table></div>}
