package egovframework.com.platform.governance.web;

import egovframework.com.platform.governance.service.ActorProcessGovernanceService;
import jakarta.servlet.http.HttpServletRequest;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.security.Principal;
import java.util.Map;
import java.util.UUID;

@RestController
@RequiredArgsConstructor
@RequestMapping({"/admin/api/system/actor-process","/en/admin/api/system/actor-process"})
public class ActorProcessGovernanceApiController {
    private final ActorProcessGovernanceService service;
    @GetMapping public Map<String,Object> dashboard(){return service.dashboard();}
    @GetMapping("/design-assets") public Map<String,Object> designAssets(){return service.designAssetInventory();}
    @GetMapping("/assets/search") public Map<String,Object> searchAssets(@RequestParam(defaultValue="") String query,@RequestParam(defaultValue="") String assetType,@RequestParam(defaultValue="30") int limit){return service.searchAssetCatalog(query,assetType,limit);}
    @GetMapping("/assets/impact") public ResponseEntity<?> assetImpact(@RequestParam String assetId,@RequestParam(defaultValue="2") int depth){try{return ResponseEntity.ok(service.assetImpact(assetId,depth));}catch(Exception e){return bad(e);}}
    @PostMapping("/assets/refresh") public ResponseEntity<?> refreshAssets(HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.refreshAssetCatalog(p==null?"SYSTEM":p.getName()));}catch(Exception e){return bad(e);}}
    @PostMapping("/design-assets/preflight") public ResponseEntity<?> designPreflight(@RequestBody Map<String,Object>b,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.runDesignPreflight(b,p==null?"SYSTEM":p.getName()));}catch(Exception e){return ResponseEntity.badRequest().body(Map.of("success",false,"message",e.getMessage()==null?"Request failed":e.getMessage()));}}
    @PostMapping("/actors") public ResponseEntity<?> actor(@RequestBody Map<String,Object>b){return run(()->service.createActor(b));}
    @PostMapping("/work-types") public ResponseEntity<?> workType(@RequestBody Map<String,Object>b){return run(()->service.saveWorkType(b));}
    @PostMapping("/assignments") public ResponseEntity<?> assignment(@RequestBody Map<String,Object>b){return run(()->service.assignActor(b));}
    @PostMapping("/processes") public ResponseEntity<?> process(@RequestBody Map<String,Object>b){return run(()->service.createProcess(b));}
    @PostMapping("/steps") public ResponseEntity<?> step(@RequestBody Map<String,Object>b,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.addStep(b,p==null?"SYSTEM":p.getName()));}catch(Exception e){return bad(e);}}
    @PostMapping("/development/plan") public ResponseEntity<?> plan(@RequestBody Map<String,Object>b,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.generateDevelopmentPlan(String.valueOf(b.get("processCode")),String.valueOf(b.get("stepCode")),p==null?"SYSTEM":p.getName()));}catch(Exception e){return bad(e);}}
    @PostMapping("/development/bootstrap-process") public ResponseEntity<?> bootstrapProcess(@RequestBody Map<String,Object>b,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.bootstrapProcessDevelopment(b,p==null?"SYSTEM":p.getName()));}catch(Exception e){return bad(e);}}
    @PostMapping("/development/direct") public ResponseEntity<?> directDevelopment(@RequestBody Map<String,Object>b,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.executeDesignDirectDevelopment(b,p==null?"SYSTEM":p.getName()));}catch(Exception e){return bad(e);}}
    @PostMapping("/design/save-and-generate") public ResponseEntity<?> saveDesignAndGenerate(@RequestBody Map<String,Object>b,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.saveDesignAndGenerate(b,p==null?"SYSTEM":p.getName()));}catch(Exception e){return bad(e);}}
    @PostMapping("/development/approve") public ResponseEntity<?> approve(@RequestBody Map<String,Object>b,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.approveDevelopmentPlan(String.valueOf(b.get("processCode")),String.valueOf(b.get("stepCode")),p==null?"SYSTEM":p.getName()));}catch(Exception e){return bad(e);}}
    @PostMapping("/development/preflight") public ResponseEntity<?> developmentPreflight(@RequestBody Map<String,Object>b,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.runScreenDevelopmentPreflight(String.valueOf(b.get("processCode")),String.valueOf(b.get("stepCode")),p==null?"SYSTEM":p.getName()));}catch(Exception e){return bad(e);}}
    @PostMapping("/design/validate") public ResponseEntity<?> validateDesign(@RequestBody Map<String,Object>b,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.validateProcessDesign(String.valueOf(b.get("processCode")),p==null?"SYSTEM":p.getName()));}catch(Exception e){return bad(e);}}
    @PostMapping("/common-features/install") public ResponseEntity<?> installFeature(@RequestBody Map<String,Object>b,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.installCommonFeature(String.valueOf(b.get("featureCode")),String.valueOf(b.getOrDefault("projectScope","PLATFORM")),p==null?"SYSTEM":p.getName(),config(b.get("configuration"))));}catch(Exception e){return bad(e);}}
    @PostMapping("/professional-screen-contracts") public ResponseEntity<?> professionalScreenContract(@RequestBody Map<String,Object>b,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.saveProfessionalScreenContract(b,p==null?"SYSTEM":p.getName()));}catch(Exception e){return bad(e);}}
    @PostMapping("/professional-factory/execute") public ResponseEntity<?> executeProfessionalFactory(@RequestBody Map<String,Object>b,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.executeProfessionalFactory(b,p==null?"SYSTEM":p.getName()));}catch(Exception e){return bad(e);}}
    @PostMapping("/professional-factory/evidence") public ResponseEntity<?> recordProfessionalEvidence(@RequestBody Map<String,Object>b,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.recordProfessionalEvidence(b,p==null?"SYSTEM":p.getName()));}catch(Exception e){return bad(e);}}
    @PostMapping("/professional-factory/assemble-assets") public ResponseEntity<?> assembleAssets(@RequestBody Map<String,Object>b,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.assembleScreenAssets(String.valueOf(b.get("processCode")),p==null?"SYSTEM":p.getName()));}catch(Exception e){return bad(e);}}
    @PostMapping("/executions/start") public ResponseEntity<?> startExecution(@RequestBody Map<String,Object>b,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.startProcessExecution(b,p==null?"SYSTEM":p.getName()));}catch(Exception e){return bad(e);}}
    @PostMapping("/executions/{executionId}/commands") public ResponseEntity<?> executeCommand(@PathVariable UUID executionId,@RequestBody Map<String,Object>b,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.executeProcessCommand(executionId,b,p==null?"SYSTEM":p.getName()));}catch(Exception e){return bad(e);}}
    @PostMapping("/backend/verify") public ResponseEntity<?> verifyBackend(@RequestBody Map<String,Object>b,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.verifyBackendProcessContracts(String.valueOf(b.getOrDefault("sourceCommit","")),p==null?"SYSTEM":p.getName()));}catch(Exception e){return bad(e);}}
    @PostMapping("/backend/runtime-smoke") public ResponseEntity<?> runtimeSmoke(@RequestParam(defaultValue="") String processCode,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.runProcessRuntimeSmoke(processCode,p==null?"SYSTEM":p.getName()));}catch(Exception e){return bad(e);}}
    @PostMapping("/development/claim") public ResponseEntity<?> claim(@RequestBody Map<String,Object>b){try{return ResponseEntity.ok(service.claimDevelopmentJob(String.valueOf(b.getOrDefault("workerId","AI_RUNNER"))));}catch(Exception e){return bad(e);}}
    @PostMapping("/development/heartbeat") public ResponseEntity<?> heartbeat(@RequestBody Map<String,Object>b){try{return ResponseEntity.ok(service.heartbeatDevelopmentJob(Long.parseLong(String.valueOf(b.get("jobId"))),String.valueOf(b.get("leaseToken")),String.valueOf(b.getOrDefault("workerId","AI_RUNNER"))));}catch(Exception e){return bad(e);}}
    @PostMapping("/development/complete") public ResponseEntity<?> complete(@RequestBody Map<String,Object>b){try{return ResponseEntity.ok(service.completeDevelopmentJob(b,String.valueOf(b.getOrDefault("workerId","AI_RUNNER"))));}catch(Exception e){return bad(e);}}
    @PostMapping("/development/retry") public ResponseEntity<?> retry(@RequestBody Map<String,Object>b,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.retryDevelopmentJob(Long.parseLong(String.valueOf(b.get("jobId"))),p==null?"SYSTEM":p.getName()));}catch(Exception e){return bad(e);}}
    @PostMapping("/development/request") public ResponseEntity<?> requestDevelopment(@RequestBody Map<String,Object>b,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.requestDevelopmentJob(Long.parseLong(String.valueOf(b.get("jobId"))),p==null?"SYSTEM":p.getName()));}catch(Exception e){return bad(e);}}
    @PostMapping("/references/scan") public ResponseEntity<?> scanReferences(@RequestBody Map<String,Object>b,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.scanReferences(String.valueOf(b.getOrDefault("rootPath","/opt/reference")),p==null?"SYSTEM":p.getName()));}catch(Exception e){return bad(e);}}
    @PostMapping("/generation/compile") public ResponseEntity<?> compileScreens(@RequestBody Map<String,Object>b,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.compileScreenBlueprints(b,p==null?"SYSTEM":p.getName()));}catch(Exception e){return bad(e);}}
    @PostMapping("/generation/compile-and-queue") public ResponseEntity<?> compileAndQueueScreens(@RequestBody Map<String,Object>b,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.compileAndQueueScreens(b,p==null?"SYSTEM":p.getName()));}catch(Exception e){return bad(e);}}
    @PostMapping("/generation/adopt-existing") public ResponseEntity<?> adoptExistingScreens(@RequestBody Map<String,Object>b,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.adoptExistingScreens(b,p==null?"SYSTEM":p.getName()));}catch(Exception e){return bad(e);}}
    @PostMapping("/generation/queue") public ResponseEntity<?> queueScreens(@RequestBody Map<String,Object>b,HttpServletRequest request){Principal p=request.getUserPrincipal();try{return ResponseEntity.ok(service.queueScreenGeneration(Long.parseLong(String.valueOf(b.get("batchId"))),p==null?"SYSTEM":p.getName()));}catch(Exception e){return bad(e);}}
    @GetMapping("/generation/batches/{batchId}/export") public ResponseEntity<?> exportScreens(@PathVariable long batchId){try{return ResponseEntity.ok(service.exportScreenGeneration(batchId));}catch(Exception e){return bad(e);}}
    @PostMapping("/cases") public ResponseEntity<?> simulationCase(@RequestBody Map<String,Object>b){return run(()->service.createCase(b));}
    @PostMapping("/artifacts") public ResponseEntity<?> artifact(@RequestBody Map<String,Object>b){return run(()->service.saveArtifact(b));}
    @PostMapping("/runs") public ResponseEntity<?> runCase(@RequestBody Map<String,Object>b, HttpServletRequest request){Principal p=request.getUserPrincipal();return run(()->service.recordRun(b,p==null?"SYSTEM":p.getName()));}
    @PostMapping("/standard-pack") public ResponseEntity<?> standardPack(){try{return ResponseEntity.ok(service.installStandardPack());}catch(Exception e){return ResponseEntity.badRequest().body(Map.of("success",false,"message",e.getMessage()==null?"Request failed":e.getMessage()));}}
    private ResponseEntity<?> bad(Exception e){return ResponseEntity.badRequest().body(Map.of("success",false,"message",e.getMessage()==null?"Request failed":e.getMessage()));}
    private ResponseEntity<?> run(Runnable command){try{command.run();return ResponseEntity.ok(Map.of("success",true));}catch(Exception e){return ResponseEntity.badRequest().body(Map.of("success",false,"message",e.getMessage()==null?"Request failed":e.getMessage()));}}
    private Map<String,Object> config(Object value){Map<String,Object> result=new java.util.LinkedHashMap<>();if(value instanceof Map<?,?> raw)raw.forEach((key,item)->result.put(String.valueOf(key),item));return result;}
}
