// Generated from the approved alerts-design/index.html. These are proposed event rules.
export const alertCatalog = [
  {
    "id": "N01",
    "area": "공통 업무",
    "name": "업무 배정·인계",
    "trigger": "담당자로 새로 배정되거나 인계가 확정됨",
    "recipient": "새 담당자·인계자",
    "priority": "보통",
    "resolve": "인계 확인",
    "menu": "일반 내 업무",
    "url": "/mypage/my-tasks"
  },
  {
    "id": "N02",
    "area": "공통 업무",
    "name": "마감 임박·기한 경과",
    "trigger": "미완료 업무가 예고 시점 또는 기한에 도달",
    "recipient": "담당자·지연 책임자",
    "priority": "높음",
    "resolve": "완료·기한 변경",
    "menu": "마감·지연 현황",
    "url": "/emission/deadline-status"
  },
  {
    "id": "N03",
    "area": "탄소배출",
    "name": "활동자료 제출 요청",
    "trigger": "사업장별 제출 요청 발행",
    "recipient": "자료 제출 담당자",
    "priority": "보통",
    "resolve": "자료 제출",
    "menu": "자료 제출 요청",
    "url": "/emission/data-request"
  },
  {
    "id": "N04",
    "area": "탄소배출",
    "name": "자료 접수 대기",
    "trigger": "담당 사업장 자료가 제출됨",
    "recipient": "접수 담당자",
    "priority": "보통",
    "resolve": "접수·보완 요청",
    "menu": "자료 제출 요청",
    "url": "/emission/data-request"
  },
  {
    "id": "N05",
    "area": "탄소배출",
    "name": "활동자료 보완 요청",
    "trigger": "누락·오류 항목과 보완 기한이 지정됨",
    "recipient": "제출 담당자",
    "priority": "높음",
    "resolve": "보완 재제출",
    "menu": "보완·재산정",
    "url": "/emission/correction"
  },
  {
    "id": "N06",
    "area": "탄소배출",
    "name": "증빙 누락·유효성 문제",
    "trigger": "제출 검사에서 필수 증빙 누락·불일치 확인",
    "recipient": "자료 작성자",
    "priority": "높음",
    "resolve": "증빙 보완·재검사",
    "menu": "증빙 자료함",
    "url": "/emission/evidence"
  },
  {
    "id": "N07",
    "area": "탄소배출",
    "name": "외부자료 수집 실패",
    "trigger": "예약 수집이 실패하거나 예정 시점을 초과",
    "recipient": "연계 담당자",
    "priority": "높음",
    "resolve": "재수집 성공",
    "menu": "외부 데이터 연계",
    "url": "/emission/external-data"
  },
  {
    "id": "N08",
    "area": "탄소배출",
    "name": "배출계수 적용 검토",
    "trigger": "사용 중 계수의 개정·적용기간 변경이 확인됨",
    "recipient": "산정 담당자",
    "priority": "보통",
    "resolve": "영향 검토 기록",
    "menu": "산정 기준·배출계수",
    "url": "/home/emission/factor-reference"
  },
  {
    "id": "N09",
    "area": "탄소배출",
    "name": "산정 실패·완료",
    "trigger": "사용자가 요청한 산정 작업이 종료됨",
    "recipient": "산정 요청자",
    "priority": "실패 시 높음",
    "resolve": "실패 조치·결과 확인",
    "menu": "산정 결과",
    "url": "/emission/calculation-results"
  },
  {
    "id": "N10",
    "area": "탄소배출",
    "name": "검증 보완·재검증 요청",
    "trigger": "검증자가 쟁점을 등록하거나 보완본 제출",
    "recipient": "해당 작성자·검증자",
    "priority": "높음",
    "resolve": "쟁점 해소",
    "menu": "데이터 검증",
    "url": "/emission/data-validation"
  },
  {
    "id": "N11",
    "area": "탄소배출",
    "name": "검토·승인 요청",
    "trigger": "검토 대상 버전이 제출됨",
    "recipient": "지정 검토자·승인자",
    "priority": "보통",
    "resolve": "승인·반려",
    "menu": "검토·승인",
    "url": "/emission/review-approval"
  },
  {
    "id": "N12",
    "area": "탄소배출",
    "name": "승인·반려 결과",
    "trigger": "승인 또는 사유 있는 반려가 확정됨",
    "recipient": "요청자",
    "priority": "반려 시 높음",
    "resolve": "반려 보완·결과 확인",
    "menu": "검토·승인",
    "url": "/emission/review-approval"
  },
  {
    "id": "N13",
    "area": "탄소배출",
    "name": "보고서 기준 재확인",
    "trigger": "보고서가 참조한 확정 결과와 새 버전이 달라짐",
    "recipient": "보고서 작성자",
    "priority": "높음",
    "resolve": "기준 재확인",
    "menu": "보고서 작성",
    "url": "/emission/report-write"
  },
  {
    "id": "N14",
    "area": "탄소배출",
    "name": "제출 접수·보완·수리",
    "trigger": "기관 응답이 연계되거나 담당자가 증빙과 함께 기록",
    "recipient": "제출 담당자",
    "priority": "보완 시 높음",
    "resolve": "보완 제출·수리 확인",
    "menu": "보고서 제출",
    "url": "/emission/report-submission"
  },
  {
    "id": "N15",
    "area": "탄소배출",
    "name": "보고서·인증서 준비 완료",
    "trigger": "사용자 요청 파일 생성이 완료됨",
    "recipient": "요청자",
    "priority": "정보",
    "resolve": "열람",
    "menu": "보고서·인증서 다운로드",
    "url": "/emission/report-download"
  },
  {
    "id": "N16",
    "area": "제품 LCA",
    "name": "LCI 데이터 매핑 보완",
    "trigger": "필수 입력의 미매핑·단위 불일치가 검사됨",
    "recipient": "LCA 수행자",
    "priority": "높음",
    "resolve": "매핑 보완·재검사",
    "menu": "LCI 데이터 매핑",
    "url": "/lca/data-mapping"
  },
  {
    "id": "N17",
    "area": "제품 LCA",
    "name": "LCI 산정 실패·완료",
    "trigger": "요청한 LCI 산정 실행이 종료됨",
    "recipient": "산정 요청자",
    "priority": "실패 시 높음",
    "resolve": "재실행·결과 확인",
    "menu": "LCI 산정",
    "url": "/lca/calculation"
  },
  {
    "id": "N18",
    "area": "제품 LCA",
    "name": "LCIA 평가 검토 필요",
    "trigger": "평가 실패 또는 참조 LCI·방법론 버전 변경",
    "recipient": "LCA 수행자·검토자",
    "priority": "높음",
    "resolve": "재평가·검토",
    "menu": "LCIA 영향평가",
    "url": "/lca/impact-assessment"
  },
  {
    "id": "N19",
    "area": "제품 LCA",
    "name": "민감도 분석 실행 결과",
    "trigger": "요청한 분석 실행이 완료되거나 실패",
    "recipient": "분석 요청자",
    "priority": "실패 시 높음",
    "resolve": "결과 확인·재실행",
    "menu": "민감도 분석",
    "url": "/lca/sensitivity-analysis"
  },
  {
    "id": "N20",
    "area": "제품 LCA",
    "name": "결과 해석 보완",
    "trigger": "검토자가 해석·가정·개선안 보완을 요청",
    "recipient": "LCA 작성자",
    "priority": "보통",
    "resolve": "보완본 검토",
    "menu": "결과 해석·개선안",
    "url": "/lca/interpretation"
  },
  {
    "id": "N21",
    "area": "감축 관리",
    "name": "감축 과제 승인 요청·결과",
    "trigger": "과제 검토 요청 또는 승인·반려 발생",
    "recipient": "승인자·신청자",
    "priority": "보통",
    "resolve": "승인·보완",
    "menu": "과제 승인",
    "url": "/reduction/task/approval"
  },
  {
    "id": "N22",
    "area": "감축 관리",
    "name": "실적 제출 지연",
    "trigger": "과제 실적 제출 기한 경과",
    "recipient": "과제 담당자",
    "priority": "높음",
    "resolve": "실적 제출",
    "menu": "감축 실적",
    "url": "/reduction/performance"
  },
  {
    "id": "N23",
    "area": "감축 관리",
    "name": "목표 이탈 조치 필요",
    "trigger": "승인된 허용 편차 기준을 초과",
    "recipient": "목표 담당자",
    "priority": "높음",
    "resolve": "원인·조치 등록",
    "menu": "목표 대비 실적",
    "url": "/reduction/target-gap"
  },
  {
    "id": "N24",
    "area": "모니터링",
    "name": "중요 경보 발생·복구",
    "trigger": "승인된 경보 규칙의 발령 또는 복구",
    "recipient": "해당 사업장 경보 담당자",
    "priority": "긴급",
    "resolve": "경보 조치·복구",
    "menu": "경보 현황",
    "url": "/monitoring/alerts"
  },
  {
    "id": "N25",
    "area": "탄소·자원",
    "name": "무결성 검증 실패",
    "trigger": "추적 데이터 또는 연결 증빙 검증 실패",
    "recipient": "해당 거래·MRV 담당자",
    "priority": "높음",
    "resolve": "불일치 해소",
    "menu": "무결성 추적",
    "url": "/co2/integrity"
  },
  {
    "id": "N26",
    "area": "교육·지원",
    "name": "교육 일정·수료 결과",
    "trigger": "신청한 과정 일정 변경·마감·수료 확정",
    "recipient": "해당 수강자",
    "priority": "보통",
    "resolve": "확인·수강",
    "menu": "나의 교육",
    "url": "/edu/my_course"
  },
  {
    "id": "N27",
    "area": "교육·지원",
    "name": "문의 답변 등록",
    "trigger": "본인 문의에 담당자 답변이 등록됨",
    "recipient": "문의 작성자",
    "priority": "정보",
    "resolve": "답변 확인",
    "menu": "문의 내역",
    "url": "/support/inquiry"
  },
  {
    "id": "N28",
    "area": "계정·회원",
    "name": "위임·승계 확인 요청",
    "trigger": "본인에게 담당자 위임·승계 요청 도착",
    "recipient": "수임 대상자",
    "priority": "높음",
    "resolve": "수락·거절",
    "menu": "회원사 담당자 위임·승계",
    "url": "/work/company-manager-delegation"
  },
  {
    "id": "N29",
    "area": "계정·회원",
    "name": "계정 정보·권한 변경",
    "trigger": "본인 연락처·접근권한 변경이 완료됨",
    "recipient": "계정 소유자",
    "priority": "정보",
    "resolve": "확인·이의 문의",
    "menu": "마이페이지",
    "url": "/mypage/profile"
  },
  {
    "id": "N30",
    "area": "서비스",
    "name": "서비스 점검·장애 영향",
    "trigger": "관리자가 영향 메뉴와 시간을 확정하여 공지",
    "recipient": "영향받는 사용자",
    "priority": "장애 시 높음",
    "resolve": "복구 확인",
    "menu": "서비스 상태",
    "url": "/mtn/status"
  }
] as const;
