import { useEffect, useMemo, useState } from "react";
import { buildLocalizedPath, isEnglish } from "../../lib/navigation/runtime";

type Task={id:number;projectId:string;projectName:string;site:string;name:string;type:string;status:string;priority:string;assignee:string;dueDate:string;targetUrl:string};
type Response={items:Task[];summary:{today:number;overdue:number;approval:number}};
type Kind="ALL"|"OVERDUE"|"TODAY"|"APPROVAL"|"PRIORITY";
const dateOnly=()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),d.getDate())};
const days=(value:string)=>Math.round((new Date(`${value}T00:00:00`).getTime()-dateOnly().getTime())/86400000);

export function HomeAlertsPage(){const en=isEnglish(),api=buildLocalizedPath("/home/api/emission-tasks","/en/home/api/emission-tasks");const[data,setData]=useState<Response|null>(null),[kind,setKind]=useState<Kind>("ALL"),[keyword,setKeyword]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true);
useEffect(()=>{fetch(api,{credentials:"include"}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.message);setData(b)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[api]);
const items=useMemo(()=>(data?.items||[]).filter(x=>x.status!=="DONE").filter(x=>kind==="ALL"||(kind==="OVERDUE"&&days(x.dueDate)<0)||(kind==="TODAY"&&days(x.dueDate)===0)||(kind==="APPROVAL"&&x.type==="APPROVAL")||(kind==="PRIORITY"&&["URGENT","HIGH"].includes(x.priority))).filter(x=>!keyword||`${x.name} ${x.projectName} ${x.site}`.toLowerCase().includes(keyword.toLowerCase())).sort((a,b)=>days(a.dueDate)-days(b.dueDate)),[data,kind,keyword]);
const t=en?{eyebrow:"Integrated Home",title:"Priority Alerts",desc:"Review overdue tasks, today's deadlines and pending approvals that require action.",all:"All",overdue:"Overdue",today:"Due Today",approval:"Pending Approval",priority:"High Priority",search:"Search project, task or site",task:"Alert / Project",site:"Site",owner:"Assignee",due:"Due",action:"Action",open:"Review",empty:"No alerts match the selected conditions.",loading:"Loading alerts..."}:{eyebrow:"통합 홈",title:"주요 알림",desc:"즉시 조치가 필요한 지연 업무, 오늘 마감과 승인 대기 항목을 우선순위로 확인합니다.",all:"전체",overdue:"지연",today:"오늘 마감",approval:"승인 대기",priority:"높은 우선순위",search:"프로젝트, 업무 또는 사업장 검색",task:"알림 / 프로젝트",site:"사업장",owner:"담당자",due:"마감",action:"처리",open:"확인",empty:"선택한 조건에 해당하는 알림이 없습니다.",loading:"알림을 불러오는 중입니다."};
const cards:[[Kind,string,number,string],string][]=[[["OVERDUE",t.overdue,data?.summary.overdue||0,"error"],"bg-red-50 text-red-800 border-red-200"],[["TODAY",t.today,data?.summary.today||0,"today"],"bg-orange-50 text-orange-800 border-orange-200"],[["APPROVAL",t.approval,data?.summary.approval||0,"approval"],"bg-blue-50 text-blue-800 border-blue-200"],[["PRIORITY",t.priority,(data?.items||[]).filter(x=>x.status!=="DONE"&&["URGENT","HIGH"].includes(x.priority)).length,"priority_high"],"bg-violet-50 text-violet-800 border-violet-200"]];
return <main className="min-h-[calc(100vh-80px)] bg-[#f5f7fa] px-4 py-8 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold text-[#246beb]">{t.eyebrow}</p><h1 className="mt-2 text-3xl font-black text-[#052b57]">{t.title}</h1><p className="mt-2 text-slate-600">{t.desc}</p><section className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([[value,label,count,icon],style])=><button key={value} onClick={()=>setKind(value)} className={`rounded-2xl border p-5 text-left shadow-sm ${style}`}><span className="material-symbols-outlined">{icon}</span><span className="ml-2 text-sm font-bold">{label}</span><strong className="mt-3 block text-3xl">{count}</strong></button>)}</section>
<section className="mt-5 rounded-2xl border bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 md:flex-row"><input className="h-11 flex-1 rounded-lg border px-4" value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder={t.search}/><select className="h-11 rounded-lg border bg-white px-4" value={kind} onChange={e=>setKind(e.target.value as Kind)}><option value="ALL">{t.all}</option><option value="OVERDUE">{t.overdue}</option><option value="TODAY">{t.today}</option><option value="APPROVAL">{t.approval}</option><option value="PRIORITY">{t.priority}</option></select></div></section>{error&&<p className="mt-4 rounded-xl bg-red-50 p-4 font-bold text-red-700">{error}</p>}
<section className="mt-5 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-100"><tr>{[t.task,t.site,t.owner,t.due,t.action].map(x=><th key={x} className="px-5 py-3">{x}</th>)}</tr></thead><tbody>{items.map(x=>{const remain=days(x.dueDate),base=x.targetUrl||"/emission/project/detail",glue=base.includes("?")?"&":"?",ko=`${base}${glue}projectId=${encodeURIComponent(x.projectId)}`;return <tr key={x.id} className="border-t hover:bg-slate-50"><td className="px-5 py-4"><div className="flex items-start gap-3"><span className={`mt-1 h-2.5 w-2.5 rounded-full ${remain<0?"bg-red-500":remain===0?"bg-orange-500":"bg-blue-500"}`}/><div><strong className="block text-slate-900">{x.name}</strong><span className="mt-1 block text-slate-500">{x.projectName}</span></div></div></td><td className="px-5">{x.site||"-"}</td><td className="px-5">{x.assignee||"-"}</td><td className={`px-5 font-bold ${remain<0?"text-red-700":""}`}>{remain<0?`${t.overdue} ${Math.abs(remain)}${en?"d":"일"}`:remain===0?t.today:`D-${remain}`}<span className="mt-1 block text-xs font-normal text-slate-500">{x.dueDate}</span></td><td className="px-5"><a href={buildLocalizedPath(ko,`/en${ko}`)} className="rounded-lg bg-[#246beb] px-3 py-2 font-bold text-white">{t.open}</a></td></tr>})}</tbody></table></div>{(loading||!items.length)&&<p className="p-10 text-center text-slate-500">{loading?t.loading:t.empty}</p>}</section></div></main>}
