---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-engineering
  title: Platform Engineering
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: carbon-operations
  title: Carbon Operations
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: verification-governance
  title: Verification Governance
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: resonance-requester
  title: Resonance Requester
spec:
  profile:
    displayName: Resonance Requester
  memberOf: [platform-engineering]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: resonance-reviewer
  title: Resonance Reviewer
spec:
  profile:
    displayName: Resonance Reviewer
  memberOf: [carbon-operations]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: resonance-approver
  title: Resonance Approver
spec:
  profile:
    displayName: Resonance Approver
  memberOf: [verification-governance]
