const $=s=>document.querySelector(s),E=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),API='/projects/P006/registry-api';let meta,offset=0,editing=null,detailId=null,pendingImport=null,assetAfter='';
function say(x){$('#message').textContent=x}
async function api(path,method='GET',body){const r=await fetch(API+path,{method,credentials:'same-origin',headers:method==='GET'?{}:{'Content-Type':'application/json','X-P006-Requested-With':'equipment-registry'},body:body?JSON.stringify(body):undefined});let d;try{d=await r.json()}catch{throw Error('서버 JSON 응답 없음: '+r.status)}if(!r.ok){if(r.status===401){$('#login').hidden=false;$('#app').hidden=true}throw Error(d.error||r.status)}return d}
function form(f){return Object.fromEntries(new FormData(f))}function parseJson(v){return JSON.parse(v||'{}')}
function options(rows,key='id',label='name',blank=true){return(blank?'<option value="">미선택 / 미확인</option>':'')+rows.map(x=>`<option value="${E(x[key])}">${E(typeof label==='function'?label(x):x[label])}</option>`).join('')}
function parents(){let ent=$('#entity').value;$('#parent').innerHTML=options(ent==='plant'?meta.customers:ent==='line'?meta.plants:ent==='process'?meta.lines:[]);$('#parent').disabled=ent==='customer'}
function renderForm(){const opts={process:options(meta.hierarchy,'id',x=>[x.customer_name,x.plant_name,x.line_name,x.name].join(' / ')),equipmentType:options(meta.types,'code'),model:options(meta.models,'id',x=>x.manufacturer_name+' / '+x.name),option:options(meta.options)};$('#fields').innerHTML=meta.contract.equipmentForm.map(f=>`<label>${E(f.label)}${f.required?' *':''}${opts[f.type]?`<select name="${f.key}" ${f.required?'required':''}>${opts[f.type]}</select>`:f.type==='json'?`<textarea name="${f.key}">{}</textarea>`:`<input name="${f.key}" ${f.required?'required':''}>`}</label>`).join('');$('#fields [name=modelId]').onchange=()=>{$('#fields [name=optionId]').innerHTML=options(meta.options.filter(o=>o.model_id===$('#fields [name=modelId]').value))}}
async function init(){try{meta=await api('/meta');$('#login').hidden=true;$('#app').hidden=false;$('#actor').textContent=`접속: ${meta.actor.name} · ${meta.actor.admin?'프로젝트 관리자':'명시적으로 허용된 업체만 표시'}`;$('#libraryCount').textContent=`공통 자산 ${meta.library.total}종 · Entry USD ${meta.library.connected}종 · Equipment Type ${meta.types.length}개`;const selected=$('#customerFilter').value;$('#customerFilter').innerHTML='<option value="">접근 가능한 전체 업체</option>'+options(meta.customers,'id','name',false);$('#customerFilter').value=selected;$('#accessCustomer').innerHTML=options(meta.customers);$('#manufacturerSelect').innerHTML=options(meta.manufacturers);$('#modelType').innerHTML=options(meta.types,'code');$('#optionModel').innerHTML=options(meta.models,'id',x=>x.manufacturer_name+' / '+x.name);$('#help').textContent=meta.contract.help;$('#qa').textContent=meta.contract.qa;$('#nextTask').textContent=meta.contract.next;parents();if(!editing)renderForm();await load()}catch(e){say(e.message)}}
async function load(){const c=$('#customerFilter').value,query='?customerId='+encodeURIComponent(c),s=await api('/stats'+query),r=await api('/equipment'+query+'&offset='+offset+'&q='+encodeURIComponent($('#search').value));$('#stats').innerHTML=s.customers.map(x=>`<tr><td>${E(x.name)}</td>${['total','connected','coverage','exact_match','close_match','reference_match','no_match','blocked','verified'].map(k=>`<td>${x[k]??'—'}${k==='coverage'&&x[k]!=null?'%':''}</td>`).join('')}</tr>`).join('')||'<tr><td colspan="10">등록된 업체가 없습니다. 실제 업체부터 등록하세요.</td></tr>';$('#equipment').innerHTML=r.items.map(x=>`<tr><td>${E(x.customer_name)}<br>${E(x.plant_name)} / ${E(x.line_name)}<br>${E(x.process_name)}</td><td><b>${E(x.name)}</b><br>${E(x.code)}<small><br>${E(x.equipment_type_code)}<br>관리 ${E(x.management_number||'미등록')} / 일련 ${E(x.serial_number||'미등록')}</small></td><td>${E(x.manufacturer_name||'미확인')}<br>${E(x.model_name||'미확인')}<br>${E(x.option_name||'옵션 미확인')}</td><td>${x.image?`<img src="${E(x.image)}" data-image="${E(x.image)}" alt="추천 자산">`:'NO_PREVIEW'}</td><td>${E(x.matched_asset_id||'미선정')}<code>${E(x.entry_usd||'Entry 미연결')}</code></td><td><span class="badge ${x.match_grade}">${x.match_grade}</span><br>${x.connected_asset_id?'연결 수용됨':'추천/검토 대기'}<br>${E(x.verification.status||'UNVERIFIED')}<small><br>REAL UNBOUND</small></td><td><button data-detail="${x.id}">상세·자료</button> <button data-edit="${x.id}">수정</button> <button data-match="${x.id}">재매칭</button>${['EXACT_MATCH','REFERENCE_MATCH'].includes(x.match_grade)&&x.matched_asset_id?` <button data-bind="${x.id}" data-asset="${x.matched_asset_id}" data-grade="${x.match_grade}">연결 수용</button>`:''}</td></tr>`).join('')||'<tr><td colspan="7">실제 설비가 없습니다. 종류 16개를 실제 설비로 복제하지 않았습니다.</td></tr>';$('#page').textContent=`${r.total?offset+1:0}–${Math.min(offset+50,r.total)} / ${r.total}`;$('#prev').disabled=offset===0;$('#next').disabled=offset+50>=r.total;let n=await api('/candidates'+query);$('#candidates').innerHTML=n.items.map(x=>`<p>${E(x.customer_name)} / ${E(x.name)} · ${E(x.status)} · 후보 ${E(x.id)}</p>`).join('')||'<p>신규 자산 후보 없음</p>'}
async function detail(id){detailId=id;let d=await api('/equipment/'+id);$('#detailTitle').textContent=d.equipment.customer_name+' / '+d.equipment.name;$('#detailData').textContent=JSON.stringify(d.equipment,null,2);$('#evidenceList').innerHTML=d.evidence.map(x=>`<article><b>${E(x.kind)} ${E(x.name)}</b> · ${E(x.review_status)}<p>${E(x.source_uri||'업로드 자료')}<br>SHA ${E(x.sha256||'원본 참조')}<br>자료 ID ${x.id}</p>${x.sha256?`<a href="${API}/evidence/${x.id}">권한 확인 후 다운로드</a>`:''}${meta.actor.admin?` <button data-review="${x.id}" data-status="APPROVED">실제 검토 후 승인</button> <button data-review="${x.id}" data-status="REJECTED">반려</button>`:''}</article>`).join('');if(!$('#detail').open)$('#detail').showModal()}
function guarded(fn){return async e=>{if(e?.type==='submit')e.preventDefault();try{await fn(e)}catch(x){say(x.message)}}}
$('#loginForm').onsubmit=guarded(async e=>{let r=await fetch('/r/P006/actuator/p006/auth/login',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(form(e.target))});if(!r.ok)throw Error('P006 로그인 실패 '+r.status);e.target.password.value='';await init();say('로그인 완료')});
$('#hierarchyForm').onsubmit=guarded(async e=>{await api('/hierarchy','POST',form(e.target));e.target.code.value='';e.target.name.value='';await init();say('계층 등록 완료')});$('#entity').onchange=parents;
for(const [id,path,convert] of [['manufacturerForm','manufacturers'],['modelForm','models'],['optionForm','options','parameters'],['typeForm','types'],['accessForm','customer-access'],['bindingForm','model-assets','evidenceIds']])$('#'+id).onsubmit=guarded(async e=>{let p=form(e.target);if(convert)p[convert]=parseJson(p[convert]);await api('/'+path,'POST',p);await init();say('등록 완료: '+path)});
$('#equipmentForm').onsubmit=guarded(async e=>{let p=form(e.target);for(let f of meta.contract.equipmentForm)if(f.type==='json')p[f.key]=parseJson(p[f.key]);if(editing)p.version=editing.version;let r=await api('/equipment'+(editing?'/'+editing.id:''),editing?'PATCH':'POST',p);editing=null;$('#editing').textContent='';await init();say('저장 완료 · '+r.match.grade)});
$('#cancelEdit').onclick=()=>{editing=null;renderForm();$('#editing').textContent='신규 등록'};
document.addEventListener('click',guarded(async ev=>{const b=ev.target.closest('button,img[data-image]');if(!b)return;if(b.dataset.detail)await detail(b.dataset.detail);if(b.dataset.edit){let r=await api('/equipment/'+b.dataset.edit);editing=r.equipment;renderForm();for(let f of meta.contract.equipmentForm){let key=f.key.replace(/[A-Z]/g,x=>'_'+x.toLowerCase()),v=editing[key];$('#equipmentForm [name='+f.key+']').value=f.type==='json'?JSON.stringify(v||{}):v||''}$('#editing').textContent='수정 중: '+editing.id+' · version '+editing.version;$('#register').scrollIntoView()}if(b.dataset.match){await api('/equipment/'+b.dataset.match+'/match','POST',{});await load();say('재매칭 완료; 이전 연결 수용은 재확인 필요')}if(b.dataset.bind){if(!confirm(b.dataset.grade+' 기준으로 연결을 수용합니까? 기준 형상 수용은 실물/물리/READY/REAL 검증이 아닙니다.'))return;await api('/equipment/'+b.dataset.bind+'/bind','POST',{assetId:b.dataset.asset,acceptReference:true});await load();say('연결 수용 완료')}if(b.dataset.review){let note=prompt('실제 자료를 확인한 검토 근거를 입력하세요.');if(!note)return;await api('/evidence/'+b.dataset.review+'/review','POST',{status:b.dataset.status,note});await detail(detailId);await load()}if(b.dataset.image){$('#largeImage').src=b.dataset.image;$('#imageDialog').showModal()}}));
$('#closeDetail').onclick=()=>$('#detail').close();$('#closeImage').onclick=()=>$('#imageDialog').close();
$('#evidenceForm').onsubmit=guarded(async e=>{let p=form(e.target),f=$('#evidenceFile').files[0];if(f){if(f.size>5*1024*1024)throw Error('5MB 초과: 원본 경로로 등록하세요');p.mime=f.type;p.contentBase64=await new Promise((resolve,reject)=>{let r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(f)})}await api('/equipment/'+detailId+'/evidence','POST',p);$('#evidenceFile').value='';await detail(detailId);say('자료는 UNREVIEWED로 등록되었습니다')});
function csv(s){let rs=[],r=[],v='',quoted=false;for(let i=0;i<s.length;i++){let c=s[i];if(c==='"'){if(quoted&&s[i+1]==='"'){v+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){r.push(v);v=''}else if(c==='\n'&&!quoted){r.push(v.replace(/\r$/,''));rs.push(r);r=[];v=''}else v+=c}if(quoted)throw Error('CSV 따옴표 미종결');if(v||r.length){r.push(v.replace(/\r$/,''));rs.push(r)}let keys=rs.shift().map(x=>x.replace(/^\uFEFF/,''));return rs.filter(x=>x.some(Boolean)).map(r=>{if(r.length!==keys.length)throw Error('CSV 열 수 불일치');let p=Object.fromEntries(keys.map((k,i)=>[k,r[i]]));for(let f of meta.contract.equipmentForm)if(f.type==='json')p[f.key]=parseJson(p[f.key]);return p})}
$('#importFile').onchange=()=>{pendingImport=null;$('#commitImport').disabled=true};$('#validateImport').onclick=guarded(async()=>{let f=$('#importFile').files[0];if(!f)throw Error('파일을 선택하세요');let s=await f.text();pendingImport=f.name.endsWith('.csv')?csv(s):JSON.parse(s);if(!Array.isArray(pendingImport))throw Error('최상위 JSON 배열 필요');let r=await api('/equipment/import','POST',{items:pendingImport,dryRun:true});$('#importResult').textContent=JSON.stringify(r,null,2);$('#commitImport').disabled=false});$('#commitImport').onclick=guarded(async()=>{let r=await api('/equipment/import','POST',{items:pendingImport,dryRun:false});pendingImport=null;$('#commitImport').disabled=true;$('#importResult').textContent=JSON.stringify(r,null,2);await load()});
$('#reload').onclick=guarded(init);$('#customerFilter').onchange=guarded(async()=>{offset=0;await load()});let timer;$('#search').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{offset=0;load().catch(e=>say(e.message))},250)};$('#prev').onclick=guarded(async()=>{offset=Math.max(0,offset-50);await load()});$('#next').onclick=guarded(async()=>{offset+=50;await load()});
async function assets(reset){if(reset)assetAfter='';let d=await api('/assets?q='+encodeURIComponent($('#assetSearch').value)+'&after='+assetAfter);$('#assets').innerHTML=d.items.map(a=>`<article class="card">${a.image?`<img data-image="${E(a.image)}" src="${E(a.image)}" alt="${E(a.name)}">`:'NO_PREVIEW'}<b>${E(a.id)} ${E(a.name)}</b><p>${E(a.english_name)}</p><small>${E(a.category)}</small><p>${E(a.purpose)}</p><code>${E(a.entry_usd||'USD 미연결 / BLOCKED')}</code></article>`).join('');if(d.items.length)assetAfter=d.items.at(-1).id;$('#assetMore').disabled=d.items.length<50}
$('#assetFind').onclick=guarded(()=>assets(true));$('#assetMore').onclick=guarded(()=>assets(false));init();
$('#newAssetForm').onsubmit=guarded(async e=>{let p=form(e.target);p.variant=parseJson(p.variant);let r=await api('/assets','POST',p);await init();say('공통 자산 등록: '+r.id+' · '+r.status+' · 실제 설비 연결은 별도 검토')});
