const $=s=>document.querySelector(s),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let data=[],visible=[];const selected=new Set();
async function api(path,body){let r=await fetch('/projects/P006/registry-api'+path,{credentials:'same-origin',method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-P006-Requested-With':'equipment-registry'}:{},body:body?JSON.stringify(body):undefined});let d=await r.json();if(!r.ok)throw Error(d.error||r.status);return d}
function msg(s){$('#message').textContent=s}async function guard(fn){try{await fn()}catch(e){msg(e.message)}}
function render(){let q=$('#search').value.trim().toLowerCase();visible=data.filter(x=>(!q||JSON.stringify([x.source_name,x.asset_name,x.asset_id,x.id]).toLowerCase().includes(q))&&(!$('#ownership').value||x.attribution_status===$('#ownership').value)&&(!$('#grade').value||x.grade===$('#grade').value));$('#shown').textContent=`표시 ${visible.length} / 전체 ${data.length} · 선택 ${selected.size}`;
 $('#rows').innerHTML=visible.map(x=>{let e=x.evidence,r=x.recommendation;return `<tr><td><input type="checkbox" data-id="${esc(x.id)}" aria-label="${esc(x.source_name)} 선택" ${selected.has(x.id)?'checked':''}></td><td><b>${esc(x.source_name)}</b><small>${esc(x.id)}</small><small>${esc(e.fileName)} · ${esc(e.sheet)}!${esc(e.cell)}</small><small>번호 원문: ${esc(e.numberVerbatim||'번호 없음')}</small><details><summary>원본·귀속 증거</summary><pre>${esc(JSON.stringify(e,null,2))}</pre></details></td><td>${esc(x.customer_name)} / ${esc(x.plant_name)}<small>라인 ${esc(x.line_name)} / 공정 ${esc(x.process_name)}</small><b>${x.attribution_status==='UNCONFIRMED'?'귀속 확인 필요':'귀속 확정'}</b><small>${esc(x.attribution_evidence||e.attributionConfidence)}</small></td><td>제조사 ${esc(x.manufacturer)}<br>모델 ${esc(x.model)}<br>실측 치수 UNKNOWN<br>설치 위치 UNKNOWN<small>용도 해석(미검증): ${esc(x.classification.roleInterpretation)}</small></td><td>${x.image?`<img loading="lazy" src="${esc(x.image)}" data-image="${esc(x.image)}" data-caption="${esc(x.asset_name)} · 실제 설비 사진 아님" alt="${esc(x.asset_name)} 기준 자산"><small>카탈로그 기준 렌더</small>`:'NO_PREVIEW'}</td><td><b>${esc(x.asset_name||'추천 확정 보류')}</b><small>${esc(x.asset_id||'—')}</small><code>${esc(x.entry_usd||'Entry 미선정')}</code><details><summary>Base / Variant</summary><pre>${esc(JSON.stringify({base:x.base_usd,variant:x.variant},null,2))}</pre></details></td><td><b>${esc(x.grade)}</b><small>검토 점수 ${r.confidence??'해당 없음'} (동일성 확률 아님)</small>${esc(r.reason)}<details><summary>724종 검토 후보</summary>${esc(r.semanticCandidatesReviewed.join(', '))}</details></td><td>${esc(r.modifications)}<details><summary>대체 검토 후보 (미승인)</summary><pre>${esc(JSON.stringify(r.alternatives,null,2))}</pre></details><b>${esc(r.connectionStatus)}</b><small>${esc(r.unconnectedReason)}</small><small>READY 미승격 · REAL UNBOUND</small></td></tr>`}).join('');$('#all').checked=visible.length>0&&visible.every(x=>selected.has(x.id));}
async function load(){let d=await api('/intake'),m=await api('/meta');data=d.items;selected.clear();let s=d.stats;$('#metrics').innerHTML=[['원장 후보',s.total],['추천 Entry',`${s.recommended} (${s.recommendationCoverage}%)`],['귀속 확인 필요',s.ownershipPending],...Object.entries(s.grades),['연결 수용',s.acceptedConnections]].map(([k,v])=>`<article>${esc(k)}<b>${esc(v)}</b></article>`).join('');$('#process').innerHTML='<option value="">실제 공정 선택 필요</option>'+m.hierarchy.map(x=>`<option value="${esc(x.id)}">${esc([x.customer_name,x.plant_name,x.line_name,x.name].join(' → '))}</option>`).join('');render();msg(`DB 재조회 완료 · 공통 자산 ${d.library.total} / Entry ${d.library.connected} · 설치 확인과 추천은 별도`)}
$('#reload').onclick=()=>guard(load);for(let id of ['search','ownership','grade'])$('#'+id).oninput=render;
$('#all').onchange=e=>{for(let x of visible)e.target.checked?selected.add(x.id):selected.delete(x.id);render()};$('#rows').onchange=e=>{if(e.target.dataset.id){e.target.checked?selected.add(e.target.dataset.id):selected.delete(e.target.dataset.id);render()}};
$('#rows').onclick=e=>{let i=e.target.closest('[data-image]');if(i){$('#big').src=i.dataset.image;$('#caption').textContent=i.dataset.caption;$('#zoom').showModal()}};$('#closeZoom').onclick=()=>$('#zoom').close();
$('#assign').onclick=()=>guard(async()=>{if(!selected.size)throw Error('원장 후보를 선택하세요');if(!$('#process').value)throw Error('실제 등록된 공정을 선택하세요');if($('#evidence').value.trim().length<11)throw Error('귀속 확정 근거를 11자 이상 기록하세요');if(!confirm(`${selected.size}개 원장의 업체/공장 귀속을 확정합니까? 원문과 추천 등급은 유지됩니다.`))return;let r=await api('/intake/attribution',{items:data.filter(x=>selected.has(x.id)).map(x=>({id:x.id,version:x.version})),processId:$('#process').value,evidence:$('#evidence').value});await load();msg(`${r.updated}개 귀속 변경·감사 기록 완료. 매칭/실물 검증은 승격하지 않음`)});
$('#export').onclick=()=>{let a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(visible,null,2)],{type:'application/json'}));a.href=u;a.download='설비-3D-매핑-귀속미확정.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),500)};guard(load);
